'use client';

import Link from 'next/link';
import { useEffect, useRef, useState, useSyncExternalStore, type ReactNode } from 'react';
import { Search, SlidersHorizontal, Bookmark, ArrowDownUp, ArrowLeft, ArrowRight, X, Check, Download, Columns3, Database, Lightbulb, Radio, UserRound, ExternalLink } from 'lucide-react';
import { evidence, latest, models, yen, type CompanySummary } from '@/lib/catalog';
import type { CompanyRecord } from '@/types/terminal';
import type { BusinessIdeaRecord } from '@/types/idea';
import type { SignalDetailItem } from '@/data/portalSignals';
import { useAuth } from '@/context/AuthContext';
import './workspace.css';

const subscribe=(fn:()=>void)=>{window.addEventListener('popstate',fn);return()=>window.removeEventListener('popstate',fn);};
const snapshot=()=>window.location.search;
function navigate(params:URLSearchParams,replace=false){window.history[replace?'replaceState':'pushState']({},'',`/?${params}`);window.dispatchEvent(new PopStateEvent('popstate'));}
const sections=[['companies','全企業・財務台帳',Database],['ideas','事業アイデア',Lightbulb],['signals','市場調査',Radio],['saved','保存',Bookmark],['account','アカウント',UserRound]] as const;
type SavedSearch={name:string;query:string};
type LocalLibrary={ids:string[];searches:SavedSearch[]};
type Catalog={items:CompanySummary[];total:number;corpus:number;page:number;pages:number;size:number;models:string[]};
function useResource<T>(url:string){
 const [state,setState]=useState<{url:string;data?:T;error?:string}>({url:''});
 const [retry,setRetry]=useState(0);
 useEffect(()=>{const controller=new AbortController();fetch(url,{signal:controller.signal}).then(async r=>{if(!r.ok)throw new Error(r.status===404?'対象が見つかりません':'読み込みに失敗しました');return r.json() as Promise<T>;}).then(data=>setState({url,data})).catch(e=>{if(e.name!=='AbortError')setState({url,error:e.message});});return()=>controller.abort();},[url,retry]);
 return {data:state.url===url?state.data:undefined,error:state.url===url?state.error:undefined,retry:()=>setRetry(v=>v+1)};
}
function Dialog({title,onClose,children}:{title:string;onClose:()=>void;children:ReactNode}){
 const ref=useRef<HTMLDialogElement>(null);
 useEffect(()=>{const previous=document.activeElement as HTMLElement;const d=ref.current;d?.showModal();return()=>{d?.close();previous?.focus();};},[]);
 return <dialog ref={ref} className="ws-dialog" onCancel={onClose} onClick={e=>{if(e.target===e.currentTarget)onClose();}}><header><h2>{title}</h2><button aria-label="閉じる" onClick={onClose}><X size={20}/></button></header>{children}</dialog>;
}
function Message({error,retry}:{error?:string;retry?:()=>void}){return <div className="ws-message" role={error?'alert':'status'}>{error??'読み込み中…'}{error&&retry&&<button onClick={retry}>再試行</button>}</div>;}
function Section({title,children}:{title:string;children:ReactNode}){return <section className="ws-section"><h2>{title}</h2>{children}</section>;}
function Facts({rows}:{rows:[string,ReactNode][]}){return <dl className="ws-facts">{rows.map(([k,v])=><div key={k}><dt>{k}</dt><dd>{v??'未登録'}</dd></div>)}</dl>;}
function Tag({value}:{value:string}){return <span className="ws-tag">{value}</span>;}

export default function Workspace(){
 const query=useSyncExternalStore(subscribe,snapshot,()=> '');
 const params=new URLSearchParams(query), legacy=params.get('view');
 const view=params.get('tab')??(legacy==='RADAR'||legacy==='PORTAL'?'signals':legacy==='LIBRARY'?'saved':legacy==='IDEAS_VAULT'?'ideas':'companies');
 const companyId=params.get('company');
 const auth=useAuth();
 const storageKey=`kin-library-v2:${auth.user?.uid??'guest'}`;
 const [library,setLibrary]=useState<LocalLibrary>({ids:[],searches:[]});
 const [loadedKey,setLoadedKey]=useState('');
 const [notice,setNotice]=useState('');
 const [filterOpen,setFilterOpen]=useState(false);
 const [compare,setCompare]=useState<string[]>([]);
 const currentLibrary=loadedKey===storageKey?library:{ids:[],searches:[]};
 useEffect(()=>{
 const read=()=>{try{const raw=JSON.parse(localStorage.getItem(storageKey)??'{}');setLibrary({ids:Array.isArray(raw.ids)?raw.ids.filter((x:unknown)=>typeof x==='string'):[],searches:Array.isArray(raw.searches)?raw.searches.filter((x:SavedSearch)=>typeof x?.name==='string'&&typeof x?.query==='string'):[]});}catch{setLibrary({ids:[],searches:[]});}setLoadedKey(storageKey);};
 read();window.addEventListener('storage',read);return()=>window.removeEventListener('storage',read);
 },[storageKey]);
 useEffect(()=>{if(!notice)return;const t=setTimeout(()=>setNotice(''),4000);return()=>clearTimeout(t);},[notice]);
 const persist=(next:LocalLibrary)=>{try{localStorage.setItem(storageKey,JSON.stringify(next));setLibrary(next);setLoadedKey(storageKey);}catch{setNotice('保存できません。ブラウザの保存設定を確認してください');}};
 const save=(id:string)=>{const has=currentLibrary.ids.includes(id);persist({...currentLibrary,ids:has?currentLibrary.ids.filter(x=>x!==id):[...currentLibrary.ids,id]});setNotice(has?'保存を解除しました':'この端末に保存しました');};
 const toggleCompare=(id:string)=>{if(compare.includes(id))setCompare(compare.filter(x=>x!==id));else if(compare.length<4)setCompare([...compare,id]);else setNotice('比較は4社まで選択できます');};
 const go=(tab:string)=>{navigate(new URLSearchParams({tab}));window.scrollTo(0,0);};
 const open=(id:string)=>{const p=new URLSearchParams(params);if(view==='compare'){p.set('tab','companies');p.delete('ids');}p.set('company',id);navigate(p);};
 const closeDetail=()=>{const p=new URLSearchParams(params);p.delete('company');navigate(p);};
 const update=(key:string,value:string)=>{const p=new URLSearchParams(params);p.delete('company');p.delete('page');if(value)p.set(key,value);else p.delete(key);navigate(p);};
 const filters=['model','team','capital','margin','evidence'];
 const filterCount=filters.filter(k=>params.has(k)).length;
 const saveSearch=()=>{const p=new URLSearchParams(params);['company','page','view','tab'].forEach(k=>p.delete(k));p.set('tab','companies');const q=p.toString();if(currentLibrary.searches.some(s=>s.query===q)){setNotice('この検索条件は保存済みです');return;}const name=[params.get('q'),...filters.filter(k=>params.has(k)).map(k=>filterName(k,params.get(k)!))].filter(Boolean).join(' · ')||'すべての事業';persist({...currentLibrary,searches:[...currentLibrary.searches,{name,query:q}]});setNotice('検索条件を保存しました');};
 return <div className="ws-app"><a className="ws-skip" href="#workspace">本文へ</a><aside className="ws-nav"><Link className="ws-brand" href="/?tab=companies"><span>金</span><b>金鉱録<small>事業リサーチ</small></b></Link><nav aria-label="メインナビゲーション">{sections.map(([id,label,Icon])=><a key={id} href={`/?tab=${id}`} aria-current={view===id?'page':undefined} onClick={e=>{e.preventDefault();go(id);}}><Icon size={18}/><span>{label}</span>{id==='saved'&&currentLibrary.ids.length>0&&<small>{currentLibrary.ids.length}</small>}</a>)}</nav><div className="ws-nav-foot">KIN-KOROKU</div></aside>
 <main id="workspace" className="ws-main">
 {companyId&&view!=='companies'&&view!=='saved'?<CompanyDetail key={companyId} id={companyId} onBack={closeDetail} saved={currentLibrary.ids.includes(companyId)} onSave={()=>save(companyId)} compared={compare.includes(companyId)} onCompare={()=>toggleCompare(companyId)}/>:
 view==='companies'||view==='saved'?<>
 <h1 className="ws-sr">{view==='saved'?'保存した事業':'事業・財務台帳'}</h1>
 <div className="ws-presets" aria-label="主要条件"><button aria-pressed={filterCount===0} onClick={()=>{const p=new URLSearchParams(params);filters.forEach(k=>p.delete(k));p.delete('company');p.delete('page');navigate(p);}}>全件</button>{[['team','1','完全1人'],['margin','50','利益率50%以上'],['capital','0','初期資本0円'],['model','MICRO_SAAS','SaaS'],['model','LOCAL_DX','地域ビジネス']].map(([k,v,l])=><button key={l} aria-pressed={params.get(k)===v} onClick={()=>update(k,params.get(k)===v?'':v)}>{l}</button>)}</div>
 {view==='saved'&&<section className="ws-saved-searches"><h2>保存検索 <span>{currentLibrary.searches.length}</span></h2>{currentLibrary.searches.length?currentLibrary.searches.map(s=><div key={s.query}><a href={`/?${s.query}`} onClick={e=>{e.preventDefault();navigate(new URLSearchParams(s.query));}}>{s.name}<ArrowRight size={16}/></a><button aria-label={`${s.name}の保存を解除`} onClick={()=>persist({...currentLibrary,searches:currentLibrary.searches.filter(x=>x.query!==s.query)})}><X size={16}/></button></div>):<p>保存した検索はありません</p>}</section>}
 <div className="ws-toolbar"><form key={query} onSubmit={e=>{e.preventDefault();update('q',String(new FormData(e.currentTarget).get('q')??''));}} className="ws-search"><Search size={18}/><input name="q" defaultValue={params.get('q')??''} placeholder="企業名・商品・顧客・集客方法" aria-label="事業を検索"/><button type="submit">検索</button></form><button className={filterCount?'ws-button active':'ws-button'} onClick={()=>setFilterOpen(true)}><SlidersHorizontal size={16}/>条件{filterCount>0&&<b>{filterCount}</b>}</button><button className="ws-button" onClick={saveSearch}><Bookmark size={16}/><span>検索保存</span></button><a className="ws-button" href={`/api/catalog?${new URLSearchParams({...Object.fromEntries(params),...(view==='saved'?{ids:currentLibrary.ids.join(',')} :{}),format:'csv'})}`} download><Download size={16}/><span>CSV</span></a></div>
 {(params.get('q')||filterCount>0)&&<div className="ws-chips">{['q',...filters].filter(k=>params.has(k)).map(k=><button key={k} onClick={()=>update(k,'')}>{filterName(k,params.get(k)!)}<X size={14}/></button>)}<button onClick={()=>navigate(new URLSearchParams({tab:view}))}>すべて解除</button></div>}
 <div className={companyId?"ws-research-layout has-selection":"ws-research-layout"}><div className="ws-results"><CompanyList params={params} savedView={view==='saved'} ids={currentLibrary.ids} compare={compare} onCompare={toggleCompare} onOpen={open} onSave={save} update={update}/></div>{companyId&&<section className="ws-inspector" aria-label="選択した企業の分析"><CompanyDetail key={companyId} id={companyId} onBack={closeDetail} saved={currentLibrary.ids.includes(companyId)} onSave={()=>save(companyId)} compared={compare.includes(companyId)} onCompare={()=>toggleCompare(companyId)}/></section>}</div>
 </>:view==='ideas'?<Ideas params={params} onOpen={open}/>:view==='signals'?<Signals/>:view==='account'?<Account/>:view==='compare'?<header className="ws-page-head"><h1>事業比較</h1></header>:<div className="ws-message">ページが見つかりません<button onClick={()=>go('companies')}>一覧へ戻る</button></div>}
 </main>
 {compare.length>0&&<div className="ws-compare-dock"><span>{compare.length}社を選択</span><button onClick={()=>setCompare([])}>解除</button><a href={`/?tab=compare&ids=${compare.join(',')}`} onClick={e=>{e.preventDefault();navigate(new URLSearchParams({tab:'compare',ids:compare.join(',')}));}}><Columns3 size={16}/>比較する</a></div>}
 {view==='compare'&&<Dialog title="事業を比較" onClose={()=>go('companies')}><Comparison ids={(params.get('ids')??'').split(',').filter(Boolean).slice(0,4)} onOpen={open} onRemove={id=>{const p=new URLSearchParams(params);p.set('ids',(p.get('ids')??'').split(',').filter(x=>x!==id).join(','));navigate(p,true);setCompare(compare.filter(x=>x!==id));}}/></Dialog>}
 {filterOpen&&<Dialog title="絞り込み条件" onClose={()=>setFilterOpen(false)}><form className="ws-filter-form" onSubmit={e=>{e.preventDefault();const p=new URLSearchParams(params);filters.forEach(k=>p.delete(k));p.delete('page');p.delete('company');for(const [k,v] of new FormData(e.currentTarget))if(v)p.set(k,String(v));navigate(p);setFilterOpen(false);}}><Select label="収益モデル" name="model" value={params.get('model')} options={Object.entries(models)}/><Select label="運営人数" name="team" value={params.get('team')} options={[["1","1人"],["3","3人以下"],["10","10人以下"],["100","100人以下"]]}/><Select label="初期資本" name="capital" value={params.get('capital')} options={[["0","0円"],["50000","5万円以下"],["500000","50万円以下"],["1000000","100万円以下"]]}/><Select label="営業利益率" name="margin" value={params.get('margin')} options={[["0","黒字"],["30","30%以上"],["50","50%以上"],["80","80%以上"]]}/><Select label="収録データ区分" name="evidence" value={params.get('evidence')} options={Object.entries(evidence)}/><footer><button type="button" onClick={()=>{const p=new URLSearchParams(params);filters.forEach(k=>p.delete(k));p.delete('page');navigate(p);setFilterOpen(false);}}>条件を解除</button><button className="ws-primary" type="submit">適用する</button></footer></form></Dialog>}
 {notice&&<div className="ws-toast" role="status"><Check size={16}/>{notice}</div>}
 </div>;
}
function filterName(k:string,v:string){return k==='q'?`「${v}」`:k==='model'?models[v]??v:k==='team'?`${v}人以下`:k==='capital'?`初期${yen(Number(v))}以下`:k==='margin'?`営業利益率${v}%以上`:evidence[v]??v;}
function Select({label,name,value,options}:{label:string;name:string;value:string|null;options:string[][]}){return <label>{label}<select name={name} defaultValue={value??''}><option value="">すべて</option>{options.map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label>;}
function CompanyList({params,savedView,ids,compare,onCompare,onOpen,onSave,update}:{params:URLSearchParams;savedView:boolean;ids:string[];compare:string[];onCompare:(id:string)=>void;onOpen:(id:string)=>void;onSave:(id:string)=>void;update:(k:string,v:string)=>void}){
 const p=new URLSearchParams(params);p.delete('company');p.delete('lens');if(savedView)p.set('ids',ids.join(','));
 const result=useResource<Catalog>(`/api/catalog?${p}`);
 if(!result.data)return <Message error={result.error} retry={result.retry}/>;
 const data=result.data;
 const sort=params.get('sort')??'revenue';
 const lens=params.get('lens')??'financial';
 const sortColumn=(key:string)=>{const next=new URLSearchParams(params);next.set('sort',key);next.set('direction',sort===key&&params.get('direction')!=='asc'?'asc':'desc');next.delete('page');navigate(next);};
 return <><div className="ws-view-strip" aria-label="表示項目">{[["financial","財務比較"],["business","商流・顧客"],["entry","運営・参入"]].map(([id,label])=><button key={id} aria-pressed={lens===id} onClick={()=>{const n=new URLSearchParams(params);n.set("lens",id);n.delete('company');navigate(n,true);}}>{label}</button>)}</div><div className="ws-result-head"><span><b>{data.total.toLocaleString()}</b>件</span><label className="ws-mobile-sort">並び順<select aria-label="並び順" value={sort} onChange={e=>update('sort',e.target.value)}><option value="revenue">売上高</option><option value="margin">営業利益率</option><option value="team">人数</option><option value="capital">初期資本</option></select></label><span className="ws-data-note">金額：円 / 各社の直近収録期間</span></div>
 {data.items.length===0?<div className="ws-empty"><Search size={28}/><h2>{savedView?'保存した事業がありません':'一致する事業がありません'}</h2><Link href="/?tab=companies">事業一覧へ</Link></div>:<>
 <div className="ws-table-wrap"><table className={`ws-table lens-${lens}`}><caption className="ws-sr">事業検索結果</caption><thead><tr><th aria-label="比較選択"/><th>企業・事業</th><th>{lens==="entry"?"課金・運営":lens==="business"?"顧客・商品":"商品・顧客"}</th>{[['revenue','売上高'],['profit','営業利益'],['margin','営業利益率'],['team','人数'],['capital','初期資本']].map(([key,label])=><th key={key} className="numeric" aria-sort={sort===key?params.get('direction')==='asc'?'ascending':'descending':'none'}><button onClick={()=>sortColumn(key)}>{label}<ArrowDownUp size={12}/></button></th>)}<th>収録区分</th><th aria-label="保存"/></tr></thead><tbody>{data.items.map(c=><tr key={c.id} aria-selected={params.get("company")===c.id}><td><input type="checkbox" aria-label={`${c.title}を比較`} checked={compare.includes(c.id)} onChange={()=>onCompare(c.id)}/></td><td><a href={`/?${params}&company=${encodeURIComponent(c.id)}`} onClick={e=>{e.preventDefault();onOpen(c.id);}} className="ws-company-link">{c.title}</a><small>{models[c.model]}</small></td><td className="ws-business-col"><span>{lens==="entry"?c.monetization:lens==="business"?c.customer:c.what}</span><small>{lens==="entry"?`週${c.hours}時間 · ${c.channel||"集客経路未登録"}`:lens==="business"?c.what:c.customer}</small></td><td className="numeric"><strong>{yen(c.revenue)}</strong><small>{c.period}</small></td><td className="numeric"><strong className={(c.profit??0)<0?'negative':'positive'}>{yen(c.profit)}</strong></td><td className="numeric"><strong className={(c.margin??0)<0?'negative':''}>{c.margin??'—'}%</strong></td><td className="numeric">{c.team.toLocaleString()}人</td><td className="numeric">{yen(c.capital)}</td><td><Tag value={evidence[c.evidence]}/><small>出典未登録</small></td><td><button className="ws-icon" aria-label={`${c.title}を${ids.includes(c.id)?'保存解除':'保存'}`} aria-pressed={ids.includes(c.id)} onClick={()=>onSave(c.id)}><Bookmark size={17} fill={ids.includes(c.id)?'currentColor':'none'}/></button></td></tr>)}</tbody></table></div>
 <div className="ws-mobile-list">{data.items.map(c=><article key={c.id}><header><a href={`/?${params}&company=${encodeURIComponent(c.id)}`} onClick={e=>{e.preventDefault();onOpen(c.id);}}>{c.title}<ArrowRight size={16}/></a><button aria-label={`${c.title}を保存`} aria-pressed={ids.includes(c.id)} onClick={()=>onSave(c.id)}><Bookmark size={18} fill={ids.includes(c.id)?'currentColor':'none'}/></button></header><span className="ws-mobile-meta">{models[c.model]} · {c.team}人 · {evidence[c.evidence]}（出典未登録）</span><p>{c.what}</p><dl><div><dt>売上高</dt><dd>{yen(c.revenue)}</dd></div><div><dt>営業利益率</dt><dd>{c.margin??'—'}%</dd></div><div><dt>初期資本</dt><dd>{yen(c.capital)}</dd></div></dl><footer><small>{c.period}</small><label><input type="checkbox" checked={compare.includes(c.id)} onChange={()=>onCompare(c.id)}/>比較</label></footer></article>)}</div>
 </>}
 <footer className="ws-pagination"><label>表示件数<select value={data.size} onChange={e=>update('size',e.target.value)}>{[20,50,100].map(n=><option key={n}>{n}</option>)}</select></label><span>{data.total?`${(data.page-1)*data.size+1}–${Math.min(data.page*data.size,data.total)}`:'0'} / {data.total}</span><div><button disabled={data.page===1} aria-label="前のページ" onClick={()=>{const n=new URLSearchParams(params);n.set('page',String(data.page-1));navigate(n);}}><ArrowLeft size={16}/></button><label><span className="ws-sr">ページ</span><input aria-label="ページ" type="number" min={1} max={data.pages} key={data.page} defaultValue={data.page} onKeyDown={e=>{if(e.key==='Enter'){const n=new URLSearchParams(params);n.set('page',e.currentTarget.value);navigate(n);}}}/></label><span>/ {data.pages}</span><button disabled={data.page===data.pages} aria-label="次のページ" onClick={()=>{const n=new URLSearchParams(params);n.set('page',String(data.page+1));navigate(n);window.scrollTo(0,0);}}><ArrowRight size={16}/></button></div></footer></>;
}

function CompanyDetail({id,onBack,saved,onSave,compared,onCompare}:{id:string;onBack:()=>void;saved:boolean;onSave:()=>void;compared:boolean;onCompare:()=>void}){
 const result=useResource<CompanyRecord>(`/api/catalog?id=${encodeURIComponent(id)}`);
 const [tab,setTab]=useState('overview');
 if(!result.data)return <><button className="ws-back" onClick={onBack}><ArrowLeft size={16}/>一覧へ</button><Message error={result.error} retry={result.retry}/></>;
 const c=result.data,f=latest(c);
 return <><button className="ws-back" onClick={onBack}><X size={16}/>分析を閉じる</button><header className="ws-detail-head"><div><span className="ws-eyebrow">{models[c.businessModel]} · {c.ticker}</span><h1>{c.japaneseName}</h1><p>{c.businessEssence.whatItDoes}</p></div><div className="ws-detail-actions"><button className="ws-button" aria-pressed={saved} onClick={onSave}><Bookmark size={16}/>{saved?'保存済み':'保存'}</button><button className="ws-button" aria-pressed={compared} onClick={onCompare}><Columns3 size={16}/>{compared?'比較中':'比較'}</button></div></header>
 <div className="ws-metrics">{[['売上高',yen(f?.revenueJpy),f?.period],['営業利益',yen(f?.operatingProfitJpy),`利益率 ${f?.operatingMarginPercent??'—'}%`],['初期資本',yen(c.initialInvestmentJpy),'収録値'],['運営人数',`${c.teamSize.toLocaleString()}人`,`週${c.weeklyHours}時間`]].map(([k,v,s])=><div key={k}><span>{k}</span><strong>{v}</strong><small>{s}</small></div>)}</div>
 <nav className="ws-detail-tabs" aria-label="企業情報">{[['overview','概況'],['structure','収益構造'],['financials','財務'],['operations','集客・運営'],['sources','出典']].map(([id,label])=><button key={id} aria-pressed={tab===id} onClick={()=>setTab(id)}>{label}</button>)}</nav>
 {tab==='overview'&&<div className="ws-overview">
 <Section title="01 / 商流"><Facts rows={[["顧客",c.businessEssence.targetCustomer],["提供価値",c.businessEssence.valueProposition],["課金",c.businessEssence.monetizationWay],["価格",c.pricingDesign?.pricingTiers??c.pricingSecret?.priceTagExample]]}/></Section>
 <Section title="02 / 損益"><div className="ws-financial-scroll"><table className="ws-financial"><thead><tr><th>円</th>{c.financials.slice(-3).map(r=><th key={r.period}>{r.period}</th>)}</tr></thead><tbody>{([['売上高','revenueJpy'],['売上原価','cogsJpy'],['粗利益','grossProfitJpy'],['販管費','opexJpy'],['営業利益','operatingProfitJpy']] as const).map(([label,key])=><tr key={key}><th>{label}</th>{c.financials.slice(-3).map(r=><td key={r.period}>{yen(r[key])}</td>)}</tr>)}</tbody></table></div><span className="ws-footnote">{evidence[c.verifiedStatus]} · 元資料未登録</span></Section>
 <Section title="03 / 顧客獲得"><Facts rows={[["主力経路",c.trafficFaucet?.primaryChannel??c.first100CustomersStrategy?.tacticalChannel],["初動",c.initialTractionStrategy],["獲得施策",c.first100CustomersStrategy?.exactAction]]}/></Section>
 <Section title="04 / 運営コスト"><Facts rows={[["体制",`${c.teamSize}人 / 週${c.weeklyHours}時間`],["初期資本",yen(c.initialInvestmentJpy)]]}/>{c.tools.map((t,i)=><div className="ws-tool" key={i}><div><h3>{t.name}</h3><p>{t.purpose}</p></div><strong>{yen(t.monthlyCostJpy)} / 月</strong></div>)}</Section>
 <Section title="05 / 利益の源泉"><p>{c.coreMoatDescription}</p></Section>
 <Section title="06 / 制約・参入余地"><Facts rows={[["失敗・制約",c.earlyFailureLesson?.whatWentWrong],["参入余地（分析）",c.entryStrategy?.whyIncumbentCantWin]]}/></Section>
 </div>}
 {tab==='structure'&&<div className="ws-detail-grid"><div><Section title="誰に、何を、いくらで売るか"><Facts rows={[["顧客",c.businessEssence.targetCustomer],["提供価値",c.businessEssence.valueProposition],["集金方法",c.businessEssence.monetizationWay],["料金体系",c.pricingDesign?.pricingTiers??c.pricingSecret?.priceTagExample]]}/></Section><Section title="利益が残る仕組み"><p>{c.coreMoatDescription}</p>{c.pricingSecret&&<Facts rows={[["価格決定力",c.pricingSecret.defenseReason],["比較される価格",c.pricingSecret.anchorComparison]]}/>}</Section>{c.successStory&&<Section title="事業の成立過程"><Facts rows={[["創業者",c.successStory.founderProfile],["市場の隙間",c.successStory.marketGlitch],["最初の突破口",c.successStory.breakthroughMoment]]}/></Section>}</div><div><Section title="事業概要"><Facts rows={[["創業",`${c.foundedYear}年`],["拠点",c.headquarters],["創業者",c.founderName],["収録区分",evidence[c.verifiedStatus]],["元資料",'未登録']]}/></Section>{c.entryStrategy&&<Section title="参入余地 · 編集上の分析"><p>{c.entryStrategy.whyIncumbentCantWin}</p><Facts rows={[["対象市場",c.entryStrategy.targetVictimOrNiche],["参入経路",c.entryStrategy.actionableEntryRoute]]}/></Section>}{c.earlyFailureLesson&&<Section title="失敗・制約"><p>{c.earlyFailureLesson.whatWentWrong}</p><Facts rows={[["費やした資金・期間",c.earlyFailureLesson.wastedMoneyOrTime],["転換点",c.earlyFailureLesson.pivotMoment]]}/></Section>}</div></div>}
 {tab==='financials'&&<><Section title="損益計算書"><div className="ws-financial-scroll" tabIndex={0} aria-label="損益計算書"><table className="ws-financial"><thead><tr><th>項目（円）</th>{c.financials.map(r=><th key={r.period}>{r.period}</th>)}</tr></thead><tbody>{([['売上高','revenueJpy'],['売上原価','cogsJpy'],['粗利益','grossProfitJpy'],['販管費','opexJpy'],['営業利益','operatingProfitJpy'],['当期純利益','netIncomeJpy']] as const).map(([label,key])=><tr key={key}><th>{label}</th>{c.financials.map(r=><td key={r.period}>{yen(r[key])}</td>)}</tr>)}</tbody></table></div></Section>{c.passbookDetails&&<Section title={`月次収支 · ${c.passbookDetails.bankStatementDate}`}><Facts rows={[["総入金",yen(c.passbookDetails.monthlyGrossJpy)],["決済手数料",yen(c.passbookDetails.paymentFeeJpy)],["設備・道具費",yen(c.passbookDetails.infraCostJpy)],["外注費",yen(c.passbookDetails.outsourcingJpy)],["税引当",yen(c.passbookDetails.taxReserveJpy)],["創業者手残り",yen(c.passbookDetails.founderTakeHomeJpy)]]}/></Section>}<p className="ws-footnote">収録区分：{evidence[c.verifiedStatus]} / 元資料・換算根拠：未登録</p></>}
 {tab==='operations'&&<div className="ws-detail-grid"><div><Section title="顧客獲得"><p>{c.initialTractionStrategy}</p>{c.first100CustomersStrategy&&<Facts rows={[["チャネル",c.first100CustomersStrategy.tacticalChannel],["施策",c.first100CustomersStrategy.exactAction],["収録された成果",c.first100CustomersStrategy.conversionProof]]}/>}</Section>{c.trafficFaucet&&<Section title="継続集客"><Facts rows={[["主力チャネル",c.trafficFaucet.primaryChannel]]}/></Section>}{c.founderWorkload&&<Section title="運営の分担"><Facts rows={[["本人の業務",c.founderWorkload.founderTasks.join(' / ')],["自動化・委託",c.founderWorkload.automatedOrDelegatedTasks.join(' / ')]]}/></Section>}</div><Section title="道具・費用">{c.tools.length?c.tools.map((t,i)=><div className="ws-tool" key={`${t.name}-${i}`}><div><h3>{t.name}</h3><p>{t.purpose}</p></div><strong>{yen(t.monthlyCostJpy)}<small>/ 月</small></strong></div>):<p>未登録</p>}</Section></div>}
 {tab==='sources'&&<Section title="出典"><Facts rows={[["収録データ区分",evidence[c.verifiedStatus]],["元資料URL",'未登録'],["照合日",'未登録'],["通貨換算根拠",'未登録'],["収録期間",c.financials.map(f=>f.period).join(' / ')]]}/></Section>}
 </>;
}
function Comparison({ids,onOpen,onRemove}:{ids:string[];onOpen:(id:string)=>void;onRemove:(id:string)=>void}){
 const result=useResource<Catalog>(`/api/catalog?ids=${encodeURIComponent(ids.join(','))}&size=100`);
 if(!result.data)return <Message error={result.error} retry={result.retry}/>;
 const items=result.data.items;
 return <div className="ws-comparison">{items.length?<div className="ws-financial-scroll" tabIndex={0} aria-label="企業比較"><table className="ws-financial"><thead><tr><th>比較項目</th>{items.map(c=><th key={c.id}><button onClick={()=>onOpen(c.id)}>{c.title}</button><button aria-label={`${c.title}を比較から解除`} onClick={()=>onRemove(c.id)}><X size={16}/></button></th>)}</tr></thead><tbody>{['商品','顧客','売上高','営業利益率','初期資本','人数','収録区分','出典'].map((label,i)=><tr key={label}><th>{label}</th>{items.map(c=><td key={c.id}>{[c.what,c.customer,`${yen(c.revenue)} / ${c.period}`,`${c.margin??'—'}%`,yen(c.capital),`${c.team}人`,evidence[c.evidence],'未登録'][i]}</td>)}</tr>)}</tbody></table></div>:<p>比較する企業がありません</p>}</div>;
}
function Ideas({params,onOpen}:{params:URLSearchParams;onOpen:(id:string)=>void}){
 const r=useResource<BusinessIdeaRecord[]>('/api/catalog?kind=ideas');
 const [q,setQ]=useState('');
 const [category,setCategory]=useState('');
 return <><header className="ws-page-head"><div><span className="ws-eyebrow">BUSINESS IDEAS</span><h1>事業アイデア</h1></div><Tag value="構想・未検証"/></header><div className="ws-toolbar"><div className="ws-search"><Search size={18}/><input aria-label="アイデアを検索" placeholder="顧客・商品・業界" value={q} onChange={e=>setQ(e.target.value)}/></div><select aria-label="アイデアの分類" value={category} onChange={e=>setCategory(e.target.value)}><option value="">すべての分類</option>{[...new Set(r.data?.map(i=>i.categoryLabel)??[])].map(c=><option key={c}>{c}</option>)}</select></div>{!r.data?<Message error={r.error} retry={r.retry}/>:<div className="ws-editorial-list">{r.data.filter(i=>(!category||i.categoryLabel===category)&&[i.title,i.targetMarket,i.shortDescription].join(' ').includes(q)).map(i=><details key={i.id}><summary><span><small>{i.categoryLabel}</small><h2>{i.title}</h2><p>{i.shortDescription}</p></span><ArrowRight size={18}/></summary><div className="ws-editorial-body"><Facts rows={[["対象顧客",i.targetMarket],["市場の隙間",i.glitchOrTrap],["提供方法",i.actionableSteps],["必要な道具",i.requiredTools.join(' / ')],["想定初期資本",i.initialCapital],["収益想定（未検証）",i.estimatedMonthlyProfit]]}/>{i.sourceCompanyId&&<button className="ws-button" onClick={()=>{const p=new URLSearchParams(params);p.set('company',i.sourceCompanyId!);onOpen(i.sourceCompanyId!);}}>関連企業を開く<ArrowRight size={16}/></button>}</div></details>)}</div>}</>;
}
function Signals(){const r=useResource<SignalDetailItem[]>('/api/catalog?kind=signals');return <><header className="ws-page-head"><div><span className="ws-eyebrow">MARKET RESEARCH</span><h1>市場調査</h1></div><Tag value="更新日・出典未登録"/></header>{!r.data?<Message error={r.error} retry={r.retry}/>:<div className="ws-editorial-list">{r.data.map(s=><details key={s.id}><summary><span><small>調査メモ</small><h2>{s.title}</h2><p>{s.targetMarket}</p></span><ArrowRight size={18}/></summary><div className="ws-editorial-body"><Section title="市場の構造">{s.glitchOrigin.map(g=><div key={g.heading}><h3>{g.heading}</h3><p>{g.detail}</p></div>)}</Section><Facts rows={[["初期資本（推計）",s.estimatedCapital],["利益（推計）",s.estimatedMonthlyProfit],["制約・リスク",s.cautionRisk]]}/><Section title="必要な道具">{s.essentialTools.map(t=><div className="ws-tool" key={t.name}><span><h3>{t.name}</h3><p>{t.role}</p></span><strong>{t.cost}</strong></div>)}</Section></div></details>)}</div>}</>;}
function Account(){
 const auth=useAuth();const [error,setError]=useState('');const [busy,setBusy]=useState(false);
 const run=async(fn:()=>Promise<unknown>)=>{setBusy(true);setError('');try{await fn();}catch{setError('処理できませんでした。接続と設定を確認してください。');}finally{setBusy(false);}};
 return <><header className="ws-page-head"><div><span className="ws-eyebrow">ACCOUNT</span><h1>アカウント</h1></div></header><div className="ws-account"><Section title="ログイン">{auth.user?<><p>{auth.user.email}</p><button className="ws-button" disabled={busy} onClick={()=>run(auth.signOut)}>ログアウト</button></>:<><button className="ws-primary" disabled={busy} onClick={()=>run(auth.signInWithGoogle)}>Googleでログイン</button><form onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);run(()=>auth.signInWithEmail(String(f.get('email')),String(f.get('password'))));}}><label>メールアドレス<input type="email" name="email" autoComplete="email" required/></label><label>パスワード<input type="password" name="password" autoComplete="current-password" required/></label><button className="ws-button" disabled={busy}>ログイン</button></form></>}</Section><Section title="会員プラン"><p>{auth.isPro?'PRO会員':'無料会員'}</p>{!auth.isPro&&auth.user&&<button className="ws-button" disabled={busy} onClick={()=>run(async()=>{const r=await fetch('/api/checkout',{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${auth.token}`},body:JSON.stringify({product:'founding-pass'})});const data=await r.json();if(!r.ok||!data.url)throw new Error();const u=new URL(data.url);if(u.hostname!=='checkout.stripe.com')throw new Error();window.location.assign(u.href);})}>プラン・料金を確認<ExternalLink size={16}/></button>}</Section>{error&&<p role="alert">{error}</p>}</div></>;
}
