import type { RawWinnerDef } from './generate-100-winners-data';

export const REMAINING_80_DEFS: RawWinnerDef[] = [
  // 21. YETI
  {
    id: 'ent_yeti_coolers_11',
    ticker: 'YETI',
    name: 'YETI Coolers',
    tagline: '「グリズリーが乗っても絶対に壊れない」という極限の耐久性で、ただのプラスチック保冷箱を5万円で売って年商¥2,400億円を抜く頑丈さの関所',
    sector: 'PHYSICAL_ASSET',
    scale: 'ENTERPRISE',
    founder: 'Roy & Ryan Seiders（テキサスの釣り好き兄弟）',
    country: 'US',
    url: 'https://www.yeti.com',
    growthRateYoY: 15,
    architecturePattern: '回転成形（ロトモールド）工法×グリズリー耐性認証×アウトドア信者コミュニティ',
    pipelineStack: 'Shopify Plus × 直営店 × 全米アウトドア卸 × Stripe',
    targetPainWallet: '安物のクーラーボックスが数回のキャンプで蓋が割れて氷が溶けるアウトドア愛好家の絶望',
    tags: ['年商2400億', 'グリズリー耐性', 'クーラーボックス5万円', '回転成形', '信者化'],
    currency: 'USD',
    annualRevenueRaw: 1600000000,
    grossMarginPct: 58.0,
    operatingMarginPct: 16.0,
    snapshotYear: 2024,
    revenueSourceNote: 'NYSE上場（YETI）2023-2024年通期決算報告 売上高16.6億ドル',
    teamSize: 1000,
    blindspot: 'ウォルマートで3,000円で買えるクーラーボックスを、あえて「5万円」で出してプロ品質にすると、男たちがステータスシンボルとして買い漁る。',
    moatType: 'BRAND_PRESTIGE',
    moatDescription: 'ピックアップトラックの荷台にYETIのステッカーを貼ることが「本物のアウトドアマン」である社会的証明。',
    initialTraction: ['全米のアウトドアガイドやプロ釣り師に製品を配り「あいつらが使っている本物」の評判を確立', 'クマがクーラーボックスを襲撃して破壊できない動画が全米でバイラル'],
    actionPlaybook: ['日用品（保冷箱、タンブラー）を「極限環境に耐えるプロスペック」へ魔改造する', '価格を競合の10倍に設定して「富裕層のステータスシンボル」へ昇華させる', 'タンブラーやバッグへ横展開して客単価とリピート率を極大化する'],
    targetPrey: '富裕層のアウトドア愛好家、BBQ好き、ハンター',
    structuralFlaw: '大手メーカー（コールマン等）は量販店向けにコストダウンを繰り返し、安物プラスチックの泥沼から抜け出せなかった。',
    stealthEntry: '小さな釣具店や銃砲店にだけ卸し、「知る人ぞ知るプロの道具」として希少価値を演出。',
    tollGateSetup: '1台$300〜$900のハードウェア販売。タンブラー（$40）のリピート買い。',
    observations: ['【虚栄心と耐久性の結合】「絶対に壊れない」という安心感に、男たちは喜んで定価の10倍の現金を払う。']
  },

  // 22. Solo Stove
  {
    id: 'ent_solo_stove_12',
    ticker: 'SOLOST',
    name: 'Solo Stove',
    tagline: '「焚き火の煙が服や髪にこびりついて臭い」というキャンプ最大の不快感を二次燃焼構造で切除し、年商¥600億円・ナスダック上場へ成り上がった無煙焚火台',
    sector: 'PHYSICAL_ASSET',
    scale: 'ENTERPRISE',
    founder: 'Jeff & Spencer Jan（兄弟起業）',
    country: 'US',
    url: 'https://www.solostove.com',
    growthRateYoY: 20,
    architecturePattern: '二重壁二次燃焼エアフロー特許×Kickstarter連続ローンチ×D2C直販',
    pipelineStack: 'Shopify Plus × アジア提携工場 × Meta広告 × Stripe',
    targetPainWallet: 'キャンプから帰った後に服・車・髪から強烈な煙の悪臭が漂い、家族から嫌がられるパパの苦痛',
    tags: ['年商600億', '無煙焚き火', '二次燃焼特許', 'Kickstarter発', 'ナスダック上場'],
    currency: 'USD',
    annualRevenueRaw: 400000000,
    grossMarginPct: 62.0,
    operatingMarginPct: 12.0,
    snapshotYear: 2024,
    revenueSourceNote: 'Solo Brands (NYSE: DLC) 年間決算報告 売上高約4億ドル',
    teamSize: 350,
    blindspot: '人間は「火」を見るのが大好きだが、「煙」は死ぬほど嫌悪している。煙が出ない焚火台を作るだけで、庭先BBQという巨大市場が開拓された。',
    moatType: 'PROCESS_POWER',
    moatDescription: '美しいステンレス円筒デザインと、煙を極限まで燃やし尽くす二次燃焼構造の特許群。',
    initialTraction: ['Kickstarterで小型ストーブを出品し小規模黒字化', '裏庭で煙が出ない焚き火動画をFacebook広告で流し全米の住宅街に爆発普及'],
    actionPlaybook: ['太古からの人間の本能（火を見つめたい）から「付随する苦痛（煙・臭い）」だけを物理的に切除する', 'Kickstarterで初期ロットの製造資金を客から前払いさせる', 'ピザ窯や専用アクセサリを追加販売してLTVを引き上げる'],
    targetPrey: '一戸建ての庭を持つ米国のファミリー層、キャンパー',
    structuralFlaw: '伝統的なキャンプギア企業は「持ち運びの軽さ」ばかり重視し、庭先で据え置きで使う「大型・無煙」の需要を見落としていた。',
    stealthEntry: '小型のバックパック用ストーブから始め、庭用の超大型サイズ「Bonfire」で一気にマス層へブレイクスルー。',
    tollGateSetup: '$250〜$600の焚火台本体＋専用ペレット・スタンドのセット販売。',
    observations: ['【サバンナOSの苦痛切除】火を囲みたい欲望と煙を避けたい防衛本能。この2つの摩擦をゼロにした製品は爆発的に売れる。']
  },

  // 23. Stanley 1913
  {
    id: 'ent_stanley_1913_13',
    ticker: 'STANLY',
    name: 'Stanley 1913',
    tagline: '「100年間おじいちゃんの作業用だった魔法瓶」をTikTokで女子向けパステルカラーに塗り替えた瞬間、年商¥100億円から¥1,100億円へ10倍大爆発したトレンドジャック',
    sector: 'PHYSICAL_ASSET',
    scale: 'ENTERPRISE',
    founder: 'William Stanley Jr. (現CEO: Terence Reilly)',
    country: 'US',
    url: 'https://www.stanley1913.com',
    growthRateYoY: 200,
    architecturePattern: '100年の真空断熱金型×女性インフルエンサーブログ提携×限定カラー数量限定ドロップ（飢餓商法）',
    pipelineStack: 'Shopify × Target店舗独占展開 × TikTok Shop × Stripe',
    targetPainWallet: '「可愛いタンブラーを持って学校やオフィスに行き、SNSで仲間外れになりたくない」女子中高生・女性の同調圧力と承認欲求',
    tags: ['年商1100億', 'TikTokメガヒット', '100年ブランド再生', 'Quencherブーム', '飢餓商法'],
    currency: 'USD',
    annualRevenueRaw: 750000000,
    grossMarginPct: 65.0,
    operatingMarginPct: 25.0,
    snapshotYear: 2024,
    revenueSourceNote: 'CNBC / Forbes報道 年商約7.5億ドル（約1,100億円）へ急拡大',
    teamSize: 500,
    blindspot: '車のドリンクホルダーにすっぽり収まる大容量（40オンス/1.2L）ストロー付き水筒という実用性が、子育て中のママや働く女性のライフスタイルに完全適合していた。',
    moatType: 'BRAND_PRESTIGE',
    moatDescription: 'TikTokで数十億回再生された「Stanley Quencher」の文化的ブーム。スニーカーのように限定カラーをコレクションする熱狂。',
    initialTraction: ['女性向け買い物ブログ「The Buy Guide」がStanleyに直談判し、廃番寸前のQuencherを限定色で再販させて即完売', '元クロックスの仕掛け人Terence ReillyがCEOに就任しカラー戦略を一気に加速'],
    actionPlaybook: ['機能は完成しているがマーケティングが死んでいる「眠れる老舗ブランド」を買収・提携する', 'ターゲットを「ブルーカラーの男性」から「流行を作れる若い女性」へ180度ピボットする', 'スニーカーと同じ「限定色の数量限定ドロップ」を連発して行列と転売熱狂を作る'],
    targetPrey: 'TikTokを見るZ世代の女子学生、ヨガやジムに通う女性',
    structuralFlaw: '水筒メーカー（象印、タイガー、サーモス等）は実用性ばかりを宣伝し、「ファッションアイテム・自己表現」としての見せ方ができなかった。',
    stealthEntry: '車のドリンクホルダーに入る「底が細い」独特の形状で、ドライブスルーや毎日の通勤の必需品として入り込んだ。',
    tollGateSetup: '1本$45〜$55の定価販売。原価数百円の粗利爆撃。',
    observations: ['【サバンナOSの同調圧力と排除恐怖】「みんなが持っているStanleyを持っていないと恥ずかしい」という社会的証明の炎上により、水筒が年間1,000億円のドル箱へ化けた。']
  },

  // 24. Brumate
  {
    id: 'ent_brumate_14',
    ticker: 'BRUMAT',
    name: 'Brumate',
    tagline: '「最後の一口までビールがぬるくならない」缶保冷ホルダーを21歳が立ち上げ、外部資金ゼロで年商¥150億円を抜く冷たいビールの関所',
    sector: 'PHYSICAL_ASSET',
    scale: 'SMALL_TEAM',
    founder: 'Dylan Jacob（21歳ソロ起業家）',
    country: 'US',
    url: 'https://brumate.com',
    growthRateYoY: 35,
    architecturePattern: '細缶（ホワイトクロー特化）真空断熱ホルダー特許×D2C急成長×アルコール愛好家ターゲティング',
    pipelineStack: 'Shopify Plus × 中国提携工場 × Meta/TikTok広告 × Stripe',
    targetPainWallet: 'ビーチやテラスでビールを飲んでいる最中に、気温でぬるくなって不味くなる酒飲みの激痛',
    tags: ['21歳ブートストラップ', '年商150億', 'ビール缶クーラー', '外部資金ゼロ', '高粗利D2C'],
    currency: 'USD',
    annualRevenueRaw: 100000000,
    grossMarginPct: 65.0,
    operatingMarginPct: 22.0,
    snapshotYear: 2024,
    revenueSourceNote: 'Forbes 30 Under 30取材 年商1億ドル規模・外部資金ゼロ',
    teamSize: 30,
    blindspot: 'ハードセルツァー（ホワイトクロー）という細長いスリム缶のアルコールが全米で大流行したのに、従来の缶ホルダーはすべて太い通常缶用しかなかった。',
    moatType: 'PROCESS_POWER',
    moatDescription: 'スリム缶にジャストフィットする押し込み式ロック構造の特許と、お酒専用のタンブラー（ワイン用、シャンパン用）のニッチ独占。',
    initialTraction: ['Facebookのアルコール愛好家グループに向けて「最初から最後まで氷点下」の動画広告を配信', '女性向けにキラキラしたグリッターカラーを出して爆発的人気'],
    actionPlaybook: ['アルコールや嗜好品という「客が理性を失って金を払う領域」に特化する', '新しい規格やトレンド（スリム缶の台頭）に真っ先に専用アクセサリを作る', '外部資本を入れずに利益率65%のD2Cで現金を再投資し続ける'],
    targetPrey: 'ビール、ワイン、ハードセルツァーを愛飲する20〜40代男女',
    structuralFlaw: 'YETIなどの巨人は保守的で、「スリム缶専用」のような尖ったニッチ製品を出すスピードが遅かった。',
    stealthEntry: 'ガラス瓶のビールを隠してビーチで飲める保冷タンブラーからスタート。',
    tollGateSetup: '$25〜$45のD2Cアクセサリ販売。まとめ買い割引で客単価$80を維持。',
    observations: ['【トレンドの波乗りコバンザメ】ホワイトクロー（スリム缶）の世界的流行を予測し、その専用ケースを作るだけで20代の若者が年商150億の富豪へ成り上がった。']
  },

  // 25. Vuori
  {
    id: 'ent_vuori_15',
    ticker: 'VUORI',
    name: 'Vuori',
    tagline: '「ルルレモンのヨガパンツが羨ましいが女物で履けない」男たちの密かな嫉妬を極上の肌触りショートパンツで救済し、評価額¥7,500億円へ成り上がったメンズアクティブウェア',
    sector: 'PHYSICAL_ASSET',
    scale: 'SCALEUP',
    founder: 'Joe Kudla（元モデル・会計士）',
    country: 'US',
    url: 'https://vuoriclothing.com',
    growthRateYoY: 60,
    architecturePattern: '極上の肌触り独自ファブリック（DreamKnit）×ヨガ・サーフ・フィットネス統合×D2C+直営店舗展開',
    pipelineStack: 'Shopify Plus × 直営ブティック × ソフトバンク・ビジョン・ファンド出資',
    targetPainWallet: 'ナイキやアディダスのゴワゴワした化繊パンツに嫌気がさし、極上の部屋着兼トレーニングウェアを求める男の快適性への執着',
    tags: ['評価額7500億', 'ルルレモンメンズ版', 'DreamKnit', 'ソフトバンク出資', '急成長アパレル'],
    currency: 'USD',
    annualRevenueRaw: 1000000000, // 年商10億ドル規模
    grossMarginPct: 68.0,
    operatingMarginPct: 20.0,
    snapshotYear: 2024,
    revenueSourceNote: 'SoftBank Vision Fund 2出資時評価額40億ドル・2024年IPO準備報道',
    teamSize: 1500,
    blindspot: 'ルルレモンは女性市場を支配していたが、男性向けは「おまけ」程度にしか作っておらず、男性が堂々と入れるヨガ・リラックスウェアの聖地が空席だった。',
    moatType: 'BRAND_PRESTIGE',
    moatDescription: '一度触ると二度と他を履けなくなる「DreamKnit」ファブリックと、カリフォルニア沿岸のスマートな生活様式ブランド。',
    initialTraction: ['地元のヨガスタジオやサーフショップに製品を置き、インストラクターに無料で履かせる', '女性が夫や彼氏へのギフトとして買い始めたことでバイラル拡大'],
    actionPlaybook: ['女性市場で大成功したビジネスモデル（ルルレモン）を「男性向け」に翻訳する', '素材の「肌触り（触覚の快楽）」に極限までこだわり、試着した瞬間に即決させる', '店舗で体験させ、D2Cでリピートさせるオムニチャネルを組む'],
    targetPrey: 'フィットネスやサーフィンを愛し、心地よい暮らしを求める高所得男性',
    structuralFlaw: '伝統的スポーツブランド（ナイキ、アンダーアーマー）は「過酷なアスリートの汗」ばかり強調し、リラックスと日常着を兼ねた快適性を無視していた。',
    stealthEntry: '海でも履けてジムでも履けてそのままカフェに行ける「Kore Short」1本で勝負。',
    tollGateSetup: '$68〜$120の高価格帯パンツ。',
    observations: ['【触覚のサバンナOS直撃】人間は「肌触りが最高に気持ちいい」ものに理性を失う。一度履いたらナイキに戻れない身体を作って生涯顧客にする。']
  }
];
