import type { RawWinnerDef } from './generate-100-winners-data';

export const PART1_DEFS: RawWinnerDef[] = [
  // 1. PDF.ai
  {
    id: 'ent_pdf_ai_8a12',
    ticker: 'PDF.AI',
    name: 'PDF.ai',
    tagline: '「長文PDFを読むのが死ぬほど苦痛な人間」にPDFを要約・対話させ、完全1人で月商¥600万・利益率85%を抜くAIドキュメント関所',
    sector: 'AI_AUTOMATION',
    scale: 'SOLO',
    founder: 'Damon Chen（元シスコエンジニア・完全1人開発）',
    country: 'US',
    url: 'https://pdf.ai',
    growthRateYoY: 300,
    architecturePattern: 'PDFパース×ベクトル検索（LangChain/Pinecone）×ChatGPT推論ラッパー',
    pipelineStack: 'Next.js × Supabase × Pinecone × OpenAI API × Stripe',
    targetPainWallet: '契約書・学術論文・決算書を1ページずつ読むのが苦痛なビジネスマンの極限の怠惰',
    tags: ['完全1人開発', '月商600万', '利益率85%', 'PDF要約', 'バイラルローンチ'],
    currency: 'USD',
    annualRevenueRaw: 480000, // $40k/mo
    grossMarginPct: 90.0,
    operatingMarginPct: 85.0,
    snapshotYear: 2024,
    revenueSourceNote: '創業者Damon Chen公開Stripeスクショ（月商$40K ARR $500K突破）',
    teamSize: 1,
    blindspot: 'ChatGPT公式ではPDFのアップロードとピンポイント参照が当初できず、誰もがPDFの中身を瞬時に要約させたがっていた。',
    moatType: 'BRAND_PRESTIGE',
    moatDescription: '超強力なドメイン「PDF.ai」を早期取得し、SEOとTwitterバイラルで圧倒的な先行者認知を獲得。',
    initialTraction: ['TwitterでPDFを瞬時にチャット化するデモ動画を投稿し数百万インプレッション獲得', 'Product Huntで1位獲得', 'TikTokクリエイターに契約書要約動画を依頼しバイラル拡散'],
    actionPlaybook: ['誰もが扱うファイル形式（PDF, Excel, Word）×AI対話の隙間を突く', '強力なプレミアムドメイン（.ai）を抑えてSEOの関所を作る', '無料枠で2ページ読ませてから月額$15の年払いに誘導する'],
    targetPrey: '長文PDFを読まされる学生・弁護士・リサーチャー',
    structuralFlaw: '大手PDFリーダー（Adobe等）は機能が重すぎてAI対話への対応が遅れていた。',
    stealthEntry: 'ブラウザにPDFをドラッグ＆ドロップするだけの極限にシンプルなUIで参入。',
    tollGateSetup: '月$15のサブスクリプション課金。解約忘れを狙う無痛価格。',
    observations: ['【通帳手残り実額】OpenAI APIの推論費用は売上の5%未満。月商600万円に対し、創業者1人の手残りは月500万円超。']
  },

  // 2. Testimonial.to
  {
    id: 'ent_testimonial_to_7b23',
    ticker: 'TESTIM',
    name: 'Testimonial.to',
    tagline: '「顧客の推薦の声を集めるのが面倒」な全ビジネスから動画レビューを自動回収・埋め込みさせ、完全1人で年商¥1億円・利益率82%を抜く社会的証明関所',
    sector: 'NICHE_SAAS',
    scale: 'SOLO',
    founder: 'Damon Chen（ソロプレナー）',
    country: 'US',
    url: 'https://testimonial.to',
    growthRateYoY: 120,
    architecturePattern: '動画録画ウィジェット×CDN配信×埋め込みウォール・オブ・ラブ',
    pipelineStack: 'Next.js × Cloudflare Stream × Firebase × Stripe',
    targetPainWallet: '自社サービスを売りたい創業者の「社会的証明（レビュー）が集まらない」という焦燥と集客不安',
    tags: ['完全1人開発', '年商1億', '動画レビュー', 'ウォールオブラブ', '高利益率'],
    currency: 'USD',
    annualRevenueRaw: 700000,
    grossMarginPct: 90.0,
    operatingMarginPct: 82.0,
    snapshotYear: 2024,
    revenueSourceNote: 'IndieHackers公開メトリクス ARR $700K',
    teamSize: 1,
    blindspot: '客にテキストでレビューを頼んでも無視されるが、「スマホで1分動画を撮るだけ」のリンクを送ると投稿率が跳ね上がる。',
    moatType: 'SWITCHING_COST',
    moatDescription: '集まったレビュー動画が自社サイトの「Wall of Love」として埋め込まれているため、解約するとサイトの信頼性が即死する監禁構造。',
    initialTraction: ['Twitterで制作実況を行い、インディーハッカー界隈のインフルエンサーに無料で使わせる', '無料版埋め込みウィジェットに「Collected by Testimonial」のバイラル導線を設置'],
    actionPlaybook: ['「集めるのが面倒なもの（推薦、事例、アンケート）」の収集リンクを作る', '埋め込みウィジェットに自社リンクを貼って客に勝手に宣伝させる', '集めたデータを人質にして解約を不可能にする'],
    targetPrey: 'コンバージョン率を上げたいSaaS創業者やコース販売者',
    structuralFlaw: '大手CRMやフォームツールはテキスト中心で、手軽な動画レビュー収集に特化していなかった。',
    stealthEntry: 'TwitterのDMで「あなたのツールのための動画レビュー集めツールを作りました」と直談判。',
    tollGateSetup: '月$20〜$79の継続サブスク課金。',
    observations: ['【監禁の重力】レビュー動画は顧客資産そのもの。他社ツールへ移行する手間が膨大で解約率が極めて低い。']
  },

  // 3. SiteGPT
  {
    id: 'ent_sitegpt_9c34',
    ticker: 'SITE.GPT',
    name: 'SiteGPT',
    tagline: '「WebサイトのURLを入れるだけで自社専用AIチャットボットが完成」する超怠惰UIで、完全1人で年商¥4,500万・利益率80%を抜くカスタマーサポート関所',
    sector: 'AI_AUTOMATION',
    scale: 'SOLO',
    founder: 'Bhanu Teja Pachipulusu（インド在住・完全1人開発）',
    country: 'IN',
    url: 'https://sitegpt.ai',
    growthRateYoY: 250,
    architecturePattern: 'サイトクローラー×ベクトルDB×ChatGPT質問応答埋め込みウィジェット',
    pipelineStack: 'Next.js × Pinecone × OpenAI API × Paddle',
    targetPainWallet: '深夜・休日のカスタマー問い合わせに追われて寝られない中小企業オーナーの睡眠不足と人件費激痛',
    tags: ['完全1人開発', '年商4500万', 'カスタマーサポートAI', 'URL即ボット化', '高利益率'],
    currency: 'USD',
    annualRevenueRaw: 300000,
    grossMarginPct: 88.0,
    operatingMarginPct: 80.0,
    snapshotYear: 2024,
    revenueSourceNote: '創業者Bhanu Teja公開Xポスト ARR $300K達成',
    teamSize: 1,
    blindspot: '大企業向けチャットボット導入は数百万円と数ヶ月の設定が必要だったが、中小企業は「URLを入れたら今すぐ動く」ものだけを求めていた。',
    moatType: 'COUNTER_POSITIONING',
    moatDescription: '月$19からの低価格で即日導入。大手サポートツール（Zendesk等）が高単価コンサルを売る中で完全セルフサーブで対抗。',
    initialTraction: ['ChatGPTブーム初期に「URLを入れるだけで動く」画面動画をTwitterで公開', 'Product HuntでTop 3入賞'],
    actionPlaybook: ['複雑なエンタープライズ製品を「URL1本・入力1つ」の極限の怠惰UIに落とし込む', 'オープンソースやAPIを組み合わせて1週間でMVPを作る', '月額サブスクで前金を回収する'],
    targetPrey: '24時間問い合わせ対応に苦しむEC・SaaS運営者',
    structuralFlaw: '大手のサポートAIは設定が複雑で、エンジニアがいない中小企業は導入できなかった。',
    stealthEntry: '「エンジニア不要・コード不要・URLを入れるだけ」で訴求。',
    tollGateSetup: 'チャット回数に応じた月額従量課金。',
    observations: ['【サバンナOS直撃】「自分でマニュアルを作るのは死ぬほど面倒だが、URLを入れるだけならやる」という極限の怠惰を突いた大勝利。']
  },

  // 4. Feather.so
  {
    id: 'ent_feather_so_4d56',
    ticker: 'FEATHR',
    name: 'Feather.so',
    tagline: '「Notionのデータベースを書くだけで超高速ブログが立ち上がる」コバンザメ配管で、完全1人で年商¥1,500万・利益率88%を抜くNotion寄生ビジネス',
    sector: 'NICHE_SAAS',
    scale: 'SOLO',
    founder: 'Bhanu Teja Pachipulusu（ソロプレナー）',
    country: 'IN',
    url: 'https://feather.so',
    growthRateYoY: 100,
    architecturePattern: 'Notion API×静的HTML生成（SSG）×高速CDNブログホスティング',
    pipelineStack: 'Next.js × Cloudflare Workers × Notion API × Stripe',
    targetPainWallet: 'WordPressのプラグイン地獄や管理画面の重さに絶望したクリエイターの執筆ストレス',
    tags: ['完全1人開発', 'Notionコバンザメ', '利益率88%', 'ブログ自動化', '年商1500万'],
    currency: 'USD',
    annualRevenueRaw: 100000,
    grossMarginPct: 95.0,
    operatingMarginPct: 88.0,
    snapshotYear: 2024,
    revenueSourceNote: '創業者公開メトリクス ARR $100K',
    teamSize: 1,
    blindspot: '多くの人がNotionでメモを書いているのに、それをブログとして公開するにはWordPress等にコピペする二度手間が発生していた。',
    moatType: 'SWITCHING_COST',
    moatDescription: 'Notion内でブログ記事が数百本蓄積されるため、一度Featherに繋ぐと他社へ乗り換える理由が消滅する。',
    initialTraction: ['NotionコミュニティやTwitterのNotionファンに向けてデモ動画を公開', '無料版フッターに「Powered by Feather」リンクを設置'],
    actionPlaybook: ['巨大プラットフォーム（Notion, Figma, Slack）の熱狂的ユーザーが抱える「あと一歩足りない」不満を特定する', 'APIで連携して二度手間を切除するツールを作る', 'プラットフォームのエコシステム内で口コミを広げる'],
    targetPrey: '日常的にNotionで思考・メモを書いているブロガー・創業者',
    structuralFlaw: 'Notion公式は多機能ノートであり、SEOに最適化されたブログ公開エンジンには注力していなかった。',
    stealthEntry: 'Notionのテンプレート配布と見せかけてFeatherを抱き合わせで提案。',
    tollGateSetup: '月$39または年払いの固定サブスク。',
    observations: ['【寄生の極意】Notionという巨人の背中に吸盤を貼り、Notionが広がるほど何もしなくても新規顧客が流入する。']
  },

  // 5. Chatbase
  {
    id: 'ent_chatbase_6e78',
    ticker: 'CHATBS',
    name: 'Chatbase',
    tagline: '「自社のPDFやドキュメントをアップするだけで独自AIチャットボットを作る」仕組みで、22歳が完全1人で月商¥4,500万・利益率85%を叩き出したAPIラッパーの王者',
    sector: 'AI_AUTOMATION',
    scale: 'SOLO',
    founder: 'Yousef ElDanasoury（カナダ在住・22歳ソロプレナー）',
    country: 'CA',
    url: 'https://chatbase.co',
    growthRateYoY: 500,
    architecturePattern: 'ドキュメント埋め込みベクトル検索×マルチテナントUI×ChatGPTラッパー',
    pipelineStack: 'Next.js × Pinecone × LangChain × OpenAI API × Stripe',
    targetPainWallet: '「自社データを学習させたAIが欲しいが、エンジニアを雇う予算（数百万円）がない」企業の焦燥',
    tags: ['22歳完全1人', '月商4500万', '利益率85%', 'AIラッパー王者', 'ARR $3M'],
    currency: 'USD',
    annualRevenueRaw: 3600000, // $300k/mo
    grossMarginPct: 90.0,
    operatingMarginPct: 85.0,
    snapshotYear: 2024,
    revenueSourceNote: '創業者Yousef公開Stripeダッシュボード MRR $300K達成（年商約5.4億円）',
    teamSize: 1,
    blindspot: '誰もが「自社専用のChatGPT」を欲しがっていたが、ファインチューニングやRAG（検索拡張生成）の構築難易度が高すぎた。',
    moatType: 'BRAND_PRESTIGE',
    moatDescription: 'ChatGPT API公開初週に最速でローンチし、TwitterとTikTokで「自社専用AIボット」の代名詞としての地位を独占。',
    initialTraction: ['ChatGPT API公開直後に48時間でプロトタイプを作りTwitterでローンチ', 'TikTokで「会社の全マニュアルをAIに読ませてみた」動画が数百万再生'],
    actionPlaybook: ['APIの新機能発表の瞬間に寝ずに48時間でラッパーを作る', '「誰でもドラッグ＆ドロップでできる」UIに削ぎ落とす', '月$19〜$399の複数プランを用意し大企業からも小遣い感覚で前金を抜く'],
    targetPrey: '自社サイトにAIチャットボットをつけたい世界中のWebサイトオーナー',
    structuralFlaw: 'OpenAI公式は開発者向けAPIしか提供しておらず、非エンジニア向けのエンドツーエンドUIが存在しなかった。',
    stealthEntry: '「無料枠で10万文字まで試せる」フリーミアムで初期10万ユーザーを強奪。',
    tollGateSetup: '月額サブスクリプション課金。高額なエンタープライズプランも無人セルフサーブ。',
    observations: ['【通帳手残り実額】月商4,500万円に対し、OpenAI API代とサーバー代は月400万円程度。22歳創業者の手元に毎月4,000万円前後の現金が着金。']
  },

  // 6. Rewind AI
  {
    id: 'ent_rewind_ai_1f90',
    ticker: 'REWIND',
    name: 'Rewind AI',
    tagline: '「Macで見た・聞いた・言ったすべての記憶をローカル録画して検索可能にする」究極の健忘症救済で、評価額500億円・ARR数億円を抜く個人記憶OS',
    sector: 'AI_AUTOMATION',
    scale: 'SMALL_TEAM',
    founder: 'Dan Siroker（元Optimizely創業者・オバマ陣営元ディレクター）',
    country: 'US',
    url: 'https://rewind.ai',
    growthRateYoY: 200,
    architecturePattern: 'MacスクリーンOCR×ローカル音声文字起こし（Whisper）×ローカルベクトルインデックス',
    pipelineStack: 'Swift × Apple Silicon Metal × Whisper × SQLite × Stripe',
    targetPainWallet: '「あの資料どこだっけ？」「先週のMTGで何て言ってたっけ？」と思い出せないビジネスマンの脳疲労と恐怖',
    tags: ['評価額500億', 'Mac完全ローカル', '記憶の検索', 'Whisper内蔵', '高単価サブスク'],
    currency: 'USD',
    annualRevenueRaw: 5000000,
    grossMarginPct: 92.0,
    operatingMarginPct: 75.0,
    snapshotYear: 2024,
    revenueSourceNote: 'TechCrunch / a16z出資ラウンド評価額$350Mメトリクス',
    teamSize: 10,
    blindspot: 'クラウドにデータを送るとプライバシー問題で拒絶されるが、「Apple Siliconのローカル処理だから外部に一切送信しない」とすると富裕層が即決する。',
    moatType: 'PROCESS_POWER',
    moatDescription: 'Macのディスプレイ描画を圧縮率数千分の一で軽量録画・ローカルOCRする高度なネイティブ最適化技術。',
    initialTraction: ['創業者のDan SirokerがTwitterで「失われた記憶を完全に取り戻すツール」として予告動画を出し熱狂を生む', 'Sam Altmanが出資したことで権威性を獲得'],
    actionPlaybook: ['「プライバシーが絶対に漏れないローカル処理」を旗印にする', '日常の「思い出せない」という認知摩擦を切除する', '月$29という高単価な「脳のバックアップ代」を請求する'],
    targetPrey: '大量のZoom会議やSlackチャットに溺れる経営者・投資家・ナレッジワーカー',
    structuralFlaw: 'Appleはプライバシーを理由に全画面録画検索機能を標準OSに組み込んでいなかった。',
    stealthEntry: '「自分自身の難聴体験から生まれた記憶補助ツール」という強烈な創業ナラティブで支持を獲得。',
    tollGateSetup: '月$29の年間前払いプラン。',
    observations: ['【知覚価値の極致】「月数千円で自分の脳の記憶が永久に消えない」と思わせることで、価格競争を無力化。']
  },

  // 7. Cursor
  {
    id: 'ent_cursor_ai_3b89',
    ticker: 'CURSOR',
    name: 'Cursor (Anysphere)',
    tagline: '「VS Codeを丸ごとフォークし、コードベース全体を理解してワンクリックで改修する」AIネイティブエディタで、ARR ¥150億円を突破した急成長モンスター',
    sector: 'AI_AUTOMATION',
    scale: 'SMALL_TEAM',
    founder: 'Michael Truell, Sualeh Asif, Arvid Lunnemark, Aman Sanger（MIT発）',
    country: 'US',
    url: 'https://cursor.com',
    growthRateYoY: 1000,
    architecturePattern: 'VS Codeオープンソースフォーク×高速コードインデクシング×Claude 3.5 Sonnet直結',
    pipelineStack: 'TypeScript × C++ × VS Code Core × Anthropic API × Stripe',
    targetPainWallet: 'ライブラリ変更やリファクタリングで何時間も残業させられる世界中数千万人のエンジニアの苦痛',
    tags: ['ARR 150億超', 'VS Codeフォーク', 'MIT発', '世界最速成長SaaS', 'プログラミング革命'],
    currency: 'USD',
    annualRevenueRaw: 100000000, // ARR $100M+
    grossMarginPct: 75.0,
    operatingMarginPct: 50.0,
    snapshotYear: 2024,
    revenueSourceNote: '2024年TechCrunch報道 ARR $100M突破・評価額25億ドル',
    teamSize: 20,
    blindspot: 'GitHub Copilotは「単なる行補完プラグイン」に留まっていたが、エンジニアは「プロジェクト全体を横断して一気に書き換えてくれる」体験を渇望していた。',
    moatType: 'SWITCHING_COST',
    moatDescription: '「エディタそのもの」を握っているため、ショートカット・設定・キーバインド・ワークフローすべてがCursorにロックインされる。',
    initialTraction: ['VS Code設定を1クリックで完全インポートできる動線を敷き、移行摩擦をゼロにする', 'Twitterでトップエンジニアが「もう元に戻れない」と絶賛の声を連鎖拡散'],
    actionPlaybook: ['デファクトスタンダードのOSS（VS Code）を丸ごとフォークして機能を追加する', 'ワンクリックで既存環境を完全複製させて移行の壁を消す', '月$20でエンジニアの残業時間を数十時間削減し「会社経費で即決」させる'],
    targetPrey: '締め切りに追われる全世界のソフトウェアエンジニア',
    structuralFlaw: 'Microsoft（VS Code/Copilot保有）は自社製品同士の社内政治と既存Copilot売上保護でエディタ自体の破壊的再構築が遅れた。',
    stealthEntry: '「VS Codeの拡張機能」ではなく「VS Codeそのものを置き換える独立アプリ」として突如登場。',
    tollGateSetup: '月$20のProプラン、企業向け月$40プラン。経費精算されやすい価格帯。',
    observations: ['【大手の自爆構造】Microsoftが独占していたVS Codeを、MITの若手4人がオープンソースの規約通りにフォークして中身を乗っ取った資本主義の鮮やかな下克上。']
  },

  // 8. Perplexity AI
  {
    id: 'ent_perplexity_ai_5c78',
    ticker: 'PRPLX',
    name: 'Perplexity AI',
    tagline: '「広告とSEOアフィリエイトだらけでゴミ化したGoogle検索」を粉砕し、直接答えと一次出典だけを返して年商¥120億円・評価額1兆円超へ成り上がったAI検索',
    sector: 'AI_AUTOMATION',
    scale: 'SCALEUP',
    founder: 'Aravind Srinivas（元OpenAI・DeepMindリサーチャー）',
    country: 'US',
    url: 'https://perplexity.ai',
    growthRateYoY: 600,
    architecturePattern: 'ライブWebクロール×LLM要約×出典インライン脚注引用パイプライン',
    pipelineStack: 'Python × Custom Search Index × Anthropic/OpenAI API × Stripe',
    targetPainWallet: 'Googleで検索しても広告とアフィリエイト記事を5回スクロールしないと答えに辿り着けない現代人の激痛と時間の浪費',
    tags: ['Googleキラー', '年商120億', '評価額1兆円', '直接回答', 'ジェフベゾス出資'],
    currency: 'USD',
    annualRevenueRaw: 80000000,
    grossMarginPct: 70.0,
    operatingMarginPct: 35.0,
    snapshotYear: 2024,
    revenueSourceNote: '2024年メディア各社報道 ARR $80M突破 / 評価額$9Bラウンド',
    teamSize: 55,
    blindspot: 'Googleは検索結果ページの「広告クリック」で稼いでいるため、「広告を見せずに1秒で直接答えを出す」と自社の売上（年2,000億ドル）を自爆してしまう。',
    moatType: 'COUNTER_POSITIONING',
    moatDescription: 'Googleが絶対に真似できない「広告ゼロ・直接回答・出典引用」という究極のカウンターポジショニング。',
    initialTraction: ['Twitterで知識人やエンジニア向けに「学術論文や技術仕様の即答デモ」を投稿', 'ジェフ・ベゾスやNVIDIAからの巨額出資で信頼性を確立'],
    actionPlaybook: ['業界王者が「広告モデル」で稼いでいる領域に、「サブスク直接回答」で逆張りする', '一次出典リンクを必ず明記してハルシネーション（嘘）の不安を切除する', '月$20のProプランでClaude 3.5 Sonnetなどの最新モデルを使い放題にする'],
    targetPrey: 'リサーチ業務に追われるビジネスマン・アナリスト・投資家',
    structuralFlaw: 'Googleは既存の検索連動型広告収益が巨大すぎて、ゼロクリック検索への完全移行が構造的に不可能だった。',
    stealthEntry: 'Chrome拡張機能で「検索バーをPerplexityに置き換える」ハックで日常の導線を強奪。',
    tollGateSetup: '月$20のProサブスクリプション。',
    observations: ['【大企業のイノベーションのジレンマ】Googleが気づいていても手を打てない「既存売上カニバリズム」の死角を突いて、一晩で数千億円の市場を強奪。']
  },

  // 9. ElevenLabs
  {
    id: 'ent_elevenlabs_9d12',
    ticker: 'ELEVEN',
    name: 'ElevenLabs',
    tagline: '「1分間の音声サンプルから本人そっくりの感情豊かな音声をクローンする」技術で、声優・ナレーション業界をディスラプトし年商¥120億円・評価額5,000億円へ成り上がった音声AI',
    sector: 'AI_AUTOMATION',
    scale: 'SCALEUP',
    founder: 'Piotr Dabkowski & Mati Staniszewski（元Google/Palantirエンジニア・ポーランド出身）',
    country: 'US',
    url: 'https://elevenlabs.io',
    growthRateYoY: 500,
    architecturePattern: '深層音声合成モデル×話者感情埋め込み×音声マーケットプレイス',
    pipelineStack: 'Python × PyTorch × AWS GPU Cluster × Stripe',
    targetPainWallet: 'YouTube動画やオーディオブックで、声優を雇う予算（数十万円）とスタジオ収録の時間がないクリエイターの激痛',
    tags: ['音声AI王者', '年商120億', '評価額5000億', '音声クローン', '声のマーケットプレイス'],
    currency: 'USD',
    annualRevenueRaw: 80000000,
    grossMarginPct: 80.0,
    operatingMarginPct: 45.0,
    snapshotYear: 2024,
    revenueSourceNote: '2024年メディア報道 ARR $80M突破 / a16z出資評価額$3B+',
    teamSize: 50,
    blindspot: '従来の機械音声はロボット感があり動画で使えなかったが、「ため息や笑い声、息継ぎ」まで再現すると人間と区別がつかなくなり即決される。',
    moatType: 'NETWORK_EFFECT',
    moatDescription: '声優が自分の声を登録して他人に使わせ、使われた分だけ印税が入る「声のマーケットプレイス」エコシステム。',
    initialTraction: ['TikTokやYouTubeで「有名人の声で喋らせる」デモ動画が世界中で爆発的バイラル', 'オーディオブック出版社との一括提携'],
    actionPlaybook: ['人間の五感（声、顔）のクローン技術を極限まで自然にする', '月$5〜$330の従量課金で小規模YouTuberから映画スタジオまで全方位から集金する', '声の提供者に印税を払う仕組みでコンテンツ供給の堀を作る'],
    targetPrey: '動画クリエイター、ゲーム開発者、オーディオブック出版社',
    structuralFlaw: '大手クラウド（AWS Polly, Google Cloud TTS）は無機質な読み上げに留まり、クリエイティブ表現を無視していた。',
    stealthEntry: '無料枠で月10,000文字まで生成させ、一度「リアルな声」の味を占めさせてから課金させる。',
    tollGateSetup: '月額キャラクター数・生成文字数に応じた従量サブスク。',
    observations: ['【不可逆な知覚価値】一度ElevenLabsの感情豊かな声で動画を作ると、従来のロボット音声には二度と戻れない。']
  },

  // 10. Leonardo.ai
  {
    id: 'ent_leonardo_ai_7e34',
    ticker: 'LEONRD',
    name: 'Leonardo.ai',
    tagline: '「ゲームや映画のキャラクター・アセットを絵柄の一貫性を保ったまま量産できる」画像生成AIで、創業1年半で年商¥15億円・Canvaに数億ドルで巨額売却されたオーストラリアの成り上がり',
    sector: 'AI_AUTOMATION',
    scale: 'SMALL_TEAM',
    founder: 'JJ Fiasson（ゲーム開発者出身）',
    country: 'AU',
    url: 'https://leonardo.ai',
    growthRateYoY: 800,
    architecturePattern: 'Stable Diffusion微調整×アセット特化ファインチューニング×Web UIキャンバス',
    pipelineStack: 'Python × Stable Diffusion × AWS GPU × Stripe',
    targetPainWallet: 'ゲーム開発で何百枚ものアイテムやキャラを描くイラストレーターの工数と数千万円の外注費激痛',
    tags: ['Canva巨額買収', '年商15億', 'ゲームアセット特化', '絵柄一貫性', 'オーストラリア発'],
    currency: 'USD',
    annualRevenueRaw: 10000000,
    grossMarginPct: 75.0,
    operatingMarginPct: 40.0,
    snapshotYear: 2024,
    revenueSourceNote: '2024年Canvaによる買収時公表メトリクス（有料会員急増・ARR $10M規模）',
    teamSize: 40,
    blindspot: 'MidjourneyはDiscord上でしか動かず、絵柄の一貫性（同じキャラクターの別ポーズ）を保つのが不可能だった。',
    moatType: 'PROCESS_POWER',
    moatDescription: 'Webブラウザ上の洗練されたキャンバスUIと、自社スタイルを学習させられる独自モデルトレーニング機能。',
    initialTraction: ['Discordを使いたくない非エンジニア向けに美しいWeb UIを提供', 'ゲーム開発者フォーラムで「アセット量産が1日で終わる」と口コミ爆発'],
    actionPlaybook: ['Midjourneyが「Discord運用」という傲慢なUIで放置している隙に、極上のWeb UIで参入する', '「絵柄の一貫性」というクリエイター最大のペインを解決する', '巨大プラットフォーム（Canva等）へのバイアウトを狙う'],
    targetPrey: 'ゲームスタジオ、広告代理店、グラフィックデザイナー',
    structuralFlaw: 'Midjourneyは独自のWebサイトを作らずDiscordに固執し、一般デザイナーの参入障壁になっていた。',
    stealthEntry: '毎日150トークンの無料枠を配り、SNS上で生成画像が勝手にバズる仕組みを構築。',
    tollGateSetup: '月$12〜$60のサブスクリプション課金。',
    observations: ['【大手の盲点】Midjourneyの傲慢（Discord強制）を突いてWeb UIを作るだけで、創業18ヶ月で数百億円のエグジットを達成。']
  }
];
