/**
 * 旧生成パイプラインの定型文リストを作る。
 * 事例名を ◯ に置き換えた文・句が、何件の別事例に同じ形で出るかを数え、
 * THRESHOLD 件以上に出るものを「その事例に固有でない定型文」として
 * src/lib/company-access/template-phrases.json に書き出す。
 * 未確認・出典・推定などの調査状態を述べる文は数えない（表示から消さない）。
 *
 * 使い方: pnpm text:templates [追加の entities-index.json ...]
 */
import { readFile, writeFile } from 'node:fs/promises';
import {
  NARRATIVE_TEXT_PATHS,
  TEMPLATE_SENTENCE_MIN,
  clausesOf,
  entityNames,
  isPhraseClause,
  isProtectedSentence,
  readTextPath,
  sentencesOf,
  templateKey,
  tidyText,
} from '../../src/lib/company-access/natural-text-core';

const THRESHOLD = 20;
const OUTPUT = 'src/lib/company-access/template-phrases.json';

async function main() {
  const inputs = ['data/entities-index.json', ...process.argv.slice(2)];
  const sentences = new Map<string, Set<string>>();
  const clauses = new Map<string, Set<string>>();
  const add = (map: Map<string, Set<string>>, key: string, id: string) => {
    const ids = map.get(key) ?? new Set<string>();
    ids.add(id);
    map.set(key, ids);
  };
  let entityCount = 0;
  for (const input of inputs) {
    const rows: unknown = JSON.parse(await readFile(input, 'utf8'));
    if (!Array.isArray(rows)) throw new Error(`${input} is not an entity array`);
    for (const row of rows) {
      if (!row || typeof row !== 'object' || typeof (row as { id?: unknown }).id !== 'string') continue;
      const entity = row as { id: string };
      entityCount += 1;
      const names = entityNames(entity);
      for (const path of NARRATIVE_TEXT_PATHS) {
        for (const value of readTextPath(entity, path)) {
          for (const sentence of sentencesOf(tidyText(value))) {
            if (isProtectedSentence(sentence)) continue;
            const key = templateKey(sentence, names);
            if (key.length >= TEMPLATE_SENTENCE_MIN) add(sentences, key, entity.id);
            for (const clause of clausesOf(key)) if (isPhraseClause(clause)) add(clauses, clause, entity.id);
          }
        }
      }
    }
  }
  const frequent = (map: Map<string, Set<string>>) => [...map]
    .filter(([, ids]) => ids.size >= THRESHOLD)
    .map(([key]) => key)
    .sort();
  const frequentClauses = frequent(clauses);
  const clauseSet = new Set(frequentClauses);
  // 定型句を含む文は句の一致で消えるので、文としては持たない（ファイルを小さく保つ）
  const frequentSentences = frequent(sentences)
    .filter((key) => !clausesOf(key).some((clause) => isPhraseClause(clause) && clauseSet.has(clause)));
  const output = {
    note: 'Generated by scripts/text/build-template-phrases.ts. Sentences/clauses repeated across many cases are hidden from the display.',
    threshold: THRESHOLD,
    sourceEntities: entityCount,
    sentences: frequentSentences,
    clauses: frequentClauses,
  };
  await writeFile(OUTPUT, `${JSON.stringify(output, null, 1)}\n`);
  console.log(JSON.stringify({ sourceEntities: entityCount, sentences: output.sentences.length, clauses: output.clauses.length }));
}

void main().catch((error) => { console.error(error); process.exitCode = 1; });
