import { categories, evidenceMeta, moneyTypeMeta, opportunities, publicCollections, services } from "../data.js";
import { byId, compactNumber, computeOpportunityScore, escapeHTML, formatDate, formatNumber, portfolioStats, recommendationScore } from "../core.js";
import { badge, collectionCard, emptyState, icon, opportunityCard, pageHeader, serviceCard, statCard } from "../components.js";
import { store } from "../store.js";

export function renderMyGoldmine(){
  const state=store.getState(),stats=portfolioStats(state),saved=opportunities.filter(item=>state.saved.includes(item.id)),watched=opportunities.filter(item=>state.watched.includes(item.id));
  const suggested=opportunities.filter(item=>!state.saved.includes(item.id)).sort((a,b)=>recommendationScore(b,state.preferences)-recommendationScore(a,state.preferences)).slice(0,3);
  return `<main id="main-content" class="main"><div class="page">${pageHeader({eyebrow:"MY GOLDMINE",title:"自分専用の金脈ポートフォリオ",description:"保存するほど、読むだけの情報が『自分が追う市場』へ変わります。",actions:'<a class="btn" href="#/workspace">調査ノート</a><button class="btn btn-primary" data-action="export-state">データを書き出す</button>'})}<div class="grid grid-4">${statCard("保存した金脈",stats.savedCount,"自分の候補")}${statCard("追跡中",stats.watchedCount,"変化を通知")}${statCard("平均スコア",stats.averageScore||"—","保存案件")}${statCard("支払意思",formatNumber(stats.payIntent),"体験用反応合計")}</div><section class="section"><div class="section-head"><div><h2>保存した事業機会</h2><p>次に見るべき変化と最初の行動をまとめます。</p></div><a class="text-link" href="#/opportunities">金脈を追加</a></div>${saved.length?`<div class="grid grid-3">${saved.map(item=>opportunityCard(item)).join("")}</div>`:emptyState("まだ金脈を保存していません","『儲かりそう』と感じた事業機会を保存すると、ここへ集約されます。","vault",'<a class="btn btn-primary" href="#/opportunities">金脈を見る</a>')}</section><section class="section"><div class="section-head"><div><h2>変化を追跡中</h2><p>勢い、根拠、競合、価格、募集が変わると通知。</p></div></div>${watched.length?`<div class="table-wrap"><table><thead><tr><th>市場</th><th>勢い</th><th>総合</th><th>保存</th><th>更新</th></tr></thead><tbody>${watched.map(item=>`<tr data-href="#/opportunities/${item.slug}"><td><strong>${escapeHTML(item.title)}</strong><div class="muted">${escapeHTML(item.category)}</div></td><td class="green">${item.scores.momentum}</td><td class="gold">${computeOpportunityScore(item)}</td><td>${formatNumber(item.stats.saves)}</td><td>${formatDate(item.updatedAt)}</td></tr>`).join("")}</tbody></table></div>`:emptyState("追跡中の市場はありません","事業機会の『変化を追跡』を押すと、更新を通知します。","eye")}</section><section class="section"><div class="section-head"><div><h2>次に保存しそうな金脈</h2><p>選択した条件とこれまでの反応から提案。</p></div></div><div class="grid grid-3">${suggested.map(item=>opportunityCard(item,{compact:true})).join("")}</div></section></div></main>`;
}

export function renderCollections(){
  const state=store.getState(),mine=state.collections,followed=publicCollections.filter(item=>state.collectionFollows.includes(item.id));
  return `<main id="main-content" class="main"><div class="page">${pageHeader({eyebrow:"COLLECTIONS",title:"先見性を、公開できる資産にする",description:"金脈を集め、説明を付け、他人が追跡できる公開リストへ変えます。",actions:'<button class="btn btn-primary" data-action="create-collection">新しいコレクション</button>'})}<section><div class="section-head"><div><h2>注目コレクション</h2><p>編集部・発掘者が整理した入口。</p></div></div><div class="grid grid-2">${publicCollections.map(collectionCard).join("")}</div></section><section class="section"><div class="section-head"><div><h2>自分のコレクション</h2><p>非公開メモから公開リストまで管理。</p></div></div>${mine.length?`<div class="grid grid-2">${mine.map(collectionCard).join("")}</div>`:emptyState("コレクションはまだありません","保存した金脈をテーマ別にまとめ、公開・限定公開・非公開を選べます。","collection",'<button class="btn btn-primary" data-action="create-collection">最初のリストを作る</button>')}</section>${followed.length?`<section class="section"><div class="section-head"><div><h2>追跡中</h2></div></div><div class="grid grid-2">${followed.map(collectionCard).join("")}</div></section>`:""}</div></main>`;
}

export function renderWorkspace(){
  const state=store.getState(),notes=state.notes;
  return `<main id="main-content" class="main"><div class="page">${pageHeader({eyebrow:"RESEARCH WORKSPACE",title:"調査を、次の判断へ残す",description:"根拠、仮説、顧客の言葉、反証を金脈・サービス・需要に紐付けて保存します。",actions:'<button class="btn" data-action="import-state">インポート</button><button class="btn btn-primary" data-action="create-free-note">メモを追加</button>'})}<div class="grid grid-4">${statCard("調査メモ",notes.length,"ローカル＋クラウド")}${statCard("保存案件",state.saved.length,"MY GOLDMINE")}${statCard("追跡市場",state.watched.length,"アラート対象")}${statCard("プラン",state.plan.toUpperCase(),state.plan==="free"?"個人利用":"高度調査")}</div><section class="section"><div class="section-head"><div><h2>調査メモ</h2><p>CSVではなく、判断理由と反証を残します。</p></div><button class="text-link" data-action="export-notes">CSV出力</button></div>${notes.length?`<div class="grid grid-2">${notes.map(note=>{const entity=byId(opportunities,note.entityId)||byId(services,note.entityId);return `<article class="card card-pad"><div class="card-top"><div>${badge(note.entityType||"free")}${(note.tags||[]).slice(0,3).map(tag=>badge(tag)).join("")}</div><div class="button-row"><button class="icon-button" data-action="edit-note" data-id="${note.id}" aria-label="編集">${icon("edit",16)}</button><button class="icon-button" data-action="delete-note" data-id="${note.id}" aria-label="削除">${icon("trash",16)}</button></div></div><h3 class="card-title">${escapeHTML(note.title)}</h3><p class="card-copy" style="white-space:pre-wrap">${escapeHTML(note.body)}</p><div class="card-footer"><span class="muted">${entity?escapeHTML(entity.title||entity.name):"自由メモ"}</span><span class="muted">${formatDate(note.updatedAt)}</span></div></article>`;}).join("")}</div>`:emptyState("調査メモはありません","各詳細ページの『調査メモ』から、その案件に紐付けて残せます。","note",'<button class="btn btn-primary" data-action="create-free-note">自由メモを作る</button>')}</section><section class="section card card-pad"><h2>判断テンプレート</h2><div class="grid grid-4"><div><strong>事実</strong><p class="muted">出典から直接確認できること。</p></div><div><strong>解釈</strong><p class="muted">なぜ金が動いたかの因果仮説。</p></div><div><strong>反証</strong><p class="muted">この機会が弱いと判明する条件。</p></div><div><strong>次の確認</strong><p class="muted">一番安く不確実性を減らす行動。</p></div></div></section></div></main>`;
}

function submitTabs(active){
  return `<div class="tabs">${[["service","サービス"],["demand","未充足需要"],["signal","金の動き"],["correction","訂正"]].map(([id,label])=>`<a class="tab ${active===id?"active":""}" href="#/submit?type=${id}">${label}</a>`).join("")}</div>`;
}

function serviceForm(){return `<form id="service-submission" class="form"><div class="demo-banner">${icon("spark",18)}<div>URLを入れると、公開ページのタイトル・説明・画像候補を自動取得できます。取得結果は公開前に修正できます。</div></div><div class="form-group"><label>サービスURL</label><div style="display:flex;gap:8px"><input name="url" type="url" required placeholder="https://example.com" style="flex:1"><button class="btn" type="button" data-action="preview-url">URLから下書き</button></div><div class="form-error" data-error="url"></div></div><div class="form-row"><div class="form-group"><label>サービス名</label><input name="name" required maxlength="120"><div class="form-error" data-error="name"></div></div><div class="form-group"><label>カテゴリー</label><select name="category" required><option value="">選択</option>${categories.map(value=>`<option>${escapeHTML(value)}</option>`).join("")}</select><div class="form-error" data-error="category"></div></div></div><div class="form-group"><label>誰の何を解決するか</label><textarea name="oneLiner" required minlength="15" placeholder="対象顧客と、消える面倒を具体的に"></textarea><div class="form-error" data-error="oneLiner"></div></div><div class="form-row"><div class="form-group"><label>料金</label><input name="pricing" placeholder="月9,800円〜"></div><div class="form-group"><label>今ほしいもの</label><select name="intent"><option>顧客</option><option>ベータ利用者</option><option>フィードバック</option><option>提携先</option><option>アフィリエイター</option><option>投資・買収相談</option></select></div></div><div class="form-group"><label>実績・根拠（任意）</label><textarea name="evidence" placeholder="売上・利用者数は、期間・種類・証拠の有無を分けて記載"></textarea></div><div class="form-group"><label>連絡先メール</label><input name="email" type="email" autocomplete="email"><div class="form-error" data-error="email"></div></div><button class="btn btn-primary" type="submit">審査へ送る</button></form>`;}
function demandForm(){return `<form id="demand-submission" class="form"><div class="form-group"><label>欲しいもの・解決してほしいこと</label><input name="title" required minlength="8" maxlength="160" placeholder="例：LINEに散らばる請求書を会計前に整理してほしい"><div class="form-error" data-error="title"></div></div><div class="form-group"><label>どの過程で困っているか</label><textarea name="problem" required minlength="20" placeholder="今は誰が、何を、何回、どのように処理しているか"></textarea><div class="form-error" data-error="problem"></div></div><div class="form-row"><div class="form-group"><label>困っている人・払う人</label><input name="payer" required><div class="form-error" data-error="payer"></div></div><div class="form-group"><label>払ってもよい金額</label><input name="wtp" placeholder="月1万円、1件3,000円など"></div></div><div class="form-row"><div class="form-group"><label>カテゴリー</label><select name="category" required><option value="">選択</option>${categories.map(value=>`<option>${escapeHTML(value)}</option>`).join("")}</select><div class="form-error" data-error="category"></div></div><div class="form-group"><label>根拠URL（任意）</label><input name="source" type="url" placeholder="https://"></div></div><button class="btn btn-primary" type="submit">需要を投稿</button></form>`;}
function signalForm(){return `<form id="signal-submission" class="form"><div class="form-group"><label>何が起きたか</label><input name="headline" required minlength="10" maxlength="180" placeholder="誰が、何に、いくら支払ったか"><div class="form-error" data-error="headline"></div></div><div class="form-row"><div class="form-group"><label>数字の種類</label><select name="type" required><option value="">選択</option>${Object.entries(moneyTypeMeta).map(([value,label])=>`<option value="${value}">${label}</option>`).join("")}</select><div class="form-error" data-error="type"></div></div><div class="form-group"><label>金額・増加率</label><input name="amount" required placeholder="月商300万円、実支出2億円"><div class="form-error" data-error="amount"></div></div></div><div class="form-row"><div class="form-group"><label>払った側</label><input name="payer"></div><div class="form-group"><label>受け取った側</label><input name="receiver"></div></div><div class="form-group"><label>なぜ金が動いたか</label><textarea name="summary"></textarea></div><div class="form-group"><label>根拠URL</label><input name="source" type="url" required placeholder="https://"><div class="form-error" data-error="source"></div></div><button class="btn btn-primary" type="submit">審査へ送る</button></form>`;}
function correctionForm(){return `<form id="generic-correction" class="form"><div class="form-group"><label>対象URL</label><input name="target" type="url" value="${escapeHTML(location.href)}"></div><div class="form-group"><label>誤っている内容と正しい内容</label><textarea name="claim" required minlength="15"></textarea><div class="form-error" data-error="claim"></div></div><div class="form-group"><label>訂正を裏付ける根拠URL</label><input name="source" type="url" required placeholder="https://"><div class="form-error" data-error="source"></div></div><div class="form-group"><label>連絡先（任意）</label><input name="contact" type="email"></div><button class="btn btn-primary" type="submit">訂正を申請</button></form>`;}

export function renderSubmit(route){
  const type=route.query.type||"service",forms={service:serviceForm(),demand:demandForm(),signal:signalForm(),correction:correctionForm()};
  return `<main id="main-content" class="main"><div class="page page-narrow">${pageHeader({eyebrow:"CONTRIBUTE",title:"情報を載せ、需要と顧客に接続する",description:"自由広告ではなく、金・需要・サービス・根拠へ構造化して掲載します。"})}<div class="card card-pad">${submitTabs(type)}${forms[type]||forms.service}</div><section class="section grid grid-3"><div class="card card-pad"><strong>1. 自動下書き</strong><p class="muted">URLから公開情報を取得し、入力負担を減らします。</p></div><div class="card card-pad"><strong>2. 根拠審査</strong><p class="muted">未確認・所有者確認・証拠確認を分けます。</p></div><div class="card card-pad"><strong>3. 適切な人へ配信</strong><p class="muted">対応する需要・金脈を追う人に発見されます。</p></div></section></div></main>`;
}

export function renderPricing(){
  const state=store.getState();
  const plans=[
    {code:"free",name:"Free",price:"0円",copy:"金脈を見つけ、保存する",features:["最新フィード","基本DB検索","保存20件","公開コレクション追跡","週刊ダイジェスト"]},
    {code:"pro",name:"Pro",price:"月1,980円",copy:"自分向けに絞り、変化を逃さない",featured:true,features:["全詳細・履歴","保存・追跡無制限","高度フィルター","比較・調査ノート","即時アラート","CSV出力"]},
    {code:"research",name:"Research",price:"月4,980円",copy:"市場調査と提案に使う",features:["Proの全機能","根拠履歴・差分","市場マップ","データエクスポート","チーム共有準備","優先サポート"]}
  ];
  return `<main id="main-content" class="main"><div class="page page-narrow">${pageHeader({eyebrow:"PRICING",title:"夢は無料。優位性に課金する。",description:"無料で可能性を発見し、有料で根拠・比較・監視・時間短縮を買う構造です。"})}<div class="grid grid-3">${plans.map(plan=>`<article class="card plan-card ${plan.featured?"featured":""}">${plan.featured?'<span class="badge badge-gold" style="position:absolute;right:18px;top:18px">推奨</span>':""}<h2>${plan.name}</h2><p class="muted">${plan.copy}</p><div class="plan-price">${plan.price}<small>${plan.code==="free"?"":" / 月"}</small></div><ul class="feature-list">${plan.features.map(feature=>`<li>${feature}</li>`).join("")}</ul><button class="btn ${plan.featured?"btn-primary":""}" style="width:100%" data-action="choose-plan" data-plan="${plan.code}" ${state.plan===plan.code?"disabled":""}>${state.plan===plan.code?"現在のプラン":plan.code==="free"?"Freeで始める":"このプランを選ぶ"}</button></article>`).join("")}</div><section class="section card card-pad"><h2>掲載者向け収益</h2><div class="grid grid-3"><div><strong>無料掲載</strong><p class="muted">基本ページ、Organic検索、対応需要への接続。</p></div><div><strong>明示プロモーション</strong><p class="muted">対象ユーザーへ配信。ただしOrganic順位は購入不可。</p></div><div><strong>Buyer Intent</strong><p class="muted">閲覧・保存・比較・需要反応を集計し、個人を特定せず提供。</p></div></div></section></div></main>`;
}

export function renderTrust(){
  return `<main id="main-content" class="main"><div class="page page-narrow">${pageHeader({eyebrow:"TRUST & METHODOLOGY",title:"夢を大きく見せても、数字の意味は偽らない",description:"このサイトの価値は『儲かりそう』という感情と、後から検証できる構造を両立することです。"})}<section class="card card-pad"><h2>根拠ランク</h2><div class="grid grid-2">${Object.entries(evidenceMeta).map(([grade,meta])=>`<div class="source"><span class="source-grade">${grade}</span><span><strong>${escapeHTML(meta.label)}</strong><small>${escapeHTML(meta.description)}</small></span></div>`).join("")}</div></section><section class="section card card-pad"><h2>Opportunity Score</h2><div class="grid grid-3"><div><strong>金が動いた証拠 25%</strong><p class="muted">売上・支出・契約が原資料へ到達できるか。</p></div><div><strong>市場の勢い 22%</strong><p class="muted">直近で支出・需要・参入が加速しているか。</p></div><div><strong>需要の空白 23%</strong><p class="muted">欲しい人に対し、解決策が不足しているか。</p></div><div><strong>獲得経路 14%</strong><p class="muted">無名でも最初の顧客へ到達できるか。</p></div><div><strong>実行可能性 16%</strong><p class="muted">資金、技術、規制、運用の重さ。</p></div><div><strong>総合点は保証ではない</strong><p class="muted">必ず内訳・反証・リスクと一緒に表示。</p></div></div></section><section class="section card card-pad"><h2>広告とOrganic評価を分離</h2><p class="muted">プロモーション購入で、根拠ランク、Opportunity Score、Organic順位、利用者反応を変更できません。広告は専用面とラベルで明示し、ランキングViewは広告テーブルとJOINしないDB設計です。</p></section><section class="section card card-pad"><h2>訂正と更新</h2><ol class="number-list"><li>誤りの指摘には、正しい内容と根拠URLを要求</li><li>数字の期間・通貨・種類・推定か実績かを再確認</li><li>訂正履歴を残し、更新日と根拠ランクを変更</li><li>古い情報は削除せず、staleとして時系列を保全</li></ol></section></div></main>`;
}
