import { categories, demands, listings, moneyTypeMeta, opportunities, services, signals } from "../data.js";
import { byId, compactNumber, demandGapScore, escapeHTML, formatDate, formatNumber, normalizeText } from "../core.js";
import { badge, demandCard, emptyState, evidenceBadge, icon, listingCard, moneyTypeBadge, pageHeader, serviceCard, signalRow, statCard } from "../components.js";
import { store } from "../store.js";

function dbToolbar({id,query="",category="all",sort="newest",placeholder="検索",extra=""}){
  return `<form id="${id}" class="toolbar"><span>${icon("search",17)}</span><input class="field" name="query" value="${escapeHTML(query)}" placeholder="${escapeHTML(placeholder)}"><select class="select" name="category"><option value="all">すべての分野</option>${categories.map(value=>`<option ${category===value?"selected":""}>${escapeHTML(value)}</option>`).join("")}</select><select class="select" name="sort"><option value="newest" ${sort==="newest"?"selected":""}>新着順</option><option value="momentum" ${sort==="momentum"?"selected":""}>勢い順</option><option value="amount" ${sort==="amount"?"selected":""}>金額順</option><option value="evidence" ${sort==="evidence"?"selected":""}>根拠順</option></select>${extra}</form>`;
}

export function renderSignals(route){
  const q=route.query||{},query=normalizeText(q.q||""),category=q.category||"all",sort=q.sort||"newest";
  let items=signals.filter(item=>(!query||normalizeText([item.headline,item.summary,item.payer,item.receiver,item.category].join(" ")).includes(query))&&(category==="all"||item.category===category));
  const gradeValue={A:4,B:3,C:2,D:1};
  items=[...items].sort(sort==="momentum"?(a,b)=>b.change-a.change:sort==="amount"?(a,b)=>b.amountValue-a.amountValue:sort==="evidence"?(a,b)=>gradeValue[b.grade]-gradeValue[a.grade]:(a,b)=>new Date(b.occurredAt)-new Date(a.occurredAt));
  const total=items.reduce((n,item)=>n+(item.amountValue||0),0),primary=items.filter(item=>item.grade==="A").length;
  return `<main id="main-content" class="main"><div class="page">${pageHeader({eyebrow:"MONEY SIGNAL DATABASE",title:"誰が、誰に、何のために払ったか",description:"売上・利益・資金調達・GMV・実支出・契約上限を別の数字として保存します。",actions:'<a class="btn btn-primary" href="#/submit?type=signal">金の動きを投稿</a>'})}<div class="grid grid-4" style="margin-bottom:14px">${statCard("表示シグナル",items.length,"構造化済み")}${statCard("金額合計",`¥${compactNumber(total)}`,"単純合算・比較注意")}${statCard("一次証拠",primary,`${Math.round(primary/Math.max(1,items.length)*100)}%`)}${statCard("平均変化",`+${Math.round(items.reduce((n,i)=>n+i.change,0)/Math.max(1,items.length))}%`,"体験用期間比較")}</div>${dbToolbar({id:"signal-filter",query:q.q||"",category,sort,placeholder:"支払者、受取者、金額、需要で検索"})}<div class="table-wrap"><table><thead><tr><th>#</th><th>何が起きたか</th><th>金額・種類</th><th>変化</th><th>根拠</th><th>発生日</th></tr></thead><tbody>${items.map(signalRow).join("")}</tbody></table></div><section class="section card card-pad"><h2>数字を大きく見せる前に、意味を固定する</h2><div class="grid grid-4">${Object.entries(moneyTypeMeta).slice(0,12).map(([key,label])=>`<div><strong>${escapeHTML(label)}</strong><p class="muted">${key==="funding"?"投資家資本。顧客売上ではない。":key==="gmv"?"市場の取引総額。運営者売上ではない。":key==="contract_ceiling"?"最大支払可能額。実支出と分離。":key==="estimated_revenue"?"第三者推定。確定実績ではない。":"対象期間と通貨を保持。"}</p></div>`).join("")}</div></section></div></main>`;
}

export function renderDemands(route){
  const q=route.query||{},query=normalizeText(q.q||""),category=q.category||"all",sort=q.sort||"gap";
  let items=demands.filter(item=>(!query||normalizeText([item.title,item.problem,item.payer,item.wtp,item.category].join(" ")).includes(query))&&(category==="all"||item.category===category));
  items=[...items].sort(sort==="want"?(a,b)=>b.want-a.want:sort==="pay"?(a,b)=>b.wouldPay-a.wouldPay:sort==="pain"?(a,b)=>b.pain-a.pain:(a,b)=>demandGapScore(b)-demandGapScore(a));
  const extra=`<select class="select" name="sort"><option value="gap" ${sort==="gap"?"selected":""}>空白の強さ</option><option value="want" ${sort==="want"?"selected":""}>欲しい人数</option><option value="pay" ${sort==="pay"?"selected":""}>支払意思</option><option value="pain" ${sort==="pain"?"selected":""}>痛み</option></select><span class="filter-count">${items.length}件</span>`;
  return `<main id="main-content" class="main"><div class="page">${pageHeader({eyebrow:"DEMAND GAP DATABASE",title:"欲しがる人はいるのに、解決策が足りない",description:"製品ありきではなく、困る過程・支払者・支払意思・既存解決策を先に保存します。",actions:'<a class="btn btn-primary" href="#/submit?type=demand">未充足需要を投稿</a>'})}<form id="demand-filter" class="toolbar"><span>${icon("search",17)}</span><input class="field" name="query" value="${escapeHTML(q.q||"")}" placeholder="困り事、支払者、価格で検索"><select class="select" name="category"><option value="all">すべての分野</option>${categories.map(value=>`<option ${category===value?"selected":""}>${escapeHTML(value)}</option>`).join("")}</select>${extra}</form>${items.length?`<div class="grid grid-3">${items.map(demandCard).join("")}</div>`:emptyState("条件に合う需要がありません","別の業務や支払者で検索してください。","demand")}</div></main>`;
}

export function renderServices(route){
  const q=route.query||{},query=normalizeText(q.q||""),category=q.category||"all",intent=q.intent||"all";
  let items=services.filter(item=>(!query||normalizeText([item.name,item.oneLiner,item.owner,item.category,item.pricing,...item.intent].join(" ")).includes(query))&&(category==="all"||item.category===category)&&(intent==="all"||item.intent.includes(intent)));
  items=[...items].sort((a,b)=>(b.featured-a.featured)||(b.stats.leads-a.stats.leads));
  const intents=[...new Set(services.flatMap(item=>item.intent))];
  return `<main id="main-content" class="main"><div class="page">${pageHeader({eyebrow:"SERVICE DATABASE",title:"すでに存在する解決策と、まだ空いている場所",description:"掲載者の宣伝だけでなく、対応する需要・金脈・価格・信頼度・現在の募集目的を接続します。",actions:'<a class="btn btn-primary" href="#/submit?type=service">サービスを掲載</a>'})}<form id="service-filter" class="toolbar"><span>${icon("search",17)}</span><input class="field" name="query" value="${escapeHTML(q.q||"")}" placeholder="サービス、課題、運営者、価格で検索"><select class="select" name="category"><option value="all">すべての分野</option>${categories.map(value=>`<option ${category===value?"selected":""}>${escapeHTML(value)}</option>`).join("")}</select><select class="select" name="intent"><option value="all">すべての募集</option>${intents.map(value=>`<option ${intent===value?"selected":""}>${escapeHTML(value)}</option>`).join("")}</select><span class="filter-count">${items.length}件</span></form><div class="demo-banner">${icon("warning",17)}<div><strong>プロモーションは順位に影響しません。</strong> 有料枠は「プロモーション」と表示し、下のOrganic一覧と別の面で配信します。</div></div>${items.length?`<div class="grid grid-3">${items.map(serviceCard).join("")}</div>`:emptyState("サービスが見つかりません","新しいサービスを掲載すると、対応する需要者へ通知できます。","box",'<a class="btn btn-primary" href="#/submit?type=service">掲載する</a>')}</div></main>`;
}

export function renderListings(route){
  const state=store.getState(),q=route.query||{},query=normalizeText(q.q||""),type=q.type||"all";
  const combined=[...state.listings.filter(item=>item.status!=="archived"),...listings];
  const items=combined.filter(item=>(!query||normalizeText([item.title,item.summary,item.region,item.reward,...(item.tags||[])].join(" ")).includes(query))&&(type==="all"||item.type===type));
  const types={all:"すべて",beta:"ベータ",customer:"顧客",partner:"提携",poc:"PoC",feedback:"調査"};
  return `<main id="main-content" class="main"><div class="page">${pageHeader({eyebrow:"OPPORTUNITY MARKETPLACE",title:"金脈の近くで、実際の相手を見つける",description:"顧客、ベータ利用者、提携先、専門家、PoCを、関連する需要と事業機会の文脈付きで募集します。",actions:'<button class="btn btn-primary" data-action="open-listing-form">募集を作る</button>'})}<div class="grid grid-4" style="margin-bottom:14px">${statCard("公開募集",items.filter(i=>i.status==="open").length,"体験用＋自分の募集")}${statCard("応募",formatNumber(combined.reduce((n,i)=>n+(i.applications||0),0)+state.applications.length),"重複応募を防止")}${statCard("残り枠",formatNumber(combined.reduce((n,i)=>n+Math.max(0,(i.slots||0)-(i.applications||0)),0)),"募集ごとに管理")}${statCard("自分の応募",state.applications.length,"状態を追跡")}</div><form id="listing-filter" class="toolbar"><span>${icon("search",17)}</span><input class="field" name="query" value="${escapeHTML(q.q||"")}" placeholder="対象、条件、報酬、地域で検索"><div class="button-row">${Object.entries(types).map(([value,label])=>`<button type="button" class="filter-chip ${type===value?"active":""}" data-action="set-query" data-key="type" data-value="${value}">${label}</button>`).join("")}</div><span class="filter-count">${items.length}件</span></form>${items.length?`<div class="grid grid-3">${items.map(listingCard).join("")}</div>`:emptyState("募集がありません","条件を変えるか、自分の募集を作成してください。","handshake")}</div></main>`;
}
