import { categories, listings, opportunities, services } from "./data.js";
import { byId, escapeHTML, formatDateTime } from "./core.js";
import { badge, icon, modal } from "./components.js";
import { store } from "./store.js";

export function noteDialog({entityType="free",entityId="",note=null}={}){
  const entity=byId(opportunities,entityId)||byId(services,entityId);
  const title=note?"調査メモを編集":"調査メモを追加";
  return modal({id:"note-dialog",title,body:`<form id="note-form" class="form" data-note-id="${note?.id||""}" data-entity-type="${escapeHTML(entityType)}" data-entity-id="${escapeHTML(entityId)}"><div class="demo-banner">${icon("note",18)}<div>${entity?`<strong>${escapeHTML(entity.title||entity.name)}</strong> に紐付けます。`:"自由メモとして保存します。"}</div></div><div class="form-group"><label>見出し</label><input name="title" maxlength="120" required value="${escapeHTML(note?.title||"")}" placeholder="事実、仮説、反証、次の確認"></div><div class="form-group"><label>内容</label><textarea name="body" required placeholder="事実と解釈を分けて記録">${escapeHTML(note?.body||"")}</textarea></div><div class="form-group"><label>タグ（カンマ区切り）</label><input name="tags" value="${escapeHTML((note?.tags||[]).join(", "))}" placeholder="顧客インタビュー, 反証, 価格"></div><button class="btn btn-primary" type="submit">保存</button></form>`});
}

export function collectionDialog(collection=null){
  return modal({id:"collection-dialog",title:collection?"コレクションを編集":"新しいコレクション",body:`<form id="collection-form" class="form" data-id="${collection?.id||""}"><div class="form-group"><label>タイトル</label><input name="title" maxlength="120" required value="${escapeHTML(collection?.title||"")}" placeholder="例：10万円以下で検証できる金脈"></div><div class="form-group"><label>このリストの基準</label><textarea name="description" placeholder="何を入れ、何を除外するか">${escapeHTML(collection?.description||"")}</textarea></div><div class="form-group"><label>公開範囲</label><select name="visibility"><option value="private" ${collection?.visibility==="private"?"selected":""}>非公開</option><option value="unlisted" ${collection?.visibility==="unlisted"?"selected":""}>URLを知る人だけ</option><option value="public" ${collection?.visibility==="public"?"selected":""}>公開</option></select></div><button class="btn btn-primary" type="submit">${collection?"更新":"作成"}</button></form>`});
}

export function collectionPickerDialog(opportunityId){
  const collections=store.getState().collections;
  return modal({id:"collection-picker",title:"コレクションへ追加",body:`${collections.length?`<div class="form">${collections.map(collection=>{const active=collection.opportunityIds.includes(opportunityId);return `<button class="checkbox-card" data-action="toggle-collection-item" data-collection-id="${collection.id}" data-opportunity-id="${opportunityId}">${icon(active?"check":"plus",17)}<span><strong>${escapeHTML(collection.title)}</strong><small class="muted" style="display:block">${collection.opportunityIds.length}件 · ${escapeHTML(collection.visibility)}</small></span></button>`;}).join("")}<button class="btn" data-action="create-collection">新しいコレクション</button></div>`:`<div class="empty"><div class="empty-icon">${icon("collection",24)}</div><h3>コレクションがありません</h3><p>テーマ別のリストを作り、この金脈を追加できます。</p><button class="btn btn-primary" data-action="create-collection">作成する</button></div>`}`});
}

export function listingDialog({serviceId="",listing=null}={}){
  return modal({id:"listing-dialog",title:listing?"募集を編集":"募集を作成",size:"780px",body:`<form id="listing-form" class="form" data-id="${listing?.id||""}><div class="form-row"><div class="form-group"><label>対象サービス</label><select name="serviceId"><option value="">サービスなし・市場全体</option>${services.map(service=>`<option value="${service.id}" ${(listing?.serviceId||serviceId)===service.id?"selected":""}>${escapeHTML(service.name)}</option>`).join("")}</select></div><div class="form-group"><label>募集種類</label><select name="type" required><option value="beta" ${listing?.type==="beta"?"selected":""}>ベータ利用者</option><option value="customer" ${listing?.type==="customer"?"selected":""}>顧客</option><option value="partner" ${listing?.type==="partner"?"selected":""}>提携先</option><option value="poc" ${listing?.type==="poc"?"selected":""}>有償PoC</option><option value="feedback" ${listing?.type==="feedback"?"selected":""}>調査・フィードバック</option></select></div></div><div class="form-group"><label>募集タイトル</label><input name="title" required minlength="8" maxlength="160" value="${escapeHTML(listing?.title||"")}" placeholder="対象と条件が一目で分かる見出し"><div class="form-error" data-error="title"></div></div><div class="form-group"><label>対象・条件・目的</label><textarea name="summary" required minlength="20" placeholder="誰を何人、何のために募集し、何を提供するか">${escapeHTML(listing?.summary||"")}</textarea><div class="form-error" data-error="summary"></div></div><div class="form-row"><div class="form-group"><label>提供・報酬</label><input name="reward" value="${escapeHTML(listing?.reward||"")}" placeholder="3か月無料、有償PoC 20万円"></div><div class="form-group"><label>募集枠</label><input name="slots" type="number" min="1" max="999" value="${listing?.slots||5}"></div></div><div class="form-row"><div class="form-group"><label>地域</label><input name="region" value="${escapeHTML(listing?.region||"オンライン")}"></div><div class="form-group"><label>締切</label><input name="deadline" type="date" value="${escapeHTML(listing?.deadline||"")}"><div class="form-error" data-error="deadline"></div></div></div><div class="form-group"><label>タグ（カンマ区切り）</label><input name="tags" value="${escapeHTML((listing?.tags||[]).join(", "))}"></div><button class="btn btn-primary" type="submit">${listing?"更新":"審査へ送る"}</button></form>`});
}

export function reviewDialog(serviceId){
  const service=byId(services,serviceId);
  return modal({id:"review-dialog",title:"利用レビューを書く",body:`<form id="review-form" class="form" data-service-id="${serviceId}"><div class="demo-banner">${icon("info",18)}<div><strong>${escapeHTML(service?.name||"サービス")}</strong><br>販売者、従業員、競合による投稿は評価集計から分離します。</div></div><div class="form-group"><label>評価</label><select name="rating" required><option value="">選択</option><option value="5">5 — 非常に良い</option><option value="4">4 — 良い</option><option value="3">3 — 普通</option><option value="2">2 — 改善が必要</option><option value="1">1 — 問題がある</option></select><div class="form-error" data-error="rating"></div></div><div class="form-group"><label>見出し</label><input name="title" required minlength="4" maxlength="120"><div class="form-error" data-error="title"></div></div><div class="form-group"><label>どの状況で使い、何が変わったか</label><textarea name="body" required minlength="30" placeholder="機能の感想だけでなく、利用前後の過程を具体的に"></textarea><div class="form-error" data-error="body"></div></div><div class="form-group"><label>サービスとの関係</label><select name="relationship"><option>利用者</option><option>試用者</option><option>導入検討者</option><option>元利用者</option><option>販売者・関係者</option><option>競合</option></select></div><button class="btn btn-primary" type="submit">審査へ送る</button></form>`});
}

export function correctionDialog(entityType,entityId){
  return modal({id:"correction-dialog",title:"情報の訂正を申請",body:`<form id="correction-form" class="form" data-entity-type="${escapeHTML(entityType)}" data-entity-id="${escapeHTML(entityId)}"><div class="form-group"><label>誤っている内容と正しい内容</label><textarea name="claim" required minlength="15" placeholder="数字、期間、分類、説明のどこが誤っているか"></textarea><div class="form-error" data-error="claim"></div></div><div class="form-group"><label>訂正を裏付ける根拠URL</label><input name="source" type="url" required placeholder="https://"><div class="form-error" data-error="source"></div></div><div class="form-group"><label>連絡先（任意）</label><input name="contact" type="email"></div><button class="btn btn-primary" type="submit">訂正を申請</button></form>`});
}

export function claimDialog(serviceId){
  const service=byId(services,serviceId);
  return modal({id:"claim-dialog",title:"サービスページの所有者確認",body:`<div class="demo-banner">${icon("lock",18)}<div><strong>${escapeHTML(service?.name||"サービス")}</strong><br>基本情報の信頼度と、ページを編集できる所有権は別に管理します。</div></div><form id="claim-form" class="form" data-service-id="${serviceId}"><div class="form-group"><label>確認方法</label><select name="method"><option value="domain_email">ドメインメール</option><option value="dns_txt">DNS TXT</option><option value="html_meta">HTML metaタグ</option><option value="manual">書類による手動確認</option></select></div><div class="form-group"><label>説明（任意）</label><textarea name="note" placeholder="運営者との関係、利用できるドメインメールなど"></textarea></div><button class="btn btn-primary" type="submit">確認を開始</button></form>`});
}

export function cloudConfigDialog(config={}){
  return modal({id:"cloud-dialog",title:"Supabaseへ接続",body:`<div class="demo-banner">${icon("cloud",18)}<div>ブラウザには公開Anon Keyだけを保存します。Service Role、Stripe secret、メールAPIキーはEdge FunctionsのSecretへ置きます。</div></div><form id="cloud-config-form" class="form"><div class="form-group"><label>Supabase Project URL</label><input name="supabaseUrl" type="url" required value="${escapeHTML(config.supabaseUrl||"")}" placeholder="https://xxxxx.supabase.co"></div><div class="form-group"><label>Public Anon Key</label><textarea name="supabaseAnonKey" required style="min-height:90px">${escapeHTML(config.supabaseAnonKey||"")}</textarea></div><button class="btn btn-primary" type="submit">接続を保存</button></form>`});
}

export function moderationGuideDialog(){
  return modal({id:"moderation-guide",title:"公開前の審査基準",size:"820px",body:`<ol class="number-list"><li><strong>重複：</strong>既存サービス・需要・シグナルへ統合できないか。</li><li><strong>数字：</strong>売上、利益、GMV、資金調達、契約上限、実支出、推定を分類したか。</li><li><strong>期間：</strong>月、年、累計、単発を明示したか。</li><li><strong>根拠：</strong>主張を支える箇所へ到達でき、取得日を保存したか。</li><li><strong>権利：</strong>転載、画像、個人情報、利用規約に問題がないか。</li><li><strong>利害：</strong>投稿者が販売者・競合・広告主かを分離したか。</li><li><strong>入口：</strong>成功談からの飛躍ではなく、需要・獲得経路・リスクが説明できるか。</li><li><strong>公開後：</strong>更新期限とstale判定を設定したか。</li></ol>`});
}

export function moderationItemDialog(item){
  const payload=item.payload||item;
  return modal({id:"moderation-item",title:"審査対象を確認",size:"860px",body:`<div class="button-row">${badge(item.type||item.queueType,"gold")}${badge(item.status||"pending")}</div><h2>${escapeHTML(item.title||payload.name||payload.title||payload.headline||"投稿")}</h2><pre style="white-space:pre-wrap;background:var(--panel-2);border:1px solid var(--line);border-radius:12px;padding:14px;max-height:420px;overflow:auto">${escapeHTML(JSON.stringify(payload,null,2))}</pre><p class="muted">投稿 ${formatDateTime(item.createdAt)}</p><div class="button-row"><button class="btn btn-primary" data-action="moderate" data-id="${item.id}" data-queue-type="${item.queueType||"submission"}" data-status="approved">承認</button><button class="btn" data-action="moderate" data-id="${item.id}" data-queue-type="${item.queueType||"submission"}" data-status="needs_changes">修正依頼</button><button class="btn btn-danger" data-action="moderate" data-id="${item.id}" data-queue-type="${item.queueType||"submission"}" data-status="rejected">却下</button></div>`});
}
