type Entity = Record<string, unknown>;
export const DEMOTED_STATUS: string;
export const UNCONFIRMED: string;
export const BUSINESS_PREFIX: string;
export const PNL_NUMERIC_KEYS: string[];
export const PNL_FLAG_KEYS: string[];
export const PNL_OPEX_KEYS: string[];
export const PNL_KEEP_TEXT_KEYS: string[];
export const PNL_ALLOWED_KEYS: Set<string>;
export const WITHDRAWN_TOP_KEYS: string[];
export const TOP_TEXT_KEYS: string[];
export const STRATEGY_TEXT_KEYS: string[];
export const TEMPORAL_UNKNOWN: Record<string, string | number>;
export const DISCLOSURE_RE: RegExp;
export const PEAK_OR_RANGE_RE: RegExp;
export function isDemoted(e: Entity): boolean;
export function businessText(e: Entity): string | null;
export function isAllowedCard(c: unknown): boolean;
export function isAllowedStreamItem(o: unknown): boolean;
export function sourcedTexts(e: Entity): string[];
export function isAllowedObservation(text: unknown, e: Entity, allowedStreamTexts: Set<string>): boolean;
export function isAllowedDescription(value: unknown, e: Entity): boolean;
export function isAllowedRevenueLabel(label: unknown, pnl?: unknown): boolean;
export const NO_SOURCE_DOC: string;
export const PEAK_LABEL_PREFIX: string;
export function isAllowedSourceDoc(doc: unknown): boolean;
export function isAllowedEstimationLogic(text: unknown, pnl?: unknown): boolean;
export function isChannelSourced(channel: unknown, e: Entity): boolean;
export function isAllowedToolEntry(t: unknown): boolean;
export function isAllowedTimelineEvent(t: unknown): boolean;
export function isTeamSizeSourced(n: unknown, e: Entity): boolean;
export function isFoundedYearSourced(year: unknown, e: Entity): boolean;
export function revenueEvidenceTexts(e: Entity): string[];
export function operationsTemplateHits(ops: unknown): string[];
export function isOperationsTemplate(ops: unknown): boolean;
export function isGrossMargin100(pnl: unknown): boolean;
export function isRevenuePeakOrRange(e: Entity): boolean;
export function isFounderTitleOnly(founder: unknown): boolean;
export function findAllowlistViolations(e: Entity): { field: string; detail: string }[];
export function findFactsOnlyViolations(entities: Entity[]): { key: string; label: string; count: number; sample: string[] }[];
export function isFilingBackedPnl(pnl: unknown): boolean;
