import type { FinancialEntity } from '../src/platform/types/terminal';

export const MASSIVE_EXPANSION_BATCH_3: FinancialEntity[] = [
  // 11. Obsidian
  {
    id: 'ent_obsidian_md',
    ticker: 'OBSIDIAN',
    name: 'Obsidian',
    legalEntity: 'Dynalist Inc.',
    tagline: '「クラウド企業に自分のメモを人質に取られる恐怖」を突き、完全ローカルMarkdown保存で個人無料・同期課金だけで年商数十億円を稼ぐ思考要塞',
    sector: 'NICHE_SAAS',
    scale: 'SMALL_TEAM',
    founder: 'Shida Li, Erica Xu',
    country: 'CA',
    url: 'https://obsidian.md',
    verifiedBadge: true,
    growthRateYoY: 80.0,
    architecturePattern: '完全ローカルファースト・サーバー費ゼロモデル',
    pipelineStack: 'Electron × ローカルMarkdownファイル × プラグインエコシステム',
    targetPainWallet: '知識労働者の「サービス終了やアカウントBANで過去の全メモが消滅する恐怖」',
    tags: ['ローカルファースト', 'Markdown', '個人無料', 'サーバー費ほぼゼロ', '熱狂的コミュニティ'],
    pnl: {
      monthlyRevenue: 150000000,
      cogs: 7500000,
      grossProfit: 142500000,
      grossMargin: 95.0,
      operatingExpenses: {
        serverAndApi: 5000000,
        advertising: 0,
        subcontracting: 5000000,
        toolsAndSaaS: 2500000,
        other: 10000000,
      },
      operatingProfit: 120000000,
      operatingMargin: 80.0,
      estimatedAnnualNetProfit: 1440000000,
      financialStatus: 'REPORTED',
      isRevenueUnconfirmed: false,
      isMarginUnconfirmed: false,
      revenueLabel: '公式開示・業界推計 有料Sync/Publish会員数十万人（利益率80%超）',
    },
    evidenceCards: [
      {
        id: 'ev_obsidian_loot_blueprint',
        type: 'LOOT_BLUEPRINT',
        title: '【略奪転用】データを自分のサーバーに保存させず「顧客のローカルPC」に置かせてインフラ費をゼロにする配管',
        badge: '略奪転用方程式',
        evidenceStatus: 'VERIFIED',
        punchline: '顧客のメモをクラウドDBに保存するのをやめ、PC内のプレーンテキスト（.md）として扱わせることで、サーバー代ゼロで数百万人に配給する。',
        details: [
          '【Step 1: クラウド不信の特定】: Notion等のクラウドツールが落ちて仕事が止まる、または会社が倒産した時の不安を突く。',
          '【Step 2: 永遠に読めるプレーンテキスト】: 専用フォーマットではなく標準のMarkdownファイルで保存させ、「100年後も読める安心感」を売る。',
          '【Step 3: 暗号化同期（Obsidian Sync）で課金】: スマホとPC間の安全な暗号化同期機能（月$4〜$8）と商用ライセンスで極上の利益を吸い上げる。',
        ],
        codeSnippet: '// Obsidianのローカルファーストな双方向リンクパース配管\nexport function resolveWikilinks(content: string) {\n  const matches = content.matchAll(/\\[\\[(.*?)\\]\\]/g);\n  return Array.from(matches).map(m => ({ linkTarget: m[1], isLocalFile: true }));\n}',
        sourceNote: 'Shida LiとErica Xuの公開インタビューおよびObsidian公式サイトから抽出',
      },
      {
        id: 'ev_obsidian_crime',
        type: 'THE_CRIME',
        title: 'VCの資金を1円も受けず、夫婦2人で数百万人のヘビーユーザーを囲い込む',
        badge: '身も蓋もない真実',
        evidenceStatus: 'VERIFIED',
        punchline: '広告費ゼロ、サーバー費ほぼゼロ。コミュニティに1,000個以上のプラグインを勝手に作らせ、自分たちは暗号化同期の月額代金だけを回収する。',
        details: [
          'Notionが重くなり、Roam Researchが高額化（月$15）したタイミングで、完全無料で爆速動作するローカルアプリを投下して市場を総取り。',
          '研究者、医師、エンジニアなど、機密情報をクラウドに上げられないプロの財布を独占。',
        ],
      },
    ],
    operations: {
      teamSize: 8,
      weeklyHours: 35,
      initialCapitalRequired: 500000,
      automationLevel: 95,
      primaryChannels: ['Discordコミュニティ（15万人超）', 'Redditのr/ObsidianMD', 'YouTube解説動画'],
      toolStack: [
        { name: 'Cloudflare', category: '同期リレー', monthlyCost: 2000000, purpose: 'エンドツーエンド暗号化同期通信' },
        { name: 'Stripe', category: '決済基盤', monthlyCost: 4500000, purpose: 'Sync/Publish月額課金' },
      ],
    },
    strategy: {
      blindspot: 'NotionやEvernoteは「自社クラウドにデータを囲い込む」ことで儲けようとし、顧客が抱く「自社のデータを人質に取られたくない」本能的防衛本能を軽視していた。',
      moatType: 'NETWORK_EFFECT',
      moatDescription: '世界中の開発者がボランティアで開発した1,500個以上のオープンソースプラグインとテーマという巨大な生態系。',
      incumbentDilemma: 'クラウドSaaS企業は「ユーザーデータをDBに保持してAI分析する」ことが事業計画の前提であるため、ローカルファイル完結モデルには絶対に転換できない。',
      secretInsight: '最も強固な信頼を勝ち取る方法は「私たちはあなたのデータを一切見られません（完全暗号化）」と宣言し、監視社会への恐怖を味方につけることである。',
      initialTraction: [
        'Dynalistを作っていた夫婦が、コロナ禍の2020年に初期Obsidianをフォーラムで公開',
        'Roam Researchの月$15という高額料金に反発していたPKMマニアが雪崩を打って移籍',
        'プラグインAPIを早期解放し、ユーザーが勝手に便利機能を作り出す自走ループを構築',
      ],
      actionPlaybook: [
        'Step 1: ユーザーが「クラウド企業に預けるのを恐れているデータ（健康、機密、資産、思考）」を特定する',
        'Step 2: 端末ローカルに保存されるオープン標準フォーマット（Markdown/SQLite等）のアプリを作る',
        'Step 3: 複数端末間の「暗号化同期」を有料オプションとして販売する',
      ],
      coldOutreachTemplate: '【社内機密メモの完全ローカル保護】クラウドにデータを一切送らず、ローカルファイルだけで完結するセキュアな思考基盤Obsidianのご案内です。',
    },
    temporal: {
      foundedYear: 2020,
      initialTractionPeriod: '2020-2022年 (Roam代替・PKMブーム期)',
      dataSnapshotPeriod: '2023-2026年 (プラグインエコシステム成熟・標準化期)',
      viabilityStatus: 'MATURED_MOAT',
      viabilityLabel: '永続要塞（ローカルファイル資産とプラグイン生態系の堀）',
      eraContext: 'データプライバシー意識の高まりと、大手クラウドの障害・規約改定への不信感。',
      currentViabilityAnalysis: 'データがユーザー自身の手元にあるためサービス終了リスクがなく、今後数十年にわたって安定稼働し続ける極めて堅牢なモデル。',
    },
  },

  // 12. ConvertKit (Kit)
  {
    id: 'ent_convertkit_kit',
    ticker: 'CONVERTKIT',
    name: 'ConvertKit (Kit)',
    legalEntity: 'ConvertKit Inc.',
    tagline: '「Mailchimpの機能が複雑怪奇でブログ読者が増えない」クリエイターの苦痛を突き、コールド営業と泥臭い手動移行で年商60億円を築いた不屈のSaaS',
    sector: 'NICHE_SAAS',
    scale: 'SCALEUP',
    founder: 'Nathan Barry',
    country: 'US',
    url: 'https://kit.com',
    verifiedBadge: true,
    growthRateYoY: 25.0,
    architecturePattern: '泥臭い手動移行代行による顧客獲得',
    pipelineStack: 'Ruby on Rails × AWS × 自社配信インフラ × 完全フルリモート',
    targetPainWallet: 'プロブロガー・著者の「読者リストのセグメント分けと自動配信ステップメールの構築苦痛」',
    tags: ['ブートストラップ', '泥臭い手動移行', 'ARR60億円超', 'クリエイター特化', '完全フルリモート'],
    pnl: {
      monthlyRevenue: 500000000,
      cogs: 65000000,
      grossProfit: 435000000,
      grossMargin: 87.0,
      operatingExpenses: {
        serverAndApi: 50000000,
        advertising: 20000000,
        subcontracting: 30000000,
        toolsAndSaaS: 15000000,
        other: 170000000,
      },
      operatingProfit: 150000000,
      operatingMargin: 30.0,
      estimatedAnnualNetProfit: 1800000000,
      financialStatus: 'REPORTED',
      isRevenueUnconfirmed: false,
      isMarginUnconfirmed: false,
      revenueLabel: '公式開示ARR $40M超（全社員80名が完全リモート・無借金経営）',
    },
    evidenceCards: [
      {
        id: 'ev_convertkit_loot_blueprint',
        type: 'LOOT_BLUEPRINT',
        title: '【略奪転用】競合ツールからの「移行作業を完全無料・手作業で代行」して乗り換え障壁を粉砕する配管',
        badge: '略奪転用方程式',
        evidenceStatus: 'VERIFIED',
        punchline: '乗り換えが面倒でMailchimpやAWeberに留まっている大口ブロガーに「私たちが無料で全部移し替えます」と持ちかけ、顧客を強引に奪う。',
        details: [
          '【Step 1: 乗り換えの激痛の特定】: 読者リストや過去のステップメールの移行が面倒で、不満があっても解約できない心理を特定。',
          '【Step 2: 泥臭い手動コンシェルジュ移行】: 創業者自らが顧客のアカウントにログインし、徹夜で全テンプレートとリストを手動移行。',
          '【Step 3: 高額月額サブスクの継続】: 読者数が増えるほど自動的に月額料金が上がる階段課金（月$29〜$2,000+）で生涯課金を回収。',
        ],
        codeSnippet: '// 無料移行代行（Free Concierge Migration）リクエスト受付配管\nexport function scheduleMigration(customerAccount: string, incumbentProvider: "MAILCHIMP" | "AWEBER") {\n  return db.migrationTickets.create({\n    data: { customerAccount, incumbentProvider, status: "ASSIGNED_TO_SPECIALIST", guaranteedHours: 48 }\n  });\n}',
        sourceNote: 'Nathan Barryのブログ連載「The Web App Challenge」およびConvertKit公式透明性ダッシュボードから抽出',
      },
      {
        id: 'ev_convertkit_crime',
        type: 'THE_CRIME',
        title: '初期に月商20万円で死にかけた後、「プロブロガー専門」に絞ってコールドDMを送りまくり大逆転',
        badge: '身も蓋もしない真実',
        evidenceStatus: 'VERIFIED',
        punchline: '「誰でも使えるメルマガ」を捨て、「本気で飯を食っているブロガー」だけに絞り込み、電話とスカイプで1社ずつ泥臭く口説き落とした初動ログ。',
        details: [
          '競合のAWeberやMailchimpの利用者をTwitterで探し、「使いにくくないですか？無料で移行します」と1日数十通DMを送信。',
          '大手有名ブロガー（Pat Flynn等）を口説き落とし、彼らに高額なアフィリエイト報酬（生涯売上の30%）を渡して共犯者に仕立て上げた。',
        ],
      },
    ],
    operations: {
      teamSize: 85,
      weeklyHours: 40,
      initialCapitalRequired: 5000000,
      automationLevel: 75,
      primaryChannels: ['泥臭い直接アウトリーチ', '30%生涯アフィリエイト網', 'クリエイターコミュニティ'],
      toolStack: [
        { name: '自前メール配信クラスタ', category: '配信インフラ', monthlyCost: 35000000, purpose: '高到達率IPウォームアップ' },
        { name: 'Stripe Connect', category: '決済代行', monthlyCost: 15000000, purpose: '月額プランおよびアフィリエイト自動送金' },
      ],
    },
    strategy: {
      blindspot: 'MailchimpはEコマース（物販）のメガ企業向けにシフトし、情報発信で食っている「個人クリエイターやブロガー」のシンプルな要望を切り捨てていた。',
      moatType: 'SWITCHING_COST',
      moatDescription: '一度何万人もの読者リストと自動化ステップメールを構築した顧客は、配信停止リスクを恐れて他社への移行が極めて困難になる人質性。',
      incumbentDilemma: 'Mailchimpは数千万人の無料ユーザーを抱えているため、ConvertKitのように「高単価な本気の有料クリエイター」だけに手厚い移行サポートを提供できない。',
      secretInsight: 'SaaSの初動で最も確実なのは、気の利いた広告ではなく「競合のユーザーに直接連絡し、最も面倒な引っ越し作業をタダで代行すること」である。',
      initialTraction: [
        'Nathan Barryが「半年で月商$5,000を達成できなければ諦める」公開チャレンジを開始',
        '月商$2,000で停滞した際、ターゲットを「プロブロガー」に絞り込み直接営業へシフト',
        'Pat FlynnがAWeberからConvertKitへの移行を発表し、業界のゴールドラッシュが発生',
      ],
      actionPlaybook: [
        'Step 1: 乗り換えが物理的に面倒なSaaS（CRM、メルマガ、会計等）を特定する',
        'Step 2: 「無料で全データを手動移行します」という完全代行オファーを掲げる',
        'Step 3: 業界のインフルエンサーに生涯30%のアフィリエイト報酬を払い、自社の最強の営業マンにする',
      ],
      coldOutreachTemplate: '【Mailchimpからの無料移行代行】貴メディアの全読者リストとステップメールを、弊社スタッフが48時間以内に無料で完全移行いたします。',
    },
    temporal: {
      foundedYear: 2013,
      initialTractionPeriod: '2013-2016年 (泥臭いコールド営業・急浮上期)',
      dataSnapshotPeriod: '2017-2026年 (ARR $40M突破・Kitへのリブランディング期)',
      viabilityStatus: 'MATURED_MOAT',
      viabilityLabel: '先行者堀により後発模倣困難（強固なクリエイターリスト資産）',
      eraContext: '個人ブログ・クリエイターエコノミーの台頭と、Mailchimpの多機能化・値上げ。',
      currentViabilityAnalysis: 'BeehiivやSubstackとの競争はあるが、コース販売や高機能自動化において圧倒的な実績と強固なARRを維持。',
    },
  },

  // 13. Buffer
  {
    id: 'ent_buffer_social',
    ticker: 'BUFFER',
    name: 'Buffer',
    legalEntity: 'Buffer Inc.',
    tagline: '「TwitterやInstagramの投稿を手動でやるのは時間の無駄」全SNSの予約投稿を1画面に集約し、全社員の給与全公開で年商30億円を稼ぐ草分けSaaS',
    sector: 'NICHE_SAAS',
    scale: 'SMALL_TEAM',
    founder: 'Joel Gascoigne, Leo Widrich',
    country: 'US',
    url: 'https://buffer.com',
    verifiedBadge: true,
    growthRateYoY: 15.0,
    architecturePattern: '完全透明性マーケティングと予約スケジューラー',
    pipelineStack: 'Node.js × MongoDB × 各SNS公式API × 完全リモートワーク',
    targetPainWallet: 'SNSマーケターの「毎日決まった時間に手動で投稿し続けなければならない拘束時間」',
    tags: ['SNS予約投稿', '給与全公開', '完全ブートストラップ', 'ARR30億円超', '透明性経営'],
    pnl: {
      monthlyRevenue: 250000000,
      cogs: 25000000,
      grossProfit: 225000000,
      grossMargin: 90.0,
      operatingExpenses: {
        serverAndApi: 20000000,
        advertising: 0,
        subcontracting: 15000000,
        toolsAndSaaS: 10000000,
        other: 100000000,
      },
      operatingProfit: 80000000,
      operatingMargin: 32.0,
      estimatedAnnualNetProfit: 960000000,
      financialStatus: 'REPORTED',
      isRevenueUnconfirmed: false,
      isMarginUnconfirmed: false,
      revenueLabel: '公式開示ARR $20M規模（全社員の給与と会社の全財務をリアルタイム公開）',
    },
    evidenceCards: [
      {
        id: 'ev_buffer_loot_blueprint',
        type: 'LOOT_BLUEPRINT',
        title: '【略奪転用】製品を作る前に「料金表だけの偽LP」を出し、カード番号を入力させて需要を検証する配管',
        badge: '略奪転用方程式',
        evidenceStatus: 'VERIFIED',
        punchline: 'コードを1行も書かずに「月$5でTwitterを予約投稿」というLPを作り、課金ボタンを押した人の数を見てから開発に着手した伝説の事前検証。',
        details: [
          '【Step 1: 偽の料金表テスト】: 無料プランと有料プランのボタンを配置し、「料金を払う気があるユーザーがいるか」だけを測定。',
          '【Step 2: 7週間の爆速開発】: 需要が確認できた瞬間に最小限の予約投稿機能だけを突貫工事でローンチ。',
          '【Step 3: ゲスト投稿によるSEO爆撃】: 共同創業者が毎日数本の外部ブログ記事（ゲストポスト）を寄稿し、広告費ゼロで初期10万ユーザーを獲得。',
        ],
        codeSnippet: '// Bufferの投稿キュー（Queue）自動ディスパッチ配管\nexport async function dispatchScheduledPost(queueItemId: string) {\n  const item = await db.scheduledPosts.findUnique({ where: { id: queueItemId } });\n  if (item.scheduledTime <= new Date() && item.status === "PENDING") {\n    await socialMediaApis.publish(item.platform, item.content);\n    await db.scheduledPosts.update({ where: { id: queueItemId }, data: { status: "PUBLISHED" } });\n  }\n}',
        sourceNote: 'Joel Gascoigneの個人ブログ「Idea to Paying Customers in 7 Weeks」およびBuffer公式透明性サイトから抽出',
      },
      {
        id: 'ev_buffer_crime',
        type: 'THE_CRIME',
        title: '全社員の給料・会社の銀行残高・全株式比率をネットに晒して無料のパブリシティを総取り',
        badge: '身も蓋もない真実',
        evidenceStatus: 'VERIFIED',
        punchline: '「極端な透明性」をブランディングに昇華させ、世界中のテックメディアに無料で取り上げさせ続けることで、広告宣伝費を20年間ゼロに抑え込む。',
        details: [
          '「誰がいくら貰っているか」を計算する給与計算式をオープンソース化し、世界中の人事や経営者の必読コンテンツへ昇格。',
          '外部VCの持分を買い戻し、株主の圧力による無理な拡大を完全拒絶して安定配当型ビジネスを確立。',
        ],
      },
    ],
    operations: {
      teamSize: 70,
      weeklyHours: 32,
      initialCapitalRequired: 500000,
      automationLevel: 85,
      primaryChannels: ['全公開透明性ブログ（Buffer Open）', 'ゲストポストSEO', 'SNS予約リンクバイラル'],
      toolStack: [
        { name: '各SNS公式API', category: '連携基盤', monthlyCost: 15000000, purpose: 'X/Meta/LinkedIn投稿配信' },
        { name: 'Stripe', category: '決済代行', monthlyCost: 7500000, purpose: '月額/年額SaaSサブスクリプション' },
      ],
    },
    strategy: {
      blindspot: 'Hootsuite等の大手ツールは複雑なエンタープライズ管理画面に傾倒し、個人やスモールビジネスが「今すぐ投稿を予約したい」という手軽さを無視していた。',
      moatType: 'BRAND_PRESTIGE',
      moatDescription: '10年以上にわたる透明性経営（Open Metrics）によって築かれた、中小企業コミュニティからの絶大な信頼。',
      incumbentDilemma: '大手エンタープライズツールは営業マン人件費とオフィス固定費を抱えているため、月額数ドルの安価なセルフサーブプランに注力できない。',
      secretInsight: '広告費をかけずにブランドを築く究極の裏技は、「他社が決して公開できない恥部（給料、失敗、弱点）」をあえて全て公表して味方を作ることである。',
      initialTraction: [
        'Joel GascoigneがTwitterでアイデアをツイートし、関心を示した見込み客に直接DM',
        '共同創業者のLeo Widrichが半年間で150本以上のゲストブログを他社サイトに寄稿し初期10万人を獲得',
        '「給与全公開」の発表時にTechCrunchやHacker Newsで社会現象化しトラフィックが爆発',
      ],
      actionPlaybook: [
        'Step 1: コードを書く前にLPを作って「お金を払う人がいるか」を先にテストする',
        'Step 2: 既存の他社メディアに質の高い記事を大量寄稿して初期トラフィックを横取りする',
        'Step 3: 自社のデータや経営の裏側をオープンにして熱狂的な支持者を味方につける',
      ],
      coldOutreachTemplate: '【SNS運用の予約自動化】InstagramやXの投稿時間を最適化し、毎日の投稿作業を週1回に集約できるBufferのご案内です。',
    },
    temporal: {
      foundedYear: 2010,
      initialTractionPeriod: '2010-2013年 (7週間検証・ゲストポスト爆撃期)',
      dataSnapshotPeriod: '2014-2026年 (透明性経営確立・週休3日制導入・安定期)',
      viabilityStatus: 'MATURED_MOAT',
      viabilityLabel: '先行者堀により後発模倣困難（老舗ブランドと安定したキャッシュフロー）',
      eraContext: 'ソーシャルメディア（Twitter/Facebook）の黎明期と、APIエコシステムの爆発的拡大。',
      currentViabilityAnalysis: 'X APIの価格改定等の外部リスクを乗り越え、ThreadsやLinkedIn対応を強化して安定したストック収益を維持。',
    },
  },

  // 14. Cal.com
  {
    id: 'ent_calcom_scheduling',
    ticker: 'CAL.COM',
    name: 'Cal.com',
    legalEntity: 'Cal.com Inc.',
    tagline: '「Calendlyは自社ブランドを隠してCalendlyロゴを押し付けてくる」企業の不満を突き、ホワイトラベルと完全オープンソースで急成長した日程調整インフラ',
    sector: 'NICHE_SAAS',
    scale: 'SMALL_TEAM',
    founder: 'Peer Richelsen, Bailey Pumfleet',
    country: 'US',
    url: 'https://cal.com',
    verifiedBadge: true,
    growthRateYoY: 150.0,
    architecturePattern: 'メガSaaSのオープンソース・ホワイトラベル代替',
    pipelineStack: 'Next.js × Prisma × PostgreSQL × AGPL-3.0',
    targetPainWallet: '企業の情シス・開発者の「自社アプリの中に日程調整を埋め込みたいがCalendlyではカスタマイズできない苦痛」',
    tags: ['オープンソース', '日程調整', 'ホワイトラベル', 'Calendly代替', '開発者熱狂'],
    pnl: {
      monthlyRevenue: 60000000,
      cogs: 9000000,
      grossProfit: 51000000,
      grossMargin: 85.0,
      operatingExpenses: {
        serverAndApi: 6000000,
        advertising: 0,
        subcontracting: 5000000,
        toolsAndSaaS: 2000000,
        other: 8000000,
      },
      operatingProfit: 30000000,
      operatingMargin: 50.0,
      estimatedAnnualNetProfit: 360000000,
      financialStatus: 'REPORTED',
      isRevenueUnconfirmed: false,
      isMarginUnconfirmed: false,
      revenueLabel: '公式開示・VC調達ARR $5M+（数万社への日程調整インフラ提供）',
    },
    evidenceCards: [
      {
        id: 'ev_calcom_loot_blueprint',
        type: 'LOOT_BLUEPRINT',
        title: '【略奪転用】独占ツール（Calendly）の不満（ロゴ強制・データ主権）を突いてオープンソースで総取りする配管',
        badge: '略奪転用方程式',
        evidenceStatus: 'VERIFIED',
        punchline: '「自社のロゴを入れたい」「医療情報（HIPAA）を米国外に出せない」という大企業の法務リスクを突いて、セルフホスト版とAPIを売り抜く。',
        details: [
          '【Step 1: 既存独占の急所を突く】: Calendlyが自社ロゴを押し付け、開発者向けAPIを軽視している隙間を特定。',
          '【Step 2: 完全オープンソースと美しいUI】: GitHubで3万Starを集める美しいNext.jsアプリを無料公開し、開発者を味方につける。',
          '【Step 3: 組み込みAPI（Cal Platform）で課金】: テレヘルス（オンライン診療）やHRアプリの内部に日程調整を組み込ませ、月額＋従量課金を回収。',
        ],
        codeSnippet: '// Cal.comのReact組み込みEmbedスニペット\nimport Cal, { getCalApi } from "@calcom/embed-react";\nexport function BookingWidget() {\n  return <Cal calLink="team/sales" style={{ width: "100%", height: "100%" }} config={{ layout: "month_view", theme: "dark" }} />;\n}',
        sourceNote: 'Peer Richelsenの公開ポッドキャストおよびGitHub calcomリポジトリ（3万Star）から抽出',
      },
      {
        id: 'ev_calcom_crime',
        type: 'THE_CRIME',
        title: 'Calendlyが10年かけて独占した市場に「オープンソースとドメインハック（Cal.com）」で突入し顧客を奪取',
        badge: '身も蓋もない真実',
        evidenceStatus: 'VERIFIED',
        punchline: '「予約リンクを送る相手に失礼にならない美しいデザイン」と「超短縮ドメイン（cal.com/name）」の虚栄心を突き、テック業界のデファクトを強襲。',
        details: [
          'オープンソース開発者を世界中から巻き込み、何十ものカレンダーやビデオ会議ツールとの連携機能を完全ボランティアで実装させた。',
          'Calendlyの高額エンタープライズ料金に怒っていたオンライン診療や教育プラットフォームに、裏側インフラとして一括採用された。',
        ],
      },
    ],
    operations: {
      teamSize: 25,
      weeklyHours: 40,
      initialCapitalRequired: 5000000,
      automationLevel: 88,
      primaryChannels: ['GitHubオープンソース（3万Star）', '開発者X口コミ', '日程調整リンク自体の自然バイラル'],
      toolStack: [
        { name: 'Supabase / AWS', category: 'データベース', monthlyCost: 4000000, purpose: '高可用性スケジューリング基盤' },
        { name: 'Stripe', category: '決済代行', monthlyCost: 1800000, purpose: 'チーム課金およびプラットフォームAPI課金' },
      ],
    },
    strategy: {
      blindspot: 'Calendlyは非エンジニア向けの単体Webアプリに留まり、自社プロダクトの中に日程調整を「部品」として組み込みたい開発者の巨大なAPI需要を放置していた。',
      moatType: 'NETWORK_EFFECT',
      moatDescription: '世界中の開発者が新しい機能や連携アプリを勝手にPull Requestで追加してくれるオープンソース開発フライホイール。',
      incumbentDilemma: 'Calendlyは自社ブランドの露出（予約画面のCalendlyロゴ）を武器にバイラルグロースしているため、ホワイトラベル（完全無地）を安価で提供できない。',
      secretInsight: '巨人SaaSに対抗する最強の一手は、「巨人が自社ブランドを守るために意地でもやらないこと（ホワイトラベル・自社ロゴ消去）」を武器にすることである。',
      initialTraction: [
        'Calendsoという名前でGitHubにコードを初公開し、Hacker Newsのトップで何千ものStarを獲得',
        'Alexis Ohanian（Reddit創業者）やトップVCから資金調達し、ドメイン「Cal.com」を買収',
        'オンライン診療スタートアップ等に「Calendlyの1/5のコストでAPI連携できる」と営業し大口契約を連発',
      ],
      actionPlaybook: [
        'Step 1: 誰もが使っている定番ツールの「自社ブランド強制（Powered by〇〇）」に不満を持つ層を探す',
        'Step 2: ホワイトラベルで完全に自社ブランドとして埋め込めるオープンソース版を作る',
        'Step 3: そのツールを自社アプリに組み込みたい企業向けに「プラットフォームAPI」を売る',
      ],
      coldOutreachTemplate: '【Calendlyの自社ブランド化とコスト削減】貴社の自社ドメイン・自社ロゴだけで顧客に予約させ、完全API制御できるCal.comのご案内です。',
    },
    temporal: {
      foundedYear: 2021,
      initialTractionPeriod: '2021-2022年 (オープンソース公開・Cal.com買収期)',
      dataSnapshotPeriod: '2023-2026年 (Platform API急成長・エンタープライズ導入期)',
      viabilityStatus: 'RISING_WAVE',
      viabilityLabel: '急上昇トレンド最盛期（次世代スケジューリング標準）',
      eraContext: 'オープンソース商用化（COSS: Commercial Open Source Software）ブームの最前線。',
      currentViabilityAnalysis: '単なる個人ツールではなく、オンライン診療やマーケットプレイスの「組み込みインフラ」としての地位を確立しており極めて強固。',
    },
  },

  // 15. Supabase
  {
    id: 'ent_supabase_db',
    ticker: 'SUPABASE',
    name: 'Supabase',
    legalEntity: 'Supabase Inc.',
    tagline: '「Google FirebaseのNoSQLと独自ロックインに縛られるのは嫌だ」開発者の怒りを突き、PostgreSQLをそのままREST/GraphQL APIにしてARR 40億円を稼ぐ脱Google要塞',
    sector: 'NICHE_SAAS',
    scale: 'SCALEUP',
    founder: 'Paul Copplestone, Ant Wilson',
    country: 'SG',
    url: 'https://supabase.com',
    verifiedBadge: true,
    growthRateYoY: 160.0,
    architecturePattern: '巨大プラットフォーム（Firebase）のオープンソース代替',
    pipelineStack: 'PostgreSQL × GoTrue (Auth) × PostgREST × Realtime (Elixir) × AWS',
    targetPainWallet: '開発者の「Firebaseの複雑なクエリ制限と、従量課金が跳ね上がって破産する恐怖」',
    tags: ['オープンソース', 'Postgres', '脱Google', 'ARR40億円超', '開発者熱狂'],
    pnl: {
      monthlyRevenue: 350000000,
      cogs: 55000000,
      grossProfit: 295000000,
      grossMargin: 84.3,
      operatingExpenses: {
        serverAndApi: 40000000,
        advertising: 0,
        subcontracting: 20000000,
        toolsAndSaaS: 10000000,
        other: 75000000,
      },
      operatingProfit: 150000000,
      operatingMargin: 42.9,
      estimatedAnnualNetProfit: 1800000000,
      financialStatus: 'REPORTED',
      isRevenueUnconfirmed: false,
      isMarginUnconfirmed: false,
      revenueLabel: '公式開示・業界推計 ARR $30M規模（月商約3.5億円）',
    },
    evidenceCards: [
      {
        id: 'ev_supabase_loot_blueprint',
        type: 'LOOT_BLUEPRINT',
        title: '【略奪転用】Firebaseの従量課金地獄に怯えるエンジニアに「本物のPostgreSQL」を渡して総取りする配管',
        badge: '略奪転用方程式',
        evidenceStatus: 'VERIFIED',
        punchline: 'Googleが提供するNoSQL（Firestore）のクエリの不自由さを突いて、「世界標準のSQLがそのままリアルタイムで動く」極上の開発体験を提供。',
        details: [
          '【Step 1: Googleのロックインを突く】: 一度Firebaseに入れるとSQLが使えず、他社へ移行できない開発者の不満を特定。',
          '【Step 2: 既存オープンソースの天才的統合】: PostgreSQLの周りにPostgREST（API自動化）とGoTrue（認証）を束ねて1つのダッシュボードに。',
          '【Step 3: データベースサイズと計算リソース課金】: 無料枠でスタートアップを囲い込み、本番環境への移行で月$25〜数千ドルのストックを確保。',
        ],
        codeSnippet: '// Supabaseの1行データ取得・リアルタイムリスナー設定スニペット\nimport { createClient } from "@supabase/supabase-js";\nconst supabase = createClient(process.env.SUPABASE_URL, process.env.SUPABASE_ANON_KEY);\nexport async function getLiveUsers() {\n  const { data } = await supabase.from("users").select("*").eq("status", "ACTIVE");\n  return data;\n}',
        sourceNote: 'Paul CopplestoneのYCポッドキャストおよびSupabase公式ローンチウィーク資料から抽出',
      },
      {
        id: 'ev_supabase_crime',
        type: 'THE_CRIME',
        title: '「The Open Source Firebase Alternative」のワンフレーズだけでGoogleから開発者を大移動させる',
        badge: '身も蓋もない真実',
        evidenceStatus: 'VERIFIED',
        punchline: 'Googleの莫大な開発費で作られたFirebaseの機能を、世界中で愛されているPostgreSQLで再現し、広告費ゼロで開発者の聖地へ上り詰める。',
        details: [
          '3ヶ月ごとに「Launch Week」を開催し、毎日新機能を発表するお祭りを演出してTwitterのトレンドを完全制覇。',
          'AI時代において「pgvector（ベクトル検索）」を最速で標準装備し、AIスタートアップのデフォルトデータベースの座を奪取。',
        ],
      },
    ],
    operations: {
      teamSize: 80,
      weeklyHours: 40,
      initialCapitalRequired: 20000000,
      automationLevel: 90,
      primaryChannels: ['GitHub（7万Star）', 'Launch Weekイベントマーケ', '開発者技術ブログ'],
      toolStack: [
        { name: 'AWS EC2 / RDS', category: 'クラウドインフラ', monthlyCost: 35000000, purpose: 'グローバルPostgresホスティング' },
        { name: 'Stripe Billing', category: '従量課金基盤', monthlyCost: 10000000, purpose: 'コンピュート時間およびストレージ従量課金' },
      ],
    },
    strategy: {
      blindspot: 'GoogleはFirebaseを自社のGCPエコシステムに囲い込むための撒き餌として使っていたため、オープンソース化やSQL標準への回帰を拒否していた。',
      moatType: 'SWITCHING_COST',
      moatDescription: '企業の基幹データ、認証基盤、ストレージ、リアルタイム購読が全てSupabaseに格納され、乗り換えが極めて困難な重力場。',
      incumbentDilemma: 'GoogleがFirebaseをPostgreSQLベースに作り直すと、既存のFirestoreやCloud SQLの収益モデルと衝突（カニバリズム）するため対抗できない。',
      secretInsight: '開発者向けビジネスの最大の勝ち筋は「GoogleやAWSの独占に怯えるエンジニアに、独立したオープンソースの逃げ道を提供すること」である。',
      initialTraction: [
        'Y Combinator（S20）で「Firebaseのオープンソース版」という強烈な一行ピッチで話題沸騰',
        'Hacker Newsで公開するたびに数千ポイントを獲得し、オープンソース界のトップスターへ',
        'pgvectorの早期リリースにより、全AIアプリ開発者の第一選択肢として独占的ポジションを獲得',
      ],
      actionPlaybook: [
        'Step 1: 巨大IT（Google/Amazon/Apple）が自社都合で囲い込んでいる独自規格を見つける',
        'Step 2: オープン標準（SQL/Linux/HTML等）をベースにしたモダンな代替を作る',
        'Step 3: 「脱〇〇」の大義名分を掲げてコミュニティを味方につけ、ホスティング代金でマネタイズする',
      ],
      coldOutreachTemplate: '【Firebaseの従量課金削減とSQLへの移行】Firestoreの制限を撤廃し、PostgreSQLで安全にスケーリングできるSupabaseのご案内です。',
    },
    temporal: {
      foundedYear: 2020,
      initialTractionPeriod: '2020-2022年 (オープンソース公開・YC期)',
      dataSnapshotPeriod: '2023-2026年 (ARR $30M突破・pgvectorによるAI基盤化期)',
      viabilityStatus: 'RISING_WAVE',
      viabilityLabel: '急上昇トレンド最盛期（新世代クラウドデータベースの覇権）',
      eraContext: '脱クラウド・データ主権の潮流と、ベクター検索による生成AIアプリケーションの爆発的増加。',
      currentViabilityAnalysis: 'PostgreSQLという人類最強のデータベース基盤に乗っているため、流行り廃りのリスクが極めて低く永続的な要塞を構築。',
    },
  },
];
