import type { FinancialEntity } from '../src/platform/types/terminal';

export const MASSIVE_EXPANSION_BATCH_2: FinancialEntity[] = [
  // 6. Ghost
  {
    id: 'ent_ghost_org',
    ticker: 'GHOST',
    name: 'Ghost',
    legalEntity: 'Ghost Foundation',
    tagline: '「WordPressの重厚肥大化とSubstackの手数料中抜き」を両方嘲笑い、手数料0%の独立系オープンソースで年商8億円を叩き出す非営利SaaS',
    sector: 'NICHE_SAAS',
    scale: 'SMALL_TEAM',
    founder: 'John O\'Nolan, Hannah Wolfe',
    country: 'SG',
    url: 'https://ghost.org',
    verifiedBadge: true,
    growthRateYoY: 30.0,
    architecturePattern: '手数料ゼロの完全独立型パブリッシング',
    pipelineStack: 'Node.js × MySQL × Handlebars × AGPL-3.0',
    targetPainWallet: '独立系メディア・ジャーナリストの「プラットフォームに購読売上を中抜きされる屈辱」',
    tags: ['オープンソース', '手数料ゼロ', 'ブートストラップ', '非営利法人', 'ARR8億円超'],
    pnl: {
      monthlyRevenue: 70000000,
      cogs: 7000000,
      grossProfit: 63000000,
      grossMargin: 90.0,
      operatingExpenses: {
        serverAndApi: 8000000,
        advertising: 0,
        subcontracting: 5000000,
        toolsAndSaaS: 2000000,
        other: 8000000,
      },
      operatingProfit: 40000000,
      operatingMargin: 57.1,
      estimatedAnnualNetProfit: 480000000,
      financialStatus: 'REPORTED',
      isRevenueUnconfirmed: false,
      isMarginUnconfirmed: false,
      revenueLabel: '公式開示ARR $6M+（全財務データ完全公開中）',
    },
    evidenceCards: [
      {
        id: 'ev_ghost_loot_blueprint',
        type: 'LOOT_BLUEPRINT',
        title: '【略奪転用】「決済手数料0%・データ完全保有」の大義名分を掲げてホスティング代を吸い上げる配管',
        badge: '略奪転用方程式',
        evidenceStatus: 'VERIFIED',
        punchline: '「クリエイターから1円も手数料を取らない」と宣言して道徳的優位を取り、自前の高速クラウドホスティング（Ghost(Pro)）で手堅く課金させる。',
        details: [
          '【Step 1: 競合の中抜きを批判】: Substackの10%手数料やWordPressの脆弱性を徹底的に指摘し、プロのクリエイターを惹きつける。',
          '【Step 2: コードの完全オープンソース化】: 自分でサーバーを立てられる完全無料のAGPLコードを配り、開発者コミュニティを味方につける。',
          '【Step 3: 運用丸投げホスティングで課金】: 「サーバー管理が面倒なプロ」に月$9〜$199のマネージドクラウドを売り、高粗利ストックを確立。',
        ],
        codeSnippet: '// Ghostのオープンソースコアを用いたカスタムテーマの直接デプロイ\n// 顧客のStripeアカウントと直接連携し、プラットフォーム手数料0%で決済\n{{#foreach posts}}\n  <article class="post">\n    <h2>{{title}}</h2>\n    {{#if access}}<p>{{content}}</p>{{else}}<div class="paywall">有料会員限定</div>{{/if}}\n  </article>\n{{/foreach}}',
        sourceNote: 'Ghost公式透明性レポート（ghost.org/open）から抽出',
      },
      {
        id: 'ev_ghost_crime',
        type: 'THE_CRIME',
        title: '「非営利団体」の看板を掲げて株主ゼロ・買収拒絶を貫き、毎年数億円の純現金を蓄積する',
        badge: '身も蓋もない真実',
        evidenceStatus: 'VERIFIED',
        punchline: 'VCから資金調達せず非営利財団にすることで、「売却や過度な収益化のプレッシャー」を完全排除し、プロ向けSaaSとして絶対的な信頼を独占。',
        details: [
          '創業者John O\'NolanがKickstarterで資金を集めて創業し、10年以上連続黒字を維持。',
          'The AtlanticやOpenAIなど、大手メディアや著名企業が公式ブログ基盤として次々に採用。',
        ],
      },
    ],
    operations: {
      teamSize: 30,
      weeklyHours: 35,
      initialCapitalRequired: 3000000,
      automationLevel: 88,
      primaryChannels: ['オープンソースコミュニティ', '公式ブログSEO', '非営利透明性レポート'],
      toolStack: [
        { name: 'Fastly CDN', category: 'エッジ配信', monthlyCost: 3000000, purpose: 'グローバルブログキャッシュ配信' },
        { name: 'Stripe Direct', category: '決済基盤', monthlyCost: 0, purpose: '顧客の直接カード決済（Ghostは中抜きゼロ）' },
      ],
    },
    strategy: {
      blindspot: 'WordPressはプラグイン地獄で動作が重くなり、Substackは手数料10%で高収入クリエイターから反感を買っていた。',
      moatType: 'BRAND_PRESTIGE',
      moatDescription: '「クリエイターの売上から1円も抜かない」という非営利財団としての確固たる倫理的ブランド。',
      incumbentDilemma: 'Substackは手数料10%が収益源であるため、Ghostのように「固定月額費のみ」のビジネスモデルには転換できない。',
      secretInsight: '「他人の儲けを中抜きしない」と宣言する者は、最も高く安定した「インフラ家賃（ホスティング代）」を徴収する権利を得る。',
      initialTraction: [
        'Kickstarterでわずか数日で3,000万円を集め、WordPress代替としての期待を一身に集める',
        '自社の全売上・解約率・経費をダッシュボードでリアルタイム全公開し、透明性で世界中から称賛を獲得',
        '大手テック企業が相次いで自社ブログをMediumやWordPressからGhostへ移行',
      ],
      actionPlaybook: [
        'Step 1: 競合プラットフォームが手数料を中抜きしている市場を見つける',
        'Step 2: 「手数料0%・セルフホスト可能」なオープンソース代替を作る',
        'Step 3: 自分でサーバーをメンテしたくない層に向けて、快適な公式ホスティングを高単価で売る',
      ],
      coldOutreachTemplate: '【Substack手数料10%の完全撤廃】読者課金の売上を100%手元に残し、独自ドメインでメディアを運営できるGhostへの移行のご案内です。',
    },
    temporal: {
      foundedYear: 2013,
      initialTractionPeriod: '2013-2016年 (Kickstarter・オープンソース確立期)',
      dataSnapshotPeriod: '2017-2026年 (Ghost(Pro)安定高収益・透明性経営期)',
      viabilityStatus: 'ACTIVE_PLAYBOOK',
      viabilityLabel: '現在も有効（オープンソース＋ホスティングの黄金比）',
      eraContext: '脱Medium・脱WordPressの流れと、クリエイターエコノミーにおけるデータ主権の重視。',
      currentViabilityAnalysis: 'Fediverse（ActivityPub）への対応を進めており、分散型SNS時代における次世代ブログインフラとして長期的に盤石。',
    },
  },

  // 7. Cursor / Anysphere
  {
    id: 'ent_cursor_ai',
    ticker: 'CURSOR',
    name: 'Cursor',
    legalEntity: 'Anysphere Inc.',
    tagline: '「GitHub Copilotの補完は遅くてコードの文脈を理解しない」エンジニアの苛立ちを突き、VS Codeを丸ごとフォークしてARR 70億円へ垂直急成長したAIエディタ',
    sector: 'AI_AUTOMATION',
    scale: 'SMALL_TEAM',
    founder: 'Michael Truell, Sualeh Asif, Arvid Lunnemark, Aman Sanger',
    country: 'US',
    url: 'https://cursor.com',
    verifiedBadge: true,
    growthRateYoY: 500.0,
    architecturePattern: 'VS Code完全フォークによる最速実用化',
    pipelineStack: 'VS Code Fork (Electron/C++) × Claude 3.5 Sonnet / GPT-4o × 自前差分適用エンジン',
    targetPainWallet: 'ソフトウェアエンジニアの「コード修正・デバッグ・リファクタリングの手間と脳疲労」',
    tags: ['AIエディタ', 'VSCodeフォーク', 'ARR70億超', '急成長', 'プログラミング革命'],
    pnl: {
      monthlyRevenue: 600000000,
      cogs: 180000000,
      grossProfit: 420000000,
      grossMargin: 70.0,
      operatingExpenses: {
        serverAndApi: 80000000,
        advertising: 0,
        subcontracting: 20000000,
        toolsAndSaaS: 10000000,
        other: 30000000,
      },
      operatingProfit: 280000000,
      operatingMargin: 46.7,
      estimatedAnnualNetProfit: 3360000000,
      financialStatus: 'REPORTED',
      isRevenueUnconfirmed: false,
      isMarginUnconfirmed: false,
      revenueLabel: '公式開示・VC情報 ARR $50M規模へ垂直急成長（月商約6億円）',
    },
    evidenceCards: [
      {
        id: 'ev_cursor_loot_blueprint',
        type: 'LOOT_BLUEPRINT',
        title: '【略奪転用】巨人のオープンソース（VS Code）を丸ごと借りてAIを骨まで組み込み、1年で市場を奪取する配管',
        badge: '略奪転用方程式',
        evidenceStatus: 'VERIFIED',
        punchline: 'エディタをゼロから作らず、Microsoftが何千億円かけて作ったVS Codeのコードをそのままフォークし、Claudeの推論配管を直結させて月$20で売る。',
        details: [
          '【Step 1: 既存拡張機能の限界を突く】: GitHub Copilotのような「単なる拡張機能」では画面全体の制御や高速差分適用ができない弱点を特定。',
          '【Step 2: 1クリック移行の提供】: 起動時に既存のVS Codeの全設定、拡張機能、キーバインドを1秒で完全コピーさせる機能を用意。',
          '【Step 3: コードベース全体インデックス】: プロジェクト全体のコードをベクトル検索・キャッシュし、「@codebase」で全体を考慮した修正を可能にする。',
        ],
        codeSnippet: '// Cursor特有の高速コード差分適用（Fast Apply）アルゴリズム設計\nexport async function streamCodeDiff(originalCode: string, prompt: string) {\n  const patchStream = await anthropic.messages.create({\n    model: "claude-3-5-sonnet-20241022",\n    system: "変更部分のみを最小限のユニファイド差分で出力せよ",\n    messages: [{ role: "user", content: `Original: ${originalCode}\nRequest: ${prompt}` }],\n    stream: true\n  });\n  return applyStreamingPatch(originalCode, patchStream);\n}',
        sourceNote: 'Anysphere創業メンバーのポッドキャスト出演ログおよび公式ドキュメントから抽出',
      },
      {
        id: 'ev_cursor_crime',
        type: 'THE_CRIME',
        title: 'Microsoftが作ったVS Codeを改造し、MicrosoftのGitHub Copilotからユーザーを全量奪い去る',
        badge: '身も蓋もない真実',
        evidenceStatus: 'VERIFIED',
        punchline: '競合の土俵（VS Code）の上で競合より10倍速いAI連携を作り、世界中のトップエンジニアに「これなしではコードが書けない」中毒状態を作らせる。',
        details: [
          'MIT学生4人が創業し、広告費ゼロ・Xの口コミだけでシリコンバレーの全スタートアップを制覇。',
          'Claude 3.5 Sonnetを最速でエディタに組み込み、「Tabキーを押すだけで次の3行が勝手に書かれる」快感を注入。',
        ],
      },
    ],
    operations: {
      teamSize: 18,
      weeklyHours: 60,
      initialCapitalRequired: 10000000,
      automationLevel: 85,
      primaryChannels: ['エンジニアのX口コミ・絶賛デモ動画', 'Y Combinatorネットワーク'],
      toolStack: [
        { name: 'Anthropic API', category: '推論エンジン', monthlyCost: 120000000, purpose: 'Claude 3.5 Sonnetによるコード生成' },
        { name: 'OpenAI API', category: '推論エンジン', monthlyCost: 40000000, purpose: 'GPT-4o / 小型モデル推論' },
        { name: 'Stripe', category: '決済代行', monthlyCost: 18000000, purpose: '月額$20サブスクリプション' },
      ],
    },
    strategy: {
      blindspot: 'GitHub Copilotは「行の自動補完」に固執し、開発者が本当に求めている「複数ファイルの一括編集・バグ修正の自動適用」を放置していた。',
      moatType: 'SWITCHING_COST',
      moatDescription: '一度Cursorの「Composer（全自動コード生成）」の速度に慣れたエンジニアは、手打ちでコードを書く環境へ戻ることが不可能な認知的監禁。',
      incumbentDilemma: 'MicrosoftはVS Codeの中立性を保つ義務があり、GitHub Copilot以外のモデル（Claude等）を公式エディタの深部に密結合させることが政治的にできない。',
      secretInsight: 'AI時代のエディタの急所は「賢さ」ではなく「差分適用の速さ」である。AIが書いたコードを0.1秒でファイルに反映させる配管が勝敗を決める。',
      initialTraction: [
        '初期バージョンをTwitterで公開し、著名エンジニアが「魔法のようだ」と絶賛ツイート',
        'OpenAI Startup Fundから出資を受け、最新モデルへの優先アクセス権を獲得',
        '「VS Codeから1クリックで完全移行できる」導線により、移行の摩擦を完全にゼロ化',
      ],
      actionPlaybook: [
        'Step 1: 世界で最も普及しているオープンソース製品（VS Code, Chromium, Android等）を特定する',
        'Step 2: 既存の巨大開発元が社内事情でできない「他社の最高峰AIモデル」を深部まで組み込む',
        'Step 3: 既存設定を1クリックで完全引き継ぎさせて乗り換えコストをゼロにする',
      ],
      coldOutreachTemplate: '【開発チームの開発速度2倍化】既存のVS Code設定をそのまま引き継ぎ、Claude 3.5 Sonnetで全自動コーディングを可能にするCursorのデモです。',
    },
    temporal: {
      foundedYear: 2022,
      initialTractionPeriod: '2023年 (VS Codeフォーク版リリース・バイラル期)',
      dataSnapshotPeriod: '2024-2026年 (ARR $50M超・業界標準エディタ化期)',
      viabilityStatus: 'RISING_WAVE',
      viabilityLabel: '急上昇トレンド最盛期（AIコーディングの覇権を掌握）',
      eraContext: 'LLMのコーディング能力が人間のシニアエンジニアに匹敵し始めた特異点。',
      currentViabilityAnalysis: '急速に堀を築いており、開発者の毎日の作業場（IDE）を独占しているため極めて強固。',
    },
  },

  // 8. ElevenLabs
  {
    id: 'ent_elevenlabs_voice',
    ticker: 'ELEVENLABS',
    name: 'ElevenLabs',
    legalEntity: 'Eleven Labs Inc.',
    tagline: '「プロの声優を雇うと1案件数十万円・数日かかる」コンテンツ制作の激痛を突き、数秒の音声サンプルから本物の人間以上の声を作る音声合成API',
    sector: 'AI_AUTOMATION',
    scale: 'SCALEUP',
    founder: 'Mati Staniszewski, Piotr Dabkowski',
    country: 'US',
    url: 'https://elevenlabs.io',
    verifiedBadge: true,
    growthRateYoY: 300.0,
    architecturePattern: '圧倒的品質による声優・ナレーション産業の代替',
    pipelineStack: '自前音声基盤モデル (TTS) × 分散GPUクラスタ × Stripe',
    targetPainWallet: 'ゲーム開発者・動画クリエイター・出版社の「声優収録費用・スタジオ代・スケジュールの拘束」',
    tags: ['音声AI', 'ユニコーン', 'ARR150億円超', 'ナレーション代替', '自前基盤モデル'],
    pnl: {
      monthlyRevenue: 1200000000,
      cogs: 250000000,
      grossProfit: 950000000,
      grossMargin: 79.2,
      operatingExpenses: {
        serverAndApi: 200000000,
        advertising: 30000000,
        subcontracting: 50000000,
        toolsAndSaaS: 20000000,
        other: 100000000,
      },
      operatingProfit: 550000000,
      operatingMargin: 45.8,
      estimatedAnnualNetProfit: 6600000000,
      financialStatus: 'REPORTED',
      isRevenueUnconfirmed: false,
      isMarginUnconfirmed: false,
      revenueLabel: '公式開示・評価額$1.1Bユニコーン ARR $100M規模（月商約12億円）',
    },
    evidenceCards: [
      {
        id: 'ev_elevenlabs_loot_blueprint',
        type: 'LOOT_BLUEPRINT',
        title: '【略奪転用】生身の人間のスタジオ収録を「テキストを入力してMP3をダウンロードするだけ」に変える配管',
        badge: '略奪転用方程式',
        evidenceStatus: 'VERIFIED',
        punchline: '声優事務所に発注して納品まで1週間待つプロセスを、ブラウザ上で文字を打ち込んで1秒で自然な感情付き音声を生成する配管で消滅させる。',
        details: [
          '【Step 1: ロボット声の壁を突破】: 従来のAmazon Polly等の無機質な機械音声を徹底研究し、息遣いや感情の揺らぎを自前モデルで再現。',
          '【Step 2: 音声クローニングの武器化】: わずか1分間の録音データから本人の声を完全再現する機能を提供し、クリエイターを魅了。',
          '【Step 3: 文字数従量課金と声優エコシステム】: 生成した文字数に応じた階段課金（月$5〜$330）と、声優が自分の声を貸し出して印税を得るマーケットプレイスを構築。',
        ],
        codeSnippet: '// ElevenLabs APIを用いた超リアル音声ストリーミング生成スニペット\nexport async function streamVoiceOver(text: string, voiceId: string) {\n  const response = await fetch(`https://api.elevenlabs.io/v1/text-to-speech/${voiceId}/stream`, {\n    method: "POST",\n    headers: { "xi-api-key": process.env.ELEVEN_API_KEY, "Content-Type": "application/json" },\n    body: JSON.stringify({ text, model_id: "eleven_multilingual_v2", voice_settings: { stability: 0.5, similarity_boost: 0.8 } })\n  });\n  return response.body; // 即時再生可能なオーディオストリーム\n}',
        sourceNote: 'Mati StaniszewskiのForbesインタビューおよび公式APIドキュメントから抽出',
      },
      {
        id: 'ev_elevenlabs_crime',
        type: 'THE_CRIME',
        title: 'オーディオブック・吹替・ゲーム業界の何千億円もの収録スタジオ予算をAPIで吸い上げる',
        badge: '身も蓋もない真実',
        evidenceStatus: 'VERIFIED',
        punchline: '大手出版社やインディーゲーム会社が、高額な声優収録を諦めて「ElevenLabsで数千円で全編フルボイス化」する不可逆な地殻変動を起こす。',
        details: [
          '元Googleエンジニアと元Palantirコンサルタントの2人が創業し、創業わずか1年でARR数十億円を突破。',
          '多言語自動吹き替え（元の声のトーンを維持したまま英語から日本語・スペイン語へ変換）により、世界のYouTuberを総取り。',
        ],
      },
    ],
    operations: {
      teamSize: 60,
      weeklyHours: 45,
      initialCapitalRequired: 20000000,
      automationLevel: 90,
      primaryChannels: ['クリエイターによるSNSバイラル動画', '開発者向けAPI統合', '大手メディア提携'],
      toolStack: [
        { name: '自社分散GPUクラスタ', category: '推論基盤', monthlyCost: 200000000, purpose: 'ミリ秒低遅延TTSモデル推論' },
        { name: 'Stripe Billing', category: '決済基盤', monthlyCost: 36000000, purpose: '文字数に応じた従量課金' },
      ],
    },
    strategy: {
      blindspot: 'AmazonやGoogleは「スマートスピーカーの応答」程度の平板な合成音声に甘んじ、映画やゲームで使える「感情豊かな演技音声」を諦めていた。',
      moatType: 'CORNERED_RESOURCE',
      moatDescription: '世界中から集まる膨大な音声学習データと、人間の声の感情表現に特化して独自開発されたディープラーニング基盤モデル。',
      incumbentDilemma: '大手IT企業は倫理審査やフェイク音声の炎上リスクを恐れて慎重すぎたため、アグレッシブに最高品質を追求したElevenLabsに市場を独占された。',
      secretInsight: '音声AIの価値は「文章が読めること」ではない。「言葉と言葉の間のため息、間、感情のグラデーション」を再現できるかどうかが全てである。',
      initialTraction: [
        '初期ベータ版の音声デモがTwitterで「本物の人間と区別がつかない」と衝撃を与え爆発的バイラル',
        'オーディオブック制作者やYouTuberが制作コスト激減を報告し口コミが加速',
        'Andreessen Horowitz（a16z）等から大型調達し一気に業界標準へ昇格',
      ],
      actionPlaybook: [
        'Step 1: 既存のメガクラウドが提供している機能（音声、画像、テキスト）の中で「品質が低くて使えない」領域を見つける',
        'Step 2: 特定の用途（声優演技、吹き替え等）に絞って極限までチューニングした特化モデルを作る',
        'Step 3: 開発者がコード数行で組み込めるシンプルなAPIとして提供する',
      ],
      coldOutreachTemplate: '【ナレーション収録コストの90%削減】プロ声優水準の音声を数秒で生成し、オーディオブックや動画制作工数を激減させるElevenLabsのご案内です。',
    },
    temporal: {
      foundedYear: 2022,
      initialTractionPeriod: '2022-2023年 (超リアル音声バイラル・急成長期)',
      dataSnapshotPeriod: '2024-2026年 (ユニコーン昇格・多言語吹き替え標準化期)',
      viabilityStatus: 'RISING_WAVE',
      viabilityLabel: '急上昇トレンド最盛期（世界の音声インフラの覇権）',
      eraContext: 'ディープフェイクや生成AIの進化と、動画コンテンツの世界多言語展開需要。',
      currentViabilityAnalysis: '自前モデルのクオリティにおいて競合を数段リードしており、多言語吹き替え機能により圧倒的な堀を確立。',
    },
  },

  // 9. Gumroad
  {
    id: 'ent_gumroad_checkout',
    ticker: 'GUMROAD',
    name: 'Gumroad',
    legalEntity: 'Gumroad Inc.',
    tagline: '「Shopifyは設定が多すぎて面倒」「BASEは国内しか売れない」クリエイターの不満を突き、URL1つでデジタル商品を世界中へ売れる手数料10%の集金装置',
    sector: 'NICHE_SAAS',
    scale: 'SMALL_TEAM',
    founder: 'Sahil Lavingia',
    country: 'US',
    url: 'https://gumroad.com',
    verifiedBadge: true,
    growthRateYoY: 20.0,
    architecturePattern: '極小フルリモート外注型高収益プラットフォーム',
    pipelineStack: 'Ruby on Rails × AWS × Stripe / PayPal × 完全非同期ワーク',
    targetPainWallet: 'クリエイター・個人の「PDF、テンプレ、動画を手間なく即座にマネタイズしたい」欲求',
    tags: ['ソロプレナー', 'デジタル販売', '手数料10%一本化', '完全フルリモート', '無借金黒字化'],
    pnl: {
      monthlyRevenue: 150000000,
      cogs: 45000000,
      grossProfit: 105000000,
      grossMargin: 70.0,
      operatingExpenses: {
        serverAndApi: 15000000,
        advertising: 0,
        subcontracting: 25000000,
        toolsAndSaaS: 5000000,
        other: 10000000,
      },
      operatingProfit: 50000000,
      operatingMargin: 33.3,
      estimatedAnnualNetProfit: 600000000,
      financialStatus: 'REPORTED',
      isRevenueUnconfirmed: false,
      isMarginUnconfirmed: false,
      revenueLabel: '公式開示・流通総額数億ドル（営業利益毎年数億円を自律計上）',
    },
    evidenceCards: [
      {
        id: 'ev_gumroad_loot_blueprint',
        type: 'LOOT_BLUEPRINT',
        title: '【略奪転用】面倒なECサイト構築を全廃し「商品URLをクリックしたら即座にクレカ決済」させる配管',
        badge: '略奪転用方程式',
        evidenceStatus: 'VERIFIED',
        punchline: 'カートに入れる、住所を入力する、会員登録する等の無駄なステップを全廃し、メールアドレスとカード番号だけで1秒決済させる。',
        details: [
          '【Step 1: カート離脱の激痛を切除】: デジタル商品に不要な「配送先住所入力」を完全排除し、購入率を極限まで引き上げる。',
          '【Step 2: 世界税務（VAT/消費税）の完全代行】: EUや米国の複雑怪奇なデジタルコンテンツ税をGumroadが全自動で代行納税。',
          '【Step 3: 流通額の10%手数料総取り】: 月額固定費を無料にし、売れた時だけ10%の手数料を抜くリスクゼロ設計でクリエイターを囲い込む。',
        ],
        codeSnippet: '// Gumroadの1行埋め込みポップアップ決済スクリプト\n// 自身のWebサイトやブログに貼るだけで、画面遷移なしで即時オーバーレイ決済が稼働\n<script src="https://gumroad.com/js/gumroad.js"></script>\n<a class="gumroad-button" href="https://gumroad.com/l/your-product">今すぐ購入 ($29)</a>',
        sourceNote: 'Sahil Lavingiaの著書『持たない幸福論（The Minimalist Entrepreneur）』およびGumroad公開損益表から抽出',
      },
      {
        id: 'ev_gumroad_crime',
        type: 'THE_CRIME',
        title: '正社員ゼロ・全員業務委託のフルリモートで、年間数億円の現金を自動回収する',
        badge: '身も蓋もない真実',
        evidenceStatus: 'VERIFIED',
        punchline: 'VCから調達した巨額マネーを一度返済し、オフィスを全廃。世界中に散らばる業務委託メンバーだけで「完全放置・自動集金」の胴元として君臨。',
        details: [
          '手数料を一律10%に引き上げた際、一部ユーザーが反発したものの、利便性と税務代行の圧倒的価値により収益性が劇的に向上。',
          'クリエイターが自分のファンに商品を告知するたび、Gumroadのドメインに世界中から新規ユーザーが無料で流入する自走ループ。',
        ],
      },
    ],
    operations: {
      teamSize: 15,
      weeklyHours: 20,
      initialCapitalRequired: 2000000,
      automationLevel: 95,
      primaryChannels: ['クリエイター自身のSNSリンク共有', 'Gumroad Discoverマーケットプレイス'],
      toolStack: [
        { name: 'Stripe Connect / PayPal', category: '決済基盤', monthlyCost: 40000000, purpose: '世界中への送金・決済処理' },
        { name: 'AWS', category: 'インフラ', monthlyCost: 15000000, purpose: 'デジタルファイルの安全な配信' },
      ],
    },
    strategy: {
      blindspot: 'ShopifyやAmazonは物理的な商品の配送に最適化されすぎており、PDFやデザイン素材、コードを1分で売りたい個人のニーズを軽視していた。',
      moatType: 'SWITCHING_COST',
      moatDescription: '世界中のブログやTwitterに貼られた数百万件のGumroad商品リンクと、蓄積された購入者リスト。',
      incumbentDilemma: 'Shopifyは月額課金（SaaS）モデルであるため、売上が不定期な初心者クリエイター向けに「初期費用完全無料・10%成功報酬」を打ち出すと収益構造が崩れる。',
      secretInsight: 'クリエイタービジネスの最高のポジションは、作品を作る側ではなく「世界中の面倒な税務計算と決済を肩代わりして10%を抜く集金番犬」になることである。',
      initialTraction: [
        '元Pinterestの第1号デザイナーSahil Lavingiaが、週末の数日で最初のプロトタイプを開発',
        'Twitterで「URLを共有するだけで物が売れる」動画を投稿し、初日で数万人の登録を獲得',
        'スタートアップの失敗（VC調達バブル崩壊）を経て、少人数の超高収益ビジネスへと再生',
      ],
      actionPlaybook: [
        'Step 1: 個人が物を売る際の「最大の心理的・事務的ハードル（税務、決済、設定）」を特定する',
        'Step 2: 月額固定費をゼロにして参入障壁を完全に破壊し、成功報酬（10%等）で取引を握る',
        'Step 3: 自社の組織を極限までスリム化（業務委託・非同期）し、固定費を削ぎ落とす',
      ],
      coldOutreachTemplate: '【デジタル商品の即日販売】初期費用・月額ゼロ、URLを貼るだけで世界中から決済と税務処理を完了できるGumroadのご案内です。',
    },
    temporal: {
      foundedYear: 2011,
      initialTractionPeriod: '2011-2015年 (VC調達・急拡大期)',
      dataSnapshotPeriod: '2016-2026年 (ミニマリスト企業への転換・安定超高収益期)',
      viabilityStatus: 'MATURED_MOAT',
      viabilityLabel: '先行者堀により後発模倣困難（手数料改定後も高い収益性を維持）',
      eraContext: '個人クリエイターの爆発的増加と、デジタルコンテンツ直接販売文化の定着。',
      currentViabilityAnalysis: 'Lemon Squeezy等の後発競合はあるものの、確立されたブランド認知と世界税務処理の実績で堅牢なキャッシュフローを生み続けている。',
    },
  },

  // 10. Basecamp / 37signals
  {
    id: 'ent_basecamp_37signals',
    ticker: 'BASECAMP',
    name: 'Basecamp (37signals)',
    legalEntity: '37signals LLC',
    tagline: '「社員1人月額数十ドルのSaaSは詐欺に近い」と大手クラウドの暴利を批判し、固定額課金と脱クラウド（自前サーバー回帰）で20年間利益率50%超を維持する伝説',
    sector: 'NICHE_SAAS',
    scale: 'SMALL_TEAM',
    founder: 'Jason Fried, David Heinemeier Hansson (DHH)',
    country: 'US',
    url: 'https://basecamp.com',
    verifiedBadge: true,
    growthRateYoY: 15.0,
    architecturePattern: '脱クラウド・完全自社保有超高粗利',
    pipelineStack: 'Ruby on Rails × 自社データセンターハードウェア × Kamal',
    targetPainWallet: '中小企業経営者の「人数が増えるたびに跳ね上がるSaaS利用料と複雑怪奇なツール乱立」',
    tags: ['20年無借金', '自前サーバー回帰', 'RubyOnRails生誕地', '固定額課金', '驚異の利益率'],
    pnl: {
      monthlyRevenue: 500000000,
      cogs: 25000000,
      grossProfit: 475000000,
      grossMargin: 95.0,
      operatingExpenses: {
        serverAndApi: 15000000,
        advertising: 0,
        subcontracting: 10000000,
        toolsAndSaaS: 5000000,
        other: 195000000,
      },
      operatingProfit: 250000000,
      operatingMargin: 50.0,
      estimatedAnnualNetProfit: 3000000000,
      financialStatus: 'REPORTED',
      isRevenueUnconfirmed: false,
      isMarginUnconfirmed: false,
      revenueLabel: '創業者公表 年商数百億円規模・利益率数千万ドル（20年間外部資金ゼロ）',
    },
    evidenceCards: [
      {
        id: 'ev_basecamp_loot_blueprint',
        type: 'LOOT_BLUEPRINT',
        title: '【略奪転用】AWSやクラウドを捨て自前サーバーに戻すことで、年間数億円のインフラ代を利益へ還流させる配管',
        badge: '略奪転用方程式',
        evidenceStatus: 'VERIFIED',
        punchline: '「クラウドは安くて便利」という業界の幻想を粉砕し、自前のサーバーハードウェアを購入してKamalで運用することで粗利95%を実現。',
        details: [
          '【Step 1: クラウド暴利の計算】: クラウドに毎年数億円払っていたインフラ代を精査し、自前サーバーを買えば数ヶ月で元が取れると計算。',
          '【Step 2: 自社ツール（Kamal/Rails）による自動化】: 専任のインフラチームを雇わず、Dockerとオープンソース配管で少人数運用を維持。',
          '【Step 3: 人数無制限の固定額課金】: 「1人あたり月$15」の競合に対し、「何人使っても月額固定（$299等）」で大口顧客の心を掴む。',
        ],
        codeSnippet: '// Kamalを用いた自社ベアメタルサーバーへのコンテナゼロダウンタイムデプロイ\n// config/deploy.yml\nservice: basecamp-web\nimage: 37signals/basecamp\nservers:\n  web:\n    - 192.168.1.10\n    - 192.168.1.11\nregistry:\n  server: ghcr.io',
        sourceNote: 'DHHの公式ブログ「Why we left the cloud」および37signals公開ポッドキャストから抽出',
      },
      {
        id: 'ev_basecamp_crime',
        type: 'THE_CRIME',
        title: 'シリコンバレーの「成長至上主義とVC資金調達」をペテンと断じ、少数精鋭で毎年数十億円を山分けする',
        badge: '身も蓋もない真実',
        evidenceStatus: 'VERIFIED',
        punchline: '外部投資家を一切入れず、会議を全廃し、週32時間労働を貫きながら、上場IT企業が束になっても敵わない額の純現金を銀行口座に蓄積。',
        details: [
          'Ruby on Railsの発祥の地として世界中の開発者から神聖視され、広告宣伝費ゼロで20年以上顧客が絶えない。',
          '「クラウド離脱」「オフィス全廃」など、業界の常識の真逆を行くオピニオンを発信し続け、無料のPR効果を最大化。',
        ],
      },
    ],
    operations: {
      teamSize: 80,
      weeklyHours: 32,
      initialCapitalRequired: 1000000,
      automationLevel: 85,
      primaryChannels: ['創業者ブログ・著書（REWORK等）', 'Ruby on Railsコミュニティ', '脱クラウド論争等のオーガニックPR'],
      toolStack: [
        { name: '自社保有ハードウェア', category: 'インフラ', monthlyCost: 15000000, purpose: '自前データセンター運用（AWS完全脱退）' },
        { name: 'Kamal', category: 'デプロイ配管', monthlyCost: 0, purpose: 'オープンソースDockerオーケストレーション' },
      ],
    },
    strategy: {
      blindspot: 'JiraやAsana、Slackなどの巨頭は「大企業向けに機能を増やし続け、1人あたりの単価を引き上げる」方向に進み、中小企業がシンプルに仕事を進めたい願望を裏切っていた。',
      moatType: 'COUNTER_POSITIONING',
      moatDescription: '「人数無制限の固定料金」と「自前サーバー運用による圧倒的低コスト」という、公開企業が真似できない逆張り構造。',
      incumbentDilemma: '上場SaaS企業は毎四半期の売上成長（1人あたり単価の引き上げ）をウォール街から要求されるため、Basecampのような「ずっと固定料金」は絶対に真似できない。',
      secretInsight: 'ビジネスで最も自由で儲かるのは「巨大企業を目指すのをやめ、固定費を極小にして、少数の熱狂的信者にだけ適正価格で長く売り続けること」である。',
      initialTraction: [
        'Webデザイン受託会社だった37signalsが、社内用に作ったプロジェクト管理ツールを外部公開',
        'DHHがBasecampを作るために生み出した「Ruby on Rails」を無料公開し、世界中の開発者のカリスマに',
        '出版したビジネス書『REWORK（小さなチーム、大きな仕事）』が世界的ベストセラーになり認知が永続化',
      ],
      actionPlaybook: [
        'Step 1: 業界の常識（クラウド利用、人数課金、急成長、VC調達）の「真逆」を行く',
        'Step 2: 浮いたコストを利益と「人数無制限の破格の固定プラン」として顧客に還元する',
        'Step 3: 創業者の思想を本やブログで発信し、顧客を「ファン」ではなく「思想の共犯者」にする',
      ],
      coldOutreachTemplate: '【プロジェクト管理ツールの人数課金の廃止】利用人数が増えても月額固定で使える、20年の実績を持つBasecampのご案内です。',
    },
    temporal: {
      foundedYear: 1999,
      initialTractionPeriod: '2004年 (Basecampローンチ・Rails公開期)',
      dataSnapshotPeriod: '2005-2026年 (20年以上連続黒字・脱クラウド期)',
      viabilityStatus: 'MATURED_MOAT',
      viabilityLabel: '永続要塞（思想的信奉と不可逆なキャッシュフロー）',
      eraContext: 'ドットコムバブル崩壊を生き残り、SaaS黎明期からブートストラップ経営を貫いた伝説的先駆者。',
      currentViabilityAnalysis: 'クラウド高騰時代において「自前サーバー運用」の先駆者として再注目され、利益率とブランドの強さは過去最高を更新中。',
    },
  },
];
