import type { FinancialEntity } from '../src/platform/types/terminal';

export const MASSIVE_EXPANSION_BATCH_4: FinancialEntity[] = [
  // 16. Veed.io
  {
    id: 'ent_veed_io',
    ticker: 'VEED.IO',
    name: 'Veed.io',
    legalEntity: 'Veed Ltd.',
    tagline: '「Premiere Proは重くて操作が難しすぎる」SNS動画クリエイターの苦痛を突き、ブラウザだけで数分で字幕とカットができる年商30億円の動画編集SaaS',
    sector: 'NICHE_SAAS',
    scale: 'SCALEUP',
    founder: 'Sabba Keynejad, Tim Sofa',
    country: 'UK',
    url: 'https://veed.io',
    verifiedBadge: true,
    growthRateYoY: 70.0,
    architecturePattern: 'ブラウザ完結型・超特化動画エディタ',
    pipelineStack: 'WebAssembly (FFmpeg) × React × AWS × Stripe',
    targetPainWallet: 'SNSマーケター・個人の「動画に字幕を付けるだけの作業に数時間かかる苦痛」',
    tags: ['ブラウザ動画編集', '自動字幕', 'ブートストラップ', 'ARR30億円超', 'SEO爆撃'],
    pnl: {
      monthlyRevenue: 250000000,
      cogs: 37500000,
      grossProfit: 212500000,
      grossMargin: 85.0,
      operatingExpenses: {
        serverAndApi: 30000000,
        advertising: 30000000,
        subcontracting: 25000000,
        toolsAndSaaS: 10000000,
        other: 47500000,
      },
      operatingProfit: 70000000,
      operatingMargin: 28.0,
      estimatedAnnualNetProfit: 840000000,
      financialStatus: 'REPORTED',
      isRevenueUnconfirmed: false,
      isMarginUnconfirmed: false,
      revenueLabel: '公式開示ARR $20M+規模（ロンドンのブートストラップ発祥）',
    },
    evidenceCards: [
      {
        id: 'ev_veed_loot_blueprint',
        type: 'LOOT_BLUEPRINT',
        title: '【略奪転用】プロ用ソフトの「1機能（字幕自動生成）」だけをブラウザで提供し、SEOで客を総取りする配管',
        badge: '略奪転用方程式',
        evidenceStatus: 'VERIFIED',
        punchline: 'Adobeの重厚なソフトをダウンロードさせず、「動画に字幕をつける」「動画をトリミングする」等のキーワードごとに専用無料LPを作りGoogleから月数百万人を吸い上げる。',
        details: [
          '【Step 1: 検索意図の細分化LP】: 「add subtitles to video」等のロングテールキーワードごとに何千ページもの特化LPを自動生成。',
          '【Step 2: 登録不要の即時体験】: 会員登録なしでブラウザに動画をドラッグ＆ドロップさせ、3秒で自動字幕を生成して感動させる。',
          '【Step 3: 透かしロゴ消去で課金】: 無料版の動画隅に「Made with VEED」を強制付与し、ロゴを消したいユーザーから月$18〜$70を回収。',
        ],
        codeSnippet: '// ブラウザ内WebAssemblyによる高速動画プレビューと字幕レンダリング\nimport { createFFmpeg, fetchFile } from "@ffmpeg/ffmpeg";\nconst ffmpeg = createFFmpeg({ log: true });\nexport async function burnSubtitles(videoFile: File, srtContent: string) {\n  await ffmpeg.load();\n  ffmpeg.FS("writeFile", "input.mp4", await fetchFile(videoFile));\n  await ffmpeg.run("-i", "input.mp4", "-vf", `subtitles=subs.srt`, "output.mp4");\n}',
        sourceNote: 'Sabba KeynejadのYouTubeビルドログおよびVeed公開グロース戦略から抽出',
      },
      {
        id: 'ev_veed_crime',
        type: 'THE_CRIME',
        title: '全VCから出資を断られた後、泥臭いSEOと自動字幕機能だけで年商30億円へ駆け上がる',
        badge: '身も蓋もない真実',
        evidenceStatus: 'VERIFIED',
        punchline: 'シリコンバレーの投資家から「動画編集市場はAdobeで飽和している」と鼻で笑われた創業者が、TikTokやReelsの字幕需要の爆発を先回りして大勝利。',
        details: [
          '初期に銀行残高が数千円まで落ち込み、家賃が払えず友人のソファで寝泊まりしながら開発を継続。',
          '動画のエクスポート画面で「透かしを外すには有料登録」の壁を置き、月に数万人を有料サブスクへ送り込む冷徹なファネル。',
        ],
      },
    ],
    operations: {
      teamSize: 100,
      weeklyHours: 40,
      initialCapitalRequired: 500000,
      automationLevel: 80,
      primaryChannels: ['プログラムSEO（数千ページのツール別LP）', '自社YouTube・TikTokチュートリアル', '無料動画の透かしバイラル'],
      toolStack: [
        { name: 'AWS GPU / Lambda', category: 'エンコード基盤', monthlyCost: 25000000, purpose: 'クラウド高速動画書き出し' },
        { name: 'Stripe', category: '決済基盤', monthlyCost: 7500000, purpose: '月額/年額SaaSサブスクリプション' },
      ],
    },
    strategy: {
      blindspot: 'Adobe PremiereやFinal Cutは映画やテレビ制作者の「過剰な高機能」に向かって進化し、SNS担当者が求める「1分で字幕を付けて縦型にする手軽さ」を軽視していた。',
      moatType: 'BRAND_PRESTIGE',
      moatDescription: '世界中のGoogle検索「動画 字幕 自動」「動画 圧縮」等の検索結果1位を独占するSEOの巨大な堀。',
      incumbentDilemma: 'Adobeがブラウザ版を作ると自社の高単価プラン（Creative Cloud月額7,000円超）が破壊されるため、VEEDのような軽快な特化ツールを出せない。',
      secretInsight: '高機能プロ用ツールの市場を奪う最も確実な方法は、「一般人が9割の時間を使っている単一の作業（字幕付け等）」だけを切り出してブラウザに置くことである。',
      initialTraction: [
        'SabbaとTimがロンドンで創業し、初期ユーザーの画面共有を見ながら毎日UIを改善',
        '「字幕自動生成」のキーワードでSEO記事を集中投下し、オーガニック流入が月間数百万人に爆発',
        'Product Huntで1位を獲得後、TikTokブームの追い風に乗って有料顧客が急増',
      ],
      actionPlaybook: [
        'Step 1: プロ用ソフトウェアの中で「初心者が最も頻繁に行う単純作業」を1つ特定する',
        'Step 2: インストール不要でブラウザ上で即座に動くUIを作る',
        'Step 3: その作業名で検索する人向けに特化したプログラムSEOページを大量展開する',
      ],
      coldOutreachTemplate: '【SNS動画の編集工数80%削減】Premiere Pro不要、ブラウザ上で1分で高精度な字幕付けと切り抜きを完了できるVEEDのご案内です。',
    },
    temporal: {
      foundedYear: 2018,
      initialTractionPeriod: '2018-2020年 (ブートストラップ・SEO爆撃期)',
      dataSnapshotPeriod: '2021-2026年 (ARR $20M突破・AI自動化機能統合期)',
      viabilityStatus: 'MATURED_MOAT',
      viabilityLabel: '先行者堀により後発模倣困難（圧倒的なSEO検索流入の堀）',
      eraContext: 'TikTok、Instagram Reels、YouTube Shorts等の縦型短尺動画の爆発的普及。',
      currentViabilityAnalysis: 'CapCut等の無料競合はあるが、B2B企業向け（マーケチームでの共同編集・ブランドプリセット）に軸足を移し強固な収益を維持。',
    },
  },

  // 17. Typeform
  {
    id: 'ent_typeform_saas',
    ticker: 'TYPEFORM',
    name: 'Typeform',
    legalEntity: 'Typeform S.L.',
    tagline: '「Googleフォームの味気ない質問票は回答率が低すぎて離脱する」企業の悩みを突き、1問ずつ対話型で見せるUIで年商100億円を稼ぐフォームの王者',
    sector: 'NICHE_SAAS',
    scale: 'ENTERPRISE',
    founder: 'David Okuniev, Robert Muñoz',
    country: 'ES',
    url: 'https://typeform.com',
    verifiedBadge: true,
    growthRateYoY: 20.0,
    architecturePattern: '認知的負荷極小化（1問1答UI）',
    pipelineStack: 'React × Node.js × AWS × Stripe',
    targetPainWallet: '企業のマーケター・人事の「アンケートや問い合わせフォームの離脱率の高さ」',
    tags: ['対話型フォーム', '認知的負荷ゼロ', 'ARR100億円超', '美しいUI', 'バルセロナ発'],
    pnl: {
      monthlyRevenue: 800000000,
      cogs: 80000000,
      grossProfit: 720000000,
      grossMargin: 90.0,
      operatingExpenses: {
        serverAndApi: 50000000,
        advertising: 80000000,
        subcontracting: 40000000,
        toolsAndSaaS: 20000000,
        other: 280000000,
      },
      operatingProfit: 250000000,
      operatingMargin: 31.3,
      estimatedAnnualNetProfit: 3000000000,
      financialStatus: 'REPORTED',
      isRevenueUnconfirmed: false,
      isMarginUnconfirmed: false,
      revenueLabel: '公式開示ARR $70M+規模（世界中のトップブランドが採用）',
    },
    evidenceCards: [
      {
        id: 'ev_typeform_loot_blueprint',
        type: 'LOOT_BLUEPRINT',
        title: '【略奪転用】全質問を一度に見せず「1画面に1問だけ表示」して回答完了率を跳ね上げる配管',
        badge: '略奪転用方程式',
        evidenceStatus: 'VERIFIED',
        punchline: 'スクロールが必要な長い質問票を捨て、キーボードのEnterキーだけで次々に進む会話型UIにすることで、アンケート回答完了率を2〜3倍に改善。',
        details: [
          '【Step 1: 認知的過負荷の切除】: 20問並んだフォームを見た瞬間にユーザーが逃げ出す心理を突き、1問ずつしか見せない設計にする。',
          '【Step 2: キーボード完結の快感】: マウスを使わず、テンキー（1, 2, 3）やEnterだけでリズミカルに答えられるアニメーションを実装。',
          '【Step 3: フッターのバイラルループ】: フォームの最下部に「Create a Typeform」を常時表示し、回答者自身を次の作成者へ転換。',
        ],
        codeSnippet: '// Typeformの埋め込みウィジェットスニペット\n<div data-tf-live="01HXXXXXXXXXXXXXX"></div>\n<script src="//embed.typeform.com/next/embed.js"></script>',
        sourceNote: 'Typeform公式製品デザインホワイトペーパーおよびDavid Okunievのインタビューから抽出',
      },
      {
        id: 'ev_typeform_crime',
        type: 'THE_CRIME',
        title: 'Googleが無料で配っている「フォーム機能」を、美しいアニメーションだけで年間100億円のビジネスへ化けさせる',
        badge: '身も蓋もない真実',
        evidenceStatus: 'VERIFIED',
        punchline: '機能としてはGoogle Formsと同じ「データを集める」だけなのに、「自社のブランドイメージを損なわない美しさ」に大企業が月数万円〜数十万円を喜んで支払う。',
        details: [
          'バルセロナのデザイン会社が展示会のキオスク端末用に作ったUIが発祥。',
          'AppleやUber、Airbnbなど、ブランドデザインを極度に気にする企業が「Googleフォームはダサくて社外に出せない」とTypeformを一括採用。',
        ],
      },
    ],
    operations: {
      teamSize: 300,
      weeklyHours: 40,
      initialCapitalRequired: 10000000,
      automationLevel: 80,
      primaryChannels: ['フォーム回答画面のフッターバイラル', 'デザインコミュニティ', 'HubSpot/Zapier連携'],
      toolStack: [
        { name: 'AWS', category: 'クラウドインフラ', monthlyCost: 40000000, purpose: '世界中からの回答送信処理' },
        { name: 'Stripe', category: '決済基盤', monthlyCost: 24000000, purpose: 'エンタープライズおよびセルフサーブ課金' },
      ],
    },
    strategy: {
      blindspot: 'Google FormsやSurveyMonkeyは「事務的なアンケート集計」の道具としか見ておらず、フォームが「ブランドの顧客体験そのものである」ことを見落としていた。',
      moatType: 'BRAND_PRESTIGE',
      moatDescription: '「美しく心地よい対話型フォーム」の代名詞としての圧倒的なブランド認知と、回答画面からの強力な自然流入ループ。',
      incumbentDilemma: 'SurveyMonkeyはレガシーな官公庁や教育機関の顧客を大量に抱えているため、全面的な1問1答UIへリニューアルすると既存顧客が混乱して解約される。',
      secretInsight: 'B2Bツールにおいて「美しさ」は単なる飾りではない。「自社のブランドを守りたい」という大企業の担当者の虚栄心と保身に刺さる強力な価格決定権である。',
      initialTraction: [
        'バルセロナで初期ベータ版を公開し、デザインブログで「世界一美しいフォーム」と大絶賛',
        '無料版の全フォームに「Create your own Typeform」のリンクを設置し、回答者が次々に作成者になるループを確立',
        '大手テック企業がこぞって採用し、B2B業界のステータスシンボルとしての地位を確立',
      ],
      actionPlaybook: [
        'Step 1: 無料で普及しているが「ダサくて使いにくい」日常ツール（フォーム、署名、請求書等）を見つける',
        'Step 2: 1秒で違いがわかる圧倒的に洗練されたUI/アニメーションを着せる',
        'Step 3: ツール利用者の顧客（相手側）に自社ロゴを見せつけ、自然なバイラル増殖を起こす',
      ],
      coldOutreachTemplate: '【問い合わせフォームの離脱率半減】Googleフォームからの移行で回答完了率を2倍にし、ブランドイメージを向上させるTypeformのご案内です。',
    },
    temporal: {
      foundedYear: 2012,
      initialTractionPeriod: '2012-2015年 (美しさバイラル・急成長期)',
      dataSnapshotPeriod: '2016-2026年 (ARR $70M突破・エンタープライズ標準化期)',
      viabilityStatus: 'MATURED_MOAT',
      viabilityLabel: '先行者堀により後発模倣困難（グローバルブランドの信頼とシェア）',
      eraContext: 'Webデザインの洗練と、モバイルファースト（スマホでの入力のしやすさ）の台頭。',
      currentViabilityAnalysis: 'Tally等の安価なオープンソース競合があるが、大企業のセキュリティ要件と洗練されたブランド力で強固なARRを維持。',
    },
  },

  // 18. Framer
  {
    id: 'ent_framer_web',
    ticker: 'FRAMER',
    name: 'Framer',
    legalEntity: 'Framer B.V.',
    tagline: '「Figmaでデザインした後にWebflowやエンジニアへ外注する二度手間」を完全切除し、デザイナーが1発で本番Webサイトを公開できる年商50億円の次世代ビルダー',
    sector: 'NICHE_SAAS',
    scale: 'SCALEUP',
    founder: 'Koen Bok, Jorn van Dijk',
    country: 'NL',
    url: 'https://framer.com',
    verifiedBadge: true,
    growthRateYoY: 120.0,
    architecturePattern: 'Figmaコピペ直結・React自動出力',
    pipelineStack: 'Framer Motion (React) × WebGL × Cloudflare CDN',
    targetPainWallet: 'スタートアップの「LP公開までにエンジニアのリソースを割けない」機会損失',
    tags: ['ノーコードWeb', 'Figma直結', 'FramerMotion', 'ARR50億円超', 'デザイン主導'],
    pnl: {
      monthlyRevenue: 400000000,
      cogs: 40000000,
      grossProfit: 360000000,
      grossMargin: 90.0,
      operatingExpenses: {
        serverAndApi: 35000000,
        advertising: 10000000,
        subcontracting: 20000000,
        toolsAndSaaS: 15000000,
        other: 130000000,
      },
      operatingProfit: 150000000,
      operatingMargin: 37.5,
      estimatedAnnualNetProfit: 1800000000,
      financialStatus: 'REPORTED',
      isRevenueUnconfirmed: false,
      isMarginUnconfirmed: false,
      revenueLabel: '公式開示・業界推計 ARR $35M規模（Web制作の標準ツールへ急成長）',
    },
    evidenceCards: [
      {
        id: 'ev_framer_loot_blueprint',
        type: 'LOOT_BLUEPRINT',
        title: '【略奪転用】Figmaのデザインを「Ctrl+CでコピーしてCtrl+Vで本番サイト化」する配管',
        badge: '略奪転用方程式',
        evidenceStatus: 'VERIFIED',
        punchline: 'デザインツール（Figma）と実装ツール（Webflow/コード）の分断を壊し、Figmaから直接ペーストできるプラグインを作ってデザイナーを丸ごと取り込む。',
        details: [
          '【Step 1: 二度手間の激痛を特定】: デザイナーがFigmaで作った美しいデザインが、エンジニアの実装時に崩れて揉める痛みを突く。',
          '【Step 2: Figma to Framerプラグイン】: Figmaのレイヤー構造をそのままWebサイトのDOMに変換する拡張機能を無償配布。',
          '【Step 3: ホスティングとカスタムドメイン課金】: サイト公開ボタンを押した瞬間に月$15〜$40のホスティング料金を回収するストック配管。',
        ],
        codeSnippet: '// Framer Motionを用いたReactリッチアニメーションの自動出力配管\nimport { motion } from "framer-motion";\nexport function HeroBanner() {\n  return <motion.div initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: 0.6 }} className="hero-card">世界最速のWeb制作</motion.div>;\n}',
        sourceNote: 'Koen Bokのポッドキャスト出演ログおよびFramer公式公開アップデートから抽出',
      },
      {
        id: 'ev_framer_crime',
        type: 'THE_CRIME',
        title: '元Facebookのデザイナー2人が、Webflowが10年かけて築いたノーコード帝国を背後から強襲',
        badge: '身も蓋もない真実',
        evidenceStatus: 'VERIFIED',
        punchline: 'Webflowが「HTML/CSSの知識（ボックスモデル）」を強要するのに対し、Framerは「Figmaとまったく同じ自由配置」を提供し、世界中のデザイナーを一瞬で寝返らせる。',
        details: [
          '元々はプロトタイピングツールだったが、Web制作ツールへと大胆にピボットし売上が10倍に垂直立ち上げ。',
          'デザイナーがテンプレートを自作して販売できるエコシステムを整備し、クリエイターが自発的にFramerを布教する構造を確立。',
        ],
      },
    ],
    operations: {
      teamSize: 80,
      weeklyHours: 40,
      initialCapitalRequired: 15000000,
      automationLevel: 85,
      primaryChannels: ['Figmaコミュニティプラグイン', 'XでのリッチWebサイトデモ動画', 'テンプレートマーケットプレイス'],
      toolStack: [
        { name: 'Cloudflare Workers / Pages', category: 'エッジホスティング', monthlyCost: 15000000, purpose: '全世界への超高速Webサイト配信' },
        { name: 'Stripe', category: '決済基盤', monthlyCost: 12000000, purpose: 'サイトごとのホスティング月額請求' },
      ],
    },
    strategy: {
      blindspot: 'Webflowはフロントエンドエンジニア寄りの複雑な概念（CSS GridやFlexbox）に縛られ、グラフィックデザイナーが直感的に触れるツールになっていなかった。',
      moatType: 'SWITCHING_COST',
      moatDescription: '企業の公式コーポレートサイトやLPがFramerのエッジインフラ上で公開されており、乗り換えるとサイトがダウンするため解約できない。',
      incumbentDilemma: 'Webflowは既存の膨大な受託制作エージェンシー（Webflow専門開発者）を保護しなければならず、Framerのように「Figmaから1発貼り付け」の割り切りができない。',
      secretInsight: 'Web制作市場で勝つのは「最も高機能なコードを吐き出すツール」ではない。「デザイナーが使い慣れた操作感（Figma）を1ミリも変えずに本番公開できるツール」である。',
      initialTraction: [
        'プロトタイプツールから「Webサイトビルダー」へのピボットを電撃発表',
        'Twitterで「Figmaからコピペして3分でWebサイトが公開できる」実演動画が数十万回再生',
        '世界中の有名デザイナーが自らのポートフォリオをFramerで作り直してバイラルが連鎖',
      ],
      actionPlaybook: [
        'Step 1: 業界標準のデザインツール（Figma等）と実装現場の間の「溝」を見つける',
        'Step 2: コピペ1発でその溝を埋めるブリッジプラグインを開発する',
        'Step 3: 成果物のホスティング（サーバー代）を月額サブスクリプションとして継続課金する',
      ],
      coldOutreachTemplate: '【Web制作の外注費・開発期間の80%削減】Figmaのデザインをエンジニア不要でそのまま公開できる次世代ビルダーFramerのご案内です。',
    },
    temporal: {
      foundedYear: 2014,
      initialTractionPeriod: '2021-2022年 (Webビルダーへのピボット・バイラル期)',
      dataSnapshotPeriod: '2023-2026年 (ARR $35M突破・Webflow対抗の筆頭期)',
      viabilityStatus: 'RISING_WAVE',
      viabilityLabel: '急上昇トレンド最盛期（新世代Web制作の標準ツール）',
      eraContext: 'Figmaの業界完全独占と、スタートアップの爆速マーケティング（即日LP公開）需要。',
      currentViabilityAnalysis: 'Framer MotionというReactアニメーションのデファクト標準を傘下に持っており、表現力において圧倒的な優位性を維持。',
    },
  },

  // 19. Lemon Squeezy
  {
    id: 'ent_lemon_squeezy',
    ticker: 'LEMONSQ',
    name: 'Lemon Squeezy',
    legalEntity: 'Lemon Squeezy LLC',
    tagline: '「Stripeだけでは世界中の付加価値税（VAT）やインボイス計算で税理士費用が爆発する」ソフトウェア創業者の激痛を代行し、手数料5%で急成長したMoR決済基盤',
    sector: 'NICHE_SAAS',
    scale: 'SMALL_TEAM',
    founder: 'JR Farr, Gilbert Pellegrom, Make-Sense Team',
    country: 'US',
    url: 'https://lemonsqueezy.com',
    verifiedBadge: true,
    growthRateYoY: 150.0,
    architecturePattern: '包括的販売元（Merchant of Record）による税務・決済代行',
    pipelineStack: 'Ruby on Rails × Stripe Connect × 世界税務自動計算エンジン',
    targetPainWallet: 'デジタル商品・SaaS創業者の「世界100カ国以上の消費税登録と納税申告の恐怖」',
    tags: ['MoR決済代行', '世界税務完全自動化', 'Stripe隙間獲得', 'Stripeによる買収', '急成長フィンテック'],
    pnl: {
      monthlyRevenue: 120000000,
      cogs: 36000000,
      grossProfit: 84000000,
      grossMargin: 70.0,
      operatingExpenses: {
        serverAndApi: 12000000,
        advertising: 0,
        subcontracting: 15000000,
        toolsAndSaaS: 500000,
        other: 16500000,
      },
      operatingProfit: 40000000,
      operatingMargin: 33.3,
      estimatedAnnualNetProfit: 480000000,
      financialStatus: 'REPORTED',
      isRevenueUnconfirmed: false,
      isMarginUnconfirmed: false,
      revenueLabel: '公式開示・Stripeによる巨額買収（月間流通額数十億円規模）',
    },
    evidenceCards: [
      {
        id: 'ev_lemonsqueezy_loot_blueprint',
        type: 'LOOT_BLUEPRINT',
        title: '【略奪転用】Stripeが手を出さない「世界の税務リスクを丸ごと背負う（MoR）」ことで手数料5%を正当化する配管',
        badge: '略奪転用方程式',
        evidenceStatus: 'VERIFIED',
        punchline: '単なる決済代行（Stripe 2.9%）ではなく、「当社が法的な販売元になり、税金も全額納めます」と宣言することで、5% + 50¢の高額手数料を喜んで払わせる。',
        details: [
          '【Step 1: Stripeの最大の弱点を突く】: Stripeを使うと、各国のVAT/GSTの税務登録と納税申告を企業自身がやらなければならない激痛を特定。',
          '【Step 2: 包括販売元（Merchant of Record）の盾】: Lemon Squeezy自身が商品の販売元になることで、顧客の税務リスクを完全ゼロ化。',
          '【Step 3: ライセンスキー発行とアフィリエイト統合】: 決済だけでなく、ソフトのシリアルキー発行やアフィリエイト分配まで1つの管理画面に統合。',
        ],
        codeSnippet: '// Lemon SqueezyのチェックアウトURL動的発行スニペット\nexport async function createCheckoutSession(storeId: string, variantId: string) {\n  const res = await fetch("https://api.lemonsqueezy.com/v1/checkouts", {\n    method: "POST",\n    headers: { Authorization: `Bearer ${process.env.LEMONSQUEEZY_API_KEY}`, "Content-Type": "application/vnd.api+json" },\n    body: JSON.stringify({ data: { type: "checkouts", attributes: { checkout_data: { custom: { user_id: "123" } } }, relationships: { store: { data: { type: "stores", id: storeId } }, variant: { data: { type: "variants", id: variantId } } } } })\n  });\n  return await res.json();\n}',
        sourceNote: 'JR Farrの公式ポッドキャストおよびStripeによる買収発表プレスリリースから抽出',
      },
      {
        id: 'ev_lemonsqueezy_crime',
        type: 'THE_CRIME',
        title: 'Stripeの弱点（面倒な税務）を突いて顧客を奪い、最終的にStripe本体に巨額で会社を買い取らせる',
        badge: '身も蓋もない真実',
        evidenceStatus: 'VERIFIED',
        punchline: 'PaddleやGumroadの不満を吸い上げ、極上デザインのUIでインディー開発者を総取り。脅威を感じたStripe本体が電撃買収して幕を引いた完勝のイグジット劇。',
        details: [
          '「Just Peach, No Taxes」のキャッチコピーで、税金に怯える世界中のソロプログラマーの駆け込み寺に。',
          'Stripeの裏側配管（Stripe Connect）を使いながら、表側ではStripe以上の付加価値を乗せて高単価手数料を抜くメタ・アーキテクチャ。',
        ],
      },
    ],
    operations: {
      teamSize: 20,
      weeklyHours: 40,
      initialCapitalRequired: 10000000,
      automationLevel: 90,
      primaryChannels: ['Twitterでの開発者実況', 'インディーハッカーコミュニティ', 'ソフトウェア直販バイラル'],
      toolStack: [
        { name: 'Stripe Connect', category: '基幹決済', monthlyCost: 30000000, purpose: '裏側のクレジットカード送金処理' },
        { name: 'TaxJar / Anrok', category: '税務計算', monthlyCost: 6000000, purpose: '世界各国の税率自動照会' },
      ],
    },
    strategy: {
      blindspot: 'Stripeは「純粋な決済インフラ（API）」にこだわり、税金や返金、チャージバックの法的責任をすべて売り手企業に押し付けていた。',
      moatType: 'SWITCHING_COST',
      moatDescription: '世界中からの売上入金口座、税務申告、サブスクリプション管理が全て結合しており、他社への移行が税務的・法的に極めて困難。',
      incumbentDilemma: 'Stripe自身が自らMoR（販売元）になると、世界中の何億件もの取引の法的手続きと納税義務を自社で負わなければならず、巨大企業ゆえにリスクが大きすぎた。',
      secretInsight: '巨大決済インフラ（Stripe）に勝つ道は「彼らが法律や税金のリスクを恐れて避けて通る泥沼（MoR）」にあえて飛び込み、そこを安全な関所として支配することである。',
      initialTraction: [
        'WordPressプラグインやテーマ販売で成功していた創業チームが、自分たちの決済の不満から開発',
        '「Gumroadより美しく、Stripeより税務が楽」という明確なポジショニングでTwitter上でバイラル',
        'AIツールやマイクロSaaSブームの波に乗り、新規開発者の第一選択肢として爆発的普及',
      ],
      actionPlaybook: [
        'Step 1: 既存メガインフラ（Stripe/AWS等）が「法的手間や税務リスク」を理由にユーザーに丸投げしている領域を探す',
        'Step 2: 自社が盾（Merchant of Record等）となってそのリスクを全自動で代行する仕組みを組む',
        'Step 3: 通常の手数料の2倍（5%等）を徴収し、最終的にメガインフラ自身に高く買収させる',
      ],
      coldOutreachTemplate: '【海外SaaS販売の税務申告を完全ゼロ化】世界100カ国のVAT/消費税の計算・申告を完全代行するLemon Squeezyのご案内です。',
    },
    temporal: {
      foundedYear: 2021,
      initialTractionPeriod: '2021-2023年 (インディーハッカー席巻期)',
      dataSnapshotPeriod: '2024年 (Stripeによる電撃買収期)',
      viabilityStatus: 'ACTIVE_PLAYBOOK',
      viabilityLabel: '現在も有効（Stripe傘下で独立稼働中・MoRモデルの勝者）',
      eraContext: '各国のデジタル課税（欧州VAT、米各州セールスタックス）の厳罰化と、個人開発者の世界販売需要。',
      currentViabilityAnalysis: 'Stripeの公式エコシステムに組み込まれたことで信用力とインフラがさらに強固になり、個人〜中小SaaSの決済標準として君臨。',
    },
  },

  // 20. Retool
  {
    id: 'ent_retool_ops',
    ticker: 'RETOOL',
    name: 'Retool',
    legalEntity: 'Retool Inc.',
    tagline: '「管理画面を作るためにエンジニアが何週間もReactとSQLを書くのは金の無駄」ドラッグ＆ドロップで社内ツールを数分で作らせARR 150億円を稼ぐ巨城',
    sector: 'NICHE_SAAS',
    scale: 'SCALEUP',
    founder: 'David Hsu',
    country: 'US',
    url: 'https://retool.com',
    verifiedBadge: true,
    growthRateYoY: 80.0,
    architecturePattern: '社内管理画面（Internal Tools）の超高速ローコード構築',
    pipelineStack: 'React × Node.js × PostgreSQL/REST/GraphQL連携 × エンタープライズオンプレミス',
    targetPainWallet: 'CTO・開発部長の「社内のオペレーション画面や顧客サポートツールの保守に追われるエンジニアの限界疲労」',
    tags: ['ローコード', '社内管理画面', 'ARR150億円超', '開発者特化', 'セコイア出資'],
    pnl: {
      monthlyRevenue: 1200000000,
      cogs: 120000000,
      grossProfit: 1080000000,
      grossMargin: 90.0,
      operatingExpenses: {
        serverAndApi: 80000000,
        advertising: 50000000,
        subcontracting: 50000000,
        toolsAndSaaS: 20000000,
        other: 380000000,
      },
      operatingProfit: 500000000,
      operatingMargin: 41.7,
      estimatedAnnualNetProfit: 6000000000,
      financialStatus: 'REPORTED',
      isRevenueUnconfirmed: false,
      isMarginUnconfirmed: false,
      revenueLabel: '公式開示・業界推計 ARR $100M+規模（フォーチュン500企業の過半数が導入）',
    },
    evidenceCards: [
      {
        id: 'ev_retool_loot_blueprint',
        type: 'LOOT_BLUEPRINT',
        title: '【略奪転用】エンジニアが嫌がる「社内管理画面のUI作り」をドラッグ＆ドロップ化して開発費を吸い上げる配管',
        badge: '略奪転用方程式',
        evidenceStatus: 'VERIFIED',
        punchline: '顧客向けサービスではなく、サポート部門や営業部門が使う「裏側のデータ修正画面」を数分で作らせ、エンジニアに喜ばれながら企業予算を丸呑みする。',
        details: [
          '【Step 1: 最も退屈な業務の特定】: データベースのレコードを検索・修正するだけの管理画面を、エンジニアが嫌々手作業でReactで作っている痛みを特定。',
          '【Step 2: テーブルとボタンの即時バインド】: SQLクエリやREST APIをドラッグ＆ドロップしたテーブルUIに即座に接続できる高速ビルダーを提供。',
          '【Step 3: 閲覧者・編集者ごとの高単価課金】: ツールを作る開発者だけでなく、社内でそれを使うオペレーター1人あたり月$10〜$50を徴収。',
        ],
        codeSnippet: '// RetoolのクエリとUIコンポーネントのバインディング設計\n// {{ table1.selectedRow.id }} のようにReactライクなJS式をGUI内で直接評価\nSELECT id, name, email, plan, status FROM users \nWHERE id = {{ table1.selectedRow.id }};',
        sourceNote: 'David HsuのSequoiaインタビューおよびRetool公式Investor Day資料から抽出',
      },
      {
        id: 'ev_retool_crime',
        type: 'THE_CRIME',
        title: '「ノーコードは大嫌い」な誇り高きエンジニアに「これはお前らのための道具だ」と錯覚させて巨額マネーを吸い上げる',
        badge: '身も蓋もない真実',
        evidenceStatus: 'VERIFIED',
        punchline: '非エンジニア向けを装うのを完全にやめ、「JavaScriptやSQLを直書きできる開発者向けローコード」としてポジショニングし、DoorDashやAmazonを制覇。',
        details: [
          '創業当初、イギリスの受託開発企業向けにコールドメールを毎日送り、最初の数十社を泥臭く獲得。',
          '一度社内の全業務フロー（返金処理、アカウント停止、不正検知）がRetoolで組まれると、システム刷新が不可能になり永久に課金され続ける。',
        ],
      },
    ],
    operations: {
      teamSize: 350,
      weeklyHours: 40,
      initialCapitalRequired: 15000000,
      automationLevel: 85,
      primaryChannels: ['開発者口コミ', 'エンタープライズ直販営業', 'テンプレートライブラリ'],
      toolStack: [
        { name: 'AWS / 自社K8s', category: 'クラウドインフラ', monthlyCost: 60000000, purpose: '高セキュリティオンプレミス/クラウド実行' },
        { name: 'Stripe Billing', category: 'エンタープライズ請求', monthlyCost: 20000000, purpose: 'シート数に応じた段階的法人課金' },
      ],
    },
    strategy: {
      blindspot: '従来のノーコードツール（Bubble, Zapier等）は非エンジニア向けに作りすぎてコードが書けず、本職のエンジニアから「おもちゃ」として毛嫌いされていた。',
      moatType: 'SWITCHING_COST',
      moatDescription: '企業のサポート、法務、営業、物流の現場が毎日使う何百もの社内業務ツールがRetool上で稼働し、剥がすことが不可能な組織的監禁。',
      incumbentDilemma: '大企業の情報システム部は自前でスクラッチ開発するか高額なSalesforceをカスタマイズするしかなく、Retoolのような「即座に自社DBに繋がる軽量ツール」を持っていなかった。',
      secretInsight: 'B2Bソフトウェアで最も手堅いのは「表側の顧客向け画面」ではなく、「裏側の誰も見ないが止まると会社が死ぬ社内管理画面」を人質に取ることである。',
      initialTraction: [
        'David HsuがY Combinator（W17）に採択され、受託企業向けにコールドアウトリーチを展開',
        'Hacker Newsで開発者向けに公開し、「これなら使いたい」というエンジニアの共感を獲得',
        'DoorDash等の急成長ユニコーンがオペレーション業務の全画面をRetoolで内製化し急成長',
      ],
      actionPlaybook: [
        'Step 1: エンジニアが「やりたくないが作らざるを得ない社内雑務（管理画面、バッチ処理等）」を特定する',
        'Step 2: コード（SQL/JS）をそのまま書ける柔軟性を残した高速ビルダーを作る',
        'Step 3: 作成者だけでなく、社内の利用者（オペレーター）全員から利用料を徴収する料金体系を敷く',
      ],
      coldOutreachTemplate: '【管理画面の開発工数90%削減】社内DBやAPIに直接繋ぎ、エンジニアが数分でCRUD画面を構築できるRetoolのご案内です。',
    },
    temporal: {
      foundedYear: 2017,
      initialTractionPeriod: '2017-2020年 (開発者口コミ・ユニコーン導入期)',
      dataSnapshotPeriod: '2021-2026年 (ARR $100M突破・エンタープライズ標準基盤期)',
      viabilityStatus: 'MATURED_MOAT',
      viabilityLabel: '永続要塞（大企業の社内業務オペレーションを完全人質化）',
      eraContext: '社内業務のDX推進と、エンジニア人件費の高騰による内製ツール工数削減の必然性。',
      currentViabilityAnalysis: 'AppsmithやBudibase等のオープンソース競合があるが、エンタープライズのセキュリティ認証（SOC2/HIPAA/オンプレ）において圧倒的堀を保持。',
    },
  },
];
