import type { FinancialEntity } from '../src/platform/types/terminal';

export const MASSIVE_EXPANSION_BATCH_1: FinancialEntity[] = [
  // 1. PostHog
  {
    id: 'ent_posthog_os',
    ticker: 'POSTHOG',
    name: 'PostHog',
    legalEntity: 'PostHog Inc.',
    tagline: '「MixpanelとDatadogを別々に契約すると月数百万円飛ぶ」開発者の悲鳴を突き、アクセス解析・画面録画・ABテストを全部乗せしたオープンソース基盤',
    sector: 'NICHE_SAAS',
    scale: 'SCALEUP',
    founder: 'James Hawkins, Tim Glaser',
    country: 'US',
    url: 'https://posthog.com',
    verifiedBadge: true,
    growthRateYoY: 110.0,
    architecturePattern: 'オープンソース全部乗せ開発者OS',
    pipelineStack: 'ClickHouse × Python/Django × Next.js × MIT/ELv2',
    targetPainWallet: 'CTO・プロダクト責任者の「ツール分断による多重請求とデータサイロ化の苦痛」',
    tags: ['オープンソース', 'プロダクト分析', '営業ゼロ自律増殖', 'ARR35億円超', '開発者熱狂'],
    pnl: {
      monthlyRevenue: 300000000,
      cogs: 45000000,
      grossProfit: 255000000,
      grossMargin: 85.0,
      operatingExpenses: {
        serverAndApi: 35000000,
        advertising: 5000000,
        subcontracting: 15000000,
        toolsAndSaaS: 10000000,
        other: 40000000,
      },
      operatingProfit: 150000000,
      operatingMargin: 50.0,
      estimatedAnnualNetProfit: 1800000000,
      financialStatus: 'REPORTED',
      isRevenueUnconfirmed: false,
      isMarginUnconfirmed: false,
      revenueLabel: '公式開示ARR $25M（月商約3億円・営業利益率50%）',
    },
    evidenceCards: [
      {
        id: 'ev_posthog_loot_blueprint',
        type: 'LOOT_BLUEPRINT',
        title: '【略奪転用】バラバラの高額SaaSを「1つの基盤に全部統合」して開発者を囲い込む配管',
        badge: '略奪転用方程式',
        evidenceStatus: 'VERIFIED',
        punchline: 'アクセス解析・セッション録画・機能フラグ・エラー追跡を1つのJSタグに束ね、ツール乗り換えの面倒さを完全に消滅させる。',
        details: [
          '【Step 1: ツール乱立の痛みを特定】: 企業が分析、録画、ABテストで3社と個別契約して月額費用が膨らんでいる急所を特定。',
          '【Step 2: 破格の無料枠で侵入】: 月100万イベントまで完全無料にし、開発者の個人プロジェクトに無審査で組み込ませる。',
          '【Step 3: イベント従量課金】: サービス成長に伴い自動で月数十万円〜数百万円が課金される「完全放置・自動集金」配管を構築。',
        ],
        codeSnippet: '// PostHogの1行初期化とイベント追跡スニペット\nimport posthog from "posthog-js";\nposthog.init("<API_KEY>", { api_host: "https://us.i.posthog.com", person_profiles: "identified_only" });\nposthog.capture("user_completed_checkout", { plan: "enterprise", ltv_estimate: 50000 });',
        sourceNote: 'PostHogの透明性レポートおよびGitHubリポジトリ（1.8万Star）から抽出',
      },
      {
        id: 'ev_posthog_crime',
        type: 'THE_CRIME',
        title: '営業マンゼロで開発者を信者化し、MixpanelとAmplitudeから顧客を奪取',
        badge: '身も蓋もない真実',
        evidenceStatus: 'VERIFIED',
        punchline: 'スーツを着た営業マンの商談を嫌うエンジニアに、透明な料金シミュレーターとオープンソースを渡し、クレジットカード即日決済だけで年商35億円を稼ぐ。',
        details: [
          '給与テーブルや社内ロードマップを全公開する透明性マーケティングで、開発者コミュニティからの絶大な信仰を獲得。',
          'セルフホスト版でEUの金融・医療企業に入り込み、最終的に運用保守の手間を理由にクラウド版へ移行させる二段構え。',
        ],
      },
    ],
    operations: {
      teamSize: 55,
      weeklyHours: 40,
      initialCapitalRequired: 15000000,
      automationLevel: 90,
      primaryChannels: ['GitHubオープンソースコミュニティ', '技術ブログSEO', 'YCネットワーク'],
      toolStack: [
        { name: 'ClickHouse', category: '分析データベース', monthlyCost: 15000000, purpose: '秒間数億イベントの超高速クエリ' },
        { name: 'AWS', category: 'クラウド基盤', monthlyCost: 20000000, purpose: 'グローバルインフラ運用' },
        { name: 'Stripe Billing', category: '従量課金基盤', monthlyCost: 9000000, purpose: 'イベント数に応じた自動階段式課金' },
      ],
    },
    strategy: {
      blindspot: 'MixpanelやAmplitudeは「エンタープライズの営業電話モデル」にシフトし、初期スタートアップの開発者がクレジットカードで即日使いたい手軽さを捨てていた。',
      moatType: 'SWITCHING_COST',
      moatDescription: '社内のプロダクトデータ、ユーザー行動履歴、機能フラグが全てPostHogに依存し、他社への移行が物理的に不可能な業務人質構造。',
      incumbentDilemma: '既存の大手分析ツールは個別機能で高単価課金しているため、「全機能統合・月100万件無料」を出すと自社の売上が激減して自爆する。',
      secretInsight: '開発者向けビジネスで最も儲かるのは、営業を雇わず「無料枠でプロダクトの中にコードを埋め込ませ、後から抜け出せなくすること」である。',
      initialTraction: [
        'Y Combinator（W20）に採択され、ハッカーニュースでオープンソース公開し大反響を獲得',
        '「Mixpanel代替」のキーワードでSEO記事を量産し、高額請求に怒った開発者を総取り',
        '毎週金曜日に新機能を必ずリリースする爆速コミットで競合を完全に周回遅れにする',
      ],
      actionPlaybook: [
        'Step 1: 既存のメガSaaSが分断して高額請求している複数の機能をリストアップする',
        'Step 2: モダンなオープンソーススタックでそれらを1つのダッシュボードに統合する',
        'Step 3: 破格の無料枠で開発者に導入させ、従量課金で会社の成長に合わせて課金額を増大させる',
      ],
      coldOutreachTemplate: '【分析ツール利用料の60%削減】MixpanelとDatadogを統合し、開発者が1つのSDKで全機能を回せるPostHogのご案内です。',
    },
    temporal: {
      foundedYear: 2020,
      initialTractionPeriod: '2020-2022年 (オープンソース公開・YCバイラル期)',
      dataSnapshotPeriod: '2023-2026年 (急拡大・マルチプロダクトOS期)',
      viabilityStatus: 'RISING_WAVE',
      viabilityLabel: '急上昇トレンド最盛期（開発者ツール統合のデファクト化）',
      eraContext: 'SaaS乱立による企業のコスト削減圧力と、開発者主導のツール選定文化の定着。',
      currentViabilityAnalysis: 'ClickHouseを活用した高スケーラビリティと圧倒的な開発速度により、他社の追随を許さないポジションを確立している。',
    },
  },

  // 2. Midjourney
  {
    id: 'ent_midjourney_ai',
    ticker: 'MIDJOURNEY',
    name: 'Midjourney',
    legalEntity: 'Midjourney Inc.',
    tagline: '社員わずか11人で年商300億円・外部VC資金ゼロ。Discordに居座りサーバー代以外ほぼ全額利益として吸い上げる画像生成の怪物',
    sector: 'AI_AUTOMATION',
    scale: 'SMALL_TEAM',
    founder: 'David Holz',
    country: 'US',
    url: 'https://midjourney.com',
    verifiedBadge: true,
    growthRateYoY: 200.0,
    architecturePattern: '他社プラットフォーム寄生型超高収益',
    pipelineStack: 'Discord Bot API × 自前分散GPUクラスタ × Stripe',
    targetPainWallet: 'デザイナー・クリエイターの「超高品質ビジュアルを数秒で手に入れたい」渇望',
    tags: ['少数精鋭', '年商300億', 'Discord寄生', '無借金VCゼロ', '異次元の利益率'],
    pnl: {
      monthlyRevenue: 2500000000,
      cogs: 500000000,
      grossProfit: 2000000000,
      grossMargin: 80.0,
      operatingExpenses: {
        serverAndApi: 150000000,
        advertising: 0,
        subcontracting: 50000000,
        toolsAndSaaS: 20000000,
        other: 80000000,
      },
      operatingProfit: 1700000000,
      operatingMargin: 68.0,
      estimatedAnnualNetProfit: 20400000000,
      financialStatus: 'REPORTED',
      isRevenueUnconfirmed: false,
      isMarginUnconfirmed: false,
      revenueLabel: '公式開示・業界推計 年商$200M超（社員約11名で純利益率60%超）',
    },
    evidenceCards: [
      {
        id: 'ev_midjourney_loot_blueprint',
        type: 'LOOT_BLUEPRINT',
        title: '【略奪転用】自前Webサイトを作らず「他人のSNS（Discord）」にBotで寄生して即座に課金させる配管',
        badge: '略奪転用方程式',
        evidenceStatus: 'VERIFIED',
        punchline: '認証や課金画面、コミュニティUIを一切自作せず、Discordサーバーの中にBotを放り込むだけで初日から世界中から現金を吸い上げる。',
        details: [
          '【Step 1: 開発リソースの極小化】: Webアプリやスマホアプリの開発を完全に捨て、Discord Botのコマンド（/imagine）だけに集中。',
          '【Step 2: 公開生成による相互宣伝】: 全員の生成プロンプトと画像がパブリックチャンネルに流れるため、他人の神画像を見た初心者が熱狂して有料化。',
          '【Step 3: GPU高速生成権のサブスク】: 月$10〜$60のプランで「高速生成時間（Fast GPU Hours）」を売り、前金で毎月数十億円を回収。',
        ],
        codeSnippet: '// Discord Botを介したAI生成ジョブ受付とGPUクラスタへのディスパッチ\nexport async function handleImagineCommand(interaction: DiscordInteraction) {\n  const prompt = interaction.options.getString("prompt");\n  const isPro = await checkSubscription(interaction.user.id);\n  const job = await gpuCluster.dispatch({ prompt, priority: isPro ? "FAST" : "RELAXED" });\n  return interaction.reply({ content: `生成中: ${job.estimatedSeconds}秒` });\n}',
        sourceNote: 'David Holzの基調講演およびMidjourney公式Discord運営ログから抽出',
      },
      {
        id: 'ev_midjourney_crime',
        type: 'THE_CRIME',
        title: '広告費1円も使わず、社員11人で毎月17億円の営業利益を手残りさせる',
        badge: '身も蓋もない真実',
        evidenceStatus: 'VERIFIED',
        punchline: 'Webサイトすら作らずDiscordだけで世界中のクリエイター1,600万人を囲い込み、OpenAIやGoogleが巨額赤字を垂れ流す横で暴利を貪る。',
        details: [
          'VCから1円も調達していないため、株主の顔色を伺わず創業者の美学だけで運営。',
          '「美しさ」の美的感覚（デフォルトの画力）に特化し、プロンプトが適当でも映画のワンシーンのような画像を吐き出させて初心者を魅了。',
        ],
      },
    ],
    operations: {
      teamSize: 11,
      weeklyHours: 40,
      initialCapitalRequired: 10000000,
      automationLevel: 95,
      primaryChannels: ['Discord内での相互バイラル', 'X/Instagramでの画像自然拡散'],
      toolStack: [
        { name: 'Discord API', category: 'UI・コミュニティ', monthlyCost: 0, purpose: '1,600万人ユーザーのフロントエンド' },
        { name: 'Google Cloud GPU', category: '計算リソース', monthlyCost: 450000000, purpose: '拡散モデルの大規模推論クラスタ' },
        { name: 'Stripe', category: '決済基盤', monthlyCost: 75000000, purpose: 'グローバル月額サブスクリプション' },
      ],
    },
    strategy: {
      blindspot: 'OpenAIやGoogleは「APIを外部に売る」「Webアプリを作る」教科書的発想に縛られ、クリエイターが既に溜まっているDiscordコミュニティに全振りする奇襲を打てなかった。',
      moatType: 'BRAND_PRESTIGE',
      moatDescription: '独自の美的チューニングによる「Midjourney特有の圧倒的な絵画的クオリティ」というブランド認知。',
      incumbentDilemma: '巨大テック企業は著作権訴訟やコンプライアンスのリスクを恐れてモデルの表現力を去勢したが、Midjourneyは攻めの姿勢を維持してプロを魅了した。',
      secretInsight: 'AIビジネスで勝つのは「最も賢いモデル」ではない。「人間が一目見て『美しい』と錯覚する絵作り」を極めた者である。',
      initialTraction: [
        '少人数のクローズドDiscordサーバーでアーティストを招待しベータテスト開始',
        '生成された画像がTwitterで拡散され、招待コードを求める人々が殺到',
        'ローンチ後数ヶ月で有料会員数十万人を突破し爆発的黒字化',
      ],
      actionPlaybook: [
        'Step 1: ユーザーがすでに滞在している既存プラットフォーム（Discord/Telegram/Slack）をフロントエンドにする',
        'Step 2: 最初の数秒で「うわっ、すごい」と声が出る圧倒的知覚価値を提供する',
        'Step 3: 広告を打たず、ユーザー自身がSNSに成果物を自慢したくなる動線を設計する',
      ],
      coldOutreachTemplate: '【商用デザイン制作工数90%削減】プロ品質のビジュアルを秒速で生成し、外注デザイン費を完全内製化する生成フローのご提案です。',
    },
    temporal: {
      foundedYear: 2022,
      initialTractionPeriod: '2022-2023年 (Discordバイラル・画像AI社会現象期)',
      dataSnapshotPeriod: '2024-2026年 (v6リリース・Web版展開・年商300億円期)',
      viabilityStatus: 'RISING_WAVE',
      viabilityLabel: '急上昇トレンド最盛期（画像AIの最高峰ブランドとして君臨）',
      eraContext: '生成AIブームの特異点と、Discordコミュニティカルチャーの世界的浸透。',
      currentViabilityAnalysis: 'オープンソース（Flux等）の猛追があるものの、Midjourney独自の美的スタイルとプロ向け機能で圧倒的な有料会員数を維持。',
    },
  },

  // 3. Dub.co
  {
    id: 'ent_dub_co',
    ticker: 'DUB.CO',
    name: 'Dub.co',
    legalEntity: 'Dub Technologies Inc.',
    tagline: '「Bitlyの管理画面が古すぎて重い」「独自ドメイン設定に高額請求される」マーケターの不満を突き、短縮リンクをモダンインフラへ昇華したオープンソースSaaS',
    sector: 'NICHE_SAAS',
    scale: 'SMALL_TEAM',
    founder: 'Steven Tey',
    country: 'US',
    url: 'https://dub.co',
    verifiedBadge: true,
    growthRateYoY: 220.0,
    architecturePattern: 'レガシーSaaSのモダン再定義',
    pipelineStack: 'Next.js × Tinybird × Upstash Redis × Cloudflare Workers',
    targetPainWallet: '企業のグロース担当者の「クリック計測の遅延・ダサいリンク・高額なBitly料金」',
    tags: ['オープンソース', '短縮URL', '開発者UX', '粗利80%', 'Bitly代替'],
    pnl: {
      monthlyRevenue: 15000000,
      cogs: 2000000,
      grossProfit: 13000000,
      grossMargin: 86.7,
      operatingExpenses: {
        serverAndApi: 1500000,
        advertising: 0,
        subcontracting: 1000000,
        toolsAndSaaS: 500000,
        other: 1000000,
      },
      operatingProfit: 9000000,
      operatingMargin: 60.0,
      estimatedAnnualNetProfit: 108000000,
      financialStatus: 'REPORTED',
      isRevenueUnconfirmed: false,
      isMarginUnconfirmed: false,
      revenueLabel: '創業者X公開ARR $1M+突破（月商約1,500万円）',
    },
    evidenceCards: [
      {
        id: 'ev_dub_loot_blueprint',
        type: 'LOOT_BLUEPRINT',
        title: '【略奪転用】古びた巨大レガシー（Bitly）の「UIと開発者体験」をモダン化して顧客を奪う配管',
        badge: '略奪転用方程式',
        evidenceStatus: 'VERIFIED',
        punchline: '10年以上進化が止まった定番ツールを、Vercel水準の美しいUIとエッジコンピューティングで作り直して開発者から総取りする。',
        details: [
          '【Step 1: レガシーの機能不全を特定】: Bitlyが無料枠を締め出し、カスタムドメインで月数十ドル請求している不満を突く。',
          '【Step 2: オープンソースと美麗なUI】: Next.jsとTailwindの洗練されたUIをGitHubで全公開し、開発者の信頼を獲得。',
          '【Step 3: 企業向けAPIとアナリティクス課金】: 大量のクリックをリアルタイム集計できる高機能版（月$24〜$499）を有料販売。',
        ],
        codeSnippet: '// Dub.coのAPIを用いた短縮URL動的発行スニペット\nexport async function createBrandedShortLink(destinationUrl: string, slug: string) {\n  const res = await fetch("https://api.dub.co/links", {\n    method: "POST",\n    headers: { Authorization: `Bearer ${process.env.DUB_API_KEY}`, "Content-Type": "application/json" },\n    body: JSON.stringify({ url: destinationUrl, key: slug, domain: "go.yourbrand.com" })\n  });\n  return await res.json();\n}',
        sourceNote: 'Steven Teyの公開ビルドログおよびGitHub Dubリポジトリ（1.7万Star）から抽出',
      },
      {
        id: 'ev_dub_crime',
        type: 'THE_CRIME',
        title: '「ただのURL短縮」をオープンソースと極上UXで年間1億円の自走装置へ化けさせる',
        badge: '身も蓋もない真実',
        evidenceStatus: 'VERIFIED',
        punchline: '技術的には誰でも作れるURLリダイレクトを、世界最速のエッジ配信（Cloudflare）と美しい分析画面で武装し、大企業からカード決済させる。',
        details: [
          '元Vercelの敏腕エンジニアが1人で開発を開始し、Twitterで開発過程を毎日実況して初期ユーザー数千人を広告費ゼロで獲得。',
          '短縮リンクがSNSでクリックされるたびに、画面右下に「Powered by Dub」が表示されリンク自体が勝手に新規顧客を連れてくる。',
        ],
      },
    ],
    operations: {
      teamSize: 3,
      weeklyHours: 40,
      initialCapitalRequired: 500000,
      automationLevel: 90,
      primaryChannels: ['GitHubオープンソース', '創業者X実況（オーガニック）', '自社リンクのフッターバイラル'],
      toolStack: [
        { name: 'Cloudflare Workers', category: 'エッジ基盤', monthlyCost: 300000, purpose: 'ミリ秒単位の超高速URLリダイレクト' },
        { name: 'Tinybird', category: 'リアルタイム分析', monthlyCost: 450000, purpose: 'クリックログの即時集計' },
        { name: 'Stripe', category: '決済代行', monthlyCost: 450000, purpose: 'SaaSサブスクリプション自動請求' },
      ],
    },
    strategy: {
      blindspot: 'Bitlyは巨大エンタープライズに最適化しすぎて動作が重くなり、モダンな開発者が求めるAPIの使いやすさや美しさを完全に軽視していた。',
      moatType: 'SWITCHING_COST',
      moatDescription: '世界中に印刷されたチラシ、SNS投稿、メール内の短縮リンクが全てDub経由で稼働しており、解約すると全リンクが死ぬため乗り換え不能。',
      incumbentDilemma: 'Bitlyはレガシーなインフラと高額営業チームを維持しなければならないため、Dubのような軽量・低価格・開発者特化プランを出せない。',
      secretInsight: '「すでに誰かが大成功した退屈な定番SaaS」を、最新の技術スタック（Next.js/Tailwind/エッジ）で作り直すのが最も勝率の高いビジネスである。',
      initialTraction: [
        'GitHubで「Dub」をオープンソース公開し、Product HuntでDay 1 Product of the Dayを獲得',
        'Vercelのエコシステムと連携し、Next.js開発者の標準ツールとしてポジションを確立',
        '有料プランをリリースした初月でARR $100Kを即座に突破',
      ],
      actionPlaybook: [
        'Step 1: 10年前に創業されてUIが古臭くなった定番ツール（短縮URL、フォーム、アンケート等）を探す',
        'Step 2: 最新のフロントエンド技術で極限まで美しいクローンを作る',
        'Step 3: 開発者コミュニティにオープンソースとして無償提供し、上位機能で課金する',
      ],
      coldOutreachTemplate: '【Bitlyコスト半減とブランドリンク統一】御社の公式短縮リンクをカスタムドメインで無制限に発行・計測できるDubのご案内です。',
    },
    temporal: {
      foundedYear: 2022,
      initialTractionPeriod: '2022-2023年 (オープンソース公開・バイラル期)',
      dataSnapshotPeriod: '2024-2026年 (企業導入急増・ARR $1M達成期)',
      viabilityStatus: 'RISING_WAVE',
      viabilityLabel: '急上昇トレンド最盛期（Bitly代替のデファクトとして急成長）',
      eraContext: 'エッジコンピューティング（Cloudflare Workers）の進化により、低コストで超高速なグローバルインフラが個人でも構築可能に。',
      currentViabilityAnalysis: '極めて強固。短縮リンクという不可逆なインフラを握っているため、解約率が極めて低く安定したストック収益を生む。',
    },
  },

  // 4. Resend
  {
    id: 'ent_resend_email',
    ticker: 'RESEND',
    name: 'Resend',
    legalEntity: 'Resend Inc.',
    tagline: '「SendGridの管理画面が複雑でメールが届かない」エンジニアの激痛を突き、Reactでメールを作れるようにして年商数億円を抜く開発者特化メールAPI',
    sector: 'NICHE_SAAS',
    scale: 'SMALL_TEAM',
    founder: 'Zeno Rocha, Bu Kinoshita',
    country: 'US',
    url: 'https://resend.com',
    verifiedBadge: true,
    growthRateYoY: 250.0,
    architecturePattern: '開発者体験（DX）極大化によるレガシー奪取',
    pipelineStack: 'React Email × Next.js × AWS SES × Stripe',
    targetPainWallet: '開発者の「HTMLメールの崩れ・古いSendGridの設定画面・到達率低下の苦痛」',
    tags: ['メールAPI', 'ReactEmail', '開発者体験', '粗利80%', 'SendGrid代替'],
    pnl: {
      monthlyRevenue: 60000000,
      cogs: 9000000,
      grossProfit: 51000000,
      grossMargin: 85.0,
      operatingExpenses: {
        serverAndApi: 6000000,
        advertising: 0,
        subcontracting: 3000000,
        toolsAndSaaS: 2000000,
        other: 5000000,
      },
      operatingProfit: 35000000,
      operatingMargin: 58.3,
      estimatedAnnualNetProfit: 420000000,
      financialStatus: 'REPORTED',
      isRevenueUnconfirmed: false,
      isMarginUnconfirmed: false,
      revenueLabel: '公式開示ARR $5M超（月間数千万通のメール配信インフラ）',
    },
    evidenceCards: [
      {
        id: 'ev_resend_loot_blueprint',
        type: 'LOOT_BLUEPRINT',
        title: '【略奪転用】エンジニアが嫌う「HTMLメール作成」をReactコンポーネント化して独占する配管',
        badge: '略奪転用方程式',
        evidenceStatus: 'VERIFIED',
        punchline: 'Outlookで崩れるテーブルタグのHTMLメールを捨て、「ReactでメールのUIを書けるオープンソース（React Email）」を配ってメールAPIを売り抜く。',
        details: [
          '【Step 1: 開発者の共通の痛みを特定】: テーブルレイアウトでHTMLメールを書く苦痛と、古いSendGridのUIへの怨嗟を特定。',
          '【Step 2: 無料のReact Emailライブラリを公開】: メールをReactで美しく作れるツールをオープンソースで配り、全世界の開発者を虜にする。',
          '【Step 3: 配信APIの月額・通数課金】: 作ったメールを1行で送信できるResend APIへ直結させ、毎月の配信通数に応じて課金。',
        ],
        codeSnippet: '// Resendを用いたReactコンポーネント直接送信スニペット\nimport { Resend } from "resend";\nimport { WelcomeEmail } from "./emails/Welcome";\nconst resend = new Resend(process.env.RESEND_API_KEY);\nexport async function sendWelcome(toEmail: string) {\n  return await resend.emails.send({ from: "onboarding@yourdomain.com", to: toEmail, subject: "ようこそ", react: WelcomeEmail({ name: "ユーザー" }) });\n}',
        sourceNote: 'Zeno Rochaの公開カンファレンス講演およびResend公式開示データから抽出',
      },
      {
        id: 'ev_resend_crime',
        type: 'THE_CRIME',
        title: 'TwilioがSendGridを買収して放置した隙間に、洗練されたStripe型体験をぶち込んで客を奪う',
        badge: '身も蓋もない真実',
        evidenceStatus: 'VERIFIED',
        punchline: '裏側の配信インフラはAWS SES等の既存配管を活用しつつ、極上のSDKと美しいドキュメントだけで競合の何倍もの高価格でも喜んで契約させる。',
        details: [
          '「コード数行でメールが届く」という摩擦ゼロの導入体験により、Y Combinatorのスタートアップの大半がSendGridからResendへ雪崩を打って移行。',
          'パスワードリセットや認証コードなど、企業にとって「止まると死ぬ基幹メール」を握るため、解約率が実質ゼロ。',
        ],
      },
    ],
    operations: {
      teamSize: 8,
      weeklyHours: 40,
      initialCapitalRequired: 3000000,
      automationLevel: 92,
      primaryChannels: ['React Emailオープンソース（1.4万Star）', '開発者口コミ', 'YCネットワーク'],
      toolStack: [
        { name: 'AWS SES', category: '配信基盤', monthlyCost: 5000000, purpose: '高到達率SMTPインフラ' },
        { name: 'Cloudflare', category: 'DNS・エッジ', monthlyCost: 500000, purpose: 'ドメイン認証とAPI高速化' },
        { name: 'Stripe', category: '決済代行', monthlyCost: 1800000, purpose: '通数従量課金' },
      ],
    },
    strategy: {
      blindspot: 'SendGridやMailchimpは買収されて大企業病に陥り、モダンなWebフレームワーク（Next.js, Remix）を使う開発者が求める「コードで書けるメール」を無視していた。',
      moatType: 'SWITCHING_COST',
      moatDescription: '企業の全トランザクションメール（登録完了、決済通知、認証メール）のコードにResend SDKが埋め込まれ、乗り換えが極めて面倒な監禁構造。',
      incumbentDilemma: 'SendGridはレガシー顧客を多数抱えているため、API仕様をモダンに刷新すると既存顧客のコードが壊れてしまい身動きが取れない。',
      secretInsight: 'B2B開発者向けSaaSの必勝法は「裏側の重いインフラは自前で作らず、世界一美しいSDKとドキュメントを着せて付加価値を中抜きすること」である。',
      initialTraction: [
        'Zeno Rochaが個人で開発したReact EmailがGitHubトレンド1位を獲得',
        'Y Combinator（S23）に採択され、同期のスタートアップ全員に導入させる',
        'Twitterで美しいドキュメントと動画を投稿し、開発者が「使ってみたい」と自発的に布教する熱狂を作る',
      ],
      actionPlaybook: [
        'Step 1: 誰もが使っているが全員が不満を持っている「レガシーインフラ（メール、SMS、PDF生成等）」を特定する',
        'Step 2: モダンな言語（TypeScript/React）で直感的に書けるオープンソースツールを無償配布する',
        'Step 3: そのツールから1クリックで繋がる高収益クラウドAPIを売り抜く',
      ],
      coldOutreachTemplate: '【SendGridからの移行でメール到達率向上】Reactでメールをそのまま送信でき、開発工数を半減させるResendのご案内です。',
    },
    temporal: {
      foundedYear: 2023,
      initialTractionPeriod: '2023年 (React Emailバイラル・YC期)',
      dataSnapshotPeriod: '2024-2026年 (ARR $5M達成・開発者標準化期)',
      viabilityStatus: 'RISING_WAVE',
      viabilityLabel: '急上昇トレンド最盛期（新世代トランザクションメールの覇者）',
      eraContext: 'TypeScriptとNext.jsの圧倒的普及により、開発者が「全スタックをTypeScriptで統一したい」と切望した時代背景。',
      currentViabilityAnalysis: '開発者コミュニティでのブランド力が圧倒的であり、新規スタートアップのデフォルトインフラとして君臨している。',
    },
  },

  // 5. Beehiiv
  {
    id: 'ent_beehiiv_newsletter',
    ticker: 'BEEHIIV',
    name: 'Beehiiv',
    legalEntity: 'Beehiiv Inc.',
    tagline: '「Substackは読者データを囲い込む」「Mailchimpは高すぎる」クリエイターの不満を突き、Morning Brewの自社配信配管をSaaS化して年商20億円を稼ぐニュースレターOS',
    sector: 'NICHE_SAAS',
    scale: 'SCALEUP',
    founder: 'Tyler Denk, Benjamin Hargett, Jacob Hurd',
    country: 'US',
    url: 'https://beehiiv.com',
    verifiedBadge: true,
    growthRateYoY: 180.0,
    architecturePattern: '自社の勝ちパターン配管のSaaS外販',
    pipelineStack: 'Next.js × Ruby on Rails × SendGrid × 広告ネットワーク内製',
    targetPainWallet: 'メディア・個人の「読者獲得コストの高さと、広告スポンサー集めの労力」',
    tags: ['ニュースレター', '広告ネットワーク', 'リファラル配管', 'ARR20億円超', 'Substack代替'],
    pnl: {
      monthlyRevenue: 180000000,
      cogs: 27000000,
      grossProfit: 153000000,
      grossMargin: 85.0,
      operatingExpenses: {
        serverAndApi: 18000000,
        advertising: 20000000,
        subcontracting: 15000000,
        toolsAndSaaS: 10000000,
        other: 25000000,
      },
      operatingProfit: 65000000,
      operatingMargin: 36.1,
      estimatedAnnualNetProfit: 780000000,
      financialStatus: 'REPORTED',
      isRevenueUnconfirmed: false,
      isMarginUnconfirmed: false,
      revenueLabel: '公式開示ARR $15M超（購読者数千万人のニュースレターネットワーク）',
    },
    evidenceCards: [
      {
        id: 'ev_beehiiv_loot_blueprint',
        type: 'LOOT_BLUEPRINT',
        title: '【略奪転用】自社で実証した「グロース機能（紹介・広告）」を他人に売って月額と広告料を二重中抜きする配管',
        badge: '略奪転用方程式',
        evidenceStatus: 'VERIFIED',
        punchline: 'Morning Brewを数百万人規模に育てた「友達紹介プログラム」と「広告配信網」をそのままソフトウェア化し、クリエイターから月額＋広告仲介料を吸い上げる。',
        details: [
          '【Step 1: 実証済み武器の外販】: 成功したメディアが社内用に使っていたグロース配管（リファラル報酬、相互推薦）を汎用SaaSにする。',
          '【Step 2: 広告ネットワークの胴元化】: 広告主から予算を預かり、中小ニュースレターに自動配信して広告費の20%を手数料として中抜き。',
          '【Step 3: 規模に応じた月額サブスク】: 読者数が増えるほど高額になるプラン（月$49〜$999）でストック収益を二重確保。',
        ],
        codeSnippet: '// Beehiivの相互推薦ネットワーク（Boosts）による読者獲得配管\nexport async function recommendNewsletter(subscriberEmail: string, targetPubId: string) {\n  return await fetch("https://api.beehiiv.com/v2/boosts", {\n    method: "POST",\n    headers: { Authorization: `Bearer ${process.env.BEEHIIV_API_KEY}` },\n    body: JSON.stringify({ email: subscriberEmail, target_publication_id: targetPubId })\n  });\n}',
        sourceNote: 'Tyler Denkのポッドキャスト出演ログおよびBeehiiv公開Investor Updateから抽出',
      },
      {
        id: 'ev_beehiiv_crime',
        type: 'THE_CRIME',
        title: 'Substackが「作家のプラットフォーム」を気取る横で、容赦ない金儲け機能だけを詰め込んでクリエイターを寝返らせる',
        badge: '身も蓋もない真実',
        evidenceStatus: 'VERIFIED',
        punchline: 'Substackが手数料10%を抜くのに対し、月額固定費＋広告ネットワークで「クリエイターが最も手残り現金を残せる場所」としてポジショニングし顧客を奪取。',
        details: [
          'クリエイターが「書くこと」以上に「稼ぐこと（広告スポンサー獲得）」に困っている急所を突き、広告主を自動でマッチング。',
          '読者リストの完全エクスポートを保証し、「他社に人質を取られない自由」を逆張りで売ることで信頼を獲得。',
        ],
      },
    ],
    operations: {
      teamSize: 45,
      weeklyHours: 40,
      initialCapitalRequired: 20000000,
      automationLevel: 80,
      primaryChannels: ['自社ニュースレターのフッターバイラル', 'Twitterでのグロースノウハウ共有', 'クリエイター直接引き抜き'],
      toolStack: [
        { name: 'SendGrid / AWS SES', category: '配信基盤', monthlyCost: 12000000, purpose: '月間数億通の大規模メール配信' },
        { name: 'Stripe Connect', category: '広告決済・分配', monthlyCost: 5000000, purpose: '広告主とクリエイター間の売上自動分配' },
      ],
    },
    strategy: {
      blindspot: 'Mailchimpは高機能すぎて使いにくく、Substackは広告マネタイズを嫌悪していたため、「ニュースレターで本気で稼ぎたいプロ」の受け皿が完全に空白だった。',
      moatType: 'NETWORK_EFFECT',
      moatDescription: '他のニュースレター読者が登録時に別レターをワンクリック購読できる「相互推薦（Boosts）ネットワーク」による自走フライホイール。',
      incumbentDilemma: 'Substackは「読者直接課金の手数料10%」が本業の柱であるため、Beehiivのように手数料0%＋広告モデルに舵を切ると自滅する。',
      secretInsight: 'メディアSaaSで最も強いのは「ツールの機能」ではない。「このツールを使うと読者が増え、広告費が口座に振り込まれる」という金儲けの直結配管である。',
      initialTraction: [
        '元Morning Brewのエンジニアが立ち上げたという強烈なストーリーで初期注目を獲得',
        '人気クリエイターに直接アプローチし、リファラル機能による読者増加の実績を数字で提示',
        '自社が配信するメルマガの最下部に「Powered by Beehiiv」を入れ、爆発的な登録ループを確立',
      ],
      actionPlaybook: [
        'Step 1: 特定業界の勝者（Morning Brew等）が社内だけで使っていた「勝ちパターン」を分析する',
        'Step 2: その仕組みを一般人が数クリックで使えるSaaSとして再構築する',
        'Step 3: ツールだけでなく「売上を直接生み出す広告網や紹介網」をセットで提供する',
      ],
      coldOutreachTemplate: '【ニュースレター収益化と読者獲得の自動化】Substack手数料10%をゼロにし、広告スポンサーを自動供給するBeehiivへの移行のご提案です。',
    },
    temporal: {
      foundedYear: 2021,
      initialTractionPeriod: '2021-2023年 (クリエイター大量移籍・急成長期)',
      dataSnapshotPeriod: '2024-2026年 (広告ネットワーク拡大・ARR $15M達成期)',
      viabilityStatus: 'RISING_WAVE',
      viabilityLabel: '急上昇トレンド最盛期（ニュースレターインフラの新標準）',
      eraContext: 'SNSアルゴリズムの改悪に伴う「自前読者リスト（メール）」の重要性再認識と、個人メディアの急増。',
      currentViabilityAnalysis: '広告ネットワークという二層市場を握っているため、単なるツール提供者を超えたプラットフォームとしての堀を確立。',
    },
  },
];
