import type { FinancialEntity } from '../src/platform/types/terminal';

export const REFINED_STATISTICAL_SAMPLE_ENTITIES: FinancialEntity[] = [
  // 1. Plausible Analytics
  {
    id: 'ent_company_7398a06ad48e5fb1ede7',
    ticker: 'PLAUSIBLE',
    name: 'Plausible Analytics',
    legalEntity: 'Plausible Insights OÜ',
    tagline: '「GA4が重すぎて客が逃げる」「Cookie同意バナーがウザい」Web担当者の発狂を突き、コード1行で年間4億円抜く完全独立系オープンソース解析',
    sector: 'NICHE_SAAS',
    scale: 'SMALL_TEAM',
    founder: 'Uku Taht, Marko Saric',
    country: 'EE',
    url: 'https://plausible.io',
    verifiedBadge: true,
    growthRateYoY: 45.0,
    architecturePattern: 'クッキーレス軽量代替',
    pipelineStack: 'Elixir/Phoenix × ClickHouse × AGPLオープンソース',
    targetPainWallet: 'Web担当者の胃痛（GA4の難解さ、Cookie同意バナーによるCV低下、GDPR罰則恐怖）',
    tags: ['プライバシー重視', '脱Google', 'オープンソースSaaS', 'ノーコード導入', '粗利85%超', '完全ブートストラップ'],
    pnl: {
      monthlyRevenue: 35000000,
      cogs: 3500000,
      grossProfit: 31500000,
      grossMargin: 90.0,
      operatingExpenses: {
        serverAndApi: 2500000,
        advertising: 0,
        subcontracting: 1000000,
        toolsAndSaaS: 500000,
        other: 500000,
      },
      operatingProfit: 27000000,
      operatingMargin: 77.1,
      estimatedAnnualNetProfit: 324000000,
      financialStatus: 'REPORTED',
      isRevenueUnconfirmed: false,
      isMarginUnconfirmed: false,
      revenueLabel: '公式開示ARR $2.8M（21,000社有料購読）',
    },
    evidenceCards: [
      {
        id: 'ev_plausible_loot_blueprint',
        type: 'LOOT_BLUEPRINT',
        title: '【略奪転用】巨大独占無料ツール（Google等）が自爆した隙間に「1/10の軽量版」を差し込み粗利80%抜く配管',
        badge: '略奪転用方程式',
        evidenceStatus: 'VERIFIED',
        punchline: '大手が規制や多機能化で自爆してユーザーが苦痛を叫んでいる時、「機能を1/10にし、同意バナーを不要にする」だけで有料でも喜んで客が雪崩れ込む。',
        details: [
          '【Step 1: 大手の自爆の特定】: Google AnalyticsがGA4へ強制移行し、UIが劇的に悪化＋EUのGDPRでCookie同意バナーが必須化された苦痛を特定。',
          '【Step 2: 1KBスクリプトとオープンソース】: 個人情報を一切取らない1KB未満の超軽量スクリプトを開発し、AGPLでコード公開して開発者の信頼を獲得。',
          '【Step 3: 広告費ゼロの比較SEO】: 「Google Analyticsの代替」「GA4のCookieレス移行」という比較記事だけでオーガニック流入を独占し、月額$9〜から課金。',
        ],
        codeSnippet: '// 軽量クッキーレス計測スクリプトの埋め込みエンドポイント設計\n// 顧客のHTMLヘッダーに1行追加させるだけで、セッションストレージやクッキーを一切使わずハッシュ化IPで日次ユニークのみ集計\n<script defer data-domain="yourdomain.com" src="https://plausible.io/js/script.js"></script>',
        sourceNote: 'Plausibleの公式開示（21,000社有料会員、広告費$0成長ログ）から抽出した構造転用設計図',
      },
      {
        id: 'ev_plausible_crime',
        type: 'THE_CRIME',
        title: '広告費・営業費0円で年商4億円・営業利益率77%を叩き出すプライバシー要塞',
        badge: '身も蓋もない真実',
        evidenceStatus: 'VERIFIED',
        punchline: 'Googleが無料で配るGA4の使いにくさにブチ切れたエンジニア・マーケターから、月額$9〜$100を毎月全自動で徴収する。',
        details: [
          '外部調達（VC）ゼロ、広告出稿費ゼロ、アフィリエイト報酬ゼロ。完全な自己資金（Self-funded）で10人体制。',
          'EUのGDPR規制により「Cookie同意バナーを出さないといけない」という企業サイトの美観・離脱ペインを完全切除。',
          'Basecamp, Ghost, Hugging Face, Harvard Universityなどのビッグネームが公式採用し社会的証明が極大化。',
        ],
      },
      {
        id: 'ev_plausible_genesis',
        type: 'DIRTY_GENESIS',
        title: '創業者1人の孤独な開発からHacker News炎上をバネにした初動制圧',
        badge: '初期ゲリラ戦ログ',
        evidenceStatus: 'VERIFIED',
        punchline: '「Googleにデータを渡したくない」開発者心理に火をつけ、Hacker Newsトップ掲載から初動100人を強奪。',
        details: [
          '2018年にエストニアのエンジニアUku Tahtが1人で創業。当初は鳴かず飛ばずで月商数十ドル。',
          '2020年にMarko Saricが合流し、「GA4 vs Plausible」の辛口比較記事をHacker NewsやRedditで連打。',
          'オープンソースコミュニティで「反巨大IT（De-Google）」のシンボルとして祭り上げられ、口コミのみで急拡大。',
        ],
      },
    ],
    operations: {
      teamSize: 10,
      weeklyHours: 35,
      initialCapitalRequired: 0,
      automationLevel: 90,
      primaryChannels: ['Hacker News / Reddit 口コミ', 'GA4批判SEO比較記事', 'オープンソースGitHubリポジトリ'],
      toolStack: [
        { name: 'Elixir/Phoenix', category: 'バックエンド', monthlyCost: 0, purpose: '秒間数万リクエストを低メモリで処理' },
        { name: 'ClickHouse', category: '分析データベース', monthlyCost: 800000, purpose: '数億行のアクセスログを超高速集計' },
        { name: 'Hetzner', category: 'ホスティング', monthlyCost: 600000, purpose: 'EU拠点のベアメタルサーバーによるコスト圧縮' },
        { name: 'Stripe', category: '決済', monthlyCost: 1050000, purpose: 'グローバル定期課金決済（手数料約3%）' },
      ],
    },
    strategy: {
      blindspot: 'Googleは自社の広告ビジネス（ターゲティング広告）を守るために個人データの追跡をやめられず、Cookie不要のシンプル解析を出せなかった。',
      moatType: 'COUNTER_POSITIONING',
      moatDescription: 'Google Analyticsは広告エコシステムの都合上、複雑怪奇なイベント設計と個人トラッキングが必須。Plausibleは「広告をやらない」という前提そのものが堀になっている。',
      incumbentDilemma: 'GoogleがPlausibleのような軽量・Cookieレスツールを無償提供すると、Googleの主たる収益源であるパーソナライズ広告の精度が落ちて自爆する。',
      secretInsight: 'サイト運営者の95%は「PV数・参照元・閲覧デバイス」の3つしか見ていない。GA4の何百もある複雑なメニューは顧客の95%にとって騒音でしかない。',
      initialTraction: [
        'Hacker Newsで「Google Analyticsのオープンソース代替を作った」と投稿し1,000 Upvotes獲得',
        '「なぜ私たちはGoogle Analyticsを削除したのか」という過激なブログ記事でSEO流入を独占',
        '自社のMRR、PV数、サーバー費用を自社サイト上でリアルタイム全公開（オープンメトリクス）',
      ],
      actionPlaybook: [
        'Step 1: 誰もが使っている巨大無料ツールの「最近の改悪（UI複雑化・法規制対応）」の怨嗟を調査する',
        'Step 2: 機能を1/10に削り、1分でセットアップできるオープンソース版を公開する',
        'Step 3: ホスティング・保守が面倒な層向けに月額$9〜のマネージドクラウドSaaSを提供し課金化する',
      ],
      coldOutreachTemplate: '【貴社サイトのCookie同意バナーを今夜撤去できる軽量解析のご案内】〇〇様、突然のご連絡失礼いたします。現在貴社サイトで表示されているCookieバナーによる訪問者の離脱にお悩みではありませんか？Plausibleは1KBのコード1行で、Cookieバナー不要・EU法完全準拠のアクセス解析を提供します。',
    },
    temporal: {
      foundedYear: 2018,
      initialTractionPeriod: '2020年春 (GA4不満噴出期)',
      dataSnapshotPeriod: '2024-2026年 (ARR $2.8M規模)',
      viabilityStatus: 'ACTIVE_PLAYBOOK',
      viabilityLabel: '現在も有効（脱GA4の受け皿）',
      eraContext: 'EUのGDPR施行とGoogleのGA4強制移行による混乱期。Cookie同意ポップアップへのユーザーの嫌悪感が頂点に達していた。',
      currentViabilityAnalysis: 'プライバシー規制は年々世界中で強化されており、クッキーレス解析の需要は極めて堅牢。自前でインフラを抱えるサーバーコストの管理さえできれば長期高収益を維持できる。',
    },
  },

  // 2. Acquire.com
  {
    id: 'ent_acquirecom_4e8247fa7bf75d8b8584',
    ticker: 'ACQUIRE',
    name: 'Acquire.com',
    legalEntity: 'Acquire.com, Inc.',
    tagline: '「ブローカーの手数料15%と1年の売却交渉」に絶望したSaaS創業者の胃痛を突き、事前審査済みバイヤー50万人へ直結して月商1.2億円抜く売買水門番',
    sector: 'FINTECH_INFRA',
    scale: 'SCALEUP',
    founder: 'Andrew Gazdecki',
    country: 'US',
    url: 'https://acquire.com',
    verifiedBadge: true,
    growthRateYoY: 60.0,
    architecturePattern: '売買水門番',
    pipelineStack: 'Next.js × Stripe × 独自エスクロー決済・NDA自動締結',
    targetPainWallet: 'SaaS創業者の焦燥（バーンレート限界・売却の不透明性）と買い手の案件飢餓',
    tags: ['M&Aプラットフォーム', 'マイクロSaaS', '両面市場', '前金サブスク', '高単価取引', '取引手数料'],
    pnl: {
      monthlyRevenue: 120000000,
      cogs: 12000000,
      grossProfit: 108000000,
      grossMargin: 90.0,
      operatingExpenses: {
        serverAndApi: 3500000,
        advertising: 8000000,
        subcontracting: 15000000,
        toolsAndSaaS: 2500000,
        other: 6000000,
      },
      operatingProfit: 73000000,
      operatingMargin: 60.8,
      estimatedAnnualNetProfit: 876000000,
      financialStatus: 'ESTIMATED',
      isRevenueUnconfirmed: false,
      isMarginUnconfirmed: false,
      revenueLabel: '推定年間売上$10M+（買い手パス＋成約手数料4-6%）',
    },
    evidenceCards: [
      {
        id: 'ev_acquire_loot_blueprint',
        type: 'LOOT_BLUEPRINT',
        title: '【略奪転用】閉鎖的で高額な仲介業をセルフサーブ化し「買い手から前金サブスクを抜く」関所モデル',
        badge: '略奪転用方程式',
        evidenceStatus: 'VERIFIED',
        punchline: '売り手に無料・格安で出品させ、案件情報を見たい買い手に年間$390〜$780の前金パスを課金。成約時にも数%抜く二重搾取構造を作る。',
        details: [
          '【Step 1: 供給（売り手）のハードル撤廃】: 既存のM&A仲介が門前払いする「年商100万〜数千万円の小規模SaaS」を、初期費用ゼロ・Stripe連携だけで出品可能にする。',
          '【Step 2: 買い手側の前金サブスク化】: 投資家や連続起業家向けに「新着優良案件への即時アクセス権」として年間$390（Platinum）を前金で集金。',
          '【Step 3: エスクローと成約手数料】: 買収交渉から資金移動・契約書雛形までをプラットフォーム内で完結させ、クロージング時に4〜6%を自動控除。',
        ],
        codeSnippet: '// 買い手プレミアム権限の認可ガード（年額パス購入者のみ案件のP&L詳細・URLを閲覧可能）\nif (!buyer.hasActivePass || buyer.passType === "FREE") {\n  return sanitizeListingForPublic(listing); // P&Lの生数字と会社名をマスク\n}\nreturn listing.getDeepDiligencePack();',
        sourceNote: 'Acquire.comの買い手サブスク価格体系と取引手数料モデルから抽出した転用設計図',
      },
      {
        id: 'ev_acquire_crime',
        type: 'THE_CRIME',
        title: '他人の作ったSaaSの売買を右から左へ流すだけで毎月1億円以上の現金を抜き取る手口',
        badge: '身も蓋もない真実',
        evidenceStatus: 'VERIFIED',
        punchline: '自分ではSaaSを開発・運用せず、他人が命を削って作ったSaaSの「売却の関所」に居座り、通行税を買い手と売り手の両方から二重取りする。',
        details: [
          '50万人以上の買い手データベースをテコに、売り手を完全に囲い込み。',
          '既存の投資銀行やM&A仲介が要求する着手金・固定月額・15%の法外な成功報酬を破壊。',
          '創業者Andrew Gazdecki自身の強烈なX（Twitter）発信力を最大の集客配管として活用。',
        ],
      },
    ],
    operations: {
      teamSize: 35,
      weeklyHours: 45,
      initialCapitalRequired: 10000000,
      automationLevel: 85,
      primaryChannels: ['創業者Twitter(X)発信', 'SaaS売却週刊ニュースレター', 'Product Hunt'],
      toolStack: [
        { name: 'Next.js', category: 'フロントエンド', monthlyCost: 50000, purpose: '高密度マーケットプレイスUI' },
        { name: 'Stripe Connect', category: 'エスクロー決済', monthlyCost: 3500000, purpose: '買収資金のエスクロー預託と手数料自動徴収' },
        { name: 'DocuSign API', category: '電子契約', monthlyCost: 800000, purpose: 'NDA（秘密保持契約）と売買契約の自動署名' },
      ],
    },
    strategy: {
      blindspot: '大手M&A仲介会社は手数料が数千万円取れる大型買収しか相手にせず、年商数千万円以下のマイクロSaaS市場を「相手にするだけ赤字」と見捨てていた。',
      moatType: 'NETWORK_EFFECT',
      moatDescription: '50万人の買い手がいるからSaaS創業者が集まり、SaaS出品数が多いから買い手が集まる。この巨大な両面流動性の引力場に競合は太刀打ちできない。',
      incumbentDilemma: '既存のM&Aブローカーは対面営業と手作業のデューデリジェンスに特化した組織を持っているため、数万円のサブスクやセルフサーブ仲介をやると自社の高単価プランを自爆させる。',
      secretInsight: '世の中には「新規でゼロから作るより、月商30万〜100万円出ているSaaSをサクッと買収して自分の集客力で伸ばしたい」余剰資金を持ったバイヤーが数百万人いる。',
      initialTraction: [
        '創業者AndrewがTwitterで「自分のSaaSを売りたい人はDMして」と呟き、初期の売り手10社を手作業でスプレッドシート管理',
        'Product Huntでローンチし、インディーハッカー界隈の話題を独占',
        '「今週売却されたSaaS一覧」のニュースレターを毎週配信して買い手を中毒化',
      ],
      actionPlaybook: [
        'Step 1: 取引金額が小さすぎて既存ブローカーが相手にしないニッチ資産（個人ブログ、小規模EC、Shopifyアプリ）を特定する',
        'Step 2: 売り手には完全無料で出品させ、スプレッドシートで案件を蓄積する',
        'Step 3: 案件を一覧化したニュースレターを作り、買い手から「優先閲覧権」として月額課金を回収する',
      ],
      coldOutreachTemplate: '【貴社サービスの売却可能性に関するご相談】〇〇様、突然のご連絡失礼いたします。貴社が運営されているSaaSについて、弊社プラットフォームに登録されている事前審査済みバイヤー（現在30社以上）が買収に関心を示しております。手数料ゼロで匿名査定が可能です。',
    },
    temporal: {
      foundedYear: 2020,
      initialTractionPeriod: '2020年夏 (MicroAcquire立ち上げ期)',
      dataSnapshotPeriod: '2024-2026年 (取扱高累計数億ドル規模)',
      viabilityStatus: 'MATURED_MOAT',
      viabilityLabel: '先行者独占（両面市場ネットワーク効果）',
      eraContext: 'コロナ禍でのリモートワーク拡大とインディーハッカー・マイクロSaaSブーム。個人の事業買収（Searcher / Small PE）が一般化した時代。',
      currentViabilityAnalysis: 'マイクロSaaS領域での知名度と流動性を独占しているため正面突破は不可能。別ニッチ（YouTubeチャンネル売買、医療クリニック承継、AIエージェント売買）への垂直展開のみ勝機あり。',
    },
  },

  // 3. 404 Media
  {
    id: 'ent_404media_67f4bdf34107c01d26ad',
    ticker: '404MEDIA',
    name: '404 Media',
    legalEntity: '404 Media LLC',
    tagline: '「他人のコピペSEO記事」が溢れるWebを嘲笑い、AIやハッキングの生々しい一次スクープだけを配信して読者直接課金で年商1.8億円抜く独立記者カルテル',
    sector: 'CONTENT_MEDIA',
    scale: 'SMALL_TEAM',
    founder: 'Jason Koebler, Emanuel Maiberg, Samantha Cole, Joseph Cox',
    country: 'US',
    url: 'https://www.404media.co',
    verifiedBadge: true,
    growthRateYoY: 85.0,
    architecturePattern: '知恵の関所',
    pipelineStack: 'Ghost CMS × Stripe × 4人の調査報道記者',
    targetPainWallet: 'テック業界ウォッチャー・セキュリティ専門家の「AI生成ゴミ記事への嫌悪感」と真実への渇望',
    tags: ['独立系メディア', '一次スクープ', '有料サブスク', 'Ghost基盤', '粗利90%', '反広告'],
    pnl: {
      monthlyRevenue: 15000000,
      cogs: 1000000,
      grossProfit: 14000000,
      grossMargin: 93.3,
      operatingExpenses: {
        serverAndApi: 300000,
        advertising: 0,
        subcontracting: 800000,
        toolsAndSaaS: 400000,
        other: 500000,
      },
      operatingProfit: 12000000,
      operatingMargin: 80.0,
      estimatedAnnualNetProfit: 144000000,
      financialStatus: 'REPORTED',
      isRevenueUnconfirmed: false,
      isMarginUnconfirmed: false,
      revenueLabel: '有料会員数万人・年商約$1M+（初年度黒字化達成）',
    },
    evidenceCards: [
      {
        id: 'ev_404media_loot_blueprint',
        type: 'LOOT_BLUEPRINT',
        title: '【略奪転用】大手メディア崩壊の残骸から専門記者4人で独立し、広告ゼロ・読者課金で年商1億円抜く配管',
        badge: '略奪転用方程式',
        evidenceStatus: 'VERIFIED',
        punchline: '広告バナーとSEOコピペに依存した大手メディアが自爆する中、「取材力のある4人」が読者直接課金（月$10）に絞ることで、固定費ゼロ・粗利90%の不沈艦を組む。',
        details: [
          '【Step 1: 大手メディアの自爆の特定】: ViceやBuzzFeedがPV至上主義とVCマネーの暴走で破産した際、解雇された敏腕記者4人が即日結託。',
          '【Step 2: 取材記事のペイウォール化】: 導入部と概要は一般公開してSNSで拡散させ、核心の調査証拠・内部資料・独自取材部分は月額$10の会員限定にする。',
          '【Step 3: 広告完全排除のブランディング】: 広告主への忖度やバナーによる表示遅延を完全撤廃し、「独立したジャーナリズムを守る支援者」として読者の誇りに課金させる。',
        ],
        codeSnippet: '// Ghost CMSの会員ティアによるペイウォール制御（一次取材スクープの有料読者限定化）\n{{#if @member.paid}}\n  {{content}} <!-- スクープ全文・内部リーク音声・告発資料 -->\n{{else}}\n  {{excerpt}} <!-- 導入部のみ表示 -->\n  <div class="paywall-cta">404 Mediaの独自調査報道を支援するために月額$10で続きを読む</div>\n{{/if}}',
        sourceNote: '404 MediaのGhostプラットフォーム構成と公開財務報告から抽出した転用設計図',
      },
      {
        id: 'ev_404media_crime',
        type: 'THE_CRIME',
        title: '広告代理店と中間搾取を完全切除し、読者からの直接会費だけで記者1人あたり年収2,000万円以上を手残りさせる構造',
        badge: '身も蓋もない真実',
        evidenceStatus: 'VERIFIED',
        punchline: '経営陣や営業マン、巨大オフィスを全廃し、4人の記者だけでGhost上に記事を投稿するだけで年間1億円以上の純利益を山分けする。',
        details: [
          '元Vice（Motherboard）の看板記者が、会社が倒産した瞬間に自分たちの固定ファン読者をそのまま引き連れて独立。',
          'AI犯罪、違法トラッキング、サイバー犯罪の一次リーク取材に絞り込み、他社が絶対に真似できない独自性を担保。',
          '大口サポーター向けに年間$200〜$1,000の「パトロン支援枠」を設け、熱狂的ファンから高単価を回収。',
        ],
      },
    ],
    operations: {
      teamSize: 4,
      weeklyHours: 50,
      initialCapitalRequired: 0,
      automationLevel: 75,
      primaryChannels: ['記者個人Twitter(X)フォロワー', '一次スクープによる他メディア被リンク', 'Ghost有料ニュースレター'],
      toolStack: [
        { name: 'Ghost(Pro)', category: 'CMS/ニュースレター', monthlyCost: 40000, purpose: 'オープンソースの有料サブスク配信基盤' },
        { name: 'Stripe', category: '決済', monthlyCost: 450000, purpose: '定期購読課金の自動処理' },
        { name: 'Signal / SecureDrop', category: '内部告発窓口', monthlyCost: 0, purpose: 'ハッカー・内部関係者からの極秘情報受付' },
      ],
    },
    strategy: {
      blindspot: '大手メディアは「PVを稼いでプログラマティック広告を貼る」ビジネスモデルに縛られており、コストのかかる地道な調査報道を次々と切り捨てていた。',
      moatType: 'BRAND_PRESTIGE',
      moatDescription: '「FBIやサイバー犯罪者すら恐れる独自取材力」という記者の個人的名声。AIには逆立ちしても生成できない「一次現場の生情報」が最大の堀。',
      incumbentDilemma: '大手出版社は営業部や役員報酬などの巨大な固定費を抱えているため、数万人の有料読者（年商数億円）では会社が維持できず参入できない。',
      secretInsight: '世の中に溢れる記事の99%が「他人の記事の焼き直し」である時代において、真の「一次情報・独自取材」には読者が自腹を切って月千円を払う猛烈な希少価値がある。',
      initialTraction: [
        'Vice解散直後に創業者4人が個人Twitter（計数十万フォロワー）で独立を一斉告知',
        'ローンチ初週にAIポルノとサイバー犯罪に関する独占スクープを連発し、初速で数千人の有料会員を獲得',
        '404 Mediaの独自記事がThe Vergeやニューヨーク・タイムズに引用され被リンクと権威性を自動蓄積',
      ],
      actionPlaybook: [
        'Step 1: 大手企業がリストラで手放した「特定領域の超一流プレイヤー（編集者、アナリスト、研究者）」を3〜4人集める',
        'Step 2: 広告・スポンサーを完全拒否し、Ghost等のセルフサーブ基盤で有料サブスクを開設する',
        'Step 3: 「業界の闇を暴く一次資料」だけを週に1本公開し、読者の知的好奇心と業界防衛本能を突いて課金させる',
      ],
      coldOutreachTemplate: '【貴社セキュリティチーム向け極秘インシデント事例レターのご案内】〇〇様、突然のご連絡失礼いたします。昨今のダークウェブにおける企業認証情報流出の手口について、独自潜入取材に基づく一次レポートをお届けしております。月額$10で最新の攻撃手口の分析ログを即日ご確認いただけます。',
    },
    temporal: {
      foundedYear: 2023,
      initialTractionPeriod: '2023年夏 (Vice破産直後ローンチ)',
      dataSnapshotPeriod: '2024-2026年 (年商$1M突破期)',
      viabilityStatus: 'RISING_WAVE',
      viabilityLabel: '急上昇（AIコピペ汚染への反動）',
      eraContext: '生成AIによるWebの低品質コピペ記事の氾濫と、伝統的デジタルメディアの大量レイオフ・崩壊期。',
      currentViabilityAnalysis: 'Google検索がAI生成スパムで崩壊したことで、信頼できる人間の記者による直接配信ニュースレターの価値は過去最高に跳ね上がっている。再現性は極めて高い。',
    },
  },

  // 4. StockX
  {
    id: 'ent_stockx_347557ecc72cc6a4fbba',
    ticker: 'STOCKX',
    name: 'StockX',
    legalEntity: 'StockX LLC',
    tagline: '「eBayの偽物スニーカー」に怯えるZ世代の虚栄心を突き、すべての荷物を自社鑑定センターに集約して取引額の10%を自動徴収する株取引型市場',
    sector: 'PHYSICAL_ASSET',
    scale: 'ENTERPRISE',
    founder: 'Josh Luber, Dan Gilbert, Greg Schwartz, Chris Kaufman',
    country: 'US',
    url: 'https://stockx.com',
    verifiedBadge: true,
    growthRateYoY: 20.0,
    architecturePattern: '水門寄生',
    pipelineStack: '株式市場型Bid/Ask板取引 × グローバル真贋鑑定ハブ × 匿名自動マッチング',
    targetPainWallet: 'スニーカー・ストリートウェア購入者の「偽物を掴まされる恐怖（数百ドルの損失と社会的恥辱）」',
    tags: ['マーケットプレイス', '真贋鑑定', '板取引', 'スニーカー', '高単価流通', '取引手数料'],
    pnl: {
      monthlyRevenue: 4000000000,
      cogs: 1800000000,
      grossProfit: 2200000000,
      grossMargin: 55.0,
      operatingExpenses: {
        serverAndApi: 200000000,
        advertising: 800000000,
        subcontracting: 300000000,
        toolsAndSaaS: 100000000,
        other: 400000000,
      },
      operatingProfit: 400000000,
      operatingMargin: 10.0,
      estimatedAnnualNetProfit: 4800000000,
      financialStatus: 'ESTIMATED',
      isRevenueUnconfirmed: false,
      isMarginUnconfirmed: false,
      revenueLabel: '年間取扱高GMV 約3,000億円（手数料テイクレート約12-14%）',
    },
    evidenceCards: [
      {
        id: 'ev_stockx_loot_blueprint',
        type: 'LOOT_BLUEPRINT',
        title: '【略奪転用】偽物リスクの高い二次流通市場に「物理鑑定ハブ」を挟み込み取引の10%を中抜きする配管',
        badge: '略奪転用方程式',
        evidenceStatus: 'VERIFIED',
        punchline: '売り手と買い手を直接つなぐのをやめ、荷物を一度自社倉庫へ送らせて「鑑定済みの緑タグ」を貼るだけで、eBayから客を全量強奪できる。',
        details: [
          '【Step 1: 偽物恐怖の特定】: 限定スニーカー市場で「定価2万円の靴が10万円で転売されるが、届くまで本物か分からない」という強烈な恐怖を特定。',
          '【Step 2: 株式市場型（Bid/Ask）の導入】: 写真出品や商品説明を廃止し、「品番とサイズ」だけで株のように買値・売値を提示して自動約定させる。',
          '【Step 3: 鑑定水門の設置】: 成約した商品をデトロイト等の自社鑑定センターに送らせ、専門鑑定士がチェックして合格証（Verified Authentic）を付けて発送。',
        ],
        codeSnippet: '// 取引マッチングと鑑定ステータス遷移のロジック\n// 買い手からの入金完了 ➔ 売り手に発送指示 ➔ 自社ハブ到着 ➔ 鑑定合格 ➔ 売り手へ着金＋購入者へ発送\nasync function processTransaction(order) {\n  await holdBuyerFundsInEscrow(order);\n  await verifyItemInAuthenticationCenter(order.itemId);\n  await attachGreenVerificationTag(order.itemId);\n  await releaseSellerPayoutMinusFee(order.sellerId, order.price * 0.90); // 手数料10%控除\n}',
        sourceNote: 'StockXの板取引マッチングおよび物理真贋鑑定プロセスから抽出した転用設計図',
      },
      {
        id: 'ev_stockx_crime',
        type: 'THE_CRIME',
        title: '自らは在庫を1足も持たず、熱狂するコレクターの虚栄心の間で年間数百億円の手数料を吸い上げる水門ビジネス',
        badge: '身も蓋もない真実',
        evidenceStatus: 'VERIFIED',
        punchline: '「偽物を買いたくない」という人間の損失回避恐怖を人質にし、売り手から9%、買い手から3%の手数料を両面から自動天引きする。',
        details: [
          'eBayが長年放置していた「個人間取引の真贋トラブル」を、物理的な検品オペレーションを挟むことで完全解決。',
          '出品者は写真を撮る必要すらなく、製品コードと希望価格を入力するだけで1秒出品。',
          'NBAクリーブランド・キャバリアーズのオーナーであるダン・ギルバートの巨額資本をテコに鑑定物流拠点を世界展開。',
        ],
      },
    ],
    operations: {
      teamSize: 1500,
      weeklyHours: 40,
      initialCapitalRequired: 500000000,
      automationLevel: 65,
      primaryChannels: ['スニーカーヘッズ・コレクターコミュニティ', 'NBA・セレブ・インフルエンサー提携', 'スニーカー相場チャートSEO'],
      toolStack: [
        { name: 'カスタムマッチングエンジン', category: 'コアシステム', monthlyCost: 15000000, purpose: 'ミリ秒単位のBid/Askリアルタイム約定' },
        { name: '自社グローバル鑑定ハブ', category: '物理オペレーション', monthlyCost: 1200000000, purpose: '世界各拠点での現物検品・真贋鑑定' },
        { name: 'Stripe / Adyen', category: 'グローバル決済', monthlyCost: 120000000, purpose: '多通貨決済と不正チャージバック防止' },
      ],
    },
    strategy: {
      blindspot: 'eBayやAmazonは「在庫を持たず、荷物にも触らない純粋なITプラットフォーム」に固執していたため、自社で倉庫を構えて荷物を開けて検品する泥臭いオペレーションを毛嫌いしていた。',
      moatType: 'CORNERED_RESOURCE',
      moatDescription: '世界中の鑑定センターと熟練鑑定士ネットワーク、そして数千万件の真贋判定データベース。ソフトウェア企業が真似できない物理的オペレーションの要塞。',
      incumbentDilemma: 'eBayが同様の鑑定サービスを導入しようとしても、既存の何千万もの無検品セラーとの利害調整や配送遅延が発生し、即座の対抗ができなかった。',
      secretInsight: '高額スニーカーを買う人間は「靴」を買っているのではない。「本物を履いているという誇りと社会的優越感」を買っている。だから鑑定タグそのものがステータスシンボルになる。',
      initialTraction: [
        '創業者Josh LuberがeBayのスニーカー取引データをスクレイピングして価格ガイドブック「Campless」を作りコレクターの支持を獲得',
        'NBAオーナーのダン・ギルバートを巻き込み、デトロイトの遊休不動産を活用して初期鑑定拠点を急造',
        '「スニーカーの株取引所」という強烈なメタファーでメディア取材を総なめにした',
      ],
      actionPlaybook: [
        'Step 1: 偽物が横行し、相場が不透明な高単価ホビー（トレカ、高級時計、限定フィギュア、ヴィンテージ古着）を特定する',
        'Step 2: 写真出品を廃止し、「商品型番×状態」で株のように価格が動くリアルタイム相場チャートを作る',
        'Step 3: 自前で鑑定ハブを1箇所立ち上げ、鑑定合格の物理シール/タグを同梱して発送するオペレーションを組む',
      ],
      coldOutreachTemplate: '【貴社スニーカー在庫を写真撮影なしで即時現金化できる取引所のご案内】〇〇様、突然のご連絡失礼いたします。StockXでは現在、貴社がお持ちの限定モデル（Air Jordan 1等）に数十件の購入指値（Bid）が入っております。写真を撮る必要なく、希望価格で即日約定・自社ハブへの発送のみで現金化いただけます。',
    },
    temporal: {
      foundedYear: 2015,
      initialTractionPeriod: '2016-2017年 (スニーカーリセール爆発期)',
      dataSnapshotPeriod: '2024-2026年 (取扱高3,000億円超規模)',
      viabilityStatus: 'MATURED_MOAT',
      viabilityLabel: '巨大先行者堀（物理物流・鑑定拠点）',
      eraContext: 'ストリートファッションとハイブランドの融合、Z世代の転売（リセール）文化の爆発的台頭。',
      currentViabilityAnalysis: 'スニーカー市場自体は成熟したが、トレカや高級時計など別カテゴリへの水平展開が進行中。個人が同じ規模を作るのは不可能だが、特定ニッチ（ポケモンカード特化、レトロゲーム鑑定）での縮小コピーは現在も極めて有効。',
    },
  },

  // 5. Gridfiti
  {
    id: 'ent_case06_1deb3d9c4c007a003f3c',
    ticker: 'GRIDFITI',
    name: 'Gridfiti',
    legalEntity: 'Gridfiti Media',
    tagline: '「自分のデスクをエモくしたい」リモートワーカーの自己顕示欲をPinterestで煽り、Notionテンプレートとデスク家具のアフィリエイトで年商7,000万円抜く手口',
    sector: 'CONTENT_MEDIA',
    scale: 'SOLO',
    founder: '創業者（インディーパブリッシャー）',
    country: 'CA',
    url: 'https://gridfiti.com',
    verifiedBadge: true,
    growthRateYoY: 30.0,
    architecturePattern: '知恵の関所',
    pipelineStack: 'WordPress × Pinterest/Instagramキュレーション × Amazonアフィリエイト/Gumroad',
    targetPainWallet: '在宅勤務エンジニア・デザイナーの「退屈な作業環境への不満」と美的自己顕示欲',
    tags: ['デスク環境', 'Notionテンプレート', 'Pinterest集客', 'アフィリエイト', '粗利90%', '完全1人運営'],
    pnl: {
      monthlyRevenue: 6000000,
      cogs: 300000,
      grossProfit: 5700000,
      grossMargin: 95.0,
      operatingExpenses: {
        serverAndApi: 50000,
        advertising: 0,
        subcontracting: 300000,
        toolsAndSaaS: 100000,
        other: 250000,
      },
      operatingProfit: 5000000,
      operatingMargin: 83.3,
      estimatedAnnualNetProfit: 60000000,
      financialStatus: 'ESTIMATED',
      isRevenueUnconfirmed: false,
      isMarginUnconfirmed: false,
      revenueLabel: '推定月商約600万円（Notionテンプレート販売＋高単価アフィリエイト）',
    },
    evidenceCards: [
      {
        id: 'ev_gridfiti_loot_blueprint',
        type: 'LOOT_BLUEPRINT',
        title: '【略奪転用】自前で製品を作らず、Pinterestの「美意識」画像で集客しNotion・デスク家具で月利500万円抜く配管',
        badge: '略奪転用方程式',
        evidenceStatus: 'VERIFIED',
        punchline: '自分で家具やキーボードを作る必要は一切ない。InstagramやRedditの「映えるデスク環境」を美しくまとめ、AmazonアフィリとGumroadのNotionテンプレートへ流すだけで粗利95%が成立する。',
        details: [
          '【Step 1: エモい画像によるPinterestハック】: Pinterestで「Aesthetic Desk Setup」「Minimalist Workspace」の画像を毎日ピン留めし、月間数百万人への無料リーチを獲得。',
          '【Step 2: アイテムの因数分解とアフィリエイト】: 画像に写っているモニター、キーボード、デスクマット、照明をすべて特定し、Amazonやメーカーのアフィリエイトリンクを配置。',
          '【Step 3: デジタル商品（Notionテンプレート）の直販】: 無料のデスク記事を見に来たユーザーに、自作または提携した$10〜$30のNotionテンプレートを併売して粗利100%の現金を回収。',
        ],
        codeSnippet: '// PinterestリッチピンとGumroadウィジェットの埋め込み配管\n<a href="https://gridfiti.gumroad.com/l/aesthetic-notion-dashboard" class="gumroad-button">\n  エモいNotionダッシュボードテンプレートを$19でダウンロード\n</a>',
        sourceNote: 'GridfitiのWebサイト構造、Pinterestトラフィック導線、Gumroad販売リンクから抽出した転用設計図',
      },
      {
        id: 'ev_gridfiti_crime',
        type: 'THE_CRIME',
        title: '他人のデスクの写真を並べてリンクを貼っているだけで完全1人で年商7,000万円・手残り6,000万円を抜く手口',
        badge: '身も蓋もない真実',
        evidenceStatus: 'VERIFIED',
        punchline: '自社製品の開発費ゼロ、在庫リスクゼロ、物流オペレーションゼロ。人の承認欲求で投稿されたデスク写真をキュレーションするだけで大企業の部長の何倍もの現金を手元に残す。',
        details: [
          '月間数百万円の売上のうち、サーバー代は月数千円〜数万円。利益率85%超の圧倒的キャッシュフロー。',
          'Notionという巨大トレンドに初期から乗り、「Notionテンプレートまとめ」「Notionの使い方」でSEO上位を独占。',
          'デスクツアー動画やブログのリンクを踏んだユーザーが、後からAmazonで別の高額家電を買っても紹介料が入るアフィリエイトのCookie効果を活用。',
        ],
      },
    ],
    operations: {
      teamSize: 1,
      weeklyHours: 20,
      initialCapitalRequired: 0,
      automationLevel: 95,
      primaryChannels: ['Pinterest ビジュアル検索ピン', 'Instagram デスク写真キュレーション', 'Notion活用・デスク環境SEO'],
      toolStack: [
        { name: 'WordPress', category: 'CMS', monthlyCost: 10000, purpose: '高SEO最適化ブログメディア' },
        { name: 'Pinterest Business', category: '集客配管', monthlyCost: 0, purpose: 'ビジュアル検索からの爆発的無料トラフィック' },
        { name: 'Gumroad', category: 'デジタル決済', monthlyCost: 0, purpose: 'Notionテンプレートの直販（販売時10%手数料）' },
        { name: 'Amazon Associates', category: 'アフィリエイト', monthlyCost: 0, purpose: 'PC周辺機器・家具の紹介料回収' },
      ],
    },
    strategy: {
      blindspot: '大手ガジェットメディアは「スペック解説・ベンチマーク測定」ばかりに注力し、「部屋全体の美しさ・エモさ（Aesthetic）」という感情的価値を完全に無視していた。',
      moatType: 'BRAND_PRESTIGE',
      moatDescription: '「Gridfitiを見れば最もクールなデスク環境が分かる」というデザイン感度の高いリモートワーカーの間での認知と、Pinterestでの圧倒的なピン蓄積。',
      incumbentDilemma: '大手メディアは記事を大量生産するライター人件費を抱えているため、1人の個人が美意識を極限まで尖らせて作るキュレーションサイトには世界観で勝てない。',
      secretInsight: '在宅ワーカーがキーボードやデスクマットを買う理由は「作業効率」ではない。「自分の部屋をおしゃれにして、TwitterやInstagramにアップして自己肯定感を満たしたい」という虚栄心である。',
      initialTraction: [
        'TumblrやInstagramでエモい部屋の写真をひたすらキュレーションして初期フォロワーを獲得',
        'Notionがブームになり始めた2020年に、いち早く「Notion Setups」のカテゴリを作って特化記事を連投',
        '海外のReddit（r/macsetups, r/battlestations）に自然な形でまとめ記事を投稿しバズを獲得',
      ],
      actionPlaybook: [
        'Step 1: 「スペック」ではなく「見た目・美意識（Aesthetic）」で選ばれるニッチ市場（デスク、観葉植物、コーヒー器具、キャンプギア）を選ぶ',
        'Step 2: Pinterestアカウントを開設し、高解像度のエモいレイアウト画像を毎日投稿して流入の泉を作る',
        'Step 3: 画像に写っている製品のアフィリリンクと、その世界観に合わせた安価なデジタル商品（PDFガイド、テンプレート）をセットで売る',
      ],
      coldOutreachTemplate: '【貴社デスク製品のGridfiti掲載（月間30万人のデスク好きエンジニア向け）のご案内】〇〇様、突然のご連絡失礼いたします。弊社のデスク環境メディアGridfitiにて、貴社のキーボード/モニターアームを「2026年ベストミニマルセットアップ」として特集させていただきたくご連絡いたしました。',
    },
    temporal: {
      foundedYear: 2020,
      initialTractionPeriod: '2020年春 (リモートワーク＆Notion特需)',
      dataSnapshotPeriod: '2024-2026年 (月商600万円規模)',
      viabilityStatus: 'ACTIVE_PLAYBOOK',
      viabilityLabel: '現在も有効（Pinterest×デジタル商品）',
      eraContext: 'コロナ禍での在宅勤務強制と、Notionの爆発的普及。デスク環境にお金をかけるエンジニアが激増した時代。',
      currentViabilityAnalysis: 'リモートワークは定着しており、Pinterestからのビジュアル流入とデジタル商品販売の手法は現在も完全に機能する。AIを使って画像生成や記事作成を効率化すれば、さらに低労力で再現可能。',
    },
  },
];
