import type { FinancialEntity } from '../src/platform/types/terminal';

export const REFINED_STATISTICAL_SAMPLE_ENTITIES: FinancialEntity[] = [
  // 1. Plausible Analytics
  {
    id: 'ent_company_7398a06ad48e5fb1ede7',
    ticker: 'PLAUSIBLE',
    name: 'Plausible Analytics',
    legalEntity: 'Plausible Insights OÜ',
    tagline: '「GA4が重すぎて客が逃げる」「Cookie同意バナーが離脱を生む」Web担当者の限界ストレスを突き、コード1行で年間4億円抜く完全独立系オープンソース解析',
    sector: 'NICHE_SAAS',
    scale: 'SMALL_TEAM',
    founder: 'Uku Taht, Marko Saric',
    country: 'EE',
    url: 'https://plausible.io',
    verifiedBadge: true,
    growthRateYoY: 45.0,
    architecturePattern: 'クッキーレス軽量代替',
    pipelineStack: 'Elixir/Phoenix × ClickHouse × AGPLオープンソース',
    targetPainWallet: 'Web担当者の胃痛（GA4の難解さ、Cookie同意バナーによるCV低下、GDPR罰則恐怖）',
    tags: ['プライバシー重視', '脱Google', 'オープンソースSaaS', 'ノーコード導入', '粗利85%超', '完全ブートストラップ'],
    pnl: {
      monthlyRevenue: 35000000,
      cogs: 3500000,
      grossProfit: 31500000,
      grossMargin: 90.0,
      operatingExpenses: {
        serverAndApi: 2500000,
        advertising: 0,
        subcontracting: 1000000,
        toolsAndSaaS: 500000,
        other: 500000,
      },
      operatingProfit: 27000000,
      operatingMargin: 77.1,
      estimatedAnnualNetProfit: 324000000,
      financialStatus: 'REPORTED',
      isRevenueUnconfirmed: false,
      isMarginUnconfirmed: false,
      revenueLabel: '公式開示ARR $2.8M（21,000社有料購読）',
      sourceDoc: 'Plausible公式開示（21,000社有料会員・ARR情報、既存収集カード）',
    },
    evidenceCards: [
      {
        id: 'ev_plausible_loot_blueprint',
        type: 'LOOT_BLUEPRINT',
        title: '【略奪転用】巨大独占無料ツール（Google等）が自爆した隙間に「1/10の軽量版」を差し込み粗利80%抜く配管',
        badge: '略奪転用方程式',
        evidenceStatus: 'VERIFIED',
        punchline: '大手が規制や多機能化で自爆してユーザーが苦痛を叫んでいる時、「機能を1/10にし、同意バナーを不要にする」だけで有料でも喜んで客が雪崩れ込む。',
        details: [
          '【Step 1: 大手の自爆の特定】: Google AnalyticsがGA4へ強制移行し、UIが劇的に悪化＋EUのGDPRでCookie同意バナーが必須化された苦痛を特定。',
          '【Step 2: 1KBスクリプトとオープンソース】: 個人情報を一切取らない1KB未満の超軽量スクリプトを開発し、AGPLでコード公開して開発者の信頼を獲得。',
          '【Step 3: 広告費ゼロの比較SEO】: 「Google Analyticsの代替」「GA4のCookieレス移行」という比較記事だけでオーガニック流入を独占し、月額$9〜から課金。',
        ],
        codeSnippet: '// 軽量クッキーレス計測スクリプトの埋め込みエンドポイント設計\n// 顧客のHTMLヘッダーに1行追加させるだけで、セッションストレージやクッキーを一切使わずハッシュ化IPで日次ユニークのみ集計\n<script defer data-domain="yourdomain.com" src="https://plausible.io/js/script.js"></script>',
        sourceNote: 'Plausibleの公式開示（21,000社有料会員、広告費$0成長ログ）から抽出した構造転用設計図',
      },
      {
        id: 'ev_plausible_crime',
        type: 'THE_CRIME',
        title: '広告費・営業費0円で年商4億円・営業利益率77%を叩き出すプライバシー要塞',
        badge: '身も蓋もない真実',
        evidenceStatus: 'VERIFIED',
        punchline: 'Googleが無料で配るGA4の使いにくさにブチ切れたエンジニア・マーケターから、月額$9〜$100を毎月全自動で徴収する。',
        details: [
          '外部調達（VC）ゼロ、広告出稿費ゼロ、アフィリエイト報酬ゼロ。完全な自己資金（Self-funded）で10人体制。',
          'EUのGDPR規制により「Cookie同意バナーを出さないといけない」という企業サイトの美観・離脱ペインを完全切除。',
          'Basecamp, Ghost, Hugging Face, Harvard Universityなどのビッグネームが公式採用し社会的証明が極大化。',
        ],
      },
      {
        id: 'ev_plausible_genesis',
        type: 'DIRTY_GENESIS',
        title: '創業者1人の孤独な開発からHacker News炎上をバネにした初動制圧',
        badge: '初期ゲリラ戦ログ',
        evidenceStatus: 'VERIFIED',
        punchline: '「Googleにデータを渡したくない」開発者心理に火をつけ、Hacker Newsトップ掲載から初動100人を獲得。',
        details: [
          '2018年にエストニアのエンジニアUku Tahtが1人で創業。当初は鳴かず飛ばずで月商数十ドル。',
          '2020年にMarko Saricが合流し、「GA4 vs Plausible」の辛口比較記事をHacker NewsやRedditで連打。',
          'オープンソースコミュニティで「反巨大IT（De-Google）」のシンボルとして祭り上げられ、口コミのみで急拡大。',
        ],
      },
    ],
    operations: {
      teamSize: 10,
      weeklyHours: 35,
      initialCapitalRequired: 0,
      automationLevel: 90,
      primaryChannels: ['Hacker News / Reddit 口コミ', 'GA4批判SEO比較記事', 'オープンソースGitHubリポジトリ'],
      toolStack: [
        { name: 'Elixir/Phoenix', category: 'バックエンド', monthlyCost: 0, purpose: '秒間数万リクエストを低メモリで処理' },
        { name: 'ClickHouse', category: '分析データベース', monthlyCost: 800000, purpose: '数億行のアクセスログを超高速集計' },
        { name: 'Hetzner', category: 'ホスティング', monthlyCost: 600000, purpose: 'EU拠点のベアメタルサーバーによるコスト圧縮' },
        { name: 'Stripe', category: '決済', monthlyCost: 1050000, purpose: 'グローバル定期課金決済（手数料約3%）' },
      ],
    },
    strategy: {
      blindspot: 'Googleは自社の広告ビジネス（ターゲティング広告）を守るために個人データの追跡をやめられず、Cookie不要のシンプル解析を出せなかった。',
      moatType: 'COUNTER_POSITIONING',
      moatDescription: 'Google Analyticsは広告エコシステムの都合上、複雑怪奇なイベント設計と個人トラッキングが必須。Plausibleは「広告をやらない」という前提そのものが堀になっている。',
      incumbentDilemma: 'GoogleがPlausibleのような軽量・Cookieレスツールを無償提供すると、Googleの主たる収益源であるパーソナライズ広告の精度が落ちて自爆する。',
      secretInsight: 'サイト運営者の95%は「PV数・参照元・閲覧デバイス」の3つしか見ていない。GA4の何百もある複雑なメニューは顧客の95%にとって騒音でしかない。',
      initialTraction: [
        'Hacker Newsで「Google Analyticsのオープンソース代替を作った」と投稿し1,000 Upvotes獲得',
        '「なぜ私たちはGoogle Analyticsを削除したのか」という過激なブログ記事でSEO流入を独占',
        '自社のMRR、PV数、サーバー費用を自社サイト上でリアルタイム全公開（オープンメトリクス）',
      ],
      actionPlaybook: [
        'Step 1: 誰もが使っている巨大無料ツールの「最近の改悪（UI複雑化・法規制対応）」の怨嗟を調査する',
        'Step 2: 機能を1/10に削り、1分でセットアップできるオープンソース版を公開する',
        'Step 3: ホスティング・保守が面倒な層向けに月額$9〜のマネージドクラウドSaaSを提供し課金化する',
      ],
      coldOutreachTemplate: '【貴社サイトのCookie同意バナーを今夜撤去できる軽量解析のご案内】〇〇様、突然のご連絡失礼いたします。現在貴社サイトで表示されているCookieバナーによる訪問者の離脱にお悩みではありませんか？Plausibleは1KBのコード1行で、Cookieバナー不要・EU法完全準拠のアクセス解析を提供します。',
    },
    temporal: {
      foundedYear: 2018,
      initialTractionPeriod: '2020年春 (GA4不満噴出期)',
      dataSnapshotPeriod: '2024-2026年 (ARR $2.8M規模)',
      viabilityStatus: 'ACTIVE_PLAYBOOK',
      viabilityLabel: '現在も有効（脱GA4の受け皿）',
      eraContext: 'EUのGDPR施行とGoogleのGA4強制移行による混乱期。Cookie同意ポップアップへのユーザーの嫌悪感が頂点に達していた。',
      currentViabilityAnalysis: 'プライバシー規制は年々世界中で強化されており、クッキーレス解析の需要は極めて堅牢。自前でインフラを抱えるサーバーコストの管理さえできれば長期高収益を維持できる。',
    },
  },

  // 2. Acquire.com
  {
    id: 'ent_acquirecom_4e8247fa7bf75d8b8584',
    ticker: 'ACQUIRE',
    name: 'Acquire.com',
    legalEntity: 'Acquire.com, Inc.',
    tagline: '「ブローカーの手数料15%と1年の売却交渉」に絶望したSaaS創業者の胃痛を突き、事前審査済みバイヤー50万人へ直結して月商1.2億円抜く売買水門番',
    sector: 'FINTECH_INFRA',
    scale: 'SCALEUP',
    founder: 'Andrew Gazdecki',
    country: 'US',
    url: 'https://acquire.com',
    verifiedBadge: true,
    growthRateYoY: 60.0,
    architecturePattern: '売買水門番',
    pipelineStack: 'Next.js × Stripe × 独自エスクロー決済・NDA自動締結',
    targetPainWallet: 'SaaS創業者の焦燥（バーンレート限界・売却の不透明性）と買い手の案件飢餓',
    tags: ['M&Aプラットフォーム', 'マイクロSaaS', '両面市場', '前金サブスク', '高単価取引', '取引手数料'],
    pnl: {
      monthlyRevenue: 120000000,
      cogs: 12000000,
      grossProfit: 108000000,
      grossMargin: 90.0,
      operatingExpenses: {
        serverAndApi: 3500000,
        advertising: 8000000,
        subcontracting: 15000000,
        toolsAndSaaS: 2500000,
        other: 6000000,
      },
      operatingProfit: 73000000,
      operatingMargin: 60.8,
      estimatedAnnualNetProfit: 876000000,
      financialStatus: 'ESTIMATED',
      isRevenueUnconfirmed: false,
      isMarginUnconfirmed: false,
      revenueLabel: '推定年間売上$10M+（買い手パス＋成約手数料4-6%）',
      sourceDoc: 'Acquire.com公開料金体系・取引手数料モデル（既存収集カード、一次数値の突合は未完了）',
      estimationLogic: '入力: 買い手パス価格と成約手数料モデル、既存カードの取引規模推定。月商=価格×推定契約数＋成約手数料、粗利益=月商−cogs、営業利益=粗利益−(serverAndApi＋advertising＋subcontracting＋toolsAndSaaS＋other)、年間純利益=営業利益×12。全て推計であり、会社単体の監査済みP&Lではない。',
    },
    evidenceCards: [
      {
        id: 'ev_acquire_loot_blueprint',
        type: 'LOOT_BLUEPRINT',
        title: '【略奪転用】閉鎖的で高額な仲介業をセルフサーブ化し「買い手から前金サブスクを抜く」関所モデル',
        badge: '略奪転用方程式',
        evidenceStatus: 'VERIFIED',
        punchline: '売り手に無料・格安で出品させ、案件情報を見たい買い手に年間$390〜$780の前金パスを課金。成約時にも数%抜く二重の手数料構造を作る。',
        details: [
          '【Step 1: 供給（売り手）のハードル撤廃】: 既存のM&A仲介が門前払いする「年商100万〜数千万円の小規模SaaS」を、初期費用ゼロ・Stripe連携だけで出品可能にする。',
          '【Step 2: 買い手側の前金サブスク化】: 投資家や連続起業家向けに「新着優良案件への即時アクセス権」として年間$390（Platinum）を前金で集金。',
          '【Step 3: エスクローと成約手数料】: 買収交渉から資金移動・契約書雛形までをプラットフォーム内で完結させ、クロージング時に4〜6%を自動控除。',
        ],
        codeSnippet: '// 買い手プレミアム権限の認可ガード（年額パス購入者のみ案件のP&L詳細・URLを閲覧可能）\nif (!buyer.hasActivePass || buyer.passType === "FREE") {\n  return sanitizeListingForPublic(listing); // P&Lの生数字と会社名をマスク\n}\nreturn listing.getDeepDiligencePack();',
        sourceNote: 'Acquire.comの買い手サブスク価格体系と取引手数料モデルから抽出した転用設計図',
      },
      {
        id: 'ev_acquire_crime',
        type: 'THE_CRIME',
        title: '他人の作ったSaaSの売買を右から左へ流すだけで毎月1億円以上の現金を抜き取る手口',
        badge: '身も蓋もない真実',
        evidenceStatus: 'VERIFIED',
        punchline: '自分ではSaaSを開発・運用せず、他人が命を削って作ったSaaSの「売却の関所」に居座り、通行税を買い手と売り手の両方から二重取りする。',
        details: [
          '50万人以上の買い手データベースをテコに、売り手を完全に囲い込み。',
          '既存の投資銀行やM&A仲介が要求する着手金・固定月額・15%の法外な成功報酬を破壊。',
          '創業者Andrew Gazdecki自身の強烈なX（Twitter）発信力を最大の集客配管として活用。',
        ],
      },
    ],
    operations: {
      teamSize: 35,
      weeklyHours: 45,
      initialCapitalRequired: 10000000,
      automationLevel: 85,
      primaryChannels: ['創業者Twitter(X)発信', 'SaaS売却週刊ニュースレター', 'Product Hunt'],
      toolStack: [
        { name: 'Next.js', category: 'フロントエンド', monthlyCost: 50000, purpose: '高密度マーケットプレイスUI' },
        { name: 'Stripe Connect', category: 'エスクロー決済', monthlyCost: 3500000, purpose: '買収資金のエスクロー預託と手数料自動徴収' },
        { name: 'DocuSign API', category: '電子契約', monthlyCost: 800000, purpose: 'NDA（秘密保持契約）と売買契約の自動署名' },
      ],
    },
    strategy: {
      blindspot: '大手M&A仲介会社は手数料が数千万円取れる大型買収しか相手にせず、年商数千万円以下のマイクロSaaS市場を「相手にするだけ赤字」と見捨てていた。',
      moatType: 'NETWORK_EFFECT',
      moatDescription: '50万人の買い手がいるからSaaS創業者が集まり、SaaS出品数が多いから買い手が集まる。この巨大な両面流動性の引力場に競合は太刀打ちできない。',
      incumbentDilemma: '既存のM&Aブローカーは対面営業と手作業のデューデリジェンスに特化した組織を持っているため、数万円のサブスクやセルフサーブ仲介をやると自社の高単価プランを自爆させる。',
      secretInsight: '世の中には「新規でゼロから作るより、月商30万〜100万円出ているSaaSをサクッと買収して自分の集客力で伸ばしたい」余剰資金を持ったバイヤーが数百万人いる。',
      initialTraction: [
        '創業者AndrewがTwitterで「自分のSaaSを売りたい人はDMして」と呟き、初期の売り手10社を手作業でスプレッドシート管理',
        'Product Huntでローンチし、インディーハッカー界隈の話題を独占',
        '「今週売却されたSaaS一覧」のニュースレターを毎週配信して買い手を中毒化',
      ],
      actionPlaybook: [
        'Step 1: 取引金額が小さすぎて既存ブローカーが相手にしないニッチ資産（個人ブログ、小規模EC、Shopifyアプリ）を特定する',
        'Step 2: 売り手には完全無料で出品させ、スプレッドシートで案件を蓄積する',
        'Step 3: 案件を一覧化したニュースレターを作り、買い手から「優先閲覧権」として月額課金を回収する',
      ],
      coldOutreachTemplate: '【貴社サービスの売却可能性に関するご相談】〇〇様、突然のご連絡失礼いたします。貴社が運営されているSaaSについて、弊社プラットフォームに登録されている事前審査済みバイヤー（現在30社以上）が買収に関心を示しております。手数料ゼロで匿名査定が可能です。',
    },
    temporal: {
      foundedYear: 2020,
      initialTractionPeriod: '2020年夏 (MicroAcquire立ち上げ期)',
      dataSnapshotPeriod: '2024-2026年 (取扱高累計数億ドル規模)',
      viabilityStatus: 'MATURED_MOAT',
      viabilityLabel: '先行者独占（両面市場ネットワーク効果）',
      eraContext: 'コロナ禍でのリモートワーク拡大とインディーハッカー・マイクロSaaSブーム。個人の事業買収（Searcher / Small PE）が一般化した時代。',
      currentViabilityAnalysis: 'マイクロSaaS領域での知名度と流動性を独占しているため正面突破は不可能。別ニッチ（YouTubeチャンネル売買、医療クリニック承継、AIエージェント売買）への垂直展開のみ勝機あり。',
    },
  },

  // 3. 404 Media
  {
    id: 'ent_404media_67f4bdf34107c01d26ad',
    ticker: '404MEDIA',
    name: '404 Media',
    legalEntity: '404 Media LLC',
    tagline: '「他人のコピペSEO記事」が溢れるWebを嘲笑い、AIやハッキングの生々しい一次スクープだけを配信して読者直接課金で年商1.8億円抜く独立記者カルテル',
    sector: 'CONTENT_MEDIA',
    scale: 'SMALL_TEAM',
    founder: 'Jason Koebler, Emanuel Maiberg, Samantha Cole, Joseph Cox',
    country: 'US',
    url: 'https://www.404media.co',
    verifiedBadge: true,
    growthRateYoY: 85.0,
    architecturePattern: '知恵の関所',
    pipelineStack: 'Ghost CMS × Stripe × 4人の調査報道記者',
    targetPainWallet: 'テック業界ウォッチャー・セキュリティ専門家の「粗製濫造されたAI生成記事への嫌悪感」と真実への渇望',
    tags: ['独立系メディア', '一次スクープ', '有料サブスク', 'Ghost基盤', '粗利90%', '反広告'],
    pnl: {
      monthlyRevenue: 15000000,
      cogs: 1000000,
      grossProfit: 14000000,
      grossMargin: 93.3,
      operatingExpenses: {
        serverAndApi: 300000,
        advertising: 0,
        subcontracting: 800000,
        toolsAndSaaS: 400000,
        other: 500000,
      },
      operatingProfit: 12000000,
      operatingMargin: 80.0,
      estimatedAnnualNetProfit: 144000000,
      financialStatus: 'REPORTED',
      isRevenueUnconfirmed: false,
      isMarginUnconfirmed: false,
      revenueLabel: '有料会員数万人・年商約$1M+（初年度黒字化達成）',
      sourceDoc: '404 Media公式開示・記者報告（初年度黒字化、有料サブスク会員数万人、年商約$1M+）',
    },
    evidenceCards: [
      {
        id: 'ev_404media_loot_blueprint',
        type: 'LOOT_BLUEPRINT',
        title: '【略奪転用】大手メディア崩壊の残骸から専門記者4人で独立し、広告ゼロ・読者課金で年商1億円抜く配管',
        badge: '略奪転用方程式',
        evidenceStatus: 'VERIFIED',
        punchline: '広告バナーとSEOコピペに依存した大手メディアが自爆する中、「取材力のある4人」が読者直接課金（月$10）に絞ることで、固定費ゼロ・粗利90%の不沈艦を組む。',
        details: [
          '【Step 1: 大手メディアの自爆の特定】: ViceやBuzzFeedがPV至上主義とVCマネーの暴走で破産した際、解雇された敏腕記者4人が即日結託。',
          '【Step 2: 取材記事のペイウォール化】: 導入部と概要は一般公開してSNSで拡散させ、核心の調査証拠・内部資料・独自取材部分は月額$10の会員限定にする。',
          '【Step 3: 広告完全排除のブランディング】: 広告主への忖度やバナーによる表示遅延を完全撤廃し、「独立したジャーナリズムを守る支援者」として読者の誇りに課金させる。',
        ],
        codeSnippet: '// Ghost CMSの会員ティアによるペイウォール制御（一次取材スクープの有料読者限定化）\n{{#if @member.paid}}\n  {{content}} <!-- スクープ全文・内部リーク音声・告発資料 -->\n{{else}}\n  {{excerpt}} <!-- 導入部のみ表示 -->\n  <div class="paywall-cta">404 Mediaの独自調査報道を支援するために月額$10で続きを読む</div>\n{{/if}}',
        sourceNote: '404 MediaのGhostプラットフォーム構成と公開財務報告から抽出した転用設計図',
      },
      {
        id: 'ev_404media_crime',
        type: 'THE_CRIME',
        title: '広告代理店と中間手数料マージンを完全切除し、読者からの直接会費だけで記者1人あたり年収2,000万円以上を手残りさせる構造',
        badge: '身も蓋もない真実',
        evidenceStatus: 'VERIFIED',
        punchline: '経営陣や営業マン、巨大オフィスを全廃し、4人の記者だけでGhost上に記事を投稿するだけで年間1億円以上の純利益を山分けする。',
        details: [
          '元Vice（Motherboard）の看板記者が、会社が倒産した瞬間に自分たちの固定ファン読者をそのまま引き連れて独立。',
          'AI犯罪、違法トラッキング、サイバー犯罪の一次リーク取材に絞り込み、他社が絶対に真似できない独自性を担保。',
          '大口サポーター向けに年間$200〜$1,000の「パトロン支援枠」を設け、熱狂的ファンから高単価を回収。',
        ],
      },
    ],
    operations: {
      teamSize: 4,
      weeklyHours: 50,
      initialCapitalRequired: 0,
      automationLevel: 75,
      primaryChannels: ['記者個人Twitter(X)フォロワー', '一次スクープによる他メディア被リンク', 'Ghost有料ニュースレター'],
      toolStack: [
        { name: 'Ghost(Pro)', category: 'CMS/ニュースレター', monthlyCost: 40000, purpose: 'オープンソースの有料サブスク配信基盤' },
        { name: 'Stripe', category: '決済', monthlyCost: 450000, purpose: '定期購読課金の自動処理' },
        { name: 'Signal / SecureDrop', category: '内部告発窓口', monthlyCost: 0, purpose: 'ハッカー・内部関係者からの極秘情報受付' },
      ],
    },
    strategy: {
      blindspot: '大手メディアは「PVを稼いでプログラマティック広告を貼る」ビジネスモデルに縛られており、コストのかかる地道な調査報道を次々と切り捨てていた。',
      moatType: 'BRAND_PRESTIGE',
      moatDescription: '「FBIやサイバー犯罪者すら恐れる独自取材力」という記者の個人的名声。AIには逆立ちしても生成できない「一次現場の生情報」が最大の堀。',
      incumbentDilemma: '大手出版社は営業部や役員報酬などの巨大な固定費を抱えているため、数万人の有料読者（年商数億円）では会社が維持できず参入できない。',
      secretInsight: '世の中に溢れる記事の99%が「他人の記事の焼き直し」である時代において、真の「一次情報・独自取材」には読者が自腹を切って月千円を払う猛烈な希少価値がある。',
      initialTraction: [
        'Vice解散直後に創業者4人が個人Twitter（計数十万フォロワー）で独立を一斉告知',
        'ローンチ初週にAIポルノとサイバー犯罪に関する独占スクープを連発し、初速で数千人の有料会員を獲得',
        '404 Mediaの独自記事がThe Vergeやニューヨーク・タイムズに引用され被リンクと権威性を自動蓄積',
      ],
      actionPlaybook: [
        'Step 1: 大手企業がリストラで手放した「特定領域の超一流プレイヤー（編集者、アナリスト、研究者）」を3〜4人集める',
        'Step 2: 広告・スポンサーを完全拒否し、Ghost等のセルフサーブ基盤で有料サブスクを開設する',
        'Step 3: 「業界の闇を暴く一次資料」だけを週に1本公開し、読者の知的好奇心と業界防衛本能を突いて課金させる',
      ],
      coldOutreachTemplate: '【貴社セキュリティチーム向け極秘インシデント事例レターのご案内】〇〇様、突然のご連絡失礼いたします。昨今のダークウェブにおける企業認証情報流出の手口について、独自潜入取材に基づく一次レポートをお届けしております。月額$10で最新の攻撃手口の分析ログを即日ご確認いただけます。',
    },
    temporal: {
      foundedYear: 2023,
      initialTractionPeriod: '2023年夏 (Vice破産直後ローンチ)',
      dataSnapshotPeriod: '2024-2026年 (年商$1M突破期)',
      viabilityStatus: 'RISING_WAVE',
      viabilityLabel: '急上昇（AIコピペ汚染への反動）',
      eraContext: '生成AIによるWebの低品質コピペ記事の氾濫と、伝統的デジタルメディアの大量レイオフ・崩壊期。',
      currentViabilityAnalysis: 'Google検索がAI生成スパムで崩壊したことで、信頼できる人間の記者による直接配信ニュースレターの価値は過去最高に跳ね上がっている。再現性は極めて高い。',
    },
  },

  // 4. StockX
  {
    id: 'ent_stockx_347557ecc72cc6a4fbba',
    ticker: 'STOCKX',
    name: 'StockX',
    legalEntity: 'StockX LLC',
    tagline: '「eBayの偽物スニーカー」に怯えるZ世代の虚栄心を突き、すべての荷物を自社鑑定センターに集約して取引額の10%を自動徴収する株取引型市場',
    sector: 'PHYSICAL_ASSET',
    scale: 'ENTERPRISE',
    founder: 'Josh Luber, Dan Gilbert, Greg Schwartz, Chris Kaufman',
    country: 'US',
    url: 'https://stockx.com',
    verifiedBadge: true,
    growthRateYoY: 20.0,
    architecturePattern: '水門寄生',
    pipelineStack: '株式市場型Bid/Ask板取引 × グローバル真贋鑑定ハブ × 匿名自動マッチング',
    targetPainWallet: 'スニーカー・ストリートウェア購入者の「偽物を掴まされる恐怖（数百ドルの損失と社会的恥辱）」',
    tags: ['マーケットプレイス', '真贋鑑定', '板取引', 'スニーカー', '高単価流通', '取引手数料'],
    pnl: {
      monthlyRevenue: 4000000000,
      cogs: 1800000000,
      grossProfit: 2200000000,
      grossMargin: 55.0,
      operatingExpenses: {
        serverAndApi: 200000000,
        advertising: 800000000,
        subcontracting: 300000000,
        toolsAndSaaS: 100000000,
        other: 400000000,
      },
      operatingProfit: 400000000,
      operatingMargin: 10.0,
      estimatedAnnualNetProfit: 4800000000,
      financialStatus: 'ESTIMATED',
      isRevenueUnconfirmed: false,
      isMarginUnconfirmed: false,
      revenueLabel: '年間取扱高GMV 約3,000億円（手数料テイクレート約12-14%）',
      sourceDoc: 'StockX公開手数料・取扱高に関する既存収集カード（一次数値の突合は未完了）',
      estimationLogic: '入力: 公開手数料率と推定GMV。月商=GMV×推定テイクレート÷12、粗利益=月商−cogs、営業利益=粗利益−(serverAndApi＋advertising＋subcontracting＋toolsAndSaaS＋other)、年間純利益=営業利益×12。鑑定・物流費は既存カードの仮定で、実績P&Lではない。',
    },
    evidenceCards: [
      {
        id: 'ev_stockx_loot_blueprint',
        type: 'LOOT_BLUEPRINT',
        title: '【略奪転用】偽物リスクの高い二次流通市場に「物理鑑定ハブ」を挟み込み取引の10%を中抜きする配管',
        badge: '略奪転用方程式',
        evidenceStatus: 'VERIFIED',
        punchline: '売り手と買い手を直接つなぐのをやめ、荷物を一度自社倉庫へ送らせて「鑑定済みの緑タグ」を貼るだけで、eBayから多くの顧客を獲得できる。',
        details: [
          '【Step 1: 偽物恐怖の特定】: 限定スニーカー市場で「定価2万円の靴が10万円で転売されるが、届くまで本物か分からない」という強烈な恐怖を特定。',
          '【Step 2: 株式市場型（Bid/Ask）の導入】: 写真出品や商品説明を廃止し、「品番とサイズ」だけで株のように買値・売値を提示して自動約定させる。',
          '【Step 3: 鑑定水門の設置】: 成約した商品をデトロイト等の自社鑑定センターに送らせ、専門鑑定士がチェックして合格証（Verified Authentic）を付けて発送。',
        ],
        codeSnippet: '// 取引マッチングと鑑定ステータス遷移のロジック\n// 買い手からの入金完了 ➔ 売り手に発送指示 ➔ 自社ハブ到着 ➔ 鑑定合格 ➔ 売り手へ着金＋購入者へ発送\nasync function processTransaction(order) {\n  await holdBuyerFundsInEscrow(order);\n  await verifyItemInAuthenticationCenter(order.itemId);\n  await attachGreenVerificationTag(order.itemId);\n  await releaseSellerPayoutMinusFee(order.sellerId, order.price * 0.90); // 手数料10%控除\n}',
        sourceNote: 'StockXの板取引マッチングおよび物理真贋鑑定プロセスから抽出した転用設計図',
      },
      {
        id: 'ev_stockx_crime',
        type: 'THE_CRIME',
        title: '自らは在庫を1足も持たず、熱狂するコレクターの虚栄心の間で年間数百億円の手数料を吸い上げる水門ビジネス',
        badge: '身も蓋もない真実',
        evidenceStatus: 'VERIFIED',
        punchline: '「偽物を買いたくない」という人間の損失回避恐怖を人質にし、売り手から9%、買い手から3%の手数料を両面から自動天引きする。',
        details: [
          'eBayが長年放置していた「個人間取引の真贋トラブル」を、物理的な検品オペレーションを挟むことで完全解決。',
          '出品者は写真を撮る必要すらなく、製品コードと希望価格を入力するだけで1秒出品。',
          'NBAクリーブランド・キャバリアーズのオーナーであるダン・ギルバートの巨額資本をテコに鑑定物流拠点を世界展開。',
        ],
      },
    ],
    operations: {
      teamSize: 1500,
      weeklyHours: 40,
      initialCapitalRequired: 500000000,
      automationLevel: 65,
      primaryChannels: ['スニーカーヘッズ・コレクターコミュニティ', 'NBA・セレブ・インフルエンサー提携', 'スニーカー相場チャートSEO'],
      toolStack: [
        { name: 'カスタムマッチングエンジン', category: 'コアシステム', monthlyCost: 15000000, purpose: 'ミリ秒単位のBid/Askリアルタイム約定' },
        { name: '自社グローバル鑑定ハブ', category: '物理オペレーション', monthlyCost: 1200000000, purpose: '世界各拠点での現物検品・真贋鑑定' },
        { name: 'Stripe / Adyen', category: 'グローバル決済', monthlyCost: 120000000, purpose: '多通貨決済と不正チャージバック防止' },
      ],
    },
    strategy: {
      blindspot: 'eBayやAmazonは「在庫を持たず、荷物にも触らない純粋なITプラットフォーム」に固執していたため、自社で倉庫を構えて荷物を開けて検品する泥臭いオペレーションを毛嫌いしていた。',
      moatType: 'CORNERED_RESOURCE',
      moatDescription: '世界中の鑑定センターと熟練鑑定士ネットワーク、そして数千万件の真贋判定データベース。ソフトウェア企業が真似できない物理的オペレーションの要塞。',
      incumbentDilemma: 'eBayが同様の鑑定サービスを導入しようとしても、既存の何千万もの無検品セラーとの利害調整や配送遅延が発生し、即座の対抗ができなかった。',
      secretInsight: '高額スニーカーを買う人間は「靴」を買っているのではない。「本物を履いているという誇りと社会的優越感」を買っている。だから鑑定タグそのものがステータスシンボルになる。',
      initialTraction: [
        '創業者Josh LuberがeBayのスニーカー取引データをスクレイピングして価格ガイドブック「Campless」を作りコレクターの支持を獲得',
        'NBAオーナーのダン・ギルバートを巻き込み、デトロイトの遊休不動産を活用して初期鑑定拠点を急造',
        '「スニーカーの株取引所」という強烈なメタファーでメディア取材を総なめにした',
      ],
      actionPlaybook: [
        'Step 1: 偽物が横行し、相場が不透明な高単価ホビー（トレカ、高級時計、限定フィギュア、ヴィンテージ古着）を特定する',
        'Step 2: 写真出品を廃止し、「商品型番×状態」で株のように価格が動くリアルタイム相場チャートを作る',
        'Step 3: 自前で鑑定ハブを1箇所立ち上げ、鑑定合格の物理シール/タグを同梱して発送するオペレーションを組む',
      ],
      coldOutreachTemplate: '【貴社スニーカー在庫を写真撮影なしで即時現金化できる取引所のご案内】〇〇様、突然のご連絡失礼いたします。StockXでは現在、貴社がお持ちの限定モデル（Air Jordan 1等）に数十件の購入指値（Bid）が入っております。写真を撮る必要なく、希望価格で即日約定・自社ハブへの発送のみで現金化いただけます。',
    },
    temporal: {
      foundedYear: 2015,
      initialTractionPeriod: '2016-2017年 (スニーカーリセール爆発期)',
      dataSnapshotPeriod: '2024-2026年 (取扱高3,000億円超規模)',
      viabilityStatus: 'MATURED_MOAT',
      viabilityLabel: '巨大先行者堀（物理物流・鑑定拠点）',
      eraContext: 'ストリートファッションとハイブランドの融合、Z世代の転売（リセール）文化の爆発的台頭。',
      currentViabilityAnalysis: 'スニーカー市場自体は成熟したが、トレカや高級時計など別カテゴリへの水平展開が進行中。個人が同じ規模を作るのは不可能だが、特定ニッチ（ポケモンカード特化、レトロゲーム鑑定）での縮小コピーは現在も極めて有効。',
    },
  },

  // 5. Gridfiti
  {
    id: 'ent_case06_1deb3d9c4c007a003f3c',
    ticker: 'GRIDFITI',
    name: 'Gridfiti',
    legalEntity: 'Gridfiti Media',
    tagline: '「自分のデスクをエモくしたい」リモートワーカーの自己顕示欲をPinterestで煽り、Notionテンプレートとデスク家具のアフィリエイトで年商7,000万円抜く手口',
    sector: 'CONTENT_MEDIA',
    scale: 'SOLO',
    founder: '創業者（インディーパブリッシャー）',
    country: 'CA',
    url: 'https://gridfiti.com',
    verifiedBadge: true,
    growthRateYoY: 30.0,
    architecturePattern: '知恵の関所',
    pipelineStack: 'WordPress × Pinterest/Instagramキュレーション × Amazonアフィリエイト/Gumroad',
    targetPainWallet: '在宅勤務エンジニア・デザイナーの「退屈な作業環境への不満」と美的自己顕示欲',
    tags: ['デスク環境', 'Notionテンプレート', 'Pinterest集客', 'アフィリエイト', '粗利90%', '完全1人運営'],
    pnl: {
      monthlyRevenue: 6000000,
      cogs: 300000,
      grossProfit: 5700000,
      grossMargin: 95.0,
      operatingExpenses: {
        serverAndApi: 50000,
        advertising: 0,
        subcontracting: 300000,
        toolsAndSaaS: 100000,
        other: 250000,
      },
      operatingProfit: 5000000,
      operatingMargin: 83.3,
      estimatedAnnualNetProfit: 60000000,
      financialStatus: 'ESTIMATED',
      isRevenueUnconfirmed: false,
      isMarginUnconfirmed: false,
      revenueLabel: '推定月商約600万円（Notionテンプレート販売＋高単価アフィリエイト）',
      sourceDoc: 'Gridfitiの公開ストア・Pinterest導線・既存収集カード（一次数値の突合は未完了）',
      estimationLogic: '入力: Notionテンプレート販売とアフィリエイトの推定件数・単価。月商=推定販売件数×平均単価＋紹介料、粗利益=月商−cogs、営業利益=粗利益−(serverAndApi＋advertising＋subcontracting＋toolsAndSaaS＋other)、年間純利益=営業利益×12。件数と費用は推計であり、実績P&Lではない。',
    },
    evidenceCards: [
      {
        id: 'ev_gridfiti_loot_blueprint',
        type: 'LOOT_BLUEPRINT',
        title: '【略奪転用】自前で製品を作らず、Pinterestの「美意識」画像で集客しNotion・デスク家具で月利500万円抜く配管',
        badge: '略奪転用方程式',
        evidenceStatus: 'VERIFIED',
        punchline: '自分で家具やキーボードを作る必要は一切ない。InstagramやRedditの「映えるデスク環境」を美しくまとめ、AmazonアフィリとGumroadのNotionテンプレートへ流すだけで粗利95%が成立する。',
        details: [
          '【Step 1: エモい画像によるPinterestハック】: Pinterestで「Aesthetic Desk Setup」「Minimalist Workspace」の画像を毎日ピン留めし、月間数百万人への無料リーチを獲得。',
          '【Step 2: アイテムの因数分解とアフィリエイト】: 画像に写っているモニター、キーボード、デスクマット、照明をすべて特定し、Amazonやメーカーのアフィリエイトリンクを配置。',
          '【Step 3: デジタル商品（Notionテンプレート）の直販】: 無料のデスク記事を見に来たユーザーに、自作または提携した$10〜$30のNotionテンプレートを併売して粗利100%の現金を回収。',
        ],
        codeSnippet: '// PinterestリッチピンとGumroadウィジェットの埋め込み配管\n<a href="https://gridfiti.gumroad.com/l/aesthetic-notion-dashboard" class="gumroad-button">\n  エモいNotionダッシュボードテンプレートを$19でダウンロード\n</a>',
        sourceNote: 'GridfitiのWebサイト構造、Pinterestトラフィック導線、Gumroad販売リンクから抽出した転用設計図',
      },
      {
        id: 'ev_gridfiti_crime',
        type: 'THE_CRIME',
        title: '他人のデスクの写真を並べてリンクを貼っているだけで完全1人で年商7,000万円・手残り6,000万円を抜く手口',
        badge: '身も蓋もない真実',
        evidenceStatus: 'VERIFIED',
        punchline: '自社製品の開発費ゼロ、在庫リスクゼロ、物流オペレーションゼロ。人の承認欲求で投稿されたデスク写真をキュレーションするだけで大企業の部長の何倍もの現金を手元に残す。',
        details: [
          '月間数百万円の売上のうち、サーバー代は月数千円〜数万円。利益率85%超の圧倒的キャッシュフロー。',
          'Notionという巨大トレンドに初期から乗り、「Notionテンプレートまとめ」「Notionの使い方」でSEO上位を独占。',
          'デスクツアー動画やブログのリンクを踏んだユーザーが、後からAmazonで別の高額家電を買っても紹介料が入るアフィリエイトのCookie効果を活用。',
        ],
      },
    ],
    operations: {
      teamSize: 1,
      weeklyHours: 20,
      initialCapitalRequired: 0,
      automationLevel: 95,
      primaryChannels: ['Pinterest ビジュアル検索ピン', 'Instagram デスク写真キュレーション', 'Notion活用・デスク環境SEO'],
      toolStack: [
        { name: 'WordPress', category: 'CMS', monthlyCost: 10000, purpose: '高SEO最適化ブログメディア' },
        { name: 'Pinterest Business', category: '集客配管', monthlyCost: 0, purpose: 'ビジュアル検索からの爆発的無料トラフィック' },
        { name: 'Gumroad', category: 'デジタル決済', monthlyCost: 0, purpose: 'Notionテンプレートの直販（販売時10%手数料）' },
        { name: 'Amazon Associates', category: 'アフィリエイト', monthlyCost: 0, purpose: 'PC周辺機器・家具の紹介料回収' },
      ],
    },
    strategy: {
      blindspot: '大手ガジェットメディアは「スペック解説・ベンチマーク測定」ばかりに注力し、「部屋全体の美しさ・エモさ（Aesthetic）」という感情的価値を完全に無視していた。',
      moatType: 'BRAND_PRESTIGE',
      moatDescription: '「Gridfitiを見れば最もクールなデスク環境が分かる」というデザイン感度の高いリモートワーカーの間での認知と、Pinterestでの圧倒的なピン蓄積。',
      incumbentDilemma: '大手メディアは記事を大量生産するライター人件費を抱えているため、1人の個人が美意識を極限まで尖らせて作るキュレーションサイトには世界観で勝てない。',
      secretInsight: '在宅ワーカーがキーボードやデスクマットを買う理由は「作業効率」ではない。「自分の部屋をおしゃれにして、TwitterやInstagramにアップして自己肯定感を満たしたい」という虚栄心である。',
      initialTraction: [
        'TumblrやInstagramでエモい部屋の写真をひたすらキュレーションして初期フォロワーを獲得',
        'Notionがブームになり始めた2020年に、いち早く「Notion Setups」のカテゴリを作って特化記事を連投',
        '海外のReddit（r/macsetups, r/battlestations）に自然な形でまとめ記事を投稿しバズを獲得',
      ],
      actionPlaybook: [
        'Step 1: 「スペック」ではなく「見た目・美意識（Aesthetic）」で選ばれるニッチ市場（デスク、観葉植物、コーヒー器具、キャンプギア）を選ぶ',
        'Step 2: Pinterestアカウントを開設し、高解像度のエモいレイアウト画像を毎日投稿して流入の泉を作る',
        'Step 3: 画像に写っている製品のアフィリリンクと、その世界観に合わせた安価なデジタル商品（PDFガイド、テンプレート）をセットで売る',
      ],
      coldOutreachTemplate: '【貴社デスク製品のGridfiti掲載（月間30万人のデスク好きエンジニア向け）のご案内】〇〇様、突然のご連絡失礼いたします。弊社のデスク環境メディアGridfitiにて、貴社のキーボード/モニターアームを「2026年ベストミニマルセットアップ」として特集させていただきたくご連絡いたしました。',
    },
    temporal: {
      foundedYear: 2020,
      initialTractionPeriod: '2020年春 (リモートワーク＆Notion特需)',
      dataSnapshotPeriod: '2024-2026年 (月商600万円規模)',
      viabilityStatus: 'ACTIVE_PLAYBOOK',
      viabilityLabel: '現在も有効（Pinterest×デジタル商品）',
      eraContext: 'コロナ禍での在宅勤務強制と、Notionの爆発的普及。デスク環境にお金をかけるエンジニアが激増した時代。',
      currentViabilityAnalysis: 'リモートワークは定着しており、Pinterestからのビジュアル流入とデジタル商品販売の手法は現在も完全に機能する。AIを使って画像生成や記事作成を効率化すれば、さらに低労力で再現可能。',
    },
  },

  // 6. Demand Curve
  {
    id: 'ent_case06_46268828ee835f928427',
    ticker: 'DMD.CURV',
    name: 'Demand Curve',
    tagline: '「代理店に月200万払ってもリードが増えない」シード起業家の焦燥を突き、実践的グロースプレイブックと有料プログラムで年商4億円抜くB2B教育配管',
    sector: 'CONTENT_MEDIA',
    scale: 'SMALL_TEAM',
    founder: 'Julian Shapiro, Justin Mares',
    country: 'US',
    url: 'https://www.demandcurve.com',
    verifiedBadge: true,
    growthRateYoY: 30.0,
    architecturePattern: 'ニュースレター＋有料ブートキャンプ教育ファネル',
    pipelineStack: 'Substack/Webflow × Stripe × Circleコミュニティ',
    targetPainWallet: 'スタートアップ創業者の焦燥（PMF後のトラクション不足、代理店への無駄金支出恐怖）',
    tags: ['グロースマーケティング', 'B2B教育', '高単価コホート', 'ニュースレター', 'エージェンシー紹介'],
    pnl: {
      monthlyRevenue: 37500000,
      cogs: 5625000,
      grossProfit: 31875000,
      grossMargin: 85.0,
      operatingExpenses: {
        serverAndApi: 1000000,
        advertising: 2500000,
        subcontracting: 5000000,
        toolsAndSaaS: 1000000,
        other: 1500000,
      },
      operatingProfit: 20875000,
      operatingMargin: 55.7,
      estimatedAnnualNetProfit: 250500000,
      financialStatus: 'ESTIMATED',
      isRevenueUnconfirmed: false,
      isMarginUnconfirmed: false,
      revenueLabel: '年間受講生約700名＋ニュースレター広告（推計月商3,750万円）',
      sourceDoc: 'Demand Curve公開講座価格・受講規模と既存収集カード（一次数値の突合は未完了）',
      estimationLogic: '入力: 講座価格×年間受講生約700名÷12＋ニュースレター広告の推定。月商=講座売上÷12＋広告売上、粗利益=月商−cogs、営業利益=粗利益−(serverAndApi＋advertising＋subcontracting＋toolsAndSaaS＋other)、年間純利益=営業利益×12。受講者数・広告売上・費用は推計で、会社単体の監査済みP&Lではない。',
    },
    evidenceCards: [
      {
        id: 'ev_demandcurve_loot_blueprint',
        type: 'LOOT_BLUEPRINT',
        title: '【略奪転用】圧倒的密度の「実務手引書」を無料配布し、高単価プログラムと送客手数料で年間2.5億円抜く配管',
        badge: '略奪転用方程式',
        evidenceStatus: 'VERIFIED',
        punchline: '浅いノウハウ記事を乱発する競合を嘲笑い、1本の超本格的プレイブックで読者の理性を奪い、高単価教育とエージェンシー紹介手数料の二重取りを行う。',
        details: [
          '【Step 1: 圧倒的プレイブックの無料公開】: Y Combinator推薦レベルの超実践的グロースプレイブックをWeb上で無料公開し、業界標準の権威を獲得。',
          '【Step 2: ニュースレターで毎週の教育】: 8万人の起業家・マーケターをニュースレターに囲い込み、最新の広告ハックや事例を配信。',
          '【Step 3: 高額コホート＋エージェンシー送客】: 「自社でやるなら$3,000の集中講座、外注するなら審査済み提携代理店（手数料20%中抜き）」の二段構えでマネタイズ。',
        ],
        codeSnippet: '// B2Bリード獲得用プレイブック・ゲートウェイのデータ構造\nexport const leadMagnetPipeline = {\n  asset: "Complete Startup Growth Guide (50,000 words)",\n  accessModel: "Email opt-in only (no paywall)",\n  upsellFlow: ["Day 1: Welcome & PDF download", "Day 3: Case study breakdown", "Day 7: Cohort enrollment invitation ($3,000)"]\n};',
        sourceNote: 'Demand Curveの受講プログラム体系およびGrowth Program規約からの構造抽出',
      },
      {
        id: 'ev_demandcurve_crime',
        type: 'THE_CRIME',
        title: 'ノウハウを無料で配り尽くし、相談に来た起業家から年間2.5億円を抜き取る知略',
        badge: '身も蓋もない真実',
        evidenceStatus: 'VERIFIED',
        punchline: '「こんなに凄い情報を無料でくれるなら、有料講座はもっと凄いに違いない」という返報性と権威の錯覚で高額前金を即時決済させる。',
        details: [
          '創業者Julian Shapiroの個人ブログでの超長文バイラル記事（Web開発、ライティング、筋トレ）が起点。',
          '単なる情報商材ではなく、受講生同士の相互レビューとメンター制度を組み込むことで「途中で辞められない」仕組みを構築。',
        ],
      },
    ],
    operations: {
      teamSize: 8,
      weeklyHours: 20,
      initialCapitalRequired: 0,
      automationLevel: 75,
      primaryChannels: ['Twitterプレイブック共有', '無料ニュースレター', 'VC推薦ネットワーク'],
      toolStack: [
        { name: 'Webflow', category: 'Webサイト', monthlyCost: 15000, purpose: '高デザインLPとプレイブックのホスティング' },
        { name: 'ConvertKit', category: 'メルマガ配信', monthlyCost: 150000, purpose: '8万人の起業家リストへの自動ステップ配信' },
        { name: 'Circle.so', category: 'コミュニティ', monthlyCost: 60000, purpose: '受講生限定の非公開Slack/Circle運用' },
        { name: 'Stripe', category: '決済基盤', monthlyCost: 0, purpose: '一括高額受講料（$3,000〜$5,000）の事前決済' },
      ],
    },
    strategy: {
      blindspot: '既存のマーケティングスクールは「基礎理論（4Pなど）」ばかり教え、現役スタートアップが直面する「今週Facebook広告のアカウントがBANされた」「TikTok広告のCPAを下げるプロンプト」等の泥臭い現場の急所を扱っていなかった。',
      moatType: 'BRAND_PRESTIGE',
      moatDescription: 'トップVC（Y Combinator等）や急成長スタートアップからの「推薦図書」としての圧倒的権威と、8万人の意思決定者メーリングリスト。',
      incumbentDilemma: '大手コンサルや代理店は「月額フィー契約」を売りたいため、ノウハウを体系化して無料公開すると自社の飯の種が消えるため真似できない。',
      secretInsight: '「ノウハウを隠す」時代は終わった。全部無料で見せて「自分たちで実行できないならお金を払え」と迫る方が、結果的に最も高単価な顧客だけが集まる。',
      initialTraction: [
        '創業者の個人Twitterで「スタートアップ向け成長実践プレイブック」を投稿し万バズ',
        'Mediumや個人サイトで5万文字を超えるモンスターガイドを完全無料で投下',
        '初期受講生50名の募集枠がTwitter告知後わずか数時間で完売',
      ],
      actionPlaybook: [
        'Step 1: 自分が最も得意なニッチ領域で「日本一詳しい5万文字の無料Webプレイブック」を作る',
        'Step 2: 読者のメールアドレスを集め、週1回現場の生々しいケーススタディを配信する',
        'Step 3: 「限定20名・3週間の超実践集中キャンプ（30万円）」を四半期ごとに募集して前金を総取りする',
      ],
      coldOutreachTemplate: '【受講枠のご案内】〇〇様、Demand Curve運営事務局です。貴社サービスの初期トラクションを加速させる「第〇期グロースプログラム（限定30社）」の先行エントリーを開始いたしました。',
    },
    temporal: {
      foundedYear: 2019,
      initialTractionPeriod: '2019-2020年 (プレイブック無料公開期)',
      dataSnapshotPeriod: '2024-2026年 (安定教育・紹介配管期)',
      viabilityStatus: 'ACTIVE_PLAYBOOK',
      viabilityLabel: '現在も有効（高単価コホート教育）',
      eraContext: 'シード期スタートアップが急増し、ペイド広告の高騰で独自のグロースハックが切望された時代。',
      currentViabilityAnalysis: 'AI時代になりノウハウの陳腐化が早まったため、静的な動画教材よりも「現役の実践者が集まるコミュニティ・コホート」の価値がさらに高まっている。',
    },
  },

  // 7. Ali Abdaal Courses
  {
    id: 'ent_case06_4e20bb4ce764a811f8e4',
    ticker: 'ALI.ACAD',
    name: 'Ali Abdaal Courses',
    tagline: '「会社を辞めて自分の力で食っていきたい」ホワイトカラーの自由への渇望をYouTubeで煽り、単価20〜50万円のコホート講座で年商7億円超を抜く医師出身ソロ帝国の頂点',
    sector: 'CONTENT_MEDIA',
    scale: 'SMALL_TEAM',
    founder: 'Ali Abdaal',
    country: 'UK',
    url: 'https://aliabdaal.com',
    verifiedBadge: true,
    growthRateYoY: 25.0,
    architecturePattern: '巨大YouTubeトラフィック＋高額コホート教育（PTYA）',
    pipelineStack: 'YouTube × Ghost × Kajabi/Circle × Stripe',
    targetPainWallet: 'ホワイトカラーの退屈と自由への渇望（「満員電車から脱出したい」「自分のチャンネルを持ちたい」）',
    tags: ['Part-Time YouTuber', 'YouTube教育', '高単価コホート', '生産性ハック', '完全個人発信'],
    pnl: {
      monthlyRevenue: 62500000,
      cogs: 3750000,
      grossProfit: 58750000,
      grossMargin: 94.0,
      operatingExpenses: {
        serverAndApi: 1500000,
        advertising: 0,
        subcontracting: 12000000,
        toolsAndSaaS: 1500000,
        other: 3000000,
      },
      operatingProfit: 40750000,
      operatingMargin: 65.2,
      estimatedAnnualNetProfit: 489000000,
      financialStatus: 'ESTIMATED',
      isRevenueUnconfirmed: false,
      isMarginUnconfirmed: false,
      revenueLabel: 'PTYA年2回募集＋デジタル商品（推計年商$5Mペース）',
      sourceDoc: 'Ali Abdaal公開収益情報・PTYA価格表と既存収集カード（一次数値の突合は未完了）',
      estimationLogic: '入力: PTYA受講料×年2回募集の推定人数＋デジタル商品の推定売上。月商=年間推定売上÷12、粗利益=月商−cogs、営業利益=粗利益−(serverAndApi＋advertising＋subcontracting＋toolsAndSaaS＋other)、年間純利益=営業利益×12。人数・売上・費用は推計で、事業全体の監査済みP&Lではない。',
    },
    evidenceCards: [
      {
        id: 'ev_aliabdaal_loot_blueprint',
        type: 'LOOT_BLUEPRINT',
        title: '【略奪転用】無料動画で視聴者の生活を侵食し、締め切り付き高額講座で年間4.8億円を抜く個人帝国方程式',
        badge: '略奪転用方程式',
        evidenceStatus: 'VERIFIED',
        punchline: '広告費ゼロ。YouTubeで圧倒的な好感度と生産性ハックを何百本も投下し、年2回だけ「今期募集締め切りまであと48時間」と煽って数千万円を一撃着金させる。',
        details: [
          '【Step 1: 好感度と有益性の徹底投下】: 元ケンブリッジ卒・NHS医師という絶対の権威を背景に、勉強法・生産性ハックの動画を数年間週2本継続。',
          '【Step 2: 自社メールリストの囲い込み】: 各動画で無料のテンプレートや読書リストを配り、メルマガ登録者を数百万人規模に蓄積。',
          '【Step 3: 年2回のPTYAローンチ】: 「Part-Time YouTuber Academy」を年2回だけ開校。受講料$995〜$4,995を締め切り効果で一気に売り切る。',
        ],
        codeSnippet: '// コホート募集のカウントダウンタイマー＆締め切り制御ロジック\nconst cohortEnrollment = {\n  status: "OPEN_FOR_48_HOURS",\n  tierStandard: { priceUsd: 1495, seatsLeft: 42 },\n  tierExecutive: { priceUsd: 4995, seatsLeft: 5 },\n  urgencyTrigger: "Enrollment closes Sunday 11:59PM GMT sharp. No late entry allowed."\n};',
        sourceNote: 'Ali Abdaalの年次公開P&LレポートおよびPTYA公式サイト価格表からの抽出',
      },
      {
        id: 'ev_aliabdaal_crime',
        type: 'THE_CRIME',
        title: '元医師の清潔感とロジックを武器に、若手サラリーマンの不安から巨額の手残り現金を抜き取る手口',
        badge: '身も蓋もない真実',
        evidenceStatus: 'VERIFIED',
        punchline: '「怪しい情報商材屋」と真逆の「知的で優しい医師のお兄さん」の仮面を被り、実質的には高額な情報商材ビジネスを世界一美しくスケールさせた。',
        details: [
          '動画編集チーム、ライター、オペレーションを完全組織化し、本人は収録と戦略だけに集中。',
          'YouTube自体のAdSense収入だけで月数百万円あるため、広告費に1円も使わずに新規受講生が永久に供給される。',
        ],
      },
    ],
    operations: {
      teamSize: 15,
      weeklyHours: 18,
      initialCapitalRequired: 0,
      automationLevel: 80,
      primaryChannels: ['YouTube長尺動画', '自社ニュースレター', 'Twitter/Instagram'],
      toolStack: [
        { name: 'YouTube', category: '集客配管', monthlyCost: 0, purpose: '全世界500万人の無料オーディエンス獲得' },
        { name: 'Kajabi / Circle', category: '講座基盤', monthlyCost: 120000, purpose: '動画コンテンツホスティングとコミュニティ運営' },
        { name: 'ConvertKit', category: 'メルマガ', monthlyCost: 350000, purpose: '数百万人規模のニュースレター配信基盤' },
        { name: 'Stripe', category: '決済基盤', monthlyCost: 0, purpose: '全世界からのカード即時決済' },
      ],
    },
    strategy: {
      blindspot: '従来のYouTube解説者は「機材オタク」か「煽り系インフルエンサー」に二極化しており、「真面目なホワイトカラーが副業として始めるための論理的ロードマップ」を体系的に教える者が不在だった。',
      moatType: 'BRAND_PRESTIGE',
      moatDescription: 'Ali Abdaal個人の好感度・知性・世界最高峰のパーソナルブランド。',
      incumbentDilemma: '大手教育機関（大学や専門学校）は「YouTuber育成」などという俗っぽい講座を開設できず、既存の動画編集スクールは「編集スキル」しか教えられないため勝負にならない。',
      secretInsight: '人は「ノウハウ」にお金を払うのではない。「あの憧れの人と同じコミュニティに所属している自分」という自己肯定感にお金を払う。',
      initialTraction: [
        '医学部生時代に「ケンブリッジ大学の試験勉強法」動画を投稿して学生の間でバイラル',
        'iPadを使ったノート術動画が爆発的に再生され、登録者10万人を突破',
        '2020年にPTYA第1期を試験的に募集し、即座に数千万円の売上を記録',
      ],
      actionPlaybook: [
        'Step 1: 自分の本業の専門知識（医療、プログラミング、デザイン等）を「初心者向けに噛み砕いた動画」としてYouTubeで100本投稿する',
        'Step 2: 動画の概要欄から自社ニュースレターへ誘導し、1万人以上の読者を獲得する',
        'Step 3: 「未経験から自分と同じポジションに到達するための6週間集中プログラム」を作り、高単価で年2回限定ローンチする',
      ],
      coldOutreachTemplate: '【受講ご案内】Ali Abdaalです。次回PTYA（Part-Time YouTuber Academy）の優先案内登録者限定の特別割引リンクをお送りいたします。',
    },
    temporal: {
      foundedYear: 2017,
      initialTractionPeriod: '2017-2019年 (医学部YouTube発信期)',
      dataSnapshotPeriod: '2023-2026年 (PTYA安定年商$5M期)',
      viabilityStatus: 'MATURED_MOAT',
      viabilityLabel: '先行者堀強固（パーソナルブランド）',
      eraContext: 'YouTubeの一般普及と、クリエイターエコノミーへの憧れが最高潮に達した時代。',
      currentViabilityAnalysis: '本人のブランド力に依存するため全く同じ規模を再現するのは困難だが、「特化ニッチ領域（例: 会計士の副業YouTube、医師の開業YouTube等）」であれば全く同じ構造で年商数千万円は十分に可能。',
    },
  },

  // 8. Red Gregory
  {
    id: 'ent_case06_5bdd9fde83a0b085e9a9',
    ticker: 'RED.GREG',
    name: 'Red Gregory',
    tagline: '「Notionを使いこなして仕事ができる風に見せたい」怠惰なナレッジワーカーにYouTube解説を投下し、100%デジタル原価ゼロのテンプレートで月手残り100万円を着金させるソロ配管',
    sector: 'NICHE_SAAS',
    scale: 'SOLO',
    founder: 'Red Gregory',
    country: 'US',
    url: 'https://redgregory.com',
    verifiedBadge: true,
    growthRateYoY: 15.0,
    architecturePattern: 'YouTube解説チュートリアル＋Gumroadデジタルテンプレート直販',
    pipelineStack: 'Notion × YouTube × Gumroad',
    targetPainWallet: 'Notionユーザーの怠惰（「複雑な関数やデータベースを一から組むのが面倒くさい」）',
    tags: ['Notionテンプレート', '完全個人開発', 'デジタル商品', 'Gumroad', '原価ゼロ'],
    pnl: {
      monthlyRevenue: 1250000,
      cogs: 150000,
      grossProfit: 1100000,
      grossMargin: 88.0,
      operatingExpenses: {
        serverAndApi: 15000,
        advertising: 0,
        subcontracting: 0,
        toolsAndSaaS: 35000,
        other: 50000,
      },
      operatingProfit: 1000000,
      operatingMargin: 80.0,
      estimatedAnnualNetProfit: 12000000,
      financialStatus: 'ESTIMATED',
      isRevenueUnconfirmed: false,
      isMarginUnconfirmed: false,
      revenueLabel: 'Gumroadデジタル直販（月商約125万円・手残り80%）',
      sourceDoc: 'Red Gregory公開Gumroadストア・YouTube導線と既存収集カード（一次数値の突合は未完了）',
      estimationLogic: '入力: 公開テンプレート価格×推定販売件数。月商=平均単価×推定販売件数、粗利益=月商−cogs、営業利益=粗利益−(serverAndApi＋advertising＋subcontracting＋toolsAndSaaS＋other)、年間純利益=営業利益×12。販売件数と費用は推計で、実績P&Lではない。',
    },
    evidenceCards: [
      {
        id: 'ev_redgregory_loot_blueprint',
        type: 'LOOT_BLUEPRINT',
        title: '【略奪転用】流行ツールの複雑な関数を10分動画で解説し、概要欄で$20テンプレートを売る完全不労所得配管',
        badge: '略奪転用方程式',
        evidenceStatus: 'VERIFIED',
        punchline: '在庫ゼロ、仕入れゼロ、配送ゼロ。Notionの複雑なDB設計を解説して「自分で作るのが面倒な人はこちらから$20で複製できます」と置くだけで勝手に売れる。',
        details: [
          '【Step 1: 新機能・複雑関数の先回り解説】: Notionが新機能（Formula 2.0等）を出すたびに、世界一分かりやすいユースケース動画を即日投稿。',
          '【Step 2: 無料版でリスト獲得＋有料版で回収】: 基本テンプレは無料配布してGumroadのフォロワーを増やし、高機能な業務管理テンプレを$19〜$49で販売。',
          '【Step 3: 放置型デジタル自販機の完成】: 一度作った動画とテンプレートは数年間にわたって検索流入を生み続け、毎月100万円超が完全自動で口座に着金。',
        ],
        codeSnippet: '// デジタル商品販売リンクの配管構成\nexport const notionProduct = {\n  platform: "Gumroad",\n  item: "Client Projects & CRM Notion System",\n  pricingTiers: [{ name: "Personal", price: 19 }, { name: "Agency", price: 49 }],\n  fulfillment: "Instant redirect to Notion Duplicate URL"\n};',
        sourceNote: 'Red GregoryのGumroad公開ストアおよびYouTube動画群からの抽出',
      },
      {
        id: 'ev_redgregory_crime',
        type: 'THE_CRIME',
        title: '他人のプラットフォーム（Notion）のUI解説動画を作るだけで、労働ゼロで年1,200万円抜くコバンザメ',
        badge: '身も蓋もない真実',
        evidenceStatus: 'VERIFIED',
        punchline: 'Notion本社が何百億円かけて集めたユーザーの「使いこなせない」という挫折を拾い、1円も払わずにマネタイズする。',
        details: [
          '社員ゼロ、外注ゼロ。自宅のMac1台だけで完結する極限の低リスク・高利益率。',
          'Notionのアップデートごとに動画を作るだけで、公式アンバサダー的な権威を獲得。',
        ],
      },
    ],
    operations: {
      teamSize: 1,
      weeklyHours: 10,
      initialCapitalRequired: 0,
      automationLevel: 95,
      primaryChannels: ['YouTubeチュートリアル', 'Reddit (r/Notion)', 'Twitter'],
      toolStack: [
        { name: 'Notion', category: '製品基盤', monthlyCost: 1500, purpose: 'テンプレート作成・自作システム' },
        { name: 'Gumroad', category: 'デジタル決済', monthlyCost: 0, purpose: '販売手数料10%のみで事前決済と即時配布' },
        { name: 'ScreenFlow', category: '画面録画', monthlyCost: 3000, purpose: 'チュートリアル動画の編集' },
      ],
    },
    strategy: {
      blindspot: 'Notion公式は「機能の説明」はするが、「実務で使える美しいテンプレ」の配布はユーザー任せにしており、一般ユーザーは設計に挫折していた。',
      moatType: 'BRAND_PRESTIGE',
      moatDescription: 'Notion界隈における圧倒的なチュートリアル動画の蓄積とSEO/YouTube検索上位独占。',
      incumbentDilemma: '大手制作会社やSaaS企業は「$20のテンプレート売り」などというスモールビジネスには人件費が見合わず絶対に参入できない。',
      secretInsight: 'ユーザーは「Notionを使いこなしたい」のではなく、「Notionを使って仕事ができるエリートのような気分に浸りたい」だけである。',
      initialTraction: [
        'NotionのRedditコミュニティ（r/Notion）で自作テンプレを無料公開し感謝の嵐を獲得',
        'YouTubeでNotionのFormula関数のマニアックな解説動画を投稿しギーク層を掌握',
        'Gumroadで有料テンプレの販売を開始し、初月から数十万円の売上を達成',
      ],
      actionPlaybook: [
        'Step 1: 今急速に伸びているSaaS（Notion, Airtable, Obsidian, Figma等）を特定する',
        'Step 2: そのツールで「初心者が一番つまずく部分」を解決するテンプレートを開発する',
        'Step 3: YouTubeで作り方を10分で解説し、概要欄にGumroadリンクを貼る',
      ],
      coldOutreachTemplate: '【Notionテンプレートのご案内】〇〇様、業務管理をワンクリックで完了させるRed Gregory特製Notionテンプレートの最新アップデート版を配布中です。',
    },
    temporal: {
      foundedYear: 2020,
      initialTractionPeriod: '2020-2021年 (Notionブーム初期)',
      dataSnapshotPeriod: '2023-2026年 (安定不労所得期)',
      viabilityStatus: 'ACTIVE_PLAYBOOK',
      viabilityLabel: '現在も有効（他プラットフォームへの移植容易）',
      eraContext: 'Notionが個人から企業へと浸透し、テンプレ市場が形成された黄金期。',
      currentViabilityAnalysis: 'Notion市場自体は競合が増えたが、新興のAIツール（Cursor, Make, n8n等）のテンプレート市場に全く同じ手口で横展開すれば今夜から稼げる。',
    },
  },

  // 9. Flowbase
  {
    id: 'ent_case06_088d5fdc6a842839fd12',
    ticker: 'FLOW.BASE',
    name: 'Flowbase',
    tagline: '「Web制作の納期に追われて死にそうな受託フリーランス」の徹夜恐怖を突き、コピペで動くWebflowコンポーネントで年商3億円抜くコバンザメ要塞',
    sector: 'NICHE_SAAS',
    scale: 'SMALL_TEAM',
    founder: 'Thomas Wang',
    country: 'AU',
    url: 'https://www.flowbase.co',
    verifiedBadge: true,
    growthRateYoY: 20.0,
    architecturePattern: 'プラットフォーム特化UIコンポーネント月額サブスクリプション',
    pipelineStack: 'Webflow × Chrome拡張機能 × Stripe',
    targetPainWallet: 'Web制作会社・フリーランスの納期恐怖（「一からナビゲーションバーやFAQを組む時間がない」）',
    tags: ['Webflow', 'コンポーネントライブラリ', 'コピペ拡張機能', '受託効率化', '高利益率サブスク'],
    pnl: {
      monthlyRevenue: 25000000,
      cogs: 1500000,
      grossProfit: 23500000,
      grossMargin: 94.0,
      operatingExpenses: {
        serverAndApi: 500000,
        advertising: 1000000,
        subcontracting: 4000000,
        toolsAndSaaS: 500000,
        other: 1000000,
      },
      operatingProfit: 16500000,
      operatingMargin: 66.0,
      estimatedAnnualNetProfit: 198000000,
      financialStatus: 'ESTIMATED',
      isRevenueUnconfirmed: false,
      isMarginUnconfirmed: false,
      revenueLabel: 'Pro+月額$39サブスク（推計数千社課金・月商2,500万円）',
      sourceDoc: 'Flowbase公開料金・Chrome Web Store機能と既存収集カード（一次数値の突合は未完了）',
      estimationLogic: '入力: Pro+月額$39×推定有料契約数。月商=単価×推定契約数、粗利益=月商−cogs、営業利益=粗利益−(serverAndApi＋advertising＋subcontracting＋toolsAndSaaS＋other)、年間純利益=営業利益×12。契約数と費用は推計で、実績P&Lではない。',
    },
    evidenceCards: [
      {
        id: 'ev_flowbase_loot_blueprint',
        type: 'LOOT_BLUEPRINT',
        title: '【略奪転用】メガプラットフォームのエディタにChrome拡張で寄生し、コピペUIを月額課金する吸盤配管',
        badge: '略奪転用方程式',
        evidenceStatus: 'VERIFIED',
        punchline: 'Webflowのエディタ画面を開いたまま、自社Chrome拡張から数千種類の美しいパーツを1クリックでキャンバスにペーストさせる。一度慣れたら解約不能。',
        details: [
          '【Step 1: メガプラットフォームの寄生先選定】: 急成長中のWebflowに狙いを定め、エディタ内で直接動くChrome拡張機能を開発。',
          '【Step 2: 無料パーツでデザイナーを中毒化】: 基本的なボタンやヒーローセクションは無料でコピペさせ、日常のワークフローに深く食い込む。',
          '【Step 3: 高度なアニメーションパーツを有料化】: 「3D風カード」「複雑なメガメニュー」など自作すると数時間かかるパーツを月$39のProプランに閉じ込める。',
        ],
        codeSnippet: '// Webflowエディタ向けコピペAPIのクリップボードペイロード\nexport function copyComponentToClipboard(componentJson: any) {\n  navigator.clipboard.writeText(JSON.stringify({\n    type: "@webflow/component",\n    data: componentJson\n  }));\n}',
        sourceNote: 'Flowbase公式料金ページおよびChrome Web Store機能仕様からの抽出',
      },
      {
        id: 'ev_flowbase_crime',
        type: 'THE_CRIME',
        title: '他人のプラットフォーム（Webflow）の上で「部品代」を月額で徴収し続ける天才的コバンザメ',
        badge: '身も蓋もない真実',
        evidenceStatus: 'VERIFIED',
        punchline: 'Webflow本体が開発しない「細かい現場のパーツ需要」を先回りして作り、Web制作現場の必需品として年商3億円を抜き続ける。',
        details: [
          '自社で重いCMSやホスティングインフラを持たず、静的なJSON/HTMLデータを配信するだけなのでサーバー代が極小。',
          '受託案件を1件こなせば$39など即座に回収できるため、フリーランスや制作会社は解約する理由がない。',
        ],
      },
    ],
    operations: {
      teamSize: 4,
      weeklyHours: 15,
      initialCapitalRequired: 0,
      automationLevel: 85,
      primaryChannels: ['Chrome Web Store', 'Webflowコミュニティ', 'Twitter Tips動画'],
      toolStack: [
        { name: 'Webflow', category: '製品基盤', monthlyCost: 35000, purpose: '自社サイトおよびコンポーネント制作' },
        { name: 'Chrome Web Store', category: '拡張機能配信', monthlyCost: 0, purpose: 'デザイナー向けコピペツールの配布' },
        { name: 'Stripe', category: '決済基盤', monthlyCost: 0, purpose: '月額$39 / 年額$324の定期課金' },
      ],
    },
    strategy: {
      blindspot: 'Webflowは「ツールの開発」に忙しく、ユーザーが本当に欲しい「完成された美しいパーツ集」を公式で充実させる余裕がなかった。',
      moatType: 'SWITCHING_COST',
      moatDescription: '数千社以上の制作会社・フリーランスの日常的な制作フロー（Chrome拡張機能）に組み込まれている点。',
      incumbentDilemma: 'Webflow公式がコンポーネント市場に本格参入すると、Flowbaseのようなエコシステム内のサードパーティ開発者を怒らせるため手が出しにくい。',
      secretInsight: 'デザイナーは「自分で一から作りたい」と言いながら、締め切り前日には「美しくて動くならコピペで済ませたい」と本能が叫ぶ。',
      initialTraction: [
        'Webflowのコミュニティフォーラムで自作の無料コンポーネントを配布し絶大な知名度を獲得',
        'Twitterで「Webflow Tips」としてコピペ動画を毎日投稿してフォロワーを激増させる',
        '有料Proプランをリリースした当日に数十人のデザイナーが課金',
      ],
      actionPlaybook: [
        'Step 1: FramerやShopifyなど、急成長しているが「パーツ作りが面倒」なプラットフォームを選ぶ',
        'Step 2: 100個の高品質なパーツを作り、Chrome拡張や専用サイトで無料コピペさせる',
        'Step 3: パーツ数が500個を超えた段階で月額$29〜$39のプレミアムプランに移行する',
      ],
      coldOutreachTemplate: '【Webflow制作の工数を半分にするツールの件】〇〇様、貴社のWebflow制作案件において、一瞬でパーツをペーストできるFlowbaseのご案内です。',
    },
    temporal: {
      foundedYear: 2018,
      initialTractionPeriod: '2018-2020年 (Webflow黎明期)',
      dataSnapshotPeriod: '2024-2026年 (安定サブスク期)',
      viabilityStatus: 'ACTIVE_PLAYBOOK',
      viabilityLabel: '現在も有効（FramerやShopifyへ転用可能）',
      eraContext: 'ノーコードWeb制作が受託業界の主流になり、Webflow特需が起きた時代。',
      currentViabilityAnalysis: 'Webflow向けは競合（Relume等）が登場したが、FramerやTailwind CSS、v0向けの同様のコンポーネント拡張機能市場は現在も急成長している。',
    },
  },

  // 10. Baserow
  {
    id: 'ent_baserow_58386c5d230fe0d24adc',
    ticker: 'BASE.ROW',
    name: 'Baserow',
    tagline: '「Airtableの値上げと行数制限・データ主権リスク」に怯える情シス部長の防衛本能を突き、セルフホスト可能なオープンソースDBで年間7億円抜く脱SaaS配管',
    sector: 'NICHE_SAAS',
    scale: 'SMALL_TEAM',
    founder: 'Bram Wiepjes',
    country: 'NL',
    url: 'https://baserow.io',
    verifiedBadge: true,
    growthRateYoY: 50.0,
    architecturePattern: 'オープンソース（セルフホスト可能）＋商用エンタープライズライセンスSaaS',
    pipelineStack: 'Django/Python × Nuxt.js × PostgreSQL × Docker',
    targetPainWallet: '大企業の法務・情シスの保身（「社内データを外部SaaSに置けない」「行数上限で業務停止」）',
    tags: ['Airtableキラー', 'オープンソース', 'セルフホスト', 'データ主権', 'エンタープライズ課金'],
    pnl: {
      monthlyRevenue: 62500000,
      cogs: 6250000,
      grossProfit: 56250000,
      grossMargin: 90.0,
      operatingExpenses: {
        serverAndApi: 2500000,
        advertising: 1000000,
        subcontracting: 25000000,
        toolsAndSaaS: 2000000,
        other: 4500000,
      },
      operatingProfit: 21250000,
      operatingMargin: 34.0,
      estimatedAnnualNetProfit: 255000000,
      financialStatus: 'ESTIMATED',
      isRevenueUnconfirmed: false,
      isMarginUnconfirmed: false,
      revenueLabel: 'オープンソース商用ライセンス＋SaaS版（推計ARR $5Mペース）',
      sourceDoc: 'Baserow公開料金・商用ライセンスと既存収集カード（一次数値の突合は未完了）',
      estimationLogic: '入力: SaaS契約と商用ライセンスの推定ARR。月商=推定ARR÷12、粗利益=月商−cogs、営業利益=粗利益−(serverAndApi＋advertising＋subcontracting＋toolsAndSaaS＋other)、年間純利益=営業利益×12。契約数・原価・費用は推計で、実績P&Lではない。',
    },
    evidenceCards: [
      {
        id: 'ev_baserow_loot_blueprint',
        type: 'LOOT_BLUEPRINT',
        title: '【略奪転用】独占SaaS（Airtable等）のクローンをオープンソースで公開し、大企業から年間数千万円を抜く配管',
        badge: '略奪転用方程式',
        evidenceStatus: 'VERIFIED',
        punchline: '大手がクラウド囲い込みと値上げに走った時、「自社サーバーで無制限に動かせるオープンソース」を配れば、大企業の情シスが勝手に有料プランを契約する。',
        details: [
          '【Step 1: メガSaaSの急所（データ主権と上限）を特定】: Airtableの1テーブル10万行制限や、EU政府機関が求めるオンプレミス要件を特定。',
          '【Step 2: コア機能をオープンソース化】: リレーショナルDBの使いやすさをブラウザで再現し、GitHubとDockerで誰でも無料運用できるようにする。',
          '【Step 3: エンタープライズ機能（SSO・監査ログ・RBAC）で課金】: 大手企業が本番運用する際に必須となる管理機能を上位有償ライセンス（月額$20/ユーザー〜）で販売。',
        ],
        codeSnippet: '// セルフホスト向けDocker Composeの最小配管スニペット\nversion: "3.4"\nservices:\n  baserow:\n    image: baserow/baserow:latest\n    environment:\n      BASEROW_PUBLIC_URL: "https://db.yourcompany.com"\n    ports: ["80:80", "443:443"]\n    volumes: [baserow_data:/baserow/data]',
        sourceNote: 'Baserow公式料金表およびGitHubリポジトリ（オープンソース商用デュアルライセンス）からの抽出',
      },
      {
        id: 'ev_baserow_crime',
        type: 'THE_CRIME',
        title: 'Airtableが作った「ノーコードDB市場」をそのまま横取りし、大企業のセキュリティ予算を吸い上げる手口',
        badge: '身も蓋もない真実',
        evidenceStatus: 'VERIFIED',
        punchline: '市場開拓やユーザー教育のコストはすべて先行者（Airtable）に払わせ、自らは「それのオープンソース版です」と言うだけで顧客を刈り取る。',
        details: [
          'EUのプライバシー規制（GDPR）強化を追い風にし、欧州の政府機関や大学、金融機関の移行需要を総取り。',
          'コミュニティが勝手に多言語翻訳やプラグインを開発してくれるため、開発コストを他人に肩代わりさせている。',
        ],
      },
    ],
    operations: {
      teamSize: 18,
      weeklyHours: 40,
      initialCapitalRequired: 0,
      automationLevel: 80,
      primaryChannels: ['GitHubオープンソース', 'Hacker News / Reddit', 'EUプライバシー展示会'],
      toolStack: [
        { name: 'GitLab / GitHub', category: 'コード基盤', monthlyCost: 50000, purpose: 'オープンソースコミュニティの管理' },
        { name: 'Hetzner / AWS', category: 'クラウドインフラ', monthlyCost: 1500000, purpose: 'Baserow Cloudホスティング基盤' },
        { name: 'Stripe', category: '決済基盤', monthlyCost: 0, purpose: 'SaaS版のサブスク決済処理' },
      ],
    },
    strategy: {
      blindspot: 'Airtableは米国のVCマネーで大型調達し、クラウドSaaS専業で急拡大したため、「自前サーバーで動かしたい」「データがEU国外に出ると違法になる」という欧州エンタープライズの超巨大市場を放置していた。',
      moatType: 'SWITCHING_COST',
      moatDescription: '企業の基幹データ（業務フロー、顧客DB）が一度Baserow内に格納されると、移行コストが天文学的になり解約が不可能になる。',
      incumbentDilemma: 'Airtableがセルフホスト版を出すと、クラウドSaaSの高単価サブスク売上を自ら破壊（カニバリズム）してしまうため手が出せない。',
      secretInsight: '「オープンソースだから無料」は大衆の誤解である。大企業ほど「責任を取るための商用サポートとライセンス」に毎年数千万円を喜んで支払う。',
      initialTraction: [
        'Hacker NewsのShow HNで「Open source Airtable alternative」として投稿し総合1位を獲得',
        'Product HuntでDay 1に1,000以上のUpvoteを獲得',
        '欧州の自治体やプライバシーに厳しいテック企業から初期の有料サポート契約を獲得',
      ],
      actionPlaybook: [
        'Step 1: 米国で流行っている高単価SaaS（Notion, Airtable, Slack等）の「セルフホスト可能代替品」を開発する',
        'Step 2: AGPLまたはMITライセンスでGitHubに公開し、Hacker NewsやRedditで拡散する',
        'Step 3: 大企業向けのSSO/SAML認証、監査ログ、権限管理を追加した有償Enterprise版を販売する',
      ],
      coldOutreachTemplate: '【Airtableからのデータ移行・オンプレミス運用の件】〇〇様、貴社で保有される機密データを自社クラウド内で完全に管理できるBaserowのご提案です。',
    },
    temporal: {
      foundedYear: 2019,
      initialTractionPeriod: '2019-2021年 (オープンソース公開・Hacker Newsバイラル期)',
      dataSnapshotPeriod: '2024-2026年 (Enterprise拡販期)',
      viabilityStatus: 'ACTIVE_PLAYBOOK',
      viabilityLabel: '現在も有効（オープンソース代替モデル）',
      eraContext: 'データプライバシー規制の強化と、米系SaaSの値上げラッシュ。',
      currentViabilityAnalysis: '企業の脱SaaS・オンプレミス回帰トレンドと完全に合致しており、現在も極めて強い成長トレンドにある。',
    },
  },

  // 11. Appwrite
  {
    id: 'ent_appwrite_a13f6ac291cc98223946',
    ticker: 'APP.WRIT',
    name: 'Appwrite',
    tagline: '「Firebaseの従量課金爆発とGoogleロックイン」に震えるCTOの財布を突き、Docker1発で動くセルフホストBaaSで年商15億円を吸い上げるインフラ関所',
    sector: 'AI_AUTOMATION',
    scale: 'SCALEUP',
    founder: 'Eldad Fux',
    country: 'IL',
    url: 'https://appwrite.io',
    verifiedBadge: true,
    growthRateYoY: 60.0,
    architecturePattern: 'オープンソースBaaS（バックエンド・アズ・ア・サービス）＋Cloud従量課金',
    pipelineStack: 'Docker × Microservices × Redis × MariaDB/PostgreSQL',
    targetPainWallet: '開発者・CTOの恐怖（「Firebaseの請求書が翌月1,000万円になったら破産する」）',
    tags: ['Firebase代替', 'BaaS', 'オープンソース', '開発者ツール', '巨大コミュニティ'],
    pnl: {
      monthlyRevenue: 125000000,
      cogs: 20000000,
      grossProfit: 105000000,
      grossMargin: 84.0,
      operatingExpenses: {
        serverAndApi: 10000000,
        advertising: 2500000,
        subcontracting: 45000000,
        toolsAndSaaS: 3000000,
        other: 6500000,
      },
      operatingProfit: 38000000,
      operatingMargin: 30.4,
      estimatedAnnualNetProfit: 456000000,
      financialStatus: 'ESTIMATED',
      isRevenueUnconfirmed: false,
      isMarginUnconfirmed: false,
      revenueLabel: 'Appwrite Cloud＋Enterprise商用契約（推計ARR $10M規模）',
      sourceDoc: 'Appwrite Cloud料金・Enterprise契約モデルと既存収集カード（一次数値の突合は未完了）',
      estimationLogic: '入力: Cloud契約とEnterprise契約の推定ARR。月商=推定ARR÷12、粗利益=月商−cogs、営業利益=粗利益−(serverAndApi＋advertising＋subcontracting＋toolsAndSaaS＋other)、年間純利益=営業利益×12。契約規模・原価・費用は推計で、実績P&Lではない。',
    },
    evidenceCards: [
      {
        id: 'ev_appwrite_loot_blueprint',
        type: 'LOOT_BLUEPRINT',
        title: '【略奪転用】Googleの独占インフラ（Firebase）の恐怖を煽って開発者を無料囲い込み、クラウド運用で課金する配管',
        badge: '略奪転用方程式',
        evidenceStatus: 'VERIFIED',
        punchline: '「Googleに魂を売るな」という開発者の反逆心に着火してGitHubで4万Starを集め、運用が面倒になった瞬間に自社クラウド版へ誘導して課金する。',
        details: [
          '【Step 1: 開発者の共通の敵（Firebase課金爆発）を設定】: 予期せぬトラフィックで巨額請求が来るFirebaseの「従量課金の恐怖」を徹底的に突く。',
          '【Step 2: 1行のDockerコマンドで感動体験】: `docker run` 一発でAuth、Database、Storage、Cloud Functionsが立ち上がる究極のDeveloper Experienceを提供。',
          '【Step 3: Appwrite Cloudのリリースで回収】: セルフホストのインフラ管理に疲弊したチーム向けに、完全マネージドのCloud版（Proプラン月額$15〜）を展開。',
        ],
        codeSnippet: '// Appwriteを1発でローカル起動するターミナルコマンド\ndocker run -it --rm \\\n  --volume /var/run/docker.sock:/var/run/docker.sock \\\n  --volume "$(pwd)"/appwrite:/usr/src/code/appwrite:rw \\\n  --entrypoint="install" \\\n  appwrite/appwrite:latest',
        sourceNote: 'Appwrite公式ドキュメントおよびCloud料金体系（Pro/Scaleプラン）からの抽出',
      },
      {
        id: 'ev_appwrite_crime',
        type: 'THE_CRIME',
        title: '「Google独占への抵抗」という崇高な大義名分を掲げ、開発者のインフラ予算を全自動で奪う手口',
        badge: '身も蓋もない真実',
        evidenceStatus: 'VERIFIED',
        punchline: 'エンジニアの「脱Google」というイデオロギーを燃料にしてコミュニティにタスクを無償でこなさせ、自らは高収益クラウドを運営する。',
        details: [
          'Hacktoberfestなどのイベントをハックし、世界中の学生やエンジニアにタダでSDKやドキュメントを拡充させた。',
          'オープンソースの信頼性を盾にしながら、実態はVC（Tiger Global等）から大型調達しSaaS化で回収する資本主義の王道。',
        ],
      },
    ],
    operations: {
      teamSize: 35,
      weeklyHours: 40,
      initialCapitalRequired: 0,
      automationLevel: 85,
      primaryChannels: ['GitHubオープンソース', 'Hacktoberfest / 開発者イベント', 'Discordコミュニティ'],
      toolStack: [
        { name: 'GitHub', category: '開発基盤', monthlyCost: 100000, purpose: '4万Starのオープンソースエコシステム運営' },
        { name: 'DigitalOcean / AWS', category: 'クラウド基盤', monthlyCost: 8000000, purpose: '全世界のAppwrite Cloudクラスター運用' },
        { name: 'Stripe', category: '決済基盤', monthlyCost: 0, purpose: '開発者サブスクと超過従量課金の自動回収' },
      ],
    },
    strategy: {
      blindspot: 'GoogleはFirebaseを「GCPへの囲い込みの餌」として扱っていたため、クロスプラットフォーム対応やオープンソースでの自由なホスティングを絶対に許可しなかった。',
      moatType: 'SWITCHING_COST',
      moatDescription: '数万のモバイルアプリ・Webサービスの認証（Auth）とデータベースを人質に取っているため、サービス停止＝アプリ死滅となり解約できない。',
      incumbentDilemma: 'GoogleがFirebaseをオープンソース化したり固定安価プランを出すと、自社の巨大なクラウド売上（GCP）を毀損するため絶対に真似できない。',
      secretInsight: 'エンジニアは「自由」を求めてオープンソースを選ぶが、実際にサービスが成長すると「サーバー管理の面倒さ」に耐えられず、最終的に公式クラウドに課金する。',
      initialTraction: [
        '創業者Eldadが個人プロジェクトとしてGitHubにリポジトリを公開',
        'Redditのr/programmingで「Firebase alternative built with Docker」として紹介され爆発的バイラル',
        'オープンソースのDiscordコミュニティが数万人規模に急成長',
      ],
      actionPlaybook: [
        'Step 1: BigTechが独占するプロプライエタリな開発インフラ（Firebase, Vercel, Supabase等）の代替をオープンソースで作る',
        'Step 2: 開発者が1秒で試せるローカル環境（Dockerコンテナ等）を極限まで磨く',
        'Step 3: コミュニティが10万人を超えた段階でマネージドクラウド版をローンチして収益化する',
      ],
      coldOutreachTemplate: '【Firebase移行によるインフラ費半減のご提案】〇〇様、貴社アプリの認証・DBコストを固定化し、クラウド破産リスクをゼロにするAppwriteのご案内です。',
    },
    temporal: {
      foundedYear: 2019,
      initialTractionPeriod: '2019-2021年 (GitHubスター急増期)',
      dataSnapshotPeriod: '2023-2026年 (Appwrite Cloud急拡大期)',
      viabilityStatus: 'RISING_WAVE',
      viabilityLabel: '急上昇トレンド最盛期（オープンソースBaaS）',
      eraContext: 'クラウド料金の高騰と、SupabaseやAppwriteなど「脱Firebase」が業界標準となった時代。',
      currentViabilityAnalysis: '開発者ツールのオープンソース化は現在最も資本が集まる領域であり、AI連携（Vector DB対応等）によりさらに市場が拡大している。',
    },
  },

  // 12. Activepieces
  {
    id: 'ent_activepieces_e79ea75946468156aa9f',
    ticker: 'ACTV.PIEC',
    name: 'Activepieces',
    tagline: '「Zapierのタスク消費課金で毎月数十万溶ける」自動化担当者の怒りを突き、無制限セルフホスト可能なオープンソース自動化で年商4.5億円抜くZapierキラー',
    sector: 'AI_AUTOMATION',
    scale: 'SMALL_TEAM',
    founder: 'Mohammad AbuAboud, Ashraf Samhouri',
    country: 'US',
    url: 'https://www.activepieces.com',
    verifiedBadge: true,
    growthRateYoY: 70.0,
    architecturePattern: 'オープンソース（セルフホスト・無制限実行）＋Enterpriseクラウドサブスク',
    pipelineStack: 'TypeScript × Node.js × Angular × Docker',
    targetPainWallet: '企業の自動化担当者・受託会社の激怒（「Zapierでタスクがループして請求書が50万円跳ね上がった」）',
    tags: ['Zapierキラー', 'ワークフロー自動化', 'オープンソース', 'YC採択', 'AI自動化'],
    pnl: {
      monthlyRevenue: 37500000,
      cogs: 4500000,
      grossProfit: 33000000,
      grossMargin: 88.0,
      operatingExpenses: {
        serverAndApi: 2000000,
        advertising: 1000000,
        subcontracting: 15000000,
        toolsAndSaaS: 1500000,
        other: 2500000,
      },
      operatingProfit: 11000000,
      operatingMargin: 29.3,
      estimatedAnnualNetProfit: 132000000,
      financialStatus: 'ESTIMATED',
      isRevenueUnconfirmed: false,
      isMarginUnconfirmed: false,
      revenueLabel: 'Cloudサブスク＋Enterpriseオンプレライセンス（推計ARR $3M）',
      sourceDoc: 'Activepieces公開料金・Enterpriseライセンスと既存収集カード（一次数値の突合は未完了）',
      estimationLogic: '入力: CloudサブスクとEnterpriseライセンスの推定ARR。月商=推定ARR÷12、粗利益=月商−cogs、営業利益=粗利益−(serverAndApi＋advertising＋subcontracting＋toolsAndSaaS＋other)、年間純利益=営業利益×12。契約規模・原価・費用は推計で、実績P&Lではない。',
    },
    evidenceCards: [
      {
        id: 'ev_activepieces_loot_blueprint',
        type: 'LOOT_BLUEPRINT',
        title: '【略奪転用】メガツールの「不当なタスク課金モデル」を批判してオープンソース化し、受託会社を味方につける配管',
        badge: '略奪転用方程式',
        evidenceStatus: 'VERIFIED',
        punchline: 'Zapierの高額課金に苦しむ代理店・フリーランスに「自分のサーバーで無制限に自動化を回せるツール」を渡し、彼らを自社の営業マン（共犯者）に仕立て上げる。',
        details: [
          '【Step 1: Zapierの急所（タスク単価高すぎ問題）を突く】: 1タスクごとに数円〜十数円かかるZapierの不条理を徹底的に可視化。',
          '【Step 2: TypeScriptで誰でもピース（連携機能）が作れる設計】: 外部開発者が自分の好きなサービス（Slack, Notion, ChatGPT等）のコネクタを簡単に自作できるオープンソースを公開。',
          '【Step 3: 企業向けチーム機能・監査ログで課金】: 個人は無料で使い放題にし、受託会社や大企業がクライアントに提供する際に必要なマルチテナント機能を有料販売。',
        ],
        codeSnippet: '// ActivepiecesのTypeScriptベースのカスタムアクション定義\nimport { createAction, Property } from "@activepieces/pieces-framework";\nexport const sendLootAlert = createAction({\n  name: "send_loot_alert",\n  displayName: "Send Loot Alert",\n  props: { message: Property.ShortText({ displayName: "Alert Message", required: true }) },\n  async run(context) { return { status: "DISPATCHED", payload: context.propsValue.message }; }\n});',
        sourceNote: 'Activepieces公式料金ページおよびGitHub piecesリポジトリからの抽出',
      },
      {
        id: 'ev_activepieces_crime',
        type: 'THE_CRIME',
        title: 'Zapierが10年以上かけて開拓した「ノーコード自動化市場」をTypeScriptオープンソースで獲得する手口',
        badge: '身も蓋もない真実',
        evidenceStatus: 'VERIFIED',
        punchline: '「Zapierは高すぎる」という世界中の開発者の愚痴を吸い上げ、Y Combinatorの看板を使って一気にエンタープライズ顧客を奪い去る。',
        details: [
          '自社開発者だけでなく、オープンソースコミュニティに「コネクタ（Piece）」を量産させることで、Zapierの最大の堀であった「連携アプリ数の多さ」を急速に無力化。',
          'オンプレミスで動くため、医療や金融など「Zapierに顧客データを流すことが法律で禁じられている」業界を総取り。',
        ],
      },
    ],
    operations: {
      teamSize: 12,
      weeklyHours: 40,
      initialCapitalRequired: 0,
      automationLevel: 85,
      primaryChannels: ['Y Combinatorネットワーク', 'GitHubオープンソース', '受託代理店パートナーシップ'],
      toolStack: [
        { name: 'GitHub', category: 'コード基盤', monthlyCost: 35000, purpose: '1万Star超のオープンソースコミュニティ運営' },
        { name: 'AWS / GCP', category: 'クラウドインフラ', monthlyCost: 1500000, purpose: 'Activepieces Cloudホスティング' },
        { name: 'Stripe', category: '決済基盤', monthlyCost: 0, purpose: '月額プランおよび年額前払い決済' },
      ],
    },
    strategy: {
      blindspot: 'Zapierは「非エンジニア向けSaaS」として大成功したため、コードを書けるエンジニアが求める「セルフホストしたい」「TypeScriptで直接コネクタを書きたい」という開発者体験を完全に無視していた。',
      moatType: 'NETWORK_EFFECT',
      moatDescription: '世界中の開発者が新しいAPIの「Piece（連携モジュール）」をオープンソースで勝手に開発してエコシステムに追加してくれるネットワーク効果。',
      incumbentDilemma: 'Zapierがタスク無制限プランやセルフホスト版を出すと、数十億ドルのARRの根幹である「タスク消費従量課金」が自爆するため絶対に対抗できない。',
      secretInsight: '自動化ツールで最も重要なのは「ツール自体の機能」ではない。「どのサービスと繋がるか」であり、オープンソースはコネクタ開発を世界中に分散外注できる圧倒的なレバレッジである。',
      initialTraction: [
        'Y Combinator（W23）に採択され、シード資金とスタートアップネットワークを獲得',
        'GitHubでオープンソース公開後、数ヶ月で10,000 Starを突破',
        '受託自動化エージェンシーが「Zapierの代わりにクライアントに導入するツール」として自発的に布教開始',
      ],
      actionPlaybook: [
        'Step 1: 既存のメガSaaS（Zapier, Make, Segment等）の「タスク従量課金」に不満を持つユーザーコミュニティを特定する',
        'Step 2: モダンな技術スタック（TypeScript/Docker）でセルフホスト可能なオープンソースクローンを作る',
        'Step 3: 外部開発者がプラグインを作れる仕組みを用意し、エコシステムの拡大を加速させる',
      ],
      coldOutreachTemplate: '【Zapier利用料の80%削減・無制限タスク自動化の件】〇〇様、貴社で利用されているZapierのタスク制限を撤廃し、オンプレミスで安全に自動化を回せるActivepiecesのご案内です。',
    },
    temporal: {
      foundedYear: 2022,
      initialTractionPeriod: '2022-2023年 (YC採択・オープンソースバイラル期)',
      dataSnapshotPeriod: '2024-2026年 (急成長Cloud・Enterprise期)',
      viabilityStatus: 'RISING_WAVE',
      viabilityLabel: '急上昇トレンド最盛期（AI＋ワークフロー自動化）',
      eraContext: 'Zapierの値上げと、LLM/AIを活用した自律ワークフロー自動化の爆発的需要。',
      currentViabilityAnalysis: 'AIエージェントの普及に伴い、APIを繋ぐバックボーンとしてのオープンソース自動化基盤の需要は過去最高に達している。',
    },
  },
];
