import { getCatalogManifest, getCatalogMembership, getResolvedManifest } from './release-manifest';
import { CatalogUnavailableError, decodeCatalogArtifact, readStoredArtifact } from './release-store';
import { getDossierStoragePath } from '@/lib/foundation/dossier-projection';
import { parseFinancialEntitiesResiliently } from '@/shared/financial-entity-schema';
import { isPublishableEntity } from './public-entity';
import { toPatternCase, type PatternCase, type PatternSourceCase } from './case-patterns';
import type { FinancialEntity } from '@/shared/terminal';
import type { DiscoveryDataset } from '@/features/discover';

const DISCOVERY_SCORE_KEYS = ['SURPRISE', 'BIG_CASH', 'LOW_CAPITAL', 'SOLO', 'LOW_WORK', 'CURRENT', 'FAILURE'] as const;

function isDiscoveryCase(value: unknown): boolean {
  if (!isRecord(value)) return false;
  const descriptorsValid = Array.isArray(value.descriptors)
    && value.descriptors.every((item) => isRecord(item)
      && typeof item.label === 'string'
      && typeof item.value === 'string');
  const scores = isRecord(value.scores) ? value.scores : null;
  const scoresValid = scores !== null
    && DISCOVERY_SCORE_KEYS.every((key) => typeof scores[key] === 'number'
      && Number.isFinite(scores[key] as number));
  return typeof value.id === 'string' && value.id.length > 0
    && typeof value.name === 'string' && value.name.length > 0
    && typeof value.tagline === 'string'
    && typeof value.sector === 'string'
    && typeof value.resultLabel === 'string'
    && typeof value.resultValue === 'string'
    && (value.resultAmountJpy === null || typeof value.resultAmountJpy === 'number')
    && typeof value.resultEvidenceLabel === 'string'
    && ['resultPeriod', 'resultSource', 'resultPeriodNote'].every((key) => value[key] === null || typeof value[key] === 'string')
    && typeof value.startLine === 'string'
    && typeof value.criticalInsight === 'string'
    && typeof value.whyMoneyMoved === 'string'
    && typeof value.leverage === 'string'
    && typeof value.currentLabel === 'string'
    && typeof value.currentDetail === 'string'
    && ['isCurrent', 'isFailure', 'isSolo', 'lowCapital', 'lowWork'].every((key) => typeof value[key] === 'boolean')
    && typeof value.evidenceCount === 'number'
    && descriptorsValid
    && scoresValid;
}

export function parseDiscoveryRelease(value: unknown): DiscoveryDataset {
  if (!isRecord(value)
    || !Number.isInteger(value.sourceCount) || Number(value.sourceCount) < 0
    || !Number.isInteger(value.visibleCount) || Number(value.visibleCount) < 0
    || !Array.isArray(value.cases) || !value.cases.every(isDiscoveryCase)
    || Number(value.visibleCount) !== value.cases.length
    || !Array.isArray(value.highlights) || !value.highlights.every(isDiscoveryCase)) {
    throw new Error('Invalid discovery release');
  }
  return value as unknown as DiscoveryDataset;
}

// 版（manifest）は実行時に目印から決まる。要約・探索・傾向は、版の指紋ごとに isolate 内で1回だけ読む（古い版は捨てる）。
// 失敗は覚えない。
export { CatalogUnavailableError, decodeCatalogArtifact };

/** 指紋ごとに1回だけ読む入れ物。指紋が変わったら（版が進んだら）読み直す。失敗は覚えない。 */
class Slot<T> {
  private entry: { key: string; value: Promise<T> } | undefined;
  get(key: string, load: () => Promise<T>): Promise<T> {
    if (this.entry?.key === key) return this.entry.value;
    const entry = { key, value: load() };
    this.entry = entry;
    entry.value.catch(() => { if (this.entry === entry) this.entry = undefined; });
    return entry.value;
  }
  clear(): void { this.entry = undefined; }
}

const discovery = new Slot<DiscoveryDataset>();
export async function readReleaseDiscovery(): Promise<DiscoveryDataset> {
  const manifest = await getCatalogManifest();
  return discovery.get(manifest.discovery.hash, async () => parseDiscoveryRelease(await readStoredArtifact(manifest.discovery.key, manifest.discovery.hash)));
}

const summaries = new Slot<FinancialEntity[]>();

function isRecord(value: unknown): value is Record<string, unknown> {
  return Boolean(value) && typeof value === 'object' && !Array.isArray(value);
}

/**
 * The accepted catalog artifact is immutable and its SHA-256 is verified before
 * this function runs. It is generated by `catalog:prepare`, which validates the
 * full FinancialEntity schema before publishing. Re-running the full AJV
 * FinancialEntity validator on all 3,085 rows in every cold Worker isolate is
 * needlessly expensive and can hit the Cloudflare CPU limit (1102), taking the
 * catalog API down even though the artifact is valid.
 *
 * Keep a cheap runtime boundary for the fields the paged catalog actually reads.
 * This preserves fail-closed behavior for malformed/corrupt artifacts without
 * turning every request into a full dossier validation pass.
 */
export function parseCatalogSummaryRows(value: unknown, expectedCount: number): FinancialEntity[] {
  if (!Array.isArray(value) || value.length !== expectedCount) {
    throw new Error('Invalid catalog summary release count');
  }

  const ids = new Set<string>();
  return value.map((row, index) => {
    if (!isRecord(row)
      || typeof row.id !== 'string'
      || row.id.length === 0
      || typeof row.name !== 'string'
      || row.name.length === 0
      || typeof row.ticker !== 'string'
      || typeof row.tagline !== 'string'
      || typeof row.sector !== 'string'
      || typeof row.scale !== 'string'
      || (row.founder !== undefined && typeof row.founder !== 'string')
      || !isRecord(row.pnl)
      || typeof row.pnl.operatingMargin !== 'number'
      || !isRecord(row.operations)
      || typeof row.operations.initialCapitalRequired !== 'number'
      || (row.operations.isCapitalUnconfirmed !== undefined && typeof row.operations.isCapitalUnconfirmed !== 'boolean')
      || !isRecord(row.strategy)
      || typeof row.strategy.moatType !== 'string'
      || typeof row.strategy.blindspot !== 'string'
      || !Array.isArray(row.tags)
      || !row.tags.every((tag) => typeof tag === 'string')
      || (row.batchId !== undefined && typeof row.batchId !== 'string')) {
      throw new Error(`Invalid catalog summary row at index ${index}`);
    }
    if (ids.has(row.id)) throw new Error(`Duplicate catalog summary id: ${row.id}`);
    ids.add(row.id);
    return row as unknown as FinancialEntity;
  });
}

export async function readReleaseSummaries(): Promise<FinancialEntity[]> {
  const { manifest, membership } = await getResolvedManifest();
  return summaries.get(manifest.summaries.hash, async () => {
    const value = await readStoredArtifact(manifest.summaries.key, manifest.summaries.hash);
    return membership.filterToCatalog(parseCatalogSummaryRows(value, manifest.publishedCount));
  });
}

// 公開版の詳細はハッシュで中身が決まる（不変）。同じ isolate では1事例につき1回だけ読み、展開・検査する。
// Workers は1要求あたりの CPU 時間が短いため、要求のたびに gunzip・ハッシュ照合・スキーマ検査をやり直さない。
// 上限つき（古い順に捨てる）。公開中の事例数より少し多い程度に抑え、isolate のメモリを増やし続けない。
const RELEASE_ENTITY_CACHE_LIMIT = 128;
const releaseEntities = new Map<string, Promise<FinancialEntity>>();

export async function findReleaseEntity(id: string): Promise<FinancialEntity | null> {
  const membership = await getCatalogMembership();
  const canonicalId = membership.canonicalCatalogId(id);
  const hash = membership.catalogDetailHash(id);
  if (!canonicalId || !hash) return null;
  const cacheKey = `${canonicalId}:${hash}`;
  let pending = releaseEntities.get(cacheKey);
  if (pending) {
    // 最近使った順に並べ直す
    releaseEntities.delete(cacheKey);
    releaseEntities.set(cacheKey, pending);
  } else {
    pending = readStoredArtifact(getDossierStoragePath(canonicalId, hash), hash).then((value) => {
      const parsed = parseFinancialEntitiesResiliently([value]);
      const entity = parsed.validEntities[0];
      if (!entity || entity.id !== canonicalId || !isPublishableEntity(entity)) throw new Error('Invalid catalog dossier');
      return entity;
    });
    // 失敗（R2 の一時的な不調など）は覚えない。次の要求で読み直す
    pending.catch(() => releaseEntities.delete(cacheKey));
    if (releaseEntities.size >= RELEASE_ENTITY_CACHE_LIMIT) {
      releaseEntities.delete(releaseEntities.keys().next().value as string);
    }
    releaseEntities.set(cacheKey, pending);
  }
  return pending;
}

/** テスト用: 詳細・要約・探索・傾向の isolate 内キャッシュを空にする。 */
export function clearReleaseEntityCacheForTest(): void {
  releaseEntities.clear();
  discovery.clear();
  summaries.clear();
  patternCases.clear();
}

export async function releaseApprovalCandidateIds(): Promise<Set<string>> {
  return new Set((await getCatalogManifest()).approvalCandidateIds);
}

// 傾向画面用。公開目録の全事例の詳細（reader だけ）を読み、軽い形にして isolate 内に覚える。
// 詳細は不変（ハッシュで決まる）なので、同じ版の間は1回だけ読む。失敗は覚えない。
const patternCases = new Slot<PatternCase[]>();

export async function readReleasePatternCases(): Promise<PatternCase[]> {
  const { manifest, membership, manifestHash } = await getResolvedManifest();
  // 詳細だけが変わった版でも作り直すよう、要約ではなく目録全体の指紋で覚える
  return patternCases.get(manifestHash ?? `bundled:${manifest.summaries.hash}`, async () => {
      const rows = await readReleaseSummaries();
      const out: PatternCase[] = [];
      const queue = [...rows];
      const worker = async () => {
        for (let row = queue.shift(); row; row = queue.shift()) {
          const hash = membership.catalogDetailHash(row.id);
          if (!hash) throw new CatalogUnavailableError('Catalog detail hash is missing');
          const detail = await readStoredArtifact(getDossierStoragePath(row.id, hash), hash);
          if (!isRecord(detail) || detail.id !== row.id) throw new CatalogUnavailableError('Invalid catalog dossier');
          out.push(toPatternCase({
            id: row.id,
            name: row.name,
            sector: typeof detail.sector === 'string' ? detail.sector : row.sector,
            tags: Array.isArray(detail.tags) ? detail.tags.filter((t): t is string => typeof t === 'string') : [],
            reader: isRecord(detail.reader) ? (detail.reader as PatternSourceCase['reader']) : undefined,
          }));
        }
      };
      await Promise.all(Array.from({ length: 8 }, worker));
      return out.sort((a, b) => a.id.localeCompare(b.id));
  });
}
