import { createHash } from 'node:crypto';
import { gunzipSync } from 'node:zlib';
import manifest from '../../../data/catalog-release.json';
import { getCloudflareRuntimeEnv } from '@/lib/runtime/cloudflare';
import { getFoundationBucketAsync, readR2Object } from '@/lib/storage/r2';
import { getDossierStoragePath } from '@/lib/foundation/dossier-projection';
import { parseFinancialEntitiesResiliently } from '@/shared/financial-entity-schema';
import { isPublishableEntity } from './public-entity';
import type { FinancialEntity } from '@/shared/terminal';
import type { DiscoveryDataset } from '@/features/discover';
import { compileParser } from '@/shared/validate-json';
import discoverySchema from './schemas/discovery-dataset.json';

const parseDiscovery = compileParser<DiscoveryDataset>(discoverySchema, 'DiscoveryDataset');
export async function readReleaseDiscovery(): Promise<DiscoveryDataset> {
  return parseDiscovery(await readArtifact(manifest.discovery.key, manifest.discovery.hash));
}

export async function usesCatalogRelease(): Promise<boolean> {
  // next dev installs an emulated Cloudflare context with the production vars.
  // Local editing must still read the working-tree JSON, not private remote R2.
  if (process.env.NODE_ENV === 'development') return false;
  const env = await getCloudflareRuntimeEnv();
  return env?.ENVIRONMENT === 'production';
}

export function decodeCatalogArtifact(bytes: Uint8Array, expectedHash: string): unknown {
  const json = gunzipSync(bytes, { maxOutputLength: 24 * 1024 * 1024 });
  if (createHash('sha256').update(json).digest('hex') !== expectedHash) throw new Error('Catalog artifact hash mismatch');
  return JSON.parse(json.toString('utf8')) as unknown;
}

async function readArtifact(key: string, hash: string): Promise<unknown> {
  if (!key || !/^[a-f0-9]{64}$/.test(hash)) throw new Error('Catalog release has not been prepared');
  const object = await readR2Object(await getFoundationBucketAsync('lake'), key);
  if (!object) throw new Error('Catalog release object is missing');
  return decodeCatalogArtifact(object.body, hash);
}

let summaries: Promise<FinancialEntity[]> | undefined;

function isRecord(value: unknown): value is Record<string, unknown> {
  return Boolean(value) && typeof value === 'object' && !Array.isArray(value);
}

/**
 * The accepted catalog artifact is immutable and its SHA-256 is verified before
 * this function runs. It is generated by `catalog:prepare`, which validates the
 * full FinancialEntity schema before publishing. Re-running the full AJV
 * FinancialEntity validator on all 3,085 rows in every cold Worker isolate is
 * needlessly expensive and can hit the Cloudflare CPU limit (1102), taking the
 * catalog API down even though the artifact is valid.
 *
 * Keep a cheap runtime boundary for the fields the paged catalog actually reads.
 * This preserves fail-closed behavior for malformed/corrupt artifacts without
 * turning every request into a full dossier validation pass.
 */
export function parseCatalogSummaryRows(value: unknown, expectedCount: number): FinancialEntity[] {
  if (!Array.isArray(value) || value.length !== expectedCount) {
    throw new Error('Invalid catalog summary release count');
  }

  const ids = new Set<string>();
  return value.map((row, index) => {
    if (!isRecord(row)
      || typeof row.id !== 'string'
      || row.id.length === 0
      || typeof row.name !== 'string'
      || row.name.length === 0
      || typeof row.ticker !== 'string'
      || !isRecord(row.pnl)
      || typeof row.pnl.operatingMargin !== 'number'
      || !isRecord(row.operations)
      || typeof row.operations.initialCapitalRequired !== 'number'
      || !isRecord(row.strategy)
      || typeof row.strategy.moatType !== 'string'
      || !Array.isArray(row.tags)) {
      throw new Error(`Invalid catalog summary row at index ${index}`);
    }
    if (ids.has(row.id)) throw new Error(`Duplicate catalog summary id: ${row.id}`);
    ids.add(row.id);
    return row as unknown as FinancialEntity;
  });
}

export async function readReleaseSummaries(): Promise<FinancialEntity[]> {
  if (!summaries) {
    summaries = readArtifact(manifest.summaries.key, manifest.summaries.hash).then((value) => {
      const result = parseCatalogSummaryRows(value, manifest.publishedCount);
      const featuredIdx = result.findIndex((entity) => entity.id === 'ent_photoai');
      if (featuredIdx > 0) result.unshift(...result.splice(featuredIdx, 1));
      return result;
    }).catch((error) => { summaries = undefined; throw error; });
  }
  return summaries;
}

export async function findReleaseEntity(id: string): Promise<FinancialEntity | null> {
  const details: Record<string, string> = manifest.details;
  const canonicalId = Object.keys(details).find((key) => key.toLowerCase() === id.toLowerCase());
  if (!canonicalId) return null;
  const hash = details[canonicalId];
  const value = await readArtifact(getDossierStoragePath(canonicalId, hash), hash);
  const parsed = parseFinancialEntitiesResiliently([value]);
  const entity = parsed.validEntities[0];
  if (!entity || entity.id !== canonicalId || !isPublishableEntity(entity)) throw new Error('Invalid catalog dossier');
  return entity;
}

export function releaseApprovalCandidateIds(): Set<string> {
  return new Set(manifest.approvalCandidateIds);
}

/** Check release membership without reading the full dossier from R2. */
export function hasCatalogReleaseEntity(id: string): boolean {
  const normalizedId = id.trim().toLowerCase();
  if (!normalizedId) return false;
  return Object.keys(manifest.details).some((candidate) => candidate.toLowerCase() === normalizedId);
}
