export const DEMO_MODE = true;

export const categories = [
  { id: 'ai-automation', label: 'AI・自動化', icon: 'AI', description: '人手で行われている反復業務を置き換える市場' },
  { id: 'vertical-saas', label: '業界特化SaaS', icon: 'VS', description: '業界固有の面倒を月額課金で解決する市場' },
  { id: 'commerce', label: 'EC・販売支援', icon: 'EC', description: '売る人の売上・利益・運用を改善する市場' },
  { id: 'creator', label: 'クリエイター', icon: 'CR', description: '発信・販売・コミュニティ運営を支援する市場' },
  { id: 'regulation', label: '制度・規制対応', icon: 'RG', description: '変更対応が必須になるため支払意思が生まれる市場' },
  { id: 'local-business', label: '地域・店舗', icon: 'LB', description: '現場の人手不足や集客を改善する市場' },
  { id: 'developer-tools', label: '開発者ツール', icon: 'DT', description: '開発速度・品質・運用コストを改善する市場' },
  { id: 'data-intelligence', label: 'データ・調査', icon: 'DI', description: '判断に必要な情報を集約・比較・監視する市場' }
];

export const signals = [
  {
    id: 'signal-invoice-vertical',
    title: '小規模事業者向け請求業務に継続課金が集中',
    amount: 240000000,
    amountLabel: '推定年間売上 2.4億円',
    type: 'revenue',
    typeLabel: '顧客売上',
    sourceType: 'owner-disclosure',
    evidenceGrade: 'B',
    date: '2026-08-28',
    summary: '複雑な会計ソフトではなく、請求書作成と入金確認だけに絞ったサービスが小規模事業者から支持された。',
    payer: '小規模事業者',
    receiver: '少人数SaaS運営会社',
    category: 'vertical-saas',
    region: 'global',
    sourceName: '運営者開示・料金ページ・利用者推移',
    sourceUrl: '',
    confidence: 78,
    opportunityIds: ['op-invoice-niches'],
    verified: true,
    demo: true
  },
  {
    id: 'signal-ai-reception',
    title: '電話受付の人手不足を背景にAI受付への支出が増加',
    amount: 48000000,
    amountLabel: '観測契約総額 4,800万円',
    type: 'contract',
    typeLabel: '契約額',
    sourceType: 'public-contracts',
    evidenceGrade: 'A',
    date: '2026-08-26',
    summary: '営業時間外対応、取りこぼし削減、録音要約を目的に、店舗・小規模事業者がAI電話受付を導入している。',
    payer: '地域企業・店舗',
    receiver: 'AI電話受付事業者',
    category: 'ai-automation',
    region: 'japan',
    sourceName: '公開契約・導入発表',
    sourceUrl: '',
    confidence: 86,
    opportunityIds: ['op-ai-reception-vertical'],
    verified: true,
    demo: true
  },
  {
    id: 'signal-shopify-returns',
    title: '返品・交換の自動化アプリにEC事業者の月額課金が移動',
    amount: 98000000,
    amountLabel: '推定ARR 9,800万円',
    type: 'arr',
    typeLabel: '年間継続売上',
    sourceType: 'connected-metrics',
    evidenceGrade: 'B',
    date: '2026-08-24',
    summary: '売上拡大後に発生する返品対応の人件費を減らすアプリが、Shopify事業者の継続支出を獲得した。',
    payer: '中小EC事業者',
    receiver: 'Shopifyアプリ運営者',
    category: 'commerce',
    region: 'global',
    sourceName: '接続指標・公開価格・導入店舗数',
    sourceUrl: '',
    confidence: 74,
    opportunityIds: ['op-japan-return-ops'],
    verified: true,
    demo: true
  },
  {
    id: 'signal-regulation-docs',
    title: '新制度対応で中小企業の文書作成・確認費用が急増',
    amount: 3200000000,
    amountLabel: '関連支出推計 32億円',
    type: 'market-spend',
    typeLabel: '市場支出',
    sourceType: 'government-data',
    evidenceGrade: 'A',
    date: '2026-08-22',
    summary: '制度変更に伴い、専門家相談、書類作成、教育、監査対応へ支出が集中。小規模企業向けの簡易支援が不足している。',
    payer: '制度対応が必要な中小企業',
    receiver: '士業・コンサル・業務ソフト',
    category: 'regulation',
    region: 'japan',
    sourceName: '公的統計・調達・事業者調査',
    sourceUrl: '',
    confidence: 91,
    opportunityIds: ['op-compliance-copilot'],
    verified: true,
    demo: true
  },
  {
    id: 'signal-clinic-cancel',
    title: '無断キャンセル対策に医療・美容店舗の予算が発生',
    amount: 12000000,
    amountLabel: '観測月額支出 1,200万円',
    type: 'market-spend',
    typeLabel: '市場支出',
    sourceType: 'survey-and-pricing',
    evidenceGrade: 'B',
    date: '2026-08-19',
    summary: '予約枠の損失を防ぐため、事前決済、リマインド、キャンセル待ち自動充当へ支出が生まれている。',
    payer: 'クリニック・美容店舗',
    receiver: '予約・決済SaaS',
    category: 'local-business',
    region: 'japan',
    sourceName: '料金ページ・導入事例・事業者調査',
    sourceUrl: '',
    confidence: 72,
    opportunityIds: ['op-clinic-cancel-fill'],
    verified: true,
    demo: true
  },
  {
    id: 'signal-dev-observability',
    title: '小規模開発チームが高価な監視ツールから離脱',
    amount: 67000000,
    amountLabel: '置換対象ARR 6,700万円',
    type: 'switching-spend',
    typeLabel: '乗換支出',
    sourceType: 'pricing-and-reviews',
    evidenceGrade: 'B',
    date: '2026-08-18',
    summary: '従量課金の予測不能さに不満が集まり、必要機能だけを固定料金で提供する軽量ツールが伸びている。',
    payer: '個人開発者・小規模チーム',
    receiver: '軽量監視ツール運営者',
    category: 'developer-tools',
    region: 'global',
    sourceName: '価格変更履歴・レビュー・移行事例',
    sourceUrl: '',
    confidence: 76,
    opportunityIds: ['op-simple-observability'],
    verified: true,
    demo: true
  },
  {
    id: 'signal-micro-acquisition',
    title: '小規模Web事業の売買が個人間でも定着',
    amount: 185000000,
    amountLabel: '観測成約総額 1.85億円',
    type: 'acquisition',
    typeLabel: '事業売買',
    sourceType: 'marketplace',
    evidenceGrade: 'A',
    date: '2026-08-15',
    summary: '月数万円から数十万円の利益があるサイト・アプリを、ゼロから作らず買う需要が増えている。',
    payer: '個人買収者・中小企業',
    receiver: '個人開発者・サイト運営者',
    category: 'data-intelligence',
    region: 'japan',
    sourceName: '公開成約統計',
    sourceUrl: '',
    confidence: 93,
    opportunityIds: ['op-micro-acquisition-intel'],
    verified: true,
    demo: true
  },
  {
    id: 'signal-creator-sponsor',
    title: '小規模ニュースレターにもスポンサー予算が流入',
    amount: 36000000,
    amountLabel: '観測年間広告費 3,600万円',
    type: 'ad-spend',
    typeLabel: '広告支出',
    sourceType: 'media-kit',
    evidenceGrade: 'B',
    date: '2026-08-12',
    summary: '大規模媒体よりも、購入意欲が明確な狭い読者層へ直接届ける広告が選ばれている。',
    payer: 'B2Bソフトウェア企業',
    receiver: '専門ニュースレター運営者',
    category: 'creator',
    region: 'global',
    sourceName: '媒体資料・公開スポンサー枠',
    sourceUrl: '',
    confidence: 70,
    opportunityIds: ['op-niche-newsletter-market'],
    verified: true,
    demo: true
  },
  {
    id: 'signal-review-intent',
    title: '比較・レビュー閲覧行動そのものが企業向けデータ商品化',
    amount: 410000000,
    amountLabel: '関連契約推計 4.1億円',
    type: 'data-revenue',
    typeLabel: 'データ売上',
    sourceType: 'pricing-and-filings',
    evidenceGrade: 'B',
    date: '2026-08-10',
    summary: 'どの企業が何を比較しているかという購買意向が、営業優先順位を決める高単価データになっている。',
    payer: 'B2Bベンダー',
    receiver: '比較・レビューDB',
    category: 'data-intelligence',
    region: 'global',
    sourceName: '料金・製品仕様・公開開示',
    sourceUrl: '',
    confidence: 82,
    opportunityIds: ['op-intent-for-small-vendors'],
    verified: true,
    demo: true
  },
  {
    id: 'signal-field-photo',
    title: '現場写真の整理・報告に建設事業者が継続支出',
    amount: 150000000,
    amountLabel: '推定年間支出 1.5億円',
    type: 'market-spend',
    typeLabel: '市場支出',
    sourceType: 'contracts-and-pricing',
    evidenceGrade: 'A',
    date: '2026-08-08',
    summary: '撮影、分類、台帳転記、報告書作成が現場ごとに発生し、スマートフォン中心の簡易化需要が強い。',
    payer: '工務店・設備会社',
    receiver: '現場管理ソフト・代行会社',
    category: 'vertical-saas',
    region: 'japan',
    sourceName: '公開調達・価格・導入事例',
    sourceUrl: '',
    confidence: 88,
    opportunityIds: ['op-field-photo-report'],
    verified: true,
    demo: true
  }
];

export const opportunities = [
  {
    id: 'op-invoice-niches',
    slug: 'invoice-niches',
    title: '業種別「請求・入金確認だけ」SaaS',
    hook: '複雑な会計ソフトを嫌う小規模事業者へ、必要な機能だけを売る。',
    summary: '汎用会計では拾えない業界固有の請求ルール、回収連絡、証憑共有を一つに絞る機会。',
    category: 'vertical-saas',
    region: 'japan',
    stage: 'validated',
    status: 'gold-window',
    moneyLabel: '年間2.4億円規模の先行事例',
    moneyValue: 240000000,
    moneyType: 'revenue-proof',
    momentum: 84,
    gapScore: 82,
    buildability: 86,
    evidenceGrade: 'B',
    freshnessDays: 4,
    soloFriendly: true,
    budgetBand: '10万円以下',
    timeToMvp: '3〜5週間',
    tags: ['1人開発', 'サブスク', '日本語特化', '業界特化'],
    reasons: ['会計ソフトが過剰機能', '毎月発生する必須業務', '業界ごとの書式差が大きい'],
    openings: ['訪問介護の請求確認', '小規模工務店の出来高請求', '外国人事業者向け日本語支援'],
    risks: ['会計・税務の断定表現を避ける', '既存ソフトとのデータ連携が必要', '業界選定を誤ると単価が低い'],
    nextSteps: ['候補業界3つの請求フローを聞く', '月額5,000円以上払う困り事を確認', 'CSV取込だけの試作品を作る'],
    signalIds: ['signal-invoice-vertical'],
    serviceIds: ['service-billrail'],
    demandIds: ['demand-care-invoice'],
    createdAt: '2026-08-29',
    trend: [34, 42, 44, 52, 60, 68, 84],
    featured: true
  },
  {
    id: 'op-ai-reception-vertical',
    slug: 'ai-reception-vertical',
    title: '業界特化AI電話受付',
    hook: '電話を取れない時間に失っている予約・問い合わせを、自動で売上へ戻す。',
    summary: '汎用AI電話ではなく、業界用語・予約項目・緊急度判定を事前設定した小規模事業者向け受付。',
    category: 'ai-automation',
    region: 'japan',
    stage: 'growing',
    status: 'gold-window',
    moneyLabel: '観測契約4,800万円',
    moneyValue: 48000000,
    moneyType: 'contract-proof',
    momentum: 91,
    gapScore: 79,
    buildability: 68,
    evidenceGrade: 'A',
    freshnessDays: 6,
    soloFriendly: true,
    budgetBand: '10〜50万円',
    timeToMvp: '4〜8週間',
    tags: ['AI', '音声', '店舗', '継続課金'],
    reasons: ['人手不足', '営業時間外の取りこぼし', '電話応対品質のばらつき'],
    openings: ['歯科の初診受付', '不動産内見予約', '修理業者の緊急度振り分け'],
    risks: ['誤認識時の引継ぎ設計', '個人情報・録音同意', '電話番号原価'],
    nextSteps: ['1業界に限定して会話台本を作る', '取りこぼし件数を10社に確認', '人へ転送する失敗時動線を先に作る'],
    signalIds: ['signal-ai-reception'],
    serviceIds: ['service-callmint'],
    demandIds: ['demand-dental-phone'],
    createdAt: '2026-08-27',
    trend: [28, 35, 48, 55, 67, 74, 91],
    featured: true
  },
  {
    id: 'op-japan-return-ops',
    slug: 'japan-return-ops',
    title: '日本向け返品・交換オペレーション自動化',
    hook: '売れた後に発生する面倒を減らす。EC成長企業ほど痛みが大きい。',
    summary: '返品申請、条件判定、配送ラベル、在庫反映、顧客通知を日本の配送・商習慣に合わせる。',
    category: 'commerce',
    region: 'japan',
    stage: 'validated',
    status: 'watch',
    moneyLabel: '海外先行ARR 9,800万円',
    moneyValue: 98000000,
    moneyType: 'arr-proof',
    momentum: 77,
    gapScore: 76,
    buildability: 72,
    evidenceGrade: 'B',
    freshnessDays: 8,
    soloFriendly: true,
    budgetBand: '10〜50万円',
    timeToMvp: '5〜8週間',
    tags: ['Shopify', 'EC', '業務自動化', '越境'],
    reasons: ['売上増加と共に返品作業も増える', '配送会社・倉庫との連携が分断', '顧客体験が再購入率へ影響'],
    openings: ['アパレルサイズ交換', '越境ECの日本語窓口', '中古品の状態差異受付'],
    risks: ['配送APIの仕様差', '返品条件の個社差', '低返品率店舗には価値が弱い'],
    nextSteps: ['返品月50件以上の店舗へ絞る', '手作業時間と再配送料を測る', '申請フォーム＋自動通知から始める'],
    signalIds: ['signal-shopify-returns'],
    serviceIds: ['service-returnloop-jp'],
    demandIds: ['demand-shopify-return'],
    createdAt: '2026-08-25',
    trend: [45, 48, 50, 58, 64, 71, 77],
    featured: false
  },
  {
    id: 'op-compliance-copilot',
    slug: 'compliance-copilot',
    title: '中小企業向け制度対応コパイロット',
    hook: '「何を、いつまでに、誰がやるか」だけに絞って制度対応を軽くする。',
    summary: '法務判断を代替せず、対象判定、必要書類、進捗、専門家への引継ぎを整理する支援ツール。',
    category: 'regulation',
    region: 'japan',
    stage: 'emerging',
    status: 'gold-window',
    moneyLabel: '関連支出推計32億円',
    moneyValue: 3200000000,
    moneyType: 'market-spend',
    momentum: 88,
    gapScore: 85,
    buildability: 74,
    evidenceGrade: 'A',
    freshnessDays: 10,
    soloFriendly: true,
    budgetBand: '10万円以下',
    timeToMvp: '3〜6週間',
    tags: ['制度対応', 'B2B', '文書', '専門家連携'],
    reasons: ['対応が任意ではない', '情報が散在', '中小企業に専任担当がいない'],
    openings: ['対象判定チェック', '必要資料の回収', '専門家相談前の情報整理'],
    risks: ['法律相談に該当しない設計', '情報更新責任', '誤回答時の影響'],
    nextSteps: ['制度を1つに限定', '公式情報だけでチェックリスト化', '専門家レビューの販売導線を作る'],
    signalIds: ['signal-regulation-docs'],
    serviceIds: ['service-rulepath'],
    demandIds: ['demand-regulation-checklist'],
    createdAt: '2026-08-23',
    trend: [20, 29, 38, 54, 66, 79, 88],
    featured: true
  },
  {
    id: 'op-clinic-cancel-fill',
    slug: 'clinic-cancel-fill',
    title: 'キャンセル枠の自動再販売',
    hook: '空いた予約枠を、待っている顧客へ自動で届けて売上損失を戻す。',
    summary: 'キャンセル発生時に条件の合う待機顧客へ通知し、先着または優先順位で予約を再確定する。',
    category: 'local-business',
    region: 'japan',
    stage: 'validated',
    status: 'gold-window',
    moneyLabel: '観測月額支出1,200万円',
    moneyValue: 12000000,
    moneyType: 'market-spend',
    momentum: 79,
    gapScore: 83,
    buildability: 82,
    evidenceGrade: 'B',
    freshnessDays: 13,
    soloFriendly: true,
    budgetBand: '10万円以下',
    timeToMvp: '2〜4週間',
    tags: ['予約', 'LINE', '店舗', '売上回収'],
    reasons: ['在庫が時間で消滅する', '既存予約システムに待機列が弱い', '成果を金額で示しやすい'],
    openings: ['美容医療', '自由診療歯科', 'パーソナルジム'],
    risks: ['予約システム連携', '通知頻度による離脱', '保険診療との運用差'],
    nextSteps: ['キャンセル単価が高い業種へ限定', 'LINE通知だけのMVP', '回収売上に連動した料金を検証'],
    signalIds: ['signal-clinic-cancel'],
    serviceIds: ['service-slotback'],
    demandIds: ['demand-clinic-waitlist'],
    createdAt: '2026-08-20',
    trend: [31, 38, 45, 52, 61, 73, 79],
    featured: false
  },
  {
    id: 'op-simple-observability',
    slug: 'simple-observability',
    title: '個人開発者向け固定料金の軽量監視',
    hook: '高機能よりも、請求額が予測できて異常だけ分かることに払う。',
    summary: 'ログ、エラー、稼働確認を最低限に絞り、プロジェクト数ベースの固定料金で提供する。',
    category: 'developer-tools',
    region: 'global',
    stage: 'growing',
    status: 'watch',
    moneyLabel: '乗換対象ARR 6,700万円',
    moneyValue: 67000000,
    moneyType: 'switching-spend',
    momentum: 74,
    gapScore: 71,
    buildability: 63,
    evidenceGrade: 'B',
    freshnessDays: 14,
    soloFriendly: true,
    budgetBand: '10〜50万円',
    timeToMvp: '6〜10週間',
    tags: ['開発者', '監視', '固定料金', 'グローバル'],
    reasons: ['従量課金への不安', '小規模案件には過剰機能', '乗換需要が顕在化'],
    openings: ['Next.js専用', '個人開発5プロジェクトまで', '日本語障害通知'],
    risks: ['インフラ原価', '障害時の責任', '既存OSSとの差別化'],
    nextSteps: ['料金不満レビューを分類', '監視対象をHTTPとJSエラーに限定', '原価上限を先に設計'],
    signalIds: ['signal-dev-observability'],
    serviceIds: ['service-pulsekit'],
    demandIds: ['demand-fixed-monitoring'],
    createdAt: '2026-08-19',
    trend: [40, 44, 49, 55, 64, 70, 74],
    featured: false
  },
  {
    id: 'op-micro-acquisition-intel',
    slug: 'micro-acquisition-intel',
    title: '小規模Web事業の買収候補レーダー',
    hook: '作るより、利益が出ている小さな事業を見つけて買う。',
    summary: '複数マーケットの案件を、利益、運営時間、集客依存、技術負債で比較し、買収後の改善余地を見つける。',
    category: 'data-intelligence',
    region: 'japan',
    stage: 'validated',
    status: 'gold-window',
    moneyLabel: '観測成約1.85億円',
    moneyValue: 185000000,
    moneyType: 'acquisition-proof',
    momentum: 81,
    gapScore: 77,
    buildability: 88,
    evidenceGrade: 'A',
    freshnessDays: 17,
    soloFriendly: true,
    budgetBand: '10万円以下',
    timeToMvp: '2〜4週間',
    tags: ['M&A', 'DB', '比較', 'アフィリエイト'],
    reasons: ['公開案件が分散', '数字の意味が比較しづらい', '買収後の改善余地が見えない'],
    openings: ['50万円以下案件', 'コンテンツサイト限定', '買収後90日改善プラン'],
    risks: ['利用規約・データ再利用', '案件数字の信頼性', '投資助言に見えない表現'],
    nextSteps: ['公開データ利用条件を確認', '10案件を手作業で正規化', '買い手の比較軸を聞く'],
    signalIds: ['signal-micro-acquisition'],
    serviceIds: ['service-buybox'],
    demandIds: ['demand-small-acquisition'],
    createdAt: '2026-08-16',
    trend: [35, 41, 48, 58, 65, 74, 81],
    featured: true
  },
  {
    id: 'op-niche-newsletter-market',
    slug: 'niche-newsletter-market',
    title: '専門ニュースレターのスポンサー市場',
    hook: '読者数ではなく「買う可能性が高い少数」を広告主へ売る。',
    summary: '狭い職種・業界のニュースレターを束ね、スポンサーが比較・予約・効果計測できる市場。',
    category: 'creator',
    region: 'global',
    stage: 'emerging',
    status: 'watch',
    moneyLabel: '観測広告費3,600万円',
    moneyValue: 36000000,
    moneyType: 'ad-spend',
    momentum: 70,
    gapScore: 73,
    buildability: 80,
    evidenceGrade: 'B',
    freshnessDays: 20,
    soloFriendly: true,
    budgetBand: '10万円以下',
    timeToMvp: '2〜3週間',
    tags: ['広告', 'ニュースレター', 'マーケットプレイス', 'B2B'],
    reasons: ['媒体探索が手作業', '小規模媒体は営業が弱い', '読者属性が明確'],
    openings: ['個人開発者向け媒体', '士業向け媒体', '地域経営者向け媒体'],
    risks: ['初期の媒体・広告主両面獲得', '効果計測', '広告表示の透明性'],
    nextSteps: ['20媒体を手作業登録', 'スポンサー枠の空き情報を集める', '紹介手数料だけで検証'],
    signalIds: ['signal-creator-sponsor'],
    serviceIds: ['service-sponsorgrid'],
    demandIds: ['demand-niche-sponsor'],
    createdAt: '2026-08-13',
    trend: [27, 33, 38, 45, 54, 63, 70],
    featured: false
  },
  {
    id: 'op-intent-for-small-vendors',
    slug: 'intent-for-small-vendors',
    title: '小規模SaaS向け購買意向シグナル',
    hook: '誰が料金・比較・導入ページを見ているかを、営業できない小規模運営者へ返す。',
    summary: '匿名集計と同意を前提に、カテゴリー閲覧、比較、保存、問い合わせ意向を小規模ベンダー向けに可視化する。',
    category: 'data-intelligence',
    region: 'global',
    stage: 'emerging',
    status: 'gold-window',
    moneyLabel: '関連契約推計4.1億円',
    moneyValue: 410000000,
    moneyType: 'data-revenue',
    momentum: 86,
    gapScore: 80,
    buildability: 69,
    evidenceGrade: 'B',
    freshnessDays: 22,
    soloFriendly: true,
    budgetBand: '10〜50万円',
    timeToMvp: '5〜8週間',
    tags: ['Buyer Intent', 'B2B', '分析', 'リード'],
    reasons: ['大手向け製品は高額', '小規模運営者は営業人員が少ない', '比較行動は購入に近い'],
    openings: ['Product Hunt掲載後の意向', '比較ページ閲覧者', '代替製品からの乗換意向'],
    risks: ['プライバシー・同意', '十分な閲覧母数', '誤った営業利用'],
    nextSteps: ['匿名集計だけで開始', '掲載者ダッシュボードを作る', '閲覧者への直接特定は行わない'],
    signalIds: ['signal-review-intent'],
    serviceIds: ['service-intentlane'],
    demandIds: ['demand-small-vendor-intent'],
    createdAt: '2026-08-11',
    trend: [31, 39, 47, 58, 68, 78, 86],
    featured: true
  },
  {
    id: 'op-field-photo-report',
    slug: 'field-photo-report',
    title: '現場写真から報告書を自動生成',
    hook: '撮るだけで、分類・台帳・報告書まで終わらせる。',
    summary: '工務店や設備会社向けに、スマートフォン写真へ現場・工程・箇所を付与し、定型報告書へ変換する。',
    category: 'vertical-saas',
    region: 'japan',
    stage: 'validated',
    status: 'watch',
    moneyLabel: '推定年間支出1.5億円',
    moneyValue: 150000000,
    moneyType: 'market-spend',
    momentum: 76,
    gapScore: 70,
    buildability: 77,
    evidenceGrade: 'A',
    freshnessDays: 24,
    soloFriendly: true,
    budgetBand: '10〜50万円',
    timeToMvp: '4〜7週間',
    tags: ['建設', '画像', '報告書', 'スマホ'],
    reasons: ['写真整理が毎日発生', 'PC作業が現場に合わない', '発注者提出の書式が定型'],
    openings: ['小規模修繕', '太陽光点検', '賃貸原状回復'],
    risks: ['現場通信環境', '写真誤分類', '大手既存製品との競合'],
    nextSteps: ['業種と帳票を1つに限定', 'オフライン撮影対応', 'Word/PDF出力だけで検証'],
    signalIds: ['signal-field-photo'],
    serviceIds: ['service-sitefolio'],
    demandIds: ['demand-field-photo'],
    createdAt: '2026-08-09',
    trend: [42, 45, 50, 56, 63, 70, 76],
    featured: false
  },
  {
    id: 'op-review-mining',
    slug: 'review-mining',
    title: '競合レビューから未充足需要を抽出するDB',
    hook: '「嫌われている機能」と「払われている価格」の交差点から次の商品を決める。',
    summary: '複数レビューサイトと料金ページから、不満、乗換理由、欲しい機能、顧客属性を整理する調査商品。',
    category: 'data-intelligence',
    region: 'global',
    stage: 'emerging',
    status: 'gold-window',
    moneyLabel: '調査単価 月1〜5万円',
    moneyValue: 50000000,
    moneyType: 'estimated-demand',
    momentum: 83,
    gapScore: 87,
    buildability: 84,
    evidenceGrade: 'C',
    freshnessDays: 7,
    soloFriendly: true,
    budgetBand: '10万円以下',
    timeToMvp: '2〜4週間',
    tags: ['レビュー', '市場調査', 'AI', 'DB'],
    reasons: ['レビューが分散', '読む量が多い', 'アイデア生成より根拠が強い'],
    openings: ['Shopifyアプリ', 'WordPressプラグイン', '日本のB2B SaaS'],
    risks: ['スクレイピング規約', 'レビューの代表性', 'AI要約の誤り'],
    nextSteps: ['公開利用可能な1データ源へ限定', '出典行を必ず保持', '10カテゴリーの手動レポートを販売'],
    signalIds: ['signal-review-intent'],
    serviceIds: ['service-painindex'],
    demandIds: ['demand-review-gaps'],
    createdAt: '2026-08-30',
    trend: [29, 36, 44, 55, 66, 75, 83],
    featured: true
  },
  {
    id: 'op-local-quote-followup',
    slug: 'local-quote-followup',
    title: '見積提出後の自動追客',
    hook: '見積を出したまま放置される売上を、適切な連絡で回収する。',
    summary: 'リフォーム、修理、制作会社など見積型ビジネス向けに、閲覧確認、質問回収、期限通知を自動化する。',
    category: 'local-business',
    region: 'japan',
    stage: 'emerging',
    status: 'watch',
    moneyLabel: '失注回収余地 月3〜20万円/社',
    moneyValue: 30000000,
    moneyType: 'recoverable-revenue',
    momentum: 72,
    gapScore: 78,
    buildability: 90,
    evidenceGrade: 'C',
    freshnessDays: 12,
    soloFriendly: true,
    budgetBand: '5万円以下',
    timeToMvp: '1〜3週間',
    tags: ['営業', '見積', '地域企業', '自動化'],
    reasons: ['追客が属人的', '売上効果を測りやすい', '既存CRMが重い'],
    openings: ['住宅修繕', '自動車整備', 'Web制作会社'],
    risks: ['過度な連絡', 'メール到達率', '業種ごとの営業周期'],
    nextSteps: ['見積件数が月20件以上の業種を選ぶ', 'メール＋LINEのテンプレだけ作る', '回収売上を計測する'],
    signalIds: [],
    serviceIds: [],
    demandIds: [],
    createdAt: '2026-08-21',
    trend: [30, 34, 39, 47, 56, 64, 72],
    featured: false
  }
];

export const services = [
  {
    id: 'service-billrail',
    name: 'BillRail',
    tagline: '訪問サービス事業者の請求と入金確認を1画面に。',
    description: '請求書発行、入金消込、未払い連絡を小規模事業者向けに簡略化したデモサービス。',
    category: 'vertical-saas',
    url: '',
    pricing: '月額4,980円〜',
    model: 'subscription',
    region: 'japan',
    languages: ['日本語'],
    stage: 'growth',
    owner: '2人チーム',
    verified: true,
    evidenceGrade: 'B',
    launchedAt: '2025-10-01',
    metrics: { mrr: 2100000, users: 438, growth: 18 },
    intents: ['customers', 'partners'],
    tags: ['請求', '入金', '業界特化'],
    opportunityIds: ['op-invoice-niches'],
    votes: 284,
    featured: true,
    demo: true
  },
  {
    id: 'service-callmint',
    name: 'CallMint',
    tagline: '予約電話を24時間受け、必要な内容だけ人へ渡す。',
    description: '歯科と不動産に特化したAI電話受付のデモサービス。',
    category: 'ai-automation',
    url: '',
    pricing: '月額12,800円〜',
    model: 'subscription-usage',
    region: 'japan',
    languages: ['日本語'],
    stage: 'beta',
    owner: '個人開発',
    verified: true,
    evidenceGrade: 'B',
    launchedAt: '2026-04-12',
    metrics: { mrr: 980000, users: 76, growth: 31 },
    intents: ['beta-users', 'customers'],
    tags: ['AI電話', '予約', '歯科'],
    opportunityIds: ['op-ai-reception-vertical'],
    votes: 361,
    featured: true,
    demo: true
  },
  {
    id: 'service-returnloop-jp',
    name: 'ReturnLoop JP',
    tagline: '交換申請から配送ラベルまで、日本のEC返品を自動化。',
    description: 'Shopify店舗向け返品・交換ワークフローのデモサービス。',
    category: 'commerce',
    url: '',
    pricing: '月額8,900円〜',
    model: 'subscription',
    region: 'japan',
    languages: ['日本語', '英語'],
    stage: 'early',
    owner: '3人チーム',
    verified: false,
    evidenceGrade: 'C',
    launchedAt: '2026-05-20',
    metrics: { mrr: 420000, users: 31, growth: 22 },
    intents: ['beta-users', 'affiliates'],
    tags: ['Shopify', '返品', '交換'],
    opportunityIds: ['op-japan-return-ops'],
    votes: 148,
    featured: false,
    demo: true
  },
  {
    id: 'service-rulepath',
    name: 'RulePath',
    tagline: '制度対応を「対象・期限・必要書類」に分解。',
    description: '公式情報に基づくチェックリストと専門家引継ぎを提供するデモサービス。',
    category: 'regulation',
    url: '',
    pricing: '月額3,980円〜',
    model: 'subscription',
    region: 'japan',
    languages: ['日本語'],
    stage: 'beta',
    owner: '個人開発＋監修',
    verified: true,
    evidenceGrade: 'A',
    launchedAt: '2026-06-05',
    metrics: { mrr: 610000, users: 204, growth: 42 },
    intents: ['experts', 'customers'],
    tags: ['制度', '書類', 'チェックリスト'],
    opportunityIds: ['op-compliance-copilot'],
    votes: 412,
    featured: true,
    demo: true
  },
  {
    id: 'service-slotback',
    name: 'SlotBack',
    tagline: 'キャンセル枠をLINEで待機客へ自動再販売。',
    description: '美容・自由診療向けキャンセル待ち自動化のデモサービス。',
    category: 'local-business',
    url: '',
    pricing: '月額6,800円＋成果報酬',
    model: 'hybrid',
    region: 'japan',
    languages: ['日本語'],
    stage: 'early',
    owner: '2人チーム',
    verified: true,
    evidenceGrade: 'B',
    launchedAt: '2026-02-18',
    metrics: { mrr: 1340000, users: 92, growth: 27 },
    intents: ['customers', 'integrations'],
    tags: ['予約', 'LINE', 'キャンセル'],
    opportunityIds: ['op-clinic-cancel-fill'],
    votes: 319,
    featured: true,
    demo: true
  },
  {
    id: 'service-pulsekit',
    name: 'PulseKit',
    tagline: '個人開発5サービスまで、固定料金で最低限の監視。',
    description: '稼働確認、JSエラー、週次レポートに絞ったデモ監視サービス。',
    category: 'developer-tools',
    url: '',
    pricing: '月額1,980円',
    model: 'subscription',
    region: 'global',
    languages: ['日本語', '英語'],
    stage: 'beta',
    owner: '個人開発',
    verified: false,
    evidenceGrade: 'C',
    launchedAt: '2026-07-01',
    metrics: { mrr: 188000, users: 126, growth: 54 },
    intents: ['beta-users', 'feedback'],
    tags: ['監視', '個人開発', '固定料金'],
    opportunityIds: ['op-simple-observability'],
    votes: 203,
    featured: false,
    demo: true
  },
  {
    id: 'service-buybox',
    name: 'BuyBox Radar',
    tagline: '50万円以下の小規模Web事業を比較・監視。',
    description: '案件の利益、運営時間、集客依存、改善余地を正規化するデモDB。',
    category: 'data-intelligence',
    url: '',
    pricing: '月額2,980円',
    model: 'subscription-affiliate',
    region: 'japan',
    languages: ['日本語'],
    stage: 'growth',
    owner: '個人開発',
    verified: true,
    evidenceGrade: 'A',
    launchedAt: '2026-01-10',
    metrics: { mrr: 1760000, users: 1280, growth: 16 },
    intents: ['affiliates', 'buyers'],
    tags: ['M&A', '案件比較', 'Web事業'],
    opportunityIds: ['op-micro-acquisition-intel'],
    votes: 532,
    featured: true,
    demo: true
  },
  {
    id: 'service-sponsorgrid',
    name: 'SponsorGrid',
    tagline: '専門ニュースレターのスポンサー枠を比較・予約。',
    description: '読者属性と空き枠を一覧化し、広告主と媒体を接続するデモ市場。',
    category: 'creator',
    url: '',
    pricing: '成約手数料15%',
    model: 'marketplace',
    region: 'global',
    languages: ['日本語', '英語'],
    stage: 'early',
    owner: '2人チーム',
    verified: false,
    evidenceGrade: 'C',
    launchedAt: '2026-03-15',
    metrics: { mrr: 740000, users: 418, growth: 35 },
    intents: ['publishers', 'advertisers'],
    tags: ['ニュースレター', '広告', 'スポンサー'],
    opportunityIds: ['op-niche-newsletter-market'],
    votes: 247,
    featured: false,
    demo: true
  },
  {
    id: 'service-intentlane',
    name: 'IntentLane',
    tagline: '比較・保存・料金閲覧から、小規模SaaSの買い手意向を可視化。',
    description: '個人を特定せず、カテゴリー単位の関心と変化を返すデモ分析サービス。',
    category: 'data-intelligence',
    url: '',
    pricing: '月額9,800円〜',
    model: 'subscription',
    region: 'global',
    languages: ['日本語', '英語'],
    stage: 'beta',
    owner: '3人チーム',
    verified: true,
    evidenceGrade: 'B',
    launchedAt: '2026-06-19',
    metrics: { mrr: 1120000, users: 87, growth: 48 },
    intents: ['vendors', 'design-partners'],
    tags: ['購買意向', 'B2B', '分析'],
    opportunityIds: ['op-intent-for-small-vendors'],
    votes: 398,
    featured: true,
    demo: true
  },
  {
    id: 'service-sitefolio',
    name: 'SiteFolio',
    tagline: '現場で撮影するだけ。写真台帳と報告書を自動作成。',
    description: '小規模修繕会社向け写真整理・帳票作成のデモサービス。',
    category: 'vertical-saas',
    url: '',
    pricing: '月額7,800円〜',
    model: 'subscription',
    region: 'japan',
    languages: ['日本語'],
    stage: 'growth',
    owner: '4人チーム',
    verified: true,
    evidenceGrade: 'A',
    launchedAt: '2025-08-08',
    metrics: { mrr: 3580000, users: 516, growth: 14 },
    intents: ['customers', 'resellers'],
    tags: ['建設', '写真', '報告書'],
    opportunityIds: ['op-field-photo-report'],
    votes: 456,
    featured: true,
    demo: true
  },
  {
    id: 'service-painindex',
    name: 'PainIndex',
    tagline: '競合レビューを読み、顧客が払う不満だけを抽出。',
    description: 'レビュー、価格、機能差から参入余地を整理するデモ調査DB。',
    category: 'data-intelligence',
    url: '',
    pricing: '月額4,980円',
    model: 'subscription',
    region: 'global',
    languages: ['日本語', '英語'],
    stage: 'beta',
    owner: '個人開発',
    verified: false,
    evidenceGrade: 'C',
    launchedAt: '2026-08-01',
    metrics: { mrr: 260000, users: 183, growth: 67 },
    intents: ['beta-users', 'data-partners'],
    tags: ['レビュー', '市場調査', '競合'],
    opportunityIds: ['op-review-mining'],
    votes: 344,
    featured: true,
    demo: true
  }
];

export const demands = [
  {
    id: 'demand-care-invoice',
    title: '訪問介護の請求漏れを減らす簡単な確認画面が欲しい',
    summary: '会計ソフトを入れ替えず、請求前の漏れ・未入金だけを確認したい。',
    audience: '小規模訪問介護事業者',
    region: 'japan',
    category: 'vertical-saas',
    willingnessToPay: '月額5,000〜15,000円',
    votes: 382,
    payVotes: 87,
    painScore: 88,
    alternatives: ['表計算', '会計ソフト', '事務代行'],
    gaps: ['介護固有の確認項目', '現場職員でも使える画面', '未入金連絡'],
    tags: ['請求', '介護', '業務効率'],
    opportunityIds: ['op-invoice-niches'],
    serviceIds: ['service-billrail'],
    createdAt: '2026-08-25'
  },
  {
    id: 'demand-dental-phone',
    title: '診療中の電話をAIが受け、初診予約だけ確定してほしい',
    summary: 'スタッフが電話へ出るため診療を中断している。複雑な相談は折返しでよい。',
    audience: '歯科医院',
    region: 'japan',
    category: 'ai-automation',
    willingnessToPay: '月額10,000〜30,000円',
    votes: 491,
    payVotes: 126,
    painScore: 92,
    alternatives: ['留守番電話', '電話代行', 'Web予約'],
    gaps: ['歯科用語', '緊急度判定', '既存予約台帳との連携'],
    tags: ['歯科', '電話', '予約'],
    opportunityIds: ['op-ai-reception-vertical'],
    serviceIds: ['service-callmint'],
    createdAt: '2026-08-24'
  },
  {
    id: 'demand-shopify-return',
    title: 'サイズ交換の往復連絡と在庫確認を自動化したい',
    summary: '返品率が高いアパレルECで、メール往復と配送ラベル発行に時間がかかる。',
    audience: 'Shopifyアパレル店舗',
    region: 'japan',
    category: 'commerce',
    willingnessToPay: '月額8,000〜25,000円',
    votes: 248,
    payVotes: 64,
    painScore: 81,
    alternatives: ['メール', '汎用問い合わせ管理', '倉庫代行'],
    gaps: ['日本の配送会社', '交換在庫の仮押さえ', '日本語テンプレ'],
    tags: ['返品', 'Shopify', 'アパレル'],
    opportunityIds: ['op-japan-return-ops'],
    serviceIds: ['service-returnloop-jp'],
    createdAt: '2026-08-21'
  },
  {
    id: 'demand-regulation-checklist',
    title: '新制度で自社が何をすべきか、公式根拠付きで一覧にしてほしい',
    summary: '記事を読む時間がなく、対象判定と期限、必要資料だけ知りたい。',
    audience: '従業員10〜100人の企業',
    region: 'japan',
    category: 'regulation',
    willingnessToPay: '月額3,000〜20,000円',
    votes: 614,
    payVotes: 173,
    painScore: 94,
    alternatives: ['検索', '顧問への相談', '行政資料'],
    gaps: ['自社への対象判定', '更新通知', '相談前の資料整理'],
    tags: ['制度', '中小企業', '期限'],
    opportunityIds: ['op-compliance-copilot'],
    serviceIds: ['service-rulepath'],
    createdAt: '2026-08-18'
  },
  {
    id: 'demand-clinic-waitlist',
    title: 'キャンセルが出たら条件の合う待機客へ自動で連絡してほしい',
    summary: '高単価枠が当日空くと売上を失う。スタッフが一人ずつ電話する余裕はない。',
    audience: '美容クリニック・自由診療',
    region: 'japan',
    category: 'local-business',
    willingnessToPay: '月額5,000円＋回収売上の一部',
    votes: 459,
    payVotes: 142,
    painScore: 90,
    alternatives: ['電話', '一斉LINE', '予約サイト'],
    gaps: ['施術条件の一致', '通知優先順位', '予約確定までの自動化'],
    tags: ['キャンセル', '予約', 'LINE'],
    opportunityIds: ['op-clinic-cancel-fill'],
    serviceIds: ['service-slotback'],
    createdAt: '2026-08-16'
  },
  {
    id: 'demand-fixed-monitoring',
    title: '個人開発向けに、請求が跳ねない監視ツールが欲しい',
    summary: '高度な分析は不要。落ちた、遅い、エラーが増えたことだけ知りたい。',
    audience: '個人開発者',
    region: 'global',
    category: 'developer-tools',
    willingnessToPay: '月額1,000〜3,000円',
    votes: 533,
    payVotes: 196,
    painScore: 78,
    alternatives: ['大手監視製品', 'OSS', '何もしない'],
    gaps: ['固定料金', '日本語通知', '設定の少なさ'],
    tags: ['監視', '個人開発', '固定料金'],
    opportunityIds: ['op-simple-observability'],
    serviceIds: ['service-pulsekit'],
    createdAt: '2026-08-14'
  },
  {
    id: 'demand-small-acquisition',
    title: '50万円以下で買える、手離れのよいWeb事業だけ見たい',
    summary: '案件を毎日見る時間がない。利益と運営時間が確認できるものだけ通知してほしい。',
    audience: '個人買収者・副業会社員',
    region: 'japan',
    category: 'data-intelligence',
    willingnessToPay: '月額1,000〜5,000円',
    votes: 708,
    payVotes: 231,
    painScore: 85,
    alternatives: ['M&Aサイト巡回', '仲介会社', 'SNS'],
    gaps: ['横断比較', '数字の信頼度', '運営時間'],
    tags: ['M&A', 'Web事業', '比較'],
    opportunityIds: ['op-micro-acquisition-intel'],
    serviceIds: ['service-buybox'],
    createdAt: '2026-08-12'
  },
  {
    id: 'demand-niche-sponsor',
    title: '購買意欲の高い小規模ニュースレターへ広告を出したい',
    summary: '大規模媒体より、特定職種へ届く媒体をまとめて比較したい。',
    audience: 'B2B SaaSマーケター',
    region: 'global',
    category: 'creator',
    willingnessToPay: '1枠3万〜20万円',
    votes: 302,
    payVotes: 94,
    painScore: 74,
    alternatives: ['SNS広告', '媒体へ直接連絡', '代理店'],
    gaps: ['空き枠比較', '読者属性', '効果計測'],
    tags: ['スポンサー', '広告', 'ニュースレター'],
    opportunityIds: ['op-niche-newsletter-market'],
    serviceIds: ['service-sponsorgrid'],
    createdAt: '2026-08-10'
  },
  {
    id: 'demand-small-vendor-intent',
    title: '小規模SaaSでも買い手の関心変化を知りたい',
    summary: '問い合わせ前の比較・保存行動が分かれば、作る機能と発信内容を決められる。',
    audience: '個人・小規模SaaS運営者',
    region: 'global',
    category: 'data-intelligence',
    willingnessToPay: '月額5,000〜20,000円',
    votes: 421,
    payVotes: 133,
    painScore: 82,
    alternatives: ['アクセス解析', '営業CRM', 'アンケート'],
    gaps: ['競合比較行動', '匿名集計', '小規模向け価格'],
    tags: ['購買意向', 'SaaS', '分析'],
    opportunityIds: ['op-intent-for-small-vendors'],
    serviceIds: ['service-intentlane'],
    createdAt: '2026-08-08'
  },
  {
    id: 'demand-field-photo',
    title: '現場写真を撮った順のまま、提出用台帳にしてほしい',
    summary: '事務所へ戻って写真を分類し直す作業をなくしたい。',
    audience: '小規模工務店・設備会社',
    region: 'japan',
    category: 'vertical-saas',
    willingnessToPay: '月額5,000〜15,000円',
    votes: 367,
    payVotes: 111,
    painScore: 86,
    alternatives: ['スマホ写真', '表計算', '現場管理ソフト'],
    gaps: ['簡単な操作', '定型PDF', 'オフライン撮影'],
    tags: ['建設', '写真', '報告書'],
    opportunityIds: ['op-field-photo-report'],
    serviceIds: ['service-sitefolio'],
    createdAt: '2026-08-05'
  },
  {
    id: 'demand-review-gaps',
    title: '競合レビューを全部読まず、繰り返し不満だけ知りたい',
    summary: '新規事業の判断に、顧客の不満と既存価格を同時に見たい。',
    audience: '個人開発者・新規事業担当',
    region: 'global',
    category: 'data-intelligence',
    willingnessToPay: '月額3,000〜30,000円',
    votes: 587,
    payVotes: 206,
    painScore: 89,
    alternatives: ['手作業調査', 'AIチャット', '調査会社'],
    gaps: ['出典保持', '価格との接続', '時系列変化'],
    tags: ['レビュー', '競合', '市場調査'],
    opportunityIds: ['op-review-mining'],
    serviceIds: ['service-painindex'],
    createdAt: '2026-08-29'
  }
];

export const activity = [
  { id: 'a1', type: 'signal', text: '制度対応コパイロットの根拠がAへ更新', time: '14分前' },
  { id: 'a2', type: 'service', text: 'AI電話受付に新しいサービスが登録', time: '31分前' },
  { id: 'a3', type: 'demand', text: '「固定料金の監視」へ23件の需要票', time: '1時間前' },
  { id: 'a4', type: 'growth', text: 'レビュー需要DBの注目度が今週+18%', time: '2時間前' },
  { id: 'a5', type: 'claim', text: 'サービス所有者確認が1件完了', time: '3時間前' }
];

export const editorialStats = {
  signalsTracked: 2847,
  opportunities: 184,
  verifiedSources: 1263,
  services: 943,
  demands: 412,
  updatedToday: 36
};
